import {readFile,writeFile} from 'node:fs/promises';import {createHash} from 'node:crypto';
const base='artifacts/scoped-registry-phase-5-closeout/production',data=JSON.parse(await readFile(`${base}/comparison.json`));
let html=await readFile('artifacts/scoped-registry-production-v1/page/comparison-656962fdc81a.html','utf8');
const esc=x=>String(x).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const num=x=>x==null?'—':new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(x);
function table(id,title,rows,columns,note){return `<section id="${id}" data-comparison><div class="section-heading"><h2>${title}</h2><span class="count" data-count>${rows.length} comparisons</span></div><div data-filters class="filters" hidden><label>Search<input type="search"></label><label>Metric<select data-metric-filter><option value="">All metrics</option>${[...new Set(rows.map(r=>r.metric))].map(m=>`<option>${esc(m)}</option>`).join('')}</select></label><button data-reset>Clear filters</button></div><en-table size="small" label="${title} scroll area"><table aria-describedby="${id}-note"><caption>Final Phase5 first-hydration readiness policy; exact frozen Phase4 eager reference.</caption><thead><tr>${columns.map(([key,label,numeric],i)=>`<th scope="col" class="${numeric?'numeric':''}"><button disabled data-key="${key}" data-index="${i}" data-type="${numeric?'number':'text'}" data-label="${esc(label)}" aria-label="${esc(label)}: sort ascending">${esc(label)}<span aria-hidden="true">↕</span></button></th>`).join('')}</tr></thead><tbody>${rows.map((r,j)=>`<tr data-index="${j}" data-metric="${esc(r.metric)}" data-search="${esc(Object.values(r).join(' ').toLowerCase())}">${columns.map(([key,,numeric],i)=>`<${i?'td':'th scope="row"'} class="${numeric?'numeric':''}" data-value="${esc(r[key]??'')}">${numeric?num(r[key]):esc(r[key]??'')}</${i?'td':'th'}>`).join('')}</tr>`).join('')}</tbody></table></en-table><p data-empty hidden>No matching comparisons.</p><p id="${id}-note" class="direction-note">${note}</p><p class="sr-only" role="status" aria-live="polite" aria-atomic="true"></p></section>`;}
const names={firstUseMs:'First command focus',secondUseMs:'Second command focus',hydratedMs:'First hydration readiness (includes settling)',shellReadyMs:'Native shell ready',navigationToFocusMs:'Navigation to command focus',preparationLeadMs:'Observed preparation lead',jsBytes:'JS after action · gzip',settledUnusedJSBytes:'JS after unused preparation settles · gzip',settledUnusedLiveNodes:'Live nodes after unused preparation settles',settledUnusedInertNodes:'Inert nodes after unused preparation settles',heapBytes:'Retained JS heap',nodes:'Retained DOM nodes',jsEventListeners:'Event listeners',documents:'Documents'};
const flatten=rows=>rows.map(r=>({...r,metric:names[r.metric]??r.metric,n:r.arms.map(a=>a.n).join(' / '),eager:r.arms[0].median,prepared:r.arms[1].median,cold:r.arms[2].median,delta:r.changes['prepared-eager'].difference,percent:r.changes['prepared-eager'].percent,low:r.changes['prepared-eager'].ci95?.[0]??null,high:r.changes['prepared-eager'].ci95?.[1]??null,coldDelta:r.changes['cold-eager'].difference}));
const columns=[['browser','Browser'],['profile','Profile'],['input','Interaction'],['metric','Metric'],['unit','Unit'],['n','Samples'],['eager','Phase4 eager',true],['prepared','Phase5 prepared · final',true],['cold','Phase5 cold · final',true],['delta','Prepared − eager Δ',true],['percent','Prepared − eager %',true],['low','95% Δ lower',true],['high','95% Δ upper',true],['coldDelta','Cold − eager Δ',true]];
const note='<strong>Change direction:</strong> Each Δ, percentage and interval bound is the named Phase5 policy minus Phase4 eager. Negative timing/bytes/request/retention-growth changes are generally better for equivalent functionality; positive means more. Inert storage, defined hosts, preparation lead and observation-window changes are context, not standalone performance wins. Intervals spanning zero do not establish a direction or equivalence. — means unavailable or a zero reference. Retention uses five separate runs per policy and claims no confidence intervals or proof of no leaks.';
const row=(metric,profile='constrained',input='keyboard')=>data.timing.find(r=>r.browser==='chromium'&&r.profile===profile&&r.input===input&&r.metric===metric);
const values=r=>r.arms.map(a=>num(a.median)).join(' / ');
const desktop = ['chromium','firefox','webkit'].map(browser=>{const r=data.timing.find(r=>r.browser===browser&&r.profile==='desktop'&&r.metric==='firstUseMs');return `${browser}: ${values(r)} ms`;}).join('; ');
const final=`<section id="final-findings"><h2>Final Phase5: user-confirmed opening remediation integrated</h2><p>The command module’s readiness callback now waits two animation frames after its first hydration update. Safari/VoiceOver passed the corresponding manual diagnostic. This application policy runs once per island and cancels on disposal; ordinary dialogs and repeated openings do not acquire a generic wait. Firefox draft restoration passed with a corrected review-server cache header.</p><p><strong>New capture:</strong> 540 successful timing samples, 30 per configuration, plus 15 independent retention runs. Order below is Phase4 eager / Phase5 prepared / Phase5 cold. Throttled keyboard first focus: <strong>${values(row('firstUseMs'))} ms</strong>. Second focus: <strong>${values(row('secondUseMs'))} ms</strong>. Navigation to first focus: ${values(row('navigationToFocusMs'))} ms. Prepared-minus-eager first-focus interval: ${num(row('firstUseMs').changes['prepared-eager'].ci95[0])} to ${num(row('firstUseMs').changes['prepared-eager'].ci95[1])} ms.</p><p><strong>Desktop first-use tradeoff:</strong> ${desktop}. The settling policy has a substantial WebKit first-open cost in this capture; it is retained to preserve the user-confirmed VoiceOver behavior. The report does not claim universal latency improvement. Repeated-use timings are listed separately.</p><p>Settled unused live DOM: ${values(row('settledUnusedLiveNodes','constrained','unused'))}. Inert DOM: ${values(row('settledUnusedInertNodes','constrained','unused'))}. Gzip JS: ${values(row('settledUnusedJSBytes','constrained','unused'))} bytes. Inert storage still consumes memory and HTML. The earlier Phase5 data remains below as historical evidence; do not treat it as a paired estimate of the settling cost. The final-vs-eager comparison directly measures the delivered readiness policy.</p><p>Principal manual workflows and the focused cache/native-dialog/settled-palette retests were user-confirmed. Physical IME, actual autofill and restored state inside hydrated managed fields remain unreported. Automated tests verify DOM focus, not VoiceOver cursor behavior. Real failed imports can still require reload in Chromium/WebKit. The server renderer is unchanged; older server measurements are retained as historical evidence. The application now imports a readiness helper, and its server import overhead has not been retimed.</p></section>`+
 table('final-timing','Final browser timing, delivery and DOM',flatten(data.timing),columns,note)+
 table('final-retention','Final lifecycle retention',flatten(data.retention),[['cycle','Cycle'],...columns.filter(c=>!['low','high'].includes(c[0]))],note)+
 `<section><h2>Final capture provenance</h2><p>${esc(data.methodology)}</p><p>Archive: <code>showcases/performance/baselines/scoped-registry-phase-5-closeout-v1</code>. Reference parent: <code>5cab32d9311cb1a730fa9741e3334d03f7fc442a</code>. Source/asset receipts and successful samples are included. Source is sealed by the Phase5 commit recorded in <code>artifacts/scoped-registry-phase-5-closeout/commit-boundary.json</code>.</p><p><a href="http://127.0.0.1:4231/?delay&progress-report">Final manual fixture</a> · <a href="http://127.0.0.1:4206/comparison-656962fdc81a.html?progress-report">Previous report and server investigation</a></p></section><section><h2>Preserved earlier Phase5 capture · before settling policy</h2><p>The tables and findings below preserve their original values. They are historical context; use the final tables above for the commit’s application policy.</p></section>`;
html=html.replace('<title>Phase 5 · Client performance and SSR cost investigation</title>','<title>Phase 5 · Final client readiness and performance</title>');
html=html.replace('<h1>Phase 5: scoped SSR and progressive hydration</h1>','<h1>Phase 5: final readiness and performance</h1>');
html=html.replace('href="#timing">Skip to comparisons','href="#final-timing">Skip to comparisons').replace('href="#timing">Browser comparison','href="#timing">Previous browser comparison');
html=html.replace('<nav>','<nav><a href="#final-timing">Final browser comparison</a><a href="#final-retention">Final retention</a>');
html=html.replace('<section id="findings">',final+'<section id="findings">');
html=html.replace('Manual screen-reader, autofill/history restoration and physical IME/device review remain separate from automated qualification.','Historical review status at this earlier capture: screen-reader, autofill/history restoration and physical IME/device review were separate from automated qualification. See final review status above.');
const sha256=createHash('sha256').update(html).digest('hex'),filename=`comparison-${sha256.slice(0,12)}.html`;
for(const dir of ['artifacts/scoped-registry-production-v1/page',base])await writeFile(`${dir}/${filename}`,html,{flag:'wx'});
await writeFile(`${base}/report.json`,JSON.stringify({filename,sha256,url:`http://127.0.0.1:4206/${filename}?progress-report#final-timing`,tables:9},null,2)+'\n');console.log(filename);
