import {test,expect,type Page,type Locator} from '@playwright/test';
const picker=(p:Page)=>p.locator('native-picker').first(),plane=(p:Page)=>p.locator('native-plane'),wheel=(p:Page)=>p.locator('native-wheel'),channel=(p:Page)=>p.locator('#standalone');
const columns=(n:Locator)=>n.evaluate(n=>getComputedStyle(n).gridTemplateColumns.split(' ').length);
// Pointer coordinates may be rounded to CSS pixels by the engine. Allow one degree
// at cardinal positions; keyboard increments and cancellation remain exact.
const hueNear=async(n:Locator,expected:number)=>expect.poll(async()=>{const actual=Number(await n.getAttribute('aria-valuenow'));return Math.min(Math.abs(actual-expected),360-Math.abs(actual-expected));}).toBeLessThanOrEqual(1);
const point=async(p:Page,n:Locator,x:number,y:number)=>{await n.scrollIntoViewIfNeeded();const b=(await n.boundingBox())!;await p.mouse.click(b.x+b.width*x,b.y+b.height*y);};
for(const delivery of ['js','css'])test.describe(delivery,()=>{
 test.beforeEach(async({page})=>{await page.goto('/?delivery='+delivery);await expect(picker(page).getByRole('textbox',{name:'Hex color'})).toBeVisible();await expect(plane(page).locator('[part=base]')).toHaveCSS('display','grid');});
 test('wide picker keeps its one-column composition independently of the plane',async({page})=>{await expect.poll(()=>columns(picker(page).locator('[part=base]'))).toBe(1);expect((await picker(page).locator('[part=base]').boundingBox())!.width).toBe(320);});
 test('wide plane uses available width and switches to two columns',async({page})=>{const base=plane(page).locator('[part=base]');await expect.poll(()=>columns(base)).toBe(2);expect((await base.boundingBox())!.width).toBeGreaterThan(600);});
 test('narrow plane stacks without changing the picker',async({page})=>{await plane(page).evaluate(n=>(n as HTMLElement).style.width='300px');await expect.poll(()=>columns(plane(page).locator('[part=base]'))).toBe(1);await expect.poll(()=>columns(picker(page).locator('[part=base]'))).toBe(1);});
 test('valid hex draft updates alpha preview and serialized output',async({page})=>{await picker(page).getByRole('textbox',{name:'Hex color'}).fill('#ff0000');await expect(picker(page).locator('[part=value]')).toHaveText('#ff000080');await expect(picker(page).locator('[part=preview]')).toHaveCSS('background-color','rgba(255, 0, 0, 0.5)');});
 test('invalid draft stays editable while last valid color is preserved',async({page})=>{const input=picker(page).getByRole('textbox',{name:'Hex color'});await input.fill('#bad-value');await expect(input).toHaveValue('#bad-value');await expect(picker(page).locator('[part=error]')).toHaveText('Use six hex digits');expect(await input.evaluate(n=>(n as HTMLInputElement).checkValidity())).toBe(false);await expect(picker(page).locator('[part=value]')).toHaveText('#5577cc80');await input.fill('#ffffff');await expect(picker(page).locator('[part=error]')).toBeEmpty();});
 test('native alpha keyboard updates output including transparent and opaque endpoints',async({page})=>{const input=picker(page).getByRole('slider',{name:'Alpha'});await input.focus();await input.press('ArrowRight');await expect(input).toHaveValue('51');await expect(picker(page).locator('[part=value]')).toHaveText('#5577cc82');await input.press('Home');await expect(picker(page).locator('[part=value]')).toHaveText('#5577cc00');await input.press('End');await expect(picker(page).locator('[part=value]')).toHaveText('#5577ccff');});
 test('native alpha pointer changes the preview and checkerboard remains behind it',async({page})=>{const input=picker(page).getByRole('slider',{name:'Alpha'});await point(page,input,.75,.5);expect(Number(await input.inputValue())).toBeGreaterThan(65);await expect(picker(page).locator('.preview-frame')).toHaveCSS('background-image',/repeating-conic-gradient/);expect(await picker(page).locator('native-channel').evaluate(n=>getComputedStyle(n).getPropertyValue('--_en-color-checker'))).toContain('repeating-conic-gradient');});
 test('switching output format retains picker geometry and color',async({page})=>{const before=(await picker(page).locator('[part=base]').boundingBox())!;await picker(page).getByRole('combobox').selectOption('rgb');await expect(picker(page).locator('[part=value]')).toHaveText('rgb(85 119 204 / 0.5)');const after=(await picker(page).locator('[part=base]').boundingBox())!;expect(after.width).toBe(before.width);expect(after.height).toBe(before.height);});
 test('disabled native channel retains value and semantics',async({page})=>{await channel(page).evaluate(n=>(n as any).disabled=true);const input=channel(page).getByRole('slider');await expect(input).toBeDisabled();await expect(input).toHaveValue('50');await expect(input).toHaveCSS('opacity','0.55');});
 test('plane named keyboard controls update the visible thumb',async({page})=>{const saturation=plane(page).getByRole('slider',{name:'Saturation'});await saturation.focus();await saturation.press('End');await plane(page).getByRole('slider',{name:'Brightness'}).press('Home');await expect(saturation).toHaveValue('100');expect(await plane(page).locator('[part=plane]').evaluate(n=>getComputedStyle(n).getPropertyValue('--_en-plane-x'))).toBe('100%');expect(await plane(page).locator('[part=plane]').evaluate(n=>getComputedStyle(n).getPropertyValue('--_en-plane-y'))).toBe('100%');});
 test('plane pointer sets two coordinates with an accessible equivalent',async({page})=>{await point(page,plane(page).locator('[part=plane]'),.75,.25);await expect(plane(page).getByRole('slider',{name:'Saturation'})).toHaveValue('75');await expect(plane(page).getByRole('slider',{name:'Brightness'})).toHaveValue('75');await expect(plane(page).getByRole('group',{name:'Color plane'})).toBeVisible();});
 test('plane captures and clamps a drag beyond its edges',async({page})=>{const target=plane(page).locator('[part=plane]');await target.scrollIntoViewIfNeeded();const b=(await target.boundingBox())!;await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width+50,b.y-20);await page.mouse.up();await expect(plane(page).getByRole('slider',{name:'Saturation'})).toHaveValue('100');await expect(plane(page).getByRole('slider',{name:'Brightness'})).toHaveValue('100');});
 test('plane canceled pointer interaction restores its draft',async({page})=>{const target=plane(page).locator('[part=plane]');await target.scrollIntoViewIfNeeded();const b=(await target.boundingBox())!;await page.mouse.move(b.x+b.width*.8,b.y+b.height*.2);await page.mouse.down();await expect(plane(page).getByRole('slider',{name:'Saturation'})).toHaveValue('80');await target.dispatchEvent('pointercancel',{pointerId:1});await page.mouse.up();await expect(plane(page).getByRole('slider',{name:'Saturation'})).toHaveValue('50');await expect(plane(page).getByRole('slider',{name:'Brightness'})).toHaveValue('50');});
 test('plane disabled state prevents pointer and keyboard mutation',async({page})=>{await plane(page).evaluate(n=>(n as any).disabled=true);await expect(plane(page).getByRole('slider',{name:'Saturation'})).toBeDisabled();await point(page,plane(page).locator('[part=plane]'),.9,.2);await expect(plane(page).getByRole('slider',{name:'Saturation'})).toHaveValue('50');await expect(plane(page).locator('[part=plane]')).toHaveCSS('opacity','0.55');});
 test('RTL plane maps leading edge and thumb to the same position',async({page})=>{await plane(page).evaluate(n=>n.setAttribute('dir','rtl'));const target=plane(page).locator('[part=plane]');await point(page,target,.25,.5);await expect(plane(page).getByRole('slider',{name:'Saturation'})).toHaveValue('75');const b=(await target.boundingBox())!,thumb=(await plane(page).locator('[part=thumb]').boundingBox())!;expect(Math.abs(thumb.x+thumb.width/2-(b.x+b.width*.25))).toBeLessThan(3);});
 test('wheel keyboard wraps, supports larger steps and exposes its value',async({page})=>{const slider=wheel(page).getByRole('slider',{name:'Hue wheel'});await slider.focus();await slider.press('ArrowLeft');await expect(slider).toHaveAttribute('aria-valuenow','359');await slider.press('ArrowRight');await slider.press('Shift+ArrowUp');await expect(slider).toHaveAttribute('aria-valuetext','10 degrees');await slider.press('End');await expect(slider).toHaveAttribute('aria-valuenow','359');await slider.press('Home');await expect(slider).toHaveAttribute('aria-valuenow','0');await expect(slider).toHaveCSS('outline-style','solid');});
 test('wheel pointer selects cardinal hue while RTL preserves hue orientation',async({page})=>{const slider=wheel(page).getByRole('slider');await point(page,slider,.95,.5);await hueNear(slider,90);await wheel(page).evaluate(n=>n.setAttribute('dir','rtl'));await point(page,slider,.5,.05);await hueNear(slider,0);await expect(slider).toHaveCSS('direction','ltr');});
 test('wheel pointer cancellation restores starting hue',async({page})=>{const slider=wheel(page).getByRole('slider');await slider.scrollIntoViewIfNeeded();const b=(await slider.boundingBox())!;await page.mouse.move(b.x+b.width*.95,b.y+b.height/2);await page.mouse.down();await hueNear(slider,90);await slider.dispatchEvent('pointercancel',{pointerId:1});await page.mouse.up();await expect(slider).toHaveAttribute('aria-valuenow','0');});
 test('disabled wheel is removed from sequential focus and rejects pointer changes',async({page})=>{await wheel(page).evaluate(n=>(n as any).disabled=true);const slider=wheel(page).getByRole('slider');await expect(slider).toHaveAttribute('aria-disabled','true');await expect(slider).toHaveAttribute('tabindex','-1');await point(page,slider,.95,.5);await expect(slider).toHaveAttribute('aria-valuenow','0');});
 test('scoped wheel and picker geometry hooks leave the other picker unchanged',async({page})=>{await wheel(page).evaluate(n=>(n as HTMLElement).style.setProperty('--en-color-wheel-size','180px'));await expect(wheel(page).locator('[part=base]')).toHaveCSS('width','180px');await picker(page).evaluate(n=>(n as HTMLElement).style.setProperty('--en-color-picker-preview-size','64px'));await expect(picker(page).locator('[part=preview]')).toHaveCSS('width','64px');await expect(page.locator('native-picker').nth(1).locator('[part=preview]')).toHaveCSS('width','48px');});
 test('metadata-selected public input customization stays scoped',async({page})=>{const inspector=page.locator('theme-inspector');await inspector.getByRole('combobox').selectOption('--en-control-radius');await inspector.getByRole('button',{name:'Apply scoped override'}).click();await expect(picker(page).getByRole('textbox')).toHaveCSS('border-radius','16px');expect(await page.locator('native-picker').nth(1).getByRole('textbox').evaluate(n=>getComputedStyle(n).borderRadius)).not.toBe('16px');await expect(inspector.getByRole('status')).toHaveText('Applied --en-control-radius');});
 test('barrels share fragment identity and metadata without registering elements',async({page})=>{expect(await page.evaluate(()=>{const {root,explicit,metadata}=(window as any).styleExports;return {same:root.colorPickerStyles===explicit.colorPickerStyles&&root.colorPlaneStyles===explicit.colorPlaneStyles,metadata:root.styleOverrideNames===metadata.styleOverrideNames,privateOverrides:metadata.styleOverrideNames.some((n:string)=>n.startsWith('--_')),registered:!!customElements.get('en-color-picker')};})).toEqual({same:true,metadata:true,privateOverrides:false,registered:false});});
 test('narrow viewport with enlarged text retains inputs without page overflow',async({page})=>{await page.setViewportSize({width:360,height:900});await page.evaluate(()=>document.documentElement.style.fontSize='20px');await expect.poll(()=>columns(plane(page).locator('[part=base]'))).toBe(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(360);await expect(picker(page).getByRole('textbox')).toBeVisible();});
 test('reduced motion removes plane thumb transitions',async({page})=>{await page.emulateMedia({reducedMotion:'reduce'});await expect(plane(page).locator('[part=thumb]')).toHaveCSS('transition-duration','0s');await expect(plane(page).locator('[part=thumb]')).toHaveCSS('scale','none');});
});
