export const invalidDefinitionCases = validCSS => [
  ['duplicate name', validCSS + validCSS, /Duplicate definition/],
  ['conditional definition', '@media (width > 1px) { @function --a(){result:1px;} }', /unconditional/],
  ['layered definition', '@layer a { @function --a(){result:1px;} }', /unconditional/],
  ['scoped definition', '.a { @function --a(){result:1px;} }', /unconditional/],
  ['type annotation', '@function --a(--x <length>){result:var(--x);}', /without types/],
  ['return type', '@function --a(--x) returns <length>{result:var(--x);}', /untyped/],
  ['default', '@function --a(--x:2px){result:var(--x);}', /without types/],
  ['duplicate parameter', '@function --a(--x,--x){result:var(--x);}', /unique/],
  ['shadowing local', '@function --a(--x){--x:3px;result:var(--x);}', /exactly one/],
  ['cyclic local', '@function --a(){--x:var(--x);result:var(--x,8px);}', /exactly one/],
  ['caller environment', '@function --a(){result:var(--caller);}', /must reference a parameter/],
  ['parameter fallback', '@function --a(--x){result:var(--x,8px);}', /without a fallback/],
  ['unsupported native function', '@function --a(--x){result:env(--x);}', /Definitions allow only/],
  ['uppercase var', '@function --a(--x){result:VAR(--x);}', /Definitions allow only/],
  ['composition', '@function --a(){result:--b();}', /composition/],
  ['ordered nesting', '@mixin --a(){@result{&{color:blue} color:red;}}', /ordinary declarations/],
  ['nested apply', '@mixin --a(){@result{@apply --b();}}', /ordinary declarations/],
  ['conditional body', '@mixin --a(){@result{@media (width>1px){color:red}}}', /ordinary declarations/],
  ['bare current mixin', '@mixin --a {color:red}', /untyped/],
  ['direct mixin body', '@mixin --a(){color:red}', /@result block/],
  ['empty mixin', '@mixin --a(){@result{}}', /Empty mixins/],
  ['important', '@mixin --a(){@result{color:red!important}}', /ordinary declarations/],
  ['escaped identifier', '@function --a(--x){result:v\\61r(--x)}', /Escapes/],
];
