import {LitElement,html,css,nothing} from 'lit';
import {repeat} from 'lit/directives/repeat.js';
import {ifDefined} from 'lit/directives/if-defined.js';
import {TableModel} from '@en-reve/primitives/state/table.js';
import {tableColgroup,tableRows,type TableColumn} from '@en-reve/primitives/templates/table.js';
import {foundationStyles} from '@en-reve/styles/foundations.js';
import {buttonStyles} from '@en-reve/styles/buttons.js';
import {tableStyles} from '@en-reve/styles/table.js';
import {paginationStyles} from '@en-reve/styles/pagination.js';
import {carouselStyles,carouselSlideStyles} from '@en-reve/styles/carousel.js';
const portable=new URL(location.href).searchParams.get('delivery')==='css';
const sheet=(family:string)=>portable?html`<link rel="stylesheet" href=${`/${family}.css`}>`:nothing;
type RecordItem={id:string,name:string,count:number};
class ConsumerTable extends LitElement{
 static override styles=[...(portable?[]:[foundationStyles,buttonStyles,tableStyles]),css`:host{display:block;min-inline-size:0}.en-table-native{overflow:auto;max-block-size:260px;position:relative;scroll-padding-block:50px}table{min-inline-size:720px}.en-table-selection{inline-size:64px}input{inline-size:24px;block-size:24px}caption{text-align:start}.toolbar{display:flex;gap:8px;margin-block:8px}`];
 selected=new Set<string>();veto=false;
 readonly columns:TableColumn<RecordItem>[]=[{key:'select',label:'Select record',width:'64px',className:'en-table-selection',renderCell:item=>html`<input type="checkbox" aria-label=${`Select ${item.name}`} .checked=${this.selected.has(item.id)} @change=${(event:Event)=>this.select(item.id,event)}>`},{key:'name',label:'Name',rowHeader:true,width:'380px',compare:(a,b)=>a.name.localeCompare(b.name),renderCell:item=>html`<a href=${`#${item.id}`}>${item.name}</a>`},{key:'count',label:'Count',compare:(a,b)=>a.count-b.count,renderCell:item=>item.count}];
 readonly model=new TableModel({items:Array.from({length:30},(_,i)=>({id:String(i+1),name:`Asset ${String(i+1).padStart(2,'0')}`,count:30-i})),getKey:(item:RecordItem)=>item.id,columns:this.columns,mode:'all'});
 private select(id:string,event:Event){const input=event.target as HTMLInputElement,was=this.selected.has(id),next=new Set(this.selected);if(input.checked)next.add(id);else next.delete(id);const proposal=new CustomEvent('before-selection',{detail:{keys:[...next]},cancelable:true,bubbles:true,composed:true});if(this.veto)proposal.preventDefault();this.dispatchEvent(proposal);if(proposal.defaultPrevented)input.checked=was;else{this.selected=next;this.requestUpdate();}}
 sort(key:string){this.model.setSort({column:key,direction:this.model.sort?.column===key&&this.model.sort.direction==='ascending'?'descending':'ascending'});this.requestUpdate();}
 protected override render(){return html`${sheet('table')}<div class="en-foundation"><div class="toolbar"><button class="en-button" @click=${()=>{this.model.setMode(this.model.mode==='all'?'paginated':'all');this.model.setPageSize(5);this.requestUpdate();}}>Toggle paging</button><button class="en-button" @click=${()=>{this.model.setPage(this.model.page+1);this.requestUpdate();}}>Next records</button></div><div class="en-table-native" sticky="both" data-en-sticky-selection tabindex="0" role="region" aria-label="Asset records"><table><caption>Project assets</caption>${tableColgroup(this.columns)}<thead><tr>${this.columns.map(column=>html`<th class=${ifDefined(column.className)} scope="col" aria-sort=${ifDefined(this.model.sort?.column===column.key?this.model.sort.direction:undefined)}>${column.compare?html`<button class="en-button" @click=${()=>this.sort(column.key)} aria-label=${`Sort ${column.label}`}>${column.label}</button>`:html`<span class="en-sr-only">${column.label}</span>`}</th>`)}</tr></thead><tbody>${tableRows(this.model,this.columns,{rowSelected:item=>this.selected.has(item.id)})}</tbody><tfoot><tr><td colspan="3">${this.model.items.length} records; ${this.selected.size} selected</td></tr></tfoot></table></div><p role="status">${this.selected.size} selected</p></div>`;}
}
class ConsumerPagination extends LitElement{
 static override styles=[...(portable?[]:[foundationStyles,buttonStyles,paginationStyles]),css`:host{display:block;inline-size:100%;max-inline-size:100%}.en-pagination__pages{--_en-pagination-digits:2ch}.en-pagination__direct:popover-open{display:grid}.en-pagination__direct{inset:auto;inset-inline-start:16px;inset-block-start:16px}.en-pagination__jump .en-button{grid-row:auto}`];
 current=10;total=20;veto=false;private invoker:HTMLButtonElement|null=null;
 async go(page:number){const next=Math.min(this.total,Math.max(1,Math.trunc(page)));if(!Number.isFinite(page))return false;const event=new CustomEvent('before-page',{detail:{page:next},cancelable:true,bubbles:true,composed:true});if(this.veto)event.preventDefault();this.dispatchEvent(event);if(event.defaultPrevented)return false;this.current=next;this.requestUpdate();await this.updateComplete;return true;}
 private open(event:Event){this.invoker=event.currentTarget as HTMLButtonElement;this.invoker.dataset.jumpInvoker='';const pop=this.renderRoot.querySelector<HTMLElement>('[popover]')!;pop.showPopover();this.renderRoot.querySelector<HTMLInputElement>('#page')!.value=String(this.current);this.renderRoot.querySelector<HTMLInputElement>('#page')!.focus();}
 private close(){const pop=this.renderRoot.querySelector<HTMLElement>('[popover]')!;if(pop.matches(':popover-open'))pop.hidePopover();this.invoker?.focus();delete this.invoker?.dataset.jumpInvoker;}
 private gap(side:'before'|'after',omitted:boolean,action:boolean){return html`<span class="en-pagination__intermediate-gap" data-intermediate-column=${side==='before'?'2':'4'} ?data-wide-gap=${omitted} ?data-gap-action=${action}><span class="en-pagination__gap-decoration" aria-hidden="true">${omitted?'…':''}</span><button class="en-button en-pagination__gap-trigger" aria-label="Choose page" @click=${this.open}>…</button></span>`;}
 protected override render(){const pages=[...new Set([1,...Array.from({length:5},(_,i)=>Math.min(this.total-1,Math.max(2,this.current-2+i))),this.current,this.total])].sort((a,b)=>a-b),tail=this.current>=this.total-2;return html`${sheet('pagination')}<nav class="en-pagination en-foundation" aria-label="Asset pages"><div class="en-pagination__actions"><button class="en-button" part="previous" aria-label="Previous page" ?disabled=${this.current===1} @click=${()=>this.go(this.current-1)}>Previous</button><div class="en-pagination__pages" data-intermediate data-omitted>${pages.map((page,i)=>html`${i===1?this.gap('before',pages[1]>2,tail):nothing}${i===pages.length-1?this.gap('after',pages.at(-2)!<this.total-1,!tail):nothing}<button class="en-button" data-page=${page} data-intermediate-column=${ifDefined(page===1?'1':page===this.total?'5':page===this.current?'3':undefined)} aria-label=${`Page ${page}`} aria-current=${ifDefined(page===this.current?'page':undefined)} @click=${()=>this.go(page)}>${page}</button>`)}</div><div class="en-pagination__middle"><span class="en-pagination__compact-status">${this.current} of ${this.total}</span><button class="en-button en-pagination__direct-trigger" aria-label="Choose page" @click=${this.open}>…</button></div><button class="en-button" part="next" aria-label="Next page" ?disabled=${this.current===this.total} @click=${()=>this.go(this.current+1)}>Next</button></div><p class="en-pagination__wide-status en-pagination__status" role="status">Page ${this.current} of ${this.total}</p><div class="en-pagination__direct" popover="auto" data-positioned @keydown=${(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();this.close();}}} @toggle=${(e:Event)=>{if((e as ToggleEvent).newState==='closed'){delete this.invoker?.dataset.jumpInvoker;}}}><form class="en-pagination__jump" @submit=${async(e:SubmitEvent)=>{e.preventDefault();const input=this.renderRoot.querySelector<HTMLInputElement>('#page')!;if(input.checkValidity()&&await this.go(input.valueAsNumber))this.close();}}><label for="page">Page number</label><input id="page" type="number" min="1" max=${this.total} required><button class="en-button" type="button" @click=${this.close}>Cancel</button><button class="en-button" type="submit">Go to page</button></form></div></nav>`;}
}
class ConsumerCarousel extends LitElement{
 static override styles=[...(portable?[]:[foundationStyles,buttonStyles,carouselStyles,carouselSlideStyles]),css`:host{display:block}.collection-track{--en-carousel-viewport-size:160px}.collection-slide{box-sizing:border-box;padding:4px}.slide{padding:16px}.thumbnail{background:var(--en-color-action,#5577cc)}.viewport{max-inline-size:100%}`];
 current=0;count=12;controls=true;picker=true;veto=false;width=600;private observer?:ResizeObserver;private frame=0;
 override connectedCallback(){super.connectedCallback();this.updateComplete.then(()=>{if(!this.isConnected)return;this.observer=new ResizeObserver(()=>this.measure());this.observer.observe(this);this.measure();});}
 override disconnectedCallback(){super.disconnectedCallback();this.observer?.disconnect();cancelAnimationFrame(this.frame);}
 private measure(){const v=this.renderRoot.querySelector<HTMLElement>('.viewport');if(!v)return;const style=getComputedStyle(v),width=v.clientWidth-parseFloat(style.paddingLeft)-parseFloat(style.paddingRight);if(width>0&&Math.abs(width-this.width)>.5){this.width=width;this.requestUpdate();this.updateComplete.then(()=>this.reveal());}}
 private reveal(){const v=this.renderRoot.querySelector<HTMLElement>('.viewport'),slide=this.renderRoot.querySelector<HTMLElement>(`[data-slide="${this.current}"]`);if(!v||!slide)return;const a=v.getBoundingClientRect(),b=slide.getBoundingClientRect(),rtl=getComputedStyle(v).direction==='rtl',padding=parseFloat(getComputedStyle(v).paddingInlineStart);v.scrollBy({left:rtl?b.right-a.right+padding:b.left-a.left-padding,behavior:'instant'});}
 async go(index:number){const next=Math.max(0,Math.min(this.count-1,Math.trunc(index)));if(!Number.isFinite(index))return false;const event=new CustomEvent('before-slide',{detail:{index:next},cancelable:true,bubbles:true,composed:true});if(this.veto)event.preventDefault();this.dispatchEvent(event);if(event.defaultPrevented)return false;this.current=next;this.requestUpdate();await this.updateComplete;this.reveal();return true;}
 private scrolled(){cancelAnimationFrame(this.frame);this.frame=requestAnimationFrame(()=>{const v=this.renderRoot.querySelector<HTMLElement>('.viewport')!;const next=Math.min(this.count-1,Math.max(0,Math.round(Math.abs(v.scrollLeft)/this.width)));if(next!==this.current){this.current=next;this.requestUpdate();}});}
 protected override render(){const first=Math.max(0,Math.min(this.count-5,this.current-2)),picks=Array.from({length:Math.min(5,this.count)},(_,i)=>first+i);return html`${sheet('carousel')}<section class="base en-foundation" role="region" aria-roledescription="carousel" aria-label="Cover studies"><div class="viewport" data-collection ?data-controls-ready=${this.controls} tabindex="0" aria-label="Cover slides" @scroll=${this.scrolled}><div class="collection-track" style=${`width:${this.count*this.width}px`}>${Array.from({length:this.count},(_,i)=>html`<article class="collection-slide" data-slide=${i} style=${`inset-inline-start:${i*this.width}px;width:${this.width}px`} role="group" aria-roledescription="slide" aria-label=${`${i+1} of ${this.count}`}><div class="slide"><h2>Cover ${i+1}</h2><p>A study of light and composition.</p><a href=${`#cover-${i+1}`} tabindex=${i===this.current?0:-1}>Review cover ${i+1}</a></div></article>`)}</div></div>${this.controls?html`<div class="controls" data-boundaries><button class="en-button" aria-label="First slide" ?disabled=${this.current===0} @click=${()=>this.go(0)}>First</button><button class="en-button" aria-label="Previous slide" ?disabled=${this.current===0} @click=${()=>this.go(this.current-1)}>Previous</button><span class="position" role="status">${this.current+1} of ${this.count}</span><button class="en-button" aria-label="Next slide" ?disabled=${this.current===this.count-1} @click=${()=>this.go(this.current+1)}>Next</button><button class="en-button" aria-label="Last slide" ?disabled=${this.current===this.count-1} @click=${()=>this.go(this.count-1)}>Last</button></div>`:nothing}${this.picker?html`<div class="picker" data-bounded style="--_en-picker-count:5" role="group" aria-label="Choose cover">${repeat(picks,i=>i,i=>html`<button class="en-button picker-button" aria-label=${`Show cover ${i+1}`} aria-current=${ifDefined(i===this.current?'true':undefined)} @click=${()=>this.go(i)}><span class="thumbnail" aria-hidden="true"></span><span class="picker-number">${i+1}</span></button>`)}</div><p class="picker-range">Covers ${first+1}–${first+picks.length} of ${this.count}</p>`:nothing}</section>`;}
}
customElements.define('consumer-table',ConsumerTable);customElements.define('consumer-pagination',ConsumerPagination);customElements.define('consumer-carousel',ConsumerCarousel);
