import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const base='artifacts/scoped-registry-phase-5-ssr-investigation';
const data=JSON.parse(await readFile(`${base}/comparison.json`));
const prior='artifacts/scoped-registry-production-v1/page/comparison-74c12d755954.html';
let html=await readFile(prior,'utf8');
const esc=x=>String(x).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const number=x=>x==null?'—':new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(x);
function table(id,title,description,rows,columns,note){return `<section id="${id}" data-comparison><div class="section-heading"><h2>${title}</h2><span class="count" data-count>${rows.length} comparisons</span></div><div data-filters class="filters" hidden><label>Search<input type="search"></label><label>Metric<select data-metric-filter><option value="">All metrics</option>${[...new Set(rows.map(r=>r.metric))].map(m=>`<option>${esc(m)}</option>`).join('')}</select></label><button data-reset>Clear filters</button></div><en-table size="small" label="${title} scroll area"><table aria-describedby="${id}-note"><caption>${description}</caption><thead><tr>${columns.map(([key,label,numeric],i)=>`<th scope="col" class="${numeric?'numeric':''}"><button disabled data-key="${key}" data-index="${i}" data-type="${numeric?'number':'text'}" data-label="${esc(label)}" aria-label="${esc(label)}: sort ascending">${esc(label)}<span aria-hidden="true">↕</span></button></th>`).join('')}</tr></thead><tbody>${rows.map((r,j)=>`<tr data-index="${j}" data-metric="${esc(r.metric)}" data-search="${esc(Object.values(r).join(' ').toLowerCase())}">${columns.map(([key,,numeric],i)=>`<${i?'td':'th scope="row"'} class="${numeric?'numeric':''}" data-value="${esc(r[key]??'')}">${numeric?number(r[key]):esc(r[key])}</${i?'td':'th'}>`).join('')}</tr>`).join('')}</tbody></table></en-table><p data-empty hidden>No matching comparisons.</p><p id="${id}-note" class="direction-note">${note}</p><p class="sr-only" role="status" aria-live="polite" aria-atomic="true"></p></section>`;}
const labels={'warm':'Warm renderToString','isolated-api':'Unchanged isolated API','fresh-profiled':'Fresh worker · instrumented','prewarmed-single-use':'Prewarmed single-use · prototype'};
const summaries=data.summaries;
const rows=summaries.map(s=>({policy:labels[s.policy],metric:'Server render request latency',n:s.n,request:s.metrics.requestMs.median,preparation:s.metrics.preparationMs?.median??null,total:s.metrics.creationToResultMs?.median??null,shutdown:s.metrics.shutdownMs?.median??null,cycle:s.metrics.creationToStoppedMs?.median??null,delta:s.versusApi.difference,low:s.versusApi.ci95[0],high:s.versusApi.ci95[1]}));
const stages={startupToEntryMs:'Worker creation → entry point',installMs:'DOM shim import / setup',registrationImportMs:'Registration helper import',ssrImportMs:'SSR entry and dependency import',applicationImportMs:'Application module import',definitionsMs:'Collect and register definitions',templateMs:'Create template result',renderMs:'Render and buffer HTML',requestTransferMs:'Prepared worker request handoff',resultTransferMs:'Result message delivery',otherMs:'Other timing gaps / bookkeeping',shutdownMs:'Worker termination after result'};
const fresh=summaries.find(s=>s.policy==='fresh-profiled'),prepared=summaries.find(s=>s.policy==='prewarmed-single-use');
const stageRows=Object.entries(stages).map(([key,metric])=>({metric,n:30,fresh:fresh.metrics[key].median,prewarmed:prepared.metrics[key].median}));
const supplemental=`<section id="ssr-followup"><h2>SSR follow-up: setup dominates the cost</h2><p>This is a separate diagnostic capture. The 540 frozen browser samples, retention runs and earlier server comparison below remain unchanged. Client performance remains the primary adoption criterion; request-isolated server latency is an optional deployment tradeoff.</p><p>The unchanged API reproduced <strong>${number(summaries[1].metrics.requestMs.median)} ms</strong>. A prepared single-use worker returned HTML in <strong>${number(prepared.metrics.requestMs.median)} ms after submission</strong>, excluding <strong>${number(prepared.metrics.preparationMs.median)} ms of advance preparation</strong>. End-to-end worker creation through result was ${number(prepared.metrics.creationToResultMs.median)} ms. This moves setup earlier and does not demonstrate less server work.</p><p>All arms produced identical 169,496-byte HTML (SHA-256 <code>${data.output.sha256}</code>). Ten checks cover conflicting same-tag definitions and fresh module state; the parent registry remains unchanged. Each worker renders only one request, with no template warmup in the prewarmed worker. Thirty samples per arm, five excluded warmup blocks, randomized serial order; all samples retained.</p><p><strong>Deployment options:</strong> use a warm process for a compatible definition set, generate HTML at build time or cache appropriate output, or choose per-request isolation when needed. Browser scoped registries and progressive hydration do not require a fresh server worker. Build-time generation removes this work from navigation, but still delivers HTML that the browser must download and process.</p><p><strong>Recommendation:</strong> keep the existing client comparison as the main Phase 5 evidence. Retain server isolation as opt-in. Do not add a production pool solely to unblock this phase. If request-time isolated SSR becomes important, measure pool capacity, idle memory, refill behavior and tail latency before productizing preparation. This prototype has no queue, cancellation, pool replenishment or throughput guarantee.</p></section>`+
 table('ssr-latency','SSR follow-up · request and preparation costs', 'All values are milliseconds; medians of 30 samples each. Same frozen Phase 5 packages and 50-command palette.',rows,[['policy','Execution strategy'],['n','Samples',true],['request','Request median',true],['preparation','Advance preparation median',true],['total','Creation → result median',true],['shutdown','Post-result termination median',true],['cycle','Creation → terminated median',true],['delta','Request − isolated API Δ',true],['low','95% Δ lower',true],['high','95% Δ upper',true]],'<strong>Change direction:</strong> Δ and interval bounds are request latency minus the unchanged isolated API in this new capture. Negative is faster; positive is slower. Intervals spanning zero do not establish a direction or equivalence. Prewarmed request latency excludes preparation; compare creation-to-result and creation-to-terminated as well. — means not measured, not zero. The warm process has setup outside its timer. Separate medians do not necessarily add up.')+
 table('ssr-stages','SSR follow-up · stage attribution','Instrumented fresh and prewarmed single-use workers. Each column is the median stage duration in milliseconds.',stageRows,[['metric','Stage'],['n','Samples',true],['fresh','Fresh worker',true],['prewarmed','Prewarmed worker',true]],'Lower durations generally mean less latency for equivalent work. There are no change columns in this table. Sequential imports attribute transitive/shared loading to the first importing stage; these are elapsed times, not exclusive CPU times. Startup includes creating the worker and reaching its entry point. DOM shim setup includes the installed upstream CSS-import hook. We have not separately attributed that hook. Individual stage medians do not add up exactly to the median total. Termination is measured after the result; in the public API, a following queued request can also wait for the prior worker to exit.')+
 `<section><h2>SSR diagnostic limits and evidence</h2><p>${esc(data.method)} Prewarming was completed before each request with no burst or idle wait experiment. This is a latency prototype, not a deployment capacity result. No new heap/retention or throughput campaign was run; the frozen client retention evidence remains separate. Warm filesystem caches and a shared local workstation limit generalization. Host: ${esc(JSON.stringify(data.host))}.</p><p>Source: <code>probes/scoped-hydration/ssr-profile</code>. Raw data: <code>artifacts/scoped-registry-phase-5-ssr-investigation/campaign-v1/samples.json</code>. All 98 frozen Phase 5 evidence files and 2,751 extracted library files were verified against the frozen packages. <a href="http://127.0.0.1:4206/comparison-74c12d755954.html?progress-report">Original Phase 5 report</a>.</p></section>`;
html=html.replace('</style>','main p,main code{overflow-wrap:anywhere}</style>');
html=html.replace('<title>Phase 5 · Scoped SSR performance</title>','<title>Phase 5 · Client performance and SSR cost investigation</title>');
html=html.replace('<a href="#server">Server cost</a>','<a href="#server">Frozen server cost</a><a href="#ssr-followup">SSR investigation</a>');
html=html.replace('</header>','</header><p class="direction-note">Server follow-up added: <a href="#ssr-followup">cost attribution and single-use preparation</a>. The frozen client and historical comparisons below are unchanged.</p>');
html=html.replace('<section id="historical"',supplemental+'<section id="historical"');
const sha256=createHash('sha256').update(html).digest('hex'),filename=`comparison-${sha256.slice(0,12)}.html`;
await writeFile(`artifacts/scoped-registry-production-v1/page/${filename}`,html,{flag:'wx'});
await writeFile(`${base}/${filename}`,html,{flag:'wx'});
await writeFile(`${base}/report.json`,JSON.stringify({filename,sha256,url:`http://127.0.0.1:4206/${filename}?progress-report`,previousReport:'comparison-74c12d755954.html',tables:7},null,2)+'\n');
console.log(filename);
