import os
from pathlib import Path
import json,html,hashlib,statistics
base=Path(os.environ.get('PHASE6_BASE','artifacts/scoped-registry-phase-6'));data=json.loads((base/'analysis.json').read_text());esc=lambda v:html.escape(str(v));fmt=lambda v:'—' if v is None else f'{v:,.2f}'.rstrip('0').rstrip('.') if isinstance(v,(int,float)) else esc(v)
columns=[('browser','Browser',0),('profile','Profile',0),('action','Interaction',0),('registry','Registry',0),('metric','Metric',0),('n','Samples',1),('parentMedian','Phase 5 parent',1),('median','Phase 6',1),('change','Phase 6 − parent Δ',1),('percent','Change %',1),('low','95% Δ lower',1),('high','95% Δ upper',1),('p75','Phase 6 p75',1),('spread','Phase 6 min … max',0)]
labels={'shellReadyMs':'Essential shell ready · ms','startupNodes':'Initial live nodes','startupElements':'Initial live elements','startupJSBytes':'Initial JS bodies · gzip bytes','firstFocusMs':'First calendar focus · ms','firstFrameMs':'First focus + next frame · ms','navigationToFocusMs':'Navigation to first focus · ms','secondFocusMs':'Repeat calendar focus · ms','selectionUpdateMs':'Accepted selection to update · ms','afterJSBytes':'JS bodies after use · gzip bytes','afterNodes':'Live nodes after use/close','unusedBytes':'Unused JS bodies · gzip bytes','unusedNodes':'Unused live nodes','abandonedBytes':'Abandoned-intent JS bodies · gzip bytes'}
def table(ident,title,rows,cols,note):
 filters=''.join(f'<option>{esc(m)}</option>' for m in sorted(set(str(r.get('metric','')) for r in rows)))
 head=''.join(f'<th scope="col"><button disabled data-key="{key}" data-index="{i}" data-type="{"number" if numeric else "text"}" data-label="{esc(label)}">{esc(label)}<span aria-hidden="true">↕</span></button></th>' for i,(key,label,numeric) in enumerate(cols))
 body=''
 for j,row in enumerate(rows):
  cells=''.join(f'<td data-value="{esc(row.get(key) if row.get(key) is not None else "")}">{fmt(row.get(key))}</td>' for key,_,_ in cols)
  body+=f'<tr data-index="{j}" data-metric="{esc(row.get("metric",""))}" data-search="{esc(" ".join(str(v) for v in row.values()).lower())}">{cells}</tr>'
 return f'<section id="{ident}" data-comparison><h2>{title}</h2><span data-count>{len(rows)} rows</span><div data-filters class="filters" hidden><label>Search<input type="search"></label><label>Metric<select data-metric-filter><option value="">All metrics</option>{filters}</select></label><button data-reset>Clear filters</button></div><en-table label="{title}" size="small"><table aria-describedby="{ident}-note"><caption>{title}</caption><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table></en-table><p data-empty hidden>No matching rows.</p><p id="{ident}-note" class="direction-note">{note}</p><p role="status" class="sr-only" aria-live="polite"></p></section>'
note='<strong>Change direction:</strong> Δ, percentage, and interval bounds are Phase 6 minus its matched Phase 5 parent. Negative latency, resource-body bytes and node changes are better for equivalent behavior; positive values mean added cost. Intervals crossing zero do not establish a direction or equivalence. Intervals are exploratory, with no correction for multiple comparisons. A next-frame opportunity is not proof of paint. Selection timing begins at the accepted field event, not the physical gesture. — means unavailable.'
def rows(run):
 out=[]
 for r in data['rows']:
  if r['run']!=run or r['arm']=='parent/eager':continue
  out.append(dict(r,registry=r['mode']+(' → global fallback' if r['mode']=='scoped' and r['actualModes']==['global'] else ''),metric=labels.get(r['metric'],r['metric']),low=r.get('interval',[None,None])[0],high=r.get('interval',[None,None])[1],spread=fmt(r['minimum'])+' … '+fmt(r['maximum'])))
 return out
get=lambda metric,profile='constrained',action='keyboard':next(r for r in data['rows'] if r['run']=='final-cold' and r['arm']=='candidate/dom' and r['mode']=='scoped' and r['browser']=='chromium' and r['profile']==profile and r['action']==action and r['metric']==metric)
summaries={run:json.loads((base/run/'summary.json').read_text()) for run in data['runs']}
timing=sum(v['successful']-v['retention']*v['arms'] for v in summaries.values());retentionCount=sum(v['retention']*v['arms'] for v in summaries.values())
confirmationRuns=[run for run in data['runs'] if run.startswith('confirmation-')]
budget=json.loads((base/'budget-check.json').read_text());assert budget['automatedGate']=='pass'
manifest=json.loads((base/'final-cold/manifest.json').read_text());host=manifest['host']
versions=sorted({x['browser']+' '+x['browserVersion'] for x in map(json.loads,(base/'final-cold/samples.jsonl').read_text().splitlines())})
archive=os.environ.get('PHASE6_ARCHIVE','showcases/performance/baselines/scoped-registry-phase-6-v2')
first=get('firstFocusMs');nodes=get('startupNodes');ready=get('shellReadyMs');repeat=get('secondFocusMs');byte=get('startupJSBytes')
main=f'''<header><p class="eyebrow">En Rêve / Phase 6</p><h1>Less initial date-picker DOM, measured first-use cost</h1><p>Matched production date route: sealed Phase 5 parent versus opt-in Phase 6 construction deferral. Calendar code stays eager; the grid is constructed at first opening and retained for repeat use.</p><nav><a href="#final-timing">Cold comparisons</a><a href="#warm">Warm comparisons</a><a href="#confirmation">Firefox confirmation</a><a href="#retention">Retention</a><a href="#history">Earlier phases</a><a href="http://127.0.0.1:4240/?progress-report">Manual date review</a></nav></header>
<section><h2>What changed</h2><p>Initial live DOM: <strong>{fmt(nodes['parentMedian'])} → {fmt(nodes['median'])} nodes ({fmt(nodes['percent'])}%)</strong>. Initial compressed JS bodies: {fmt(byte['parentMedian'])} → {fmt(byte['median'])} bytes, an added {fmt(byte['change'])} bytes.</p><p>Constrained Chromium, scoped mode: first focus <strong>{fmt(first['parentMedian'])} → {fmt(first['median'])} ms</strong>; repeat focus {fmt(repeat['parentMedian'])} → {fmt(repeat['median'])} ms. Essential shell readiness {fmt(ready['parentMedian'])} → {fmt(ready['median'])} ms. These are lab measurements of this date route, not command-palette or field INP results.</p><p>{timing:,} successful timing samples, with at least 30 per configuration, plus {retentionCount} separate 100-cycle retention runs. Cold, warm and any independent confirmation distributions remain separate. All three engines and explicit global/scoped-requested paths are covered by the primary campaign; Firefox’s scoped request uses the global fallback and is labeled accordingly.</p><p>A preceding closeout campaign completed 960 timing samples and 20 retention runs but was not promoted: WebKit reported a +4,103-byte increase, 7 bytes over the unchanged cap. Its complete distributions and source are retained separately in the new archive. Developer-facing error text was shortened; loading/retry messages and focus behavior were unchanged. The final candidate was fully requalified and remeasured.</p><p>The default remains eager, and range remains eager. Eager consumers also acquire approximately 4 KB of additional compressed code; preserving behavior is not a claim of zero payload overhead. Optional chunk loading is available explicitly but is not the recommended immediate-use policy: the earlier exploratory study found substantial constrained-network first-use costs. Its results preceded the compact loader and are not pooled into these final distributions.</p><p><strong>Acceptance:</strong> automated focus, form, lifecycle and deferred SSR checks passed, including repeated retry/localization and re-enable coverage. The unchanged practical budgets pass. Targeted VoiceOver review was accepted in Chrome, Firefox and Safari. Counted, localized failure messages resolve the reviewed Safari retry case. Original full weekday/date names remain: repeated column/date weekday speech in Chrome/Firefox is accepted to preserve WebKit context. Firefox’s functional native date button remains visible. Physical mobile and date-specific IME are not claimed. No universal focus delay, native-picker substitution, detached cache, or discard/recreate policy was introduced.</p></section>'''
if os.environ.get('PHASE6_REPORT_OUTPUT'):
 # Historical acceptance is never inherited by a freshly generated report.
 main=main[:main.index('<section>')]+f'<section><h2>Fresh campaign evidence</h2><p>{timing:,} timing samples and {retentionCount} separate retention runs. Cold, warm and confirmation distributions remain separate. The unchanged automated budgets pass. Exact qualification receipts accompany this run; human review, physical devices, assistive technology and IME acceptance have not been established by this execution.</p><p>These measurements cover the explicit historical parent and candidate overlay used by the date protocol. They do not establish a whole-library runtime reduction or inherit acceptance from a prior report.</p></section>'
main+=table('final-timing','Cold production date comparison',rows('final-cold'),columns,note)
main+=table('confirmation','Independent budget confirmations',sum((rows(run) for run in confirmationRuns),[]),columns,note+' Independent confirmations remain separate from primary samples. The budget record retains each original uncertainty and its resolution.') if confirmationRuns else '<section id="confirmation"><h2>Budget confirmation</h2><p>No additional confirmation was required for the final candidate: the primary intervals fit the unchanged practical limits. The rejected preceding campaign remains separate.</p></section>'
main+=table('warm','Warm HTTP-cache, new-document comparison',rows('final-warm'),columns,note+' Warm runs navigate once in the same context, then create a new document. They differ from same-document reopening. Encoded resource-body bytes describe consumed resources and include cache hits; they are not network transfer bytes.')
ret=[]
for r in data['retention']:
 ret.append(dict(r,registry=r['mode'],metric='Growth from cycle 10 to cycle 100'))
main+=table('retention','Separate repeated retention runs',ret,[('arm','Arm',0),('registry','Registry',0),('block','Repetition (0–4)',1),('metric','Checkpoint comparison',0),('heapGrowth','Heap Δ bytes',1),('nodesGrowth','DOM nodes Δ',1),('listenersGrowth','Listeners Δ',1),('documents','Documents at cycle 100',1)],'<strong>Change direction:</strong> Negative heap/node/listener growth is lower retained cost; positive growth is added retention. Changes are cycle 100 minus cycle 10 after 300 ms settling and double GC. Five repetitions per arm are descriptive and are not proof of no leaks. Module/registry residency is expected; documents are an absolute count.')
inventory=json.loads((base/'asset-inventory.json').read_text());reference=inventory['rows'][0]['entryOrPreloadGzipBytes'];assetRows=[dict(r,metric='Emitted JavaScript',change=r['entryOrPreloadGzipBytes']-reference) for r in inventory['rows']]
main+=table('assets','Deterministic production asset inventory',assetRows,[('arm','Consumption path',0),('entryOrPreloadGzipBytes','Entry + preload gzip bytes',1),('change','Initial bytes − parent Δ',1),('allEmittedGzipBytes','All emitted gzip bytes',1),('allEmittedRawBytes','All emitted raw bytes',1)],'<strong>Change direction:</strong> Negative initial-byte change is less code; positive is more. These are emitted assets using the same gzip encoder, not measured timing or warm transfer. Browser-reported encoded-body counts can differ slightly (observed in WebKit); acceptance checks each browser’s recorded byte delta. The Phase 6 eager path also pays the new capability’s byte cost despite retaining eager construction. Optional chunk delivery reduces this route’s initial code only modestly and increases total emitted bytes.')
main+='''<section id="history"><h2>Earlier phases and workload boundaries</h2><p><a href="http://127.0.0.1:4206/comparison-11f2c5584bb8.html?progress-report#final-timing">Phase 0–5 historical comparisons</a> preserve the earlier settings/command-palette campaigns, including the final Phase 5 readiness policy. Those workloads cannot be subtracted from this date-picker route. Here “Phase 5 parent” means the exact sealed parent code rebuilt into the same date consumer as Phase 6.</p><p>Phase 6 adds a measured date-specific construction boundary. It does not change the Phase 5 SSR renderer or its request-isolated worker cost. Deferred date SSR omits the calendar and preserves the native input through hydration; no-JavaScript outer-form submission still requires an actually associated native control.</p></section><section><h2>Protocol and limits</h2><p>Exact parent export and enumerated candidate overlay → generated metadata → packed packages → extracted-package Vite consumer. HTTP/2, gzip level 6, fresh browser/context per cold sample, seeded randomized matched blocks. Constrained Chromium uses 4× CPU, 150 ms latency, 1.6 Mbps down and 750 Kbps up. Touch is emulated. No outlier trimming; medians, p75 and full min/max are retained. Bootstrap intervals use 3,000 matched-block resamples and are exploratory. Long-task/layout-shift observations are retained where supported; unsupported observations are null.</p><p>Host and exact browser versions are recorded in the raw campaign manifest and samples. Each cold sample starts a fresh browser/context; host power and thermal observations are recorded at campaign start. Continuous thermal telemetry is unavailable.</p><p>Definitions share module identity and each picker uses its actual render registry. The essential field and dialog stay eager. Calendar nodes are absent initially rather than held in an inert template or detached cache. After use, the calendar stays connected when closed, so the initial node saving does not persist for fields that have been opened. Load-only preparation does not register or construct it. Aborted module requests required reload in Chromium/WebKit; Firefox recovered. Manual Safari repeatedly failed the cached import while the automated WebKit fixture could recover; both observations are preserved. Counted errors make repeated manual failures audible and leave direct native editing available. Failure type and browser cache behavior both matter.</p><p>Archive and raw results: <code>showcases/performance/baselines/scoped-registry-phase-6-v2</code>. Parent: <code>2dc77b5773839f7afdd52ce0b4fc68a6af35d0f4</code>. The report contains its own previously qualified en-table implementation; that report code is outside the measured application bundles.</p></section>'''
main=main.replace('showcases/performance/baselines/scoped-registry-phase-6-v2',esc(archive))
main+=f'<section><h2>Capture environment</h2><p>{esc(host)}; {esc(", ".join(versions))}. Exact receipts and all raw samples accompany the recorded campaign directory.</p><p><a href="http://127.0.0.1:4206/comparison-658adf53dd0c.html?progress-report#final-timing">Original Phase 6 campaign</a> is retained as historical evidence; it predates retry and lifecycle closeout. Current results use freshly measured matched controls.</p></section>'
scaffold=Path('artifacts/scoped-registry-production-v1/page/comparison-11f2c5584bb8.html').read_text();start=scaffold.index('<main>');end=scaffold.index('</main>',start);report=scaffold[:start]+'<main>'+main+scaffold[end:];a=report.index('<title>');b=report.index('</title>',a);report=report[:a]+'<title>Phase 6 · Date-picker performance'+report[b:];digest=hashlib.sha256(report.encode()).hexdigest();filename='comparison-'+digest[:12]+'.html';(base/filename).write_text(report);report_output=Path(os.environ.get('PHASE6_REPORT_OUTPUT','artifacts/scoped-registry-production-v1/page'));report_output.mkdir(parents=True,exist_ok=True);(report_output/filename).write_text(report);(base/'report.json').write_text(json.dumps({'filename':filename,'sha256':digest,'url':f"{os.environ.get('PHASE6_REPORT_ORIGIN','http://127.0.0.1:4206').rstrip('/')}/{filename}?progress-report#final-timing"},indent=2)+'\n');print(filename)
