const phase6Base=process.env.PHASE6_BASE??'artifacts/scoped-registry-phase-6';
import {chromium,firefox,webkit} from '@playwright/test';
import {readFile,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {exclusiveBrowserWork} from '../../showcases/performance/src/lock.mjs';
const base=phase6Base,report=JSON.parse(await readFile(base+'/report.json')),checks=[];
await exclusiveBrowserWork(async()=>{for(const [name,type]of Object.entries({chromium,firefox,webkit})){const browser=await type.launch();try{const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(report.url);await page.waitForFunction(()=>!!customElements.get('en-table'));const confirmed=await page.locator('#confirmation en-table').count();assert.equal(await page.locator('en-table').count(),4+confirmed);assert(await page.locator('#report-return').isVisible());
for(const id of ['final-timing','warm',...(confirmed?['confirmation']:[]),'retention','assets']){const key=id==='retention'?'heapGrowth':'change',button=page.locator(`#${id} button[data-key="${key}"]`);await button.click();assert.equal(await button.evaluate(el=>el.closest('th').getAttribute('aria-sort')),'ascending');await button.click();assert.equal(await button.evaluate(el=>el.closest('th').getAttribute('aria-sort')),'descending');assert.match(await page.locator(`#${id}-note`).textContent(),/negative/i);}
await page.locator('#final-timing input').fill('chromium constrained');assert(await page.locator('#final-timing tbody tr[hidden]').count()>0);await page.screenshot({path:`${base}/report-${name}.png`});await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));if(name==='chromium')await page.screenshot({path:base+'/report-mobile.png'});await page.goto(report.url.replace('?progress-report',''));assert(!(await page.locator('#report-return').isVisible()));assert.deepEqual(errors,[]);checks.push({name,status:'pass'});
}finally{await browser.close();}}});await writeFile(base+'/report-verification.json',JSON.stringify({checks},null,2));
