import { readFile, writeFile } from 'node:fs/promises';
import { resolve, posix } from 'node:path';
import { lab, safeId } from './config.mjs';
import { describe, pairedDifference } from '../src/analysis.mjs';
import { metricGroups, number } from '../experiments/web-awesome-metric-groups.mjs';
export const sampleImplementation=s=>s.variant&&s.variant!=='native'?s.variant:s.system;
const json=x=>JSON.stringify(x,null,2)+'\n';
const esc=x=>String(x??'—').replaceAll('|','\\|').replaceAll('\n',' ');
const fmt=(v,d=1)=>Number.isFinite(v)?v.toFixed(d):'—';
const date=ss=>{const ds=ss.map(s=>s.startedAt?.slice(0,10)).filter(Boolean).sort();return ds.length?ds[0]===ds.at(-1)?ds[0]:ds[0]+' – '+ds.at(-1):'—';};
export function verifyRun(manifest,samples){
 if(!Array.isArray(manifest.jobs))throw Error('Missing planned jobs');
 const seen=new Set();for(const sample of samples){const job=manifest.jobs.find(j=>j.id===sample.id);if(!job||seen.has(sample.id))throw Error('Unknown or duplicate sample '+sample.id);seen.add(sample.id);for(const key of ['system','variant','profile','cache','block','suite','preparation'])if(job[key]!==undefined&&job[key]!==sample[key])throw Error('Sample identity mismatch '+key);if(!['ok','failed'].includes(sample.status))throw Error('Unknown sample status');if(!sample.startedAt||(!sample.finishedAt&&sample.suite!=='lighthouse'&&manifest.options?.suite!=='lighthouse'))throw Error('Missing sample date');}
 return {planned:manifest.jobs.length,recorded:samples.length,successful:samples.filter(s=>s.status==='ok').length,failed:samples.filter(s=>s.status!=='ok').length,missing:manifest.jobs.length-samples.length};
}
export async function campaignReport(directory){
 const state=JSON.parse(await readFile(resolve(directory,'state.json'))),ctx=JSON.parse(await readFile(resolve(directory,'campaign.json')));
 if(!safeId(ctx.id)||state.id!==ctx.id)throw Error('Campaign identity mismatch');
 const inventory=JSON.parse(await readFile(resolve(directory,'inventory.json')));
 const builds=await readFile(resolve(directory,'builds.json'),'utf8').then(JSON.parse).catch(e=>{if(e.code==='ENOENT')return null;throw e;});
 const natives=inventory.systems.filter(s=>ctx.config.systems.includes(s.id));
 const implementations=ctx.config.kind==='current'?[...natives,...builds?.variants||[]]:builds?.variants || natives;
 const names=Object.fromEntries(implementations.map(s=>[s.id,s.label?'En Reve · '+s.label:s.family+' · '+s.technology]));
 const tables=[],coverage=[],all=[];
 function table(title,headers,rows,note=''){tables.push({title,headers,rows,note});}
 for(const id of state.runs){if(!safeId(id))throw Error('Invalid run ID');const dir=resolve(lab,'runs',id);let manifest,text;
  try{manifest=JSON.parse(await readFile(resolve(dir,'manifest.json')));text=await readFile(resolve(dir,'samples.jsonl'),'utf8');}catch(e){if(e.code!=='ENOENT')throw e;coverage.push([id,'—','not acquired',manifest?.jobs?.length ?? '—',0,0,0]);continue;}
  const samples=text.trim().split('\n').filter(Boolean).map(JSON.parse).map(s=>({...s,suite:s.suite||manifest.options?.suite||(id.endsWith('-lighthouse')?'lighthouse':null),runId:id}));
  const counts=verifyRun(manifest,samples);coverage.push([id,date(samples),counts.missing||counts.failed?'incomplete':'complete',counts.planned,counts.recorded,counts.successful,counts.failed]);all.push(...samples);
 }
 table('First reference comparison',['Implementation','Build fingerprint','All JS KiB','All JS gzip KiB','All JS Brotli KiB','HTML KiB','CSS Brotli KiB','JS chunks','Dynamic imports'],implementations.map(s=>{const sum=(ext,key)=>s.assets.filter(a=>a.path.endsWith(ext)).reduce((n,a)=>n+a[key],0);return[names[s.id],s.fingerprint,...[['.js','raw'],['.js','gzip'],['.js','brotli'],['.html','raw'],['.css','brotli']].map(([ext,key])=>fmt(sum(ext,key)/1024)),s.assets.filter(a=>a.path.endsWith('.js')).length,s.assets.flatMap(a=>a.imports||[]).filter(i=>i.dynamic).length];}),'All emitted/minified uncompressed JS and compressed artifact sizes; source maps excluded. These are build sizes, not actual response bytes or decoded runtime memory.');
 const payloadRows=[],chunkRows=[];
 for(const impl of implementations){
  if(!impl.assets.length)continue;
  const location=resolve(lab,builds?.variants.some(v=>v.id===impl.id)?'.cache/variants':'.cache/snapshots',impl.id);
  const html=await readFile(resolve(location,'index.html'),'utf8'),initial=new Set();
  function visit(name){if(initial.has(name))return;initial.add(name);for(const imp of impl.assets.find(a=>a.path===name)?.imports||[])if(!imp.dynamic&&imp.specifier.startsWith('.'))visit(posix.normalize(posix.join(posix.dirname(name),imp.specifier)));}
  for(const match of html.matchAll(/(?:src|href)="([^"]+\.(?:js|css))"/g))visit(match[1].replace(/^\//,''));
  const assets=impl.assets.filter(a=>!a.diagnostic),sum=(test,key)=>fmt(assets.filter(a=>test(a.path)).reduce((n,a)=>n+a[key],0)/1024);
  const js=p=>p.endsWith('.js'),css=p=>p.endsWith('.css'),htmlFile=p=>p.endsWith('.html');
  payloadRows.push([names[impl.id],ctx.id,date(all.filter(s=>sampleImplementation(s)===impl.id)),sum(js,'raw'),sum(js,'gzip'),sum(js,'brotli'),sum(p=>js(p)&&initial.has(p),'brotli'),sum(css,'raw'),sum(css,'brotli'),sum(p=>/\.woff2?$/.test(p),'brotli'),sum(htmlFile,'raw'),sum(htmlFile,'brotli')]);
  chunkRows.push([names[impl.id],ctx.id,date(all.filter(s=>sampleImplementation(s)===impl.id)),assets.filter(a=>js(a.path)).length,assets.filter(a=>css(a.path)).length,initial.size,assets.flatMap(a=>a.imports||[]).filter(i=>i.dynamic).length]);
 }
 if(payloadRows.length)table('Production payload sizes',['Implementation','Run ID','Date (UTC)','JS raw KiB','JS gzip KiB','JS Brotli KiB','Initial JS Brotli KiB','CSS raw KiB','CSS Brotli KiB','Local fonts Brotli KiB','HTML raw KiB','HTML Brotli KiB'],payloadRows,'Offline gzip9/Brotli11 sizes. Initial assets follow HTML/static imports; source maps excluded. Date identifies the measurement cohort, not an invented build date.');
 if(chunkRows.length)table('Chunk structure',['Implementation','Run ID','Date (UTC)','JS files','CSS files','Static initial assets','Dynamic import edges'],chunkRows,'Static import reachability from the production entry; actual requested bytes remain in transfer tables.');
 const bundles=await readFile(resolve(directory,'bundles.json'),'utf8').then(JSON.parse).catch(e=>{if(e.code==='ENOENT')return null;throw e;});
 if(bundles){const rows=Array.isArray(bundles)?bundles:bundles.systems; if(Array.isArray(rows))table('Native initial and complete payload',['Implementation','Initial JS Brotli KiB','All JS raw KiB','All JS gzip KiB','All JS Brotli KiB','Fonts Brotli KiB','Dynamic imports'],rows.map(r=>[names[r.id]||r.id,fmt(r.totals.js?.initialBrotli/1024),fmt(r.totals.js?.raw/1024),fmt(r.totals.js?.gzip/1024),fmt(r.totals.js?.brotli/1024),fmt(r.totals.fonts?.brotli/1024),r.dynamicImportEdges?.length]),'Native-control static import graph and all emitted assets. Candidate totals are in the first table; measured response bytes below include requests actually made.');}
 table('Acquisition coverage',['Run ID','Date (UTC)','Status','Planned n','Recorded n','Successful n','Failed n'],coverage,'Missing and failed samples remain visible. This report can be regenerated from archived raw data without starting a browser.');
 const groups={load:['loading','lcp','transfer','thread'],startup:['startup','transfer'],interactions:['interactions','transfer'],lighthouse:['lighthouse'],diagnostic:['thread'],overhead:['thread'],bfcache:[]};
 const availability=[];
 const cells=[...new Set(all.map(s=>[s.suite,s.profile,s.cache,s.preparation||'none',s.instrument===false?'uninstrumented':'instrumented'].join('|')))];
 const calendarColumns=[number('First focus ms','first',{get:s=>s.calendar?.first.inputToFocus}),number('First frame opportunity ms','frame',{get:s=>s.calendar?.first.inputToFrame}),number('Repeated focus ms','repeat',{get:s=>s.calendar?.repeat.inputToFocus}),number('Preparation to focus ms','prepare',{get:s=>s.calendar?.first.prepareToFocus})];
 const domColumns=['before','opened','closed'].flatMap(state=>['total','date','withoutDate'].flatMap(scope=>['nodes','elements'].map(key=>number(`${state} ${scope} ${key}`,'dom',{digits:0,get:s=>s.calendar?.[state]?.[scope]?.[key]}))));
 for(const cell of cells){const [suite,profile,cache,preparation,instrument]=cell.split('|');const selected=all.filter(s=>[s.suite,s.profile,s.cache,s.preparation||'none',s.instrument===false?'uninstrumented':'instrumented'].join('|')===cell);
  const descriptors=suite==='calendar'?[['Calendar focus',calendarColumns],['Connected DOM with and without date',domColumns],['Calendar response transfer',metricGroups.transfer]]:(groups[suite]||[]).map(g=>[g,metricGroups[g]]);
  if(suite==='diagnostic')descriptors.push(['Connected DOM and styles',['connectedNodes','connectedElements','openShadowRoots','styleElements','stylesheetAdoptions','uniqueAdoptedStylesheets'].map(key=>number(key,key,{digits:0,get:s=>s.connectedDOM?.[key]}))]);
  // Preserve named interaction actions, rather than reporting only the session maximum.
  if(suite==='interactions')for(const action of new Set(selected.flatMap(s=>s.metrics?.actions?.map(a=>a.name)||[])))descriptors.push([action,['semanticMs','frameOpportunityMs'].map(key=>number(key+' ms',key,{get:s=>s.metrics?.actions?.find(a=>a.name===action)?.[key]}))]);
  for(const [group,columns] of descriptors){const title=[suite,group,profile,cache,preparation,instrument].join(' · ');table(title,['Implementation','Run ID','Date (UTC)','Successful n','Failed n',...columns.map(c=>c.label)],implementations.map(impl=>{const ss=selected.filter(s=>sampleImplementation(s)===impl.id),ok=ss.filter(s=>s.status==='ok');return[names[impl.id],[...new Set(ss.map(s=>s.runId))].join(', '),date(ss),ok.length,ss.length-ok.length,...columns.map(c=>{const stats=describe(ok.map(s=>c.get?c.get(s):s.metrics?.[c.key]));availability.push({table:title,implementation:impl.id,metric:c.label,available:stats.n,successful:ok.length});return fmt(Number.isFinite(stats[c.stat])?stats[c.stat]/c.scale:null,c.digits);})];}),'Successful-sample medians unless labeled otherwise. “—” means unavailable, never zero. See metric availability for per-measurement denominators.');}
 }
 const census=await readFile(resolve(directory,'dom.json'),'utf8').then(JSON.parse).catch(e=>{if(e.code==='ENOENT')return null;throw e;});
 if(census){const rows=[];for(const impl of implementations)for(const state of ['initial','opened','closed']){const ss=census.samples.filter(s=>s.implementation===impl.id&&s.state===state);if(!ss.length)continue;rows.push([names[impl.id],ctx.id,ss[0].at.slice(0,10),state,ss.length,...['total','date','withoutDate'].flatMap(scope=>['nodes','elements'].map(key=>fmt(describe(ss.map(s=>s.data[scope][key])).median,0)))]);}
 table('Connected DOM with and without dates',['Implementation','Run ID','Date (UTC)','State','Snapshots n','Full nodes','Full elements','Date nodes','Date elements','Without date nodes','Without date elements'],rows,census.method);
 const keys=['nodes','elements','text','whitespaceText','comments','shadowRoots','slots','baseParts'];
 table('Initial non-date node composition',['Implementation','Run ID','Date (UTC)','Snapshots n','Nodes','Elements','Text nodes','Whitespace text nodes','Comments','Open shadow roots','Slots','Base parts'],implementations.map(impl=>{const ss=census.samples.filter(s=>s.implementation===impl.id&&s.state==='initial');return[names[impl.id],ctx.id,ss[0]?.at.slice(0,10)||'—',ss.length,...keys.map(key=>fmt(describe(ss.map(s=>s.data.withoutDate[key])).median,0))]}),'Connected initial tree with the complete date field excluded. Whitespace is a subset of text nodes. Base parts include SVG and native semantic elements; this is a census, not a conclusion that those elements are removable.');

 }
 const memory=all.filter(s=>s.suite==='memory');if(memory.length)table('Memory and retention',['Implementation','Run ID','Date (UTC)','Checkpoint kind','Cycles / openings','API status','API MiB','JS heap MiB','CDP nodes','Listeners'],memory.flatMap(s=>[['Journey',s.memory||[]],['Calendar',s.calendarMemory||[]]].flatMap(([kind,rows])=>rows.map(m=>[names[sampleImplementation(s)],s.runId,date([s]),kind,m.calendarOpenings??m.cycles,m.api?.status,fmt(m.api?.status==='ok'?m.api.bytes/1048576:null,2),fmt(m.chromiumJSHeapUsedSize/1048576,2),m.dom?.nodes,m.dom?.jsEventListeners]))),'No forced GC. API errors/timeouts are preserved; CDP nodes include retained/detached objects and are not connected-DOM counts. These samples alone do not establish a leak.');
 if(memory.length)for(const cycle of [...new Set(memory.flatMap(s=>(s.memory||[]).map(m=>m.cycles)))].sort((a,b)=>a-b))table('Memory after '+cycle+' cycles',['Implementation','Run ID','Date (UTC)','Checkpoints n','API success n','API unavailable n','API MiB','JS heap MiB','Browser DOM nodes','Event listeners','API status'],implementations.map(impl=>{const samples=memory.filter(s=>sampleImplementation(s)===impl.id),rows=samples.flatMap(s=>(s.memory||[]).filter(m=>m.cycles===cycle)),ok=rows.filter(m=>m.api?.status==='ok');return[names[impl.id],[...new Set(samples.map(s=>s.runId))].join(', '),date(samples),rows.length,ok.length,rows.length-ok.length,fmt(describe(ok.map(m=>m.api.bytes/1048576)).median,2),fmt(describe(rows.map(m=>m.chromiumJSHeapUsedSize/1048576)).median,2),fmt(describe(rows.map(m=>m.dom?.nodes)).median,0),fmt(describe(rows.map(m=>m.dom?.jsEventListeners)).median,0),[...new Set(rows.map(m=>m.api?.status))].join(', ')]}),'Descriptive checkpoint readings; counts and API availability are shown. No forced GC or leak conclusion.');
 if(ctx.config.kind==='current'){
  const changes=[];
  for(const [title,metric,unit] of [['load · loading · mobile · cold · none · instrumented','LCP ms','ms'],['load · loading · mobile · warm · none · instrumented','LCP ms','ms'],['startup · startup · mobile · cold · none · instrumented','Result from navigation ms','ms'],['interactions · interactions · mobile · cold · none · instrumented','Scripted INP ms','ms'],['Production payload sizes','JS raw KiB','KiB'],['Production payload sizes','Initial JS Brotli KiB','KiB'],['diagnostic · Connected DOM and styles · desktop · cold · none · instrumented','connectedNodes','nodes'],['diagnostic · Connected DOM and styles · desktop · cold · none · instrumented','connectedElements','elements']]){
   const t=tables.find(t=>t.title===title),old=t?.rows.find(r=>r[0]===names['en-reve']),fresh=t?.rows.find(r=>r[0]===names[builds.variants[0].id]),i=t?.headers.indexOf(metric);if(!old||!fresh||i<0)continue;const a=Number(old[i]),b=Number(fresh[i]);if(!Number.isFinite(a)||!Number.isFinite(b))continue;
   changes.push([names[builds.variants[0].id],ctx.id,date(all),title.split(' · ').slice(0,4).join(' / '),metric,unit,old[i],fresh[i],fmt(b-a,2),a?fmt(100*(b-a)/a,2):'—']);
  }
  table('Current minus frozen control',['Implementation','Run ID','Date (UTC)','Scenario','Metric','Unit','Frozen control','Current source','Change','Change percent'],changes,'Candidate median minus frozen-control median (or deterministic bundle size). Positive means more/slower. Separate sequential cohorts, no paired confidence interval or causal attribution; timing drift and harness differences limit comparisons to earlier dates.');
 }
 const bf=all.filter(s=>s.suite==='bfcache');if(bf.length)table('Back-forward cache observations',['Implementation','Run ID','Date (UTC)','Status','Evidence'],bf.map(s=>[names[sampleImplementation(s)],s.runId,date([s]),s.status,JSON.stringify(s.bfcache)]),'Restoration and post-return behavior are diagnostic observations; automation can affect eligibility. Raw evidence retains browser restore reasons.');
 const differences=[];
 if(builds){const eager=builds.variants.find(v=>v.policy==='calendar-eager'||v.id==='calendar-eager');if(eager)for(const profile of ctx.config.profiles)for(const [suite,metric,get] of [['load','LCP',s=>s.metrics?.lcp],['calendar','First focus',s=>s.calendar?.first.inputToFocus]]){const ss=all.filter(s=>s.suite===suite&&s.profile===profile&&s.cache==='cold'&&(!s.preparation||s.preparation==='none')&&s.status==='ok');for(const v of builds.variants.filter(v=>v.id!==eager.id)){const d=pairedDifference(ss.filter(s=>s.variant===v.id).map(s=>({block:s.block,value:get(s)})),ss.filter(s=>s.variant===eager.id).map(s=>({block:s.block,value:get(s)})),{seed:ctx.config.seed});differences.push([names[v.id],profile,metric,d.n,fmt(d.difference),fmt(d.ci95?.[0]),fmt(d.ci95?.[1])]);}}}
 if(differences.length)table('Paired change relative to eager',['Implementation','Profile','Metric','Paired n','Median change ms','95% lower ms','95% upper ms'],differences,'Candidate minus eager; positive means slower. Matched blocks from this campaign only. Exploratory bootstrap intervals, no multiple-comparison correction or automatic baseline promotion.');
 table('Metric availability',['Implementation','Table','Metric','Available n','Successful n'],availability.map(a=>[names[a.implementation],a.table,a.metric,a.available,a.successful]),'A successful sample may still have an unsupported or unavailable browser metric. Denominators are shown for every metric.');
 const header=`# Performance campaign ${ctx.id}\n\nCampaign status: **${state.status}**. ${ctx.config.kind==='current'?'Current source and frozen controls run in separate sequential cohorts; compare descriptively, not as matched randomized blocks.':''} Dates are UTC measurement dates. Rebuilding this report does not change them.\n\nThis is exploratory laboratory evidence, not field Core Web Vitals, a physical mobile device, manual accessibility acceptance, or a promoted regression baseline. First-input delay is a scripted legacy diagnostic; scripted INP describes only these journeys. Lighthouse TBT stays separate from observed long-task blocking excess.\n\nProfiles and requested throttling: ${JSON.stringify(JSON.parse(await readFile(resolve(directory,'profiles-profiles.json'))))}\n\n[Campaign configuration](campaign.json) · [Stage outcomes](state.json) · [Metric availability and tables](tables.json)\n\n`;
 const markdown=header+tables.map(t=>`## ${t.title}\n\n${t.note}\n\n`+[t.headers,t.headers.map(()=>'---'),...t.rows].map(r=>'| '+r.map(esc).join(' | ')+' |').join('\n')).join('\n\n')+'\n';
 await writeFile(resolve(directory,'tables.json'),json({schemaVersion:1,campaign:ctx.id,generatedAt:new Date().toISOString(),coverage,availability,tables}));await writeFile(resolve(directory,'results.md'),markdown);console.log('Generated',tables.length,'tables:',resolve(directory,'results.md'));return {tables,coverage};
}
