import {readFile,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';import {describe,pairedDifference} from '../../../showcases/performance/src/analysis.mjs';
const base='artifacts/scoped-registry-phase-4',read=async p=>JSON.parse(await readFile(`${base}/${p}`));const rows=async p=>(await readFile(`${base}/${p}/samples.jsonl`,'utf8')).trim().split('\n').map(JSON.parse);
const manifest=await read('campaign/manifest.json'),summary=await read('campaign/summary.json'),samples=await rows('campaign');const key=r=>[r.kind,r.phase,r.browser,r.profile,r.intent,r.block].join('/');assert.equal(summary.passed,490);assert.equal(samples.length,490);assert.deepEqual(samples.map(key),manifest.jobs.map(key));assert.equal(new Set(samples.map(key)).size,490);assert(samples.every(s=>s.status==='ok'&&!s.errors.length&&!s.failures.length));
const timing=[],retention=[];
for(const [browser,profile]of [['chromium','desktop'],['firefox','desktop'],['webkit','desktop'],['chromium','constrained']])for(const intent of ['immediate','focus500']){
 const groups=['control','candidate'].map(phase=>samples.filter(r=>r.kind==='timing'&&r.phase===phase&&r.browser===browser&&r.profile===profile&&r.intent===intent));groups.forEach(g=>assert.equal(g.length,30));
 for(const metric of Object.keys(groups[0][0].metrics).filter(m=>m!=='intentElapsedMs')){
  const pairs=groups[0].flatMap(a=>{const b=groups[1].find(b=>b.block===a.block);return Number.isFinite(a.metrics[metric])&&Number.isFinite(b.metrics[metric])?[[a,b]]:[];});
  const arms=[0,1].map(i=>describe(pairs.map(p=>p[i].metrics[metric]))),available=groups.map(g=>describe(g.map(r=>r.metrics[metric]))),delta=pairedDifference(pairs.map(p=>({block:p[1].block,value:p[1].metrics[metric]})),pairs.map(p=>({block:p[0].block,value:p[0].metrics[metric]})));
  timing.push({browser,profile,intent,metric,unit:metric.endsWith('Ms')?'ms':metric.endsWith('Requests')?'count':'bytes',pairedSamples:pairs.length,arms,available,change:{...delta,percent:arms[0].median&&delta.difference!==null?delta.difference/arms[0].median*100:null}});
 }
}
const groups=['control','candidate'].map(phase=>samples.filter(r=>r.kind==='retention'&&r.phase===phase));groups.forEach(g=>{assert.equal(g.length,5);g.forEach(r=>{assert.deepEqual(r.checkpoints.map(c=>c.cycle),[0,10,50,100]);assert(r.checkpoints.every(c=>c.apps===1));});});
const value=(r,cycle,metric)=>{const p=r.checkpoints.find(p=>p.cycle===cycle);return metric==='heapBytes'?p.heapBytes:p.dom[metric];};
for(const cycle of [0,10,50,100,'10–100'])for(const metric of ['heapBytes','nodes','jsEventListeners','documents']){const extract=r=>cycle==='10–100'?value(r,100,metric)-value(r,10,metric):value(r,cycle,metric),arms=groups.map(g=>describe(g.map(extract))),difference=arms[1].median-arms[0].median;retention.push({browser:'chromium',profile:'desktop',intent:'immediate',cycle,metric,unit:metric==='heapBytes'?'bytes':'count',arms,change:{difference,percent:arms[0].median?difference/arms[0].median*100:null,ci95:null}});}
const mechanism=await rows('containment'),mm=await read('containment/manifest.json'),ms=await read('containment/summary.json'),mkey=r=>[r.kind,r.policy,r.count,r.block].join('/');assert.equal(ms.passed,195);assert.deepEqual(mechanism.map(mkey),mm.jobs.map(mkey));assert(mechanism.every(r=>r.status==='ok'&&!r.errors.length));const containment=[],containmentRetention=[];
for(const policy of ['group','dormant','fallback'])for(const count of [1,250]){const group=mechanism.filter(r=>r.kind==='timing'&&r.policy===policy&&r.count===count);assert.equal(group.length,30);for(const metric of Object.keys(group[0].metrics))containment.push({policy,count,metric,unit:metric.endsWith('Ms')?'ms':'count',...describe(group.map(r=>r.metrics[metric]))});}
for(const policy of ['group','dormant','fallback']){const group=mechanism.filter(r=>r.kind==='retention'&&r.policy===policy);assert.equal(group.length,5);assert(group.every(r=>r.checkpoints.every(p=>p.boundaries===0)));for(const cycle of [0,10,50,100,'10–100'])for(const metric of ['heapBytes','nodes','jsEventListeners','documents'])containmentRetention.push({policy,cycle,metric,unit:metric==='heapBytes'?'bytes':'count',...describe(group.map(r=>cycle==='10–100'?value(r,100,metric)-value(r,10,metric):value(r,cycle,metric)))});}
const data={at:new Date().toISOString(),summary,containmentSummary:ms,host:manifest.host,browsers:Object.fromEntries(samples.map(r=>[r.browser,r.browserVersion])),methodology:'Paired actual production Phase 3 cleanup versus Phase 4. Immediate and 500 ms focus-intent conditions are distinct. Thirty randomized blocks per arm/configuration, exploratory paired median bootstrap (2,000 resamples, seed 42). Ten separate production retention runs. Independent Chromium mechanism study: 180 timing samples and 15 disposal runs; not a production speedup comparison.',timing,retention,containment,containmentRetention,intentLead:samples.filter(r=>r.kind==='timing'&&r.intent==='focus500').reduce((a,r)=>(a.push(r.metrics.intentElapsedMs),a),[])};await writeFile(`${base}/comparison.json`,JSON.stringify(data,null,2)+'\n');console.log(JSON.stringify({constrained:timing.filter(r=>r.profile==='constrained'&&['firstUseMs','firstFocusMs','readyMs','preparedJSBytes'].includes(r.metric)),retention:retention.filter(r=>r.cycle==='10–100'),containmentRetention:containmentRetention.filter(r=>r.cycle==='10–100')},null,2));
