import {readFile,writeFile,mkdir,cp,readdir,stat,chmod,rename} from 'node:fs/promises';import {resolve,relative} from 'node:path';import {createHash} from 'node:crypto';import assert from 'node:assert/strict';import {verifyReference} from '../../../showcases/performance/src/registry-reference.mjs';
const base=resolve('artifacts/scoped-registry-phase-4'),target=resolve('showcases/performance/baselines/scoped-registry-phase-4-v1'),pending=target+'.pending',sha=b=>createHash('sha256').update(b).digest('hex');if(process.argv.includes('--verify')){console.log(await verifyReference(target));process.exit();}assert.equal(await stat(target).catch(()=>null),null);assert.equal(await stat(pending).catch(()=>null),null);
const manifest=JSON.parse(await readFile(resolve(base,'campaign/manifest.json'))),summary=JSON.parse(await readFile(resolve(base,'campaign/summary.json'))),mechanism=JSON.parse(await readFile(resolve(base,'containment/manifest.json')));assert.equal(summary.passed,490);assert.equal(JSON.parse(await readFile(resolve(base,'containment/summary.json'))).passed,195);for(const h of manifest.harness)assert.equal(sha(await readFile(resolve('probes/production-registry/phase4',h.name))),h.sha256);for(const h of mechanism.hashes)assert.equal(sha(await readFile(h.path)),h.sha256);assert.equal(sha(await readFile(resolve(base,'protocol.md'))),manifest.protocolSha256);
const candidate=JSON.parse(await readFile(resolve(base,'candidate/receipt.json')));for(const overlay of candidate.overlays)assert.equal(sha(await readFile(overlay.path)),overlay.sha256);
for(const h of JSON.parse(await readFile(resolve(base,'support-source-audit.json')))){assert(h.unchangedSinceBeforeCapture);assert.equal(sha(await readFile(h.path)),h.sha256);}
await mkdir(pending);for(const name of ['protocol.md','comparison.json','findings.json','capture-verification.json','production-functional.json','activation-tests.json','activation-tests.log','library-tests.json','library-tests.log','browser.json','settings-browser.log','elements-build.log','docs-types.log','consumer-types.log','packed-consumer-types.log','workflow-core.log','metadata.log','metadata-check.log','node-import.log','power-before.txt','power-after.txt','thermal-before.txt','thermal-after.txt','source-snapshot.json','phase3-commit.json','support-source-audit.json'])await cp(resolve(base,name),resolve(pending,name));
for(const name of ['campaign','qualification','containment','containment-qualification','qualification-preflight-rejected','activation-packed','library-packed','before-adoption-guard'])await cp(resolve(base,name),resolve(pending,name),{recursive:true});await cp(resolve(base,'qualification-preflight-rejected.log'),resolve(pending,'qualification-preflight-rejected.log'));
await cp('probes/production-registry/phase4',resolve(pending,'harness/phase4'),{recursive:true});await cp('probes/production-registry/browser-probe.mjs',resolve(pending,'harness/browser-probe.mjs'));await mkdir(resolve(pending,'harness/cleanup'),{recursive:true});await cp('probes/production-registry/cleanup/milestones.mjs',resolve(pending,'harness/cleanup/milestones.mjs'));await cp('probes/activation-registry',resolve(pending,'harness/activation-registry'),{recursive:true});await cp('probes/activation-library',resolve(pending,'harness/activation-library'),{recursive:true});await cp('showcases/performance/src',resolve(pending,'performance-support'),{recursive:true});
const snapshot=JSON.parse(await readFile(resolve(base,'source-snapshot.json')));for(const row of snapshot.files){assert.equal(sha(await readFile(row.path)),row.sha256);const dest=resolve(pending,'implementation',row.path);await mkdir(resolve(dest,'..'),{recursive:true});await cp(row.path,dest);}
await mkdir(resolve(pending,'packed-packages'));const metafile=JSON.parse(await readFile(resolve(base,'activation-packed/metafile.json'))),input=Object.keys(metafile.inputs).find(p=>p.includes('/node_modules/@en-reve/elements/')),stage=resolve(input).split('/node_modules/')[0];const packages=JSON.parse(await readFile(resolve(base,'activation-packed/receipt.json'))).packages;for(const pkg of packages){const name=(await readdir(stage)).find(n=>n.startsWith('en-reve-'+pkg.name+'-')&&n.endsWith('.tgz'));assert(name);const bytes=await readFile(resolve(stage,name));assert.equal('sha512-'+createHash('sha512').update(bytes).digest('base64'),pkg.integrity);await cp(resolve(stage,name),resolve(pending,'packed-packages',name));}
for(const phase of ['control','candidate']){const dir=resolve(phase==='control'?'artifacts/scoped-registry-phase-3-cleanup/candidate':base+'/candidate'),dest=resolve(pending,phase),receipt=JSON.parse(await readFile(resolve(dir,'receipt.json'))),m=manifest.receipts.find(r=>r.phase===phase);assert.equal(receipt.sourceDigest,m.sourceDigest);assert.equal(receipt.assetsDigest,m.assetsDigest);for(const a of receipt.assets)assert.equal(sha(await readFile(resolve(dir,'site',a.path))),a.sha256);await mkdir(dest);for(const name of ['receipt.json','source-final.json','source.tar.gz','site.tar.gz','build.log'])await cp(resolve(dir,name),resolve(dest,name));}
const previous=[];for(const name of ['scoped-registry-phase-3-cleanup-v1','scoped-registry-production-v1'])previous.push(await verifyReference(resolve('showcases/performance/baselines',name)));await writeFile(resolve(pending,'previous-seals.json'),JSON.stringify(previous,null,2)+'\n');
await writeFile(resolve(pending,'baseline.json'),JSON.stringify({name:'scoped-registry-phase-4-v1',status:'frozen',frozenAt:new Date().toISOString(),timing:{configurations:16,successfulSamples:480,minimumPerConfiguration:30},retention:{configurations:2,successfulRuns:10,repetitionsPerConfiguration:5,checkpoints:[0,10,50,100]},containment:{timingConfigurations:6,timingSamples:180,retentionConfigurations:3,retentionRuns:15},methodology:'Paired production immediate/focus500 conditions; separate minimal-constructor containment study. No manual screen-reader or field-performance claim.'},null,2)+'\n');
async function walk(dir){const files=[];for(const e of await readdir(dir,{withFileTypes:true})){assert(!e.isSymbolicLink());const p=resolve(dir,e.name);files.push(...(e.isDirectory()?await walk(p):[p]));}return files.sort();}const files=[];for(const p of await walk(pending)){const b=await readFile(p);files.push({path:relative(pending,p),bytes:b.length,sha256:sha(b)});}await writeFile(resolve(pending,'checksums.json'),JSON.stringify({algorithm:'sha256',files},null,2)+'\n');await writeFile(resolve(pending,'seal.json'),JSON.stringify({algorithm:'sha256',checksumsSha256:sha(await readFile(resolve(pending,'checksums.json')))},null,2)+'\n');await verifyReference(pending);for(const p of await walk(pending))await chmod(p,0o444);await rename(pending,target);console.log(await verifyReference(target));
