import {execFileSync,spawnSync} from 'node:child_process';import {mkdir,readFile,writeFile,readdir,symlink,cp,stat} from 'node:fs/promises';import {resolve} from 'node:path';import {createHash} from 'node:crypto';import assert from 'node:assert/strict';
const root=resolve(import.meta.dirname,'../../..'),base=resolve(root,'artifacts/scoped-registry-phase-4'),dest=resolve(base,'candidate'),stage=resolve(dest,'source'),original=resolve(root,'artifacts/scoped-registry-phase-3-cleanup/candidate');const sha=b=>createHash('sha256').update(b).digest('hex');
assert.equal(await stat(stage).catch(()=>null),null,'Refuse to overwrite a candidate');await mkdir(stage,{recursive:true});execFileSync('tar',['-xzf',resolve(original,'source.tar.gz'),'-C',stage]);execFileSync('chmod',['-R','u+w',stage]);for(const name of ['elements','primitives','styles','tokens','ssr'])await cp(resolve(original,'source/packages',name,'dist'),resolve(stage,'packages',name,'dist'),{recursive:true});
const overlays=[];for(const path of ['apps/docs/src/workflows/settings/index.ts','apps/docs/src/workflows/settings/template.ts','apps/docs/src/workflow-pages/settings-entry.ts','apps/docs/src/workflow-pages/settings.ts']){const b=await readFile(resolve(root,path));overlays.push({path,before:sha(await readFile(resolve(stage,path))),sha256:sha(b)});await writeFile(resolve(stage,path),b);}
await mkdir(resolve(stage,'node_modules/@en-reve'),{recursive:true});for(const name of await readdir(resolve(root,'node_modules')))if(name!=='@en-reve'&&!name.startsWith('.'))await symlink(resolve(root,'node_modules',name),resolve(stage,'node_modules',name));for(const name of ['elements','primitives','styles','tokens','ssr'])await symlink(resolve(stage,'packages',name),resolve(stage,'node_modules/@en-reve',name));
const check=spawnSync(process.execPath,[resolve(root,'node_modules/typescript/bin/tsc'),'--noEmit','-p','apps/docs/tsconfig.json'],{cwd:stage,encoding:'utf8'});await writeFile(resolve(dest,'typecheck.log'),check.stdout+'\n'+check.stderr);assert.equal(check.status,0);
const build=spawnSync(process.execPath,['apps/docs/scripts/build-ssr.mjs'],{cwd:stage,encoding:'utf8',maxBuffer:100*1024*1024});await writeFile(resolve(dest,'build.log'),build.stdout+'\n'+build.stderr);assert.equal(build.status,0,'Full Vite and SSR build failed');await cp(resolve(stage,'dist'),resolve(dest,'site'),{recursive:true});
async function inventory(dir,prefix=''){const result=[];for(const e of (await readdir(dir,{withFileTypes:true})).sort((a,b)=>a.name.localeCompare(b.name))){if(e.name==='node_modules'||e.name==='.git'||(!prefix&&e.name==='dist'))continue;const path=resolve(dir,e.name),name=prefix+e.name;if(e.isDirectory())result.push(...await inventory(path,name+'/'));else if(e.isFile()){const b=await readFile(path);result.push({path:name,bytes:b.length,sha256:sha(b)});}}return result;}
let libraryFilesVerified=0;for(const name of ['elements','primitives','styles','tokens','ssr'])for(const f of await inventory(resolve(original,'source/packages',name,'dist'))){assert.equal(sha(await readFile(resolve(stage,'packages',name,'dist',f.path))),f.sha256);libraryFilesVerified++;}
const assets=await inventory(resolve(dest,'site')),source=await inventory(stage),receipt={phase:'phase4',control:'scoped-registry-phase-3-cleanup-v1/candidate',libraryFilesVerified,overlays,sourceDigest:sha(JSON.stringify(source)),assetsDigest:sha(JSON.stringify(assets)),assets,viteConfigSha256:sha(await readFile(resolve(stage,'apps/docs/vite.config.ts'))),dependencyLockSha256:sha(await readFile(resolve(stage,'package-lock.json'))),note:'Exact archived Phase 3 production sources and library outputs with four settings workflow source overlays; identical full Vite/SSR pipeline and dependencies.'};
const prior=JSON.parse(await readFile(resolve(original,'receipt.json')));assert.equal(receipt.viteConfigSha256,prior.viteConfigSha256);assert.equal(receipt.dependencyLockSha256,prior.dependencyLockSha256);
await writeFile(resolve(dest,'source-final.json'),JSON.stringify(source,null,2)+'\n');await writeFile(resolve(dest,'receipt.json'),JSON.stringify(receipt,null,2)+'\n');execFileSync('tar',['-czf',resolve(dest,'source.tar.gz'),'--exclude=*/node_modules','-C',stage,...(await readdir(stage)).filter(n=>n!=='node_modules'&&n!=='dist')]);execFileSync('tar',['-czf',resolve(dest,'site.tar.gz'),'-C',resolve(dest,'site'),'.']);console.log(JSON.stringify({libraryFilesVerified,sourceDigest:receipt.sourceDigest,assetsDigest:receipt.assetsDigest}));
