/** Candidate policy is fingerprinted, including upstream defaults that must never change implicitly. */
export const candidatePolicy = Object.freeze({
  version: 15,
  schemaVersion: '2.1.0',
  conflictPolicy: 'throw',
  validation: Object.freeze({invariants: 'error', exportTypes: 'error'}),
  typeParsing: 'public',
  sort: true,
  deprecatedLast: false,
  customJsDocTags: false,
  sourceSelection: 'explicit-program-roots-and-observed-file-equality',
  modulePaths: 'source-root-relative',
  starExports: 'explicit-public-bindings-win-duplicate-stars-fail-closed',
  externalExportReferences: 'authored-public-package-surface-with-terminal-ownership',
  nonClassDeclarations: 'source-checker-callable-initializers-with-raw-semantic-review',
  customization: 'source-omit-tags-with-serialized-css-part-exclusions-and-no-dynamic-slot-invention',
  typeLiterals: 'ast-checked-whitespace-compaction-preserves-literals-and-singleton-booleans',
  parsedTypeStructure: 'owning-compiler-preserves-readonly-tuples-methods-and-instantiated-aliases',
  parsedTypeGrammar: 'parsed-type-node-precedence-and-semantic-union-normalization',
  inferredTypeContext: 'consuming-source-node-for-inferred-and-recursive-parsed-types',
  inheritance: 'declaration-and-field-identity-with-authored-attribute-and-documentation-precedence',
  standardLibraryIdentity: 'originating-program-default-library-membership',
  exportIdentity: 'recursive-namespace-symbol-identity',
  inheritedTypeBoundary: 'owned-external-library-ancestor-declarations',
  publicContracts: 'source-lit-exclusions-before-strict-validation',
  generatorPackages: 'repository-patched-distributions-with-full-content-identity',
  legacyCutover: false,
});
