import {readFile, writeFile} from 'node:fs/promises';
import {resolve, basename} from 'node:path';
import {readDefinitionGraph} from './definition-graph.ts';
import {deliveryMetadataOutputs} from './delivery-metadata.ts';
const root = resolve(import.meta.dirname, '../../packages/elements');
const definitions = await readDefinitionGraph(root);
const lines = definitions.map(definition => {
  const file = basename(definition.source, '.ts');
  const name = file.replace(/-([a-z])/g, (_, letter) => letter.toUpperCase()) + 'Definition';
  return `  '${definition.tagName}': () => import('./definitions/${file}.js').then(module => module.${name}),`;
});
const content = `// Generated by tooling/metadata/lazy-manifest.ts from the canonical definition graph.\n// Literal imports preserve chunk boundaries; this module imports no component at startup.\nexport const elementLoaders = Object.freeze({\n${lines.join('\n')}\n});\n\nexport type LazyElementTag = keyof typeof elementLoaders;\n`;
const outputs = {'src/lazy-manifest.ts': content, ...await deliveryMetadataOutputs(definitions)};
for (const [file, generated] of Object.entries(outputs)) {
  const path = resolve(root, file);
  if (process.argv.includes('--check')) {
    if (await readFile(path, 'utf8') !== generated) throw new Error(`Lazy delivery metadata is stale: ${file}. Run npm run metadata:lazy.`);
  } else await writeFile(path, generated);
}
console.log(`Lazy manifest: ${definitions.length} canonical definitions and delivery metadata.`);
