import assert from 'node:assert/strict';
import {preparedPackages} from '../../tooling/evidence/packed-setup.mjs';
import {execFileSync} from 'node:child_process';
import {mkdir,readFile,writeFile,readdir,symlink,cp,realpath} from 'node:fs/promises';
import {resolve,join,relative,sep,dirname} from 'node:path';
import {createHash} from 'node:crypto';
import {build} from '../../showcases/performance/node_modules/esbuild/lib/main.js';
const root=resolve(import.meta.dirname,'../..'),out=resolve(process.env.EN_COLLECTION_RECIPES_OUT??'artifacts/collection-recipes');
await mkdir(dirname(out),{recursive:true});await mkdir(out,{recursive:false});
const stage=join(out,'consumer'),site=join(out,'site'),archives=join(out,'packages'),assets=join(site,'assets');
for(const path of [join(stage,'node_modules'),assets,archives])await mkdir(path,{recursive:true});
const packages=await preparedPackages(['primitives','styles','tokens','elements','ssr'],archives);
for(const archive of packages){const destination=join(stage,'node_modules',archive.name);await mkdir(destination,{recursive:true});execFileSync('tar',['-xzf',join(archives,archive.filename),'-C',destination,'--strip-components=1']);}
for(const name of await readdir(join(root,'node_modules')))if(name!=='@en-reve'&&!name.startsWith('.'))await symlink(join(root,'node_modules',name),join(stage,'node_modules',name));
await writeFile(join(stage,'package.json'),'{"type":"module"}\n');
const sources=['apps/docs/src/document-scroll-demo.ts','apps/docs/src/virtual-collection-demo.ts','probes/collection-recipes/table.ts','probes/collection-recipes/entry.ts','probes/collection-recipes/render-pages.mjs'];
for(const path of sources)await cp(join(root,path),join(stage,path.split('/').at(-1)));
const declarations=execFileSync(process.execPath,[join(root,'node_modules/typescript/bin/tsc'),'--ignoreConfig','--strict','--noEmit','--skipLibCheck','--module','NodeNext','--moduleResolution','NodeNext','--target','ES2022','--listFiles','document-scroll-demo.ts','virtual-collection-demo.ts','table.ts','entry.ts'],{cwd:stage,encoding:'utf8'});
await writeFile(join(out,'type-files.txt'),declarations);const ownTypes=declarations.trim().split('\n').filter(path=>path.includes('/@en-reve/'));assert(ownTypes.length>0);
for(const path of ownTypes)assert((await realpath(path)).startsWith(join(stage,'node_modules/@en-reve')+sep));
const result=await build({entryPoints:{table:join(stage,'entry.ts'),document:join(stage,'document-scroll-demo.ts')},outdir:assets,bundle:true,splitting:true,format:'esm',platform:'browser',target:'es2022',minify:true,metafile:true});
const inputs=Object.keys(result.metafile.inputs);assert(!inputs.some(path=>/\/packages\/[^/]+\/src\//.test(path)||/elements\/dist\/(index|catalog|lazy)\.js/.test(path)));
for(const path of inputs.filter(path=>path.includes('/@en-reve/')))assert((await realpath(resolve(root,path))).startsWith(join(stage,'node_modules/@en-reve')+sep));
const outputs=result.metafile.outputs;
const closure=(file,seen=new Set())=>{if(seen.has(file))return seen;seen.add(file);for(const dep of outputs[file].imports)if(!dep.external)closure(dep.path,seen);return seen;};
const entryInputs=Object.fromEntries([['table','entry.ts'],['document','document-scroll-demo.ts']].map(([name,entry])=>{const file=Object.keys(outputs).find(path=>outputs[path].entryPoint?.endsWith('/'+entry));assert(file);return [name,[...new Set([...closure(file)].flatMap(path=>Object.keys(outputs[path].inputs)))]];}));
assert(!entryInputs.document.some(path=>path.includes('/@en-reve/elements/')));
const definitions=inputs.filter(path=>path.includes('/elements/dist/define/')).map(path=>path.split('/').at(-1)).sort();
assert.deepEqual(definitions,['button.js','checkbox.js','icon.js','pagination.js','select.js','table.js','text-field.js']);
// Syntax removal only. Node rendering still resolves packed public entry points.
await build({entryPoints:['table.ts','virtual-collection-demo.ts'].map(file=>join(stage,file)),outdir:stage,format:'esm',platform:'node',target:'es2022',bundle:false});
execFileSync(process.execPath,[join(stage,'render-pages.mjs'),site],{cwd:stage,stdio:'inherit'});
const documentPath='apps/docs/document-scroll.html';sources.push(documentPath);
const documentHTML=await readFile(join(root,documentPath),'utf8');assert(documentHTML.includes("import './src/document-scroll-demo.ts';"));
await writeFile(join(site,'document.html'),documentHTML.replace("import './src/document-scroll-demo.ts';","import '/assets/document.js';"));
const hash=bytes=>createHash('sha256').update(bytes).digest('hex'),assetHashes={};for(const file of await readdir(assets))assetHashes[file]=hash(await readFile(join(assets,file)));
await writeFile(join(out,'metafile.json'),JSON.stringify(result.metafile,null,2)+'\n');
await writeFile(join(out,'packed.json'),JSON.stringify({schemaVersion:1,packages:packages.map(({name,integrity,shasum,setup})=>({name,integrity,shasum,setup})),types:{status:'passed',packedDeclarations:ownTypes.map(path=>relative(stage,path))},inputs,entryInputs,definitions,assets:assetHashes,pages:Object.fromEntries(await Promise.all(['table.html','document.html'].map(async file=>[file,hash(await readFile(join(site,file)))]))),sourceInputs:Object.fromEntries(await Promise.all(sources.map(async path=>[path,hash(await readFile(join(root,path)))]))),limits:['Existing authored table/list and document-scroll recipes consumed from package tarballs.','No manual AT, physical-device, retail-browser or universal SSR qualification.']},null,2)+'\n');
console.log(JSON.stringify({out,types:'passed',inputs:inputs.length}));
