import {LitElement,html,css} from 'lit';
import {ifDefined} from 'lit/directives/if-defined.js';
import {EditorDocument,type Run} from '@en-reve/primitives/state/token-document.js';
import {registerChatEditor,getChatEditorAdapter,snapshotChatEditor,type ChatEditorSnapshot} from '@en-reve/primitives/interactions/chat-editor.js';
import {EditorExtensionRegistry,EditorQueryTask,EditorBookmarks,createEditorCommandMatcher,type EditorTriggerDefinition,type EditorBookmark} from '@en-reve/primitives/interactions/editor-extensions.js';
import {writeEditorClipboard,readEditorClipboard,importClipboardRuns,sliceClipboardRuns} from '@en-reve/primitives/interactions/editor-clipboard.js';
import {foundationStyles} from '@en-reve/styles/foundations.js';
import {buttonStyles} from '@en-reve/styles/buttons.js';
import {controlStyles,formStyles} from '@en-reve/styles/controls.js';
import {tokenEditorStyles} from '@en-reve/styles/token-editor.js';
import {richTextEditorStyles} from '@en-reve/styles/rich-text-editor.js';
import {chatStyles} from '@en-reve/styles/chat.js';
import {collaborationStyles} from '@en-reve/styles/collaboration.js';
const portable=new URL(location.href).searchParams.get('delivery')==='css';
const shared=[foundationStyles,buttonStyles,controlStyles,formStyles];
const sheet=(name:string)=>portable?html`<link rel="stylesheet" href=${'/'+name+'.css'}>`:null;
type Extension=EditorTriggerDefinition&{items:readonly string[]};
class RecipeEditor extends LitElement {
 static override styles=[...shared,tokenEditorStyles,css`:host{display:block}.editor{box-sizing:border-box;inline-size:100%;resize:vertical}.preview{white-space:pre-wrap;overflow-wrap:anywhere}.popup:not(:popover-open){display:none}.actions{display:flex;flex-wrap:wrap;gap:8px}`];
 readonly model=new EditorDocument();readonly registry=new EditorExtensionRegistry<Extension>(()=>this.dismiss());readonly task=new EditorQueryTask();readonly bookmarks=new EditorBookmarks<{from:number;to:number}>();
 veto=false;composing=false;hold=false;disabled=false;readOnly=false;
 pending:{query:string;signal:AbortSignal;resolve:(items:readonly string[])=>void;reject:()=>void}[]=[];
 private dispose?:()=>void;private bookmark?:EditorBookmark;private extension?:Extension;private results:readonly string[]=[];private active=0;private count=0;
 constructor(){super();this.registry.register({id:'reference',trigger:'@',items:['Alex','Ada','Sam']});this.registry.register({id:'tool',trigger:'/',match:createEditorCommandMatcher(['Outline','Summarize brief']),items:['Outline','Summarize brief']});this.model.addEventListener('en-change',e=>{const forwarded=new CustomEvent('document-change',{detail:(e as CustomEvent).detail,cancelable:true,bubbles:true,composed:true});if(this.veto)forwarded.preventDefault();this.dispatchEvent(forwarded);if(forwarded.defaultPrevented)e.preventDefault();});}
 get value(){return this.model.value;}
 getSnapshot(){return this.model.snapshot();}
 override connectedCallback(){super.connectedCallback();this.dispose=registerChatEditor(this,{get value(){return self.value},get composing(){return self.composing},get disabled(){return self.disabled},get readOnly(){return self.readOnly},focus:options=>this.input().focus(options),reportValidity:()=>this.input().reportValidity(),getSnapshot:()=>this.getSnapshot()});const self=this;}
 override disconnectedCallback(){this.dispose?.();this.task.cancel();super.disconnectedCallback();}
 private input(){return this.renderRoot.querySelector<HTMLTextAreaElement>('textarea')!;}
 private popup(){return this.renderRoot?.querySelector<HTMLElement>('.popup');}
 private selection(){const n=this.input();this.model.select({anchor:n.selectionStart,focus:n.selectionEnd});}
 private sync(){const n=this.input();if(n.value!==this.value)n.value=this.value;n.setSelectionRange(this.model.selection.anchor,this.model.selection.focus);this.requestUpdate();}
 reset(runs:readonly Run[]){this.model.reset(runs);this.dismiss();this.sync();}
 private edit(){if(this.composing)return;const next=this.input().value,old=this.value;let from=0;while(from<next.length&&from<old.length&&next[from]===old[from])from++;let a=old.length,b=next.length;while(a>from&&b>from&&old[a-1]===next[b-1]){a--;b--;}this.model.select({anchor:from,focus:a});this.model.replace([{kind:'text',text:next.slice(from,b)}]);this.sync();this.query();}
 private key(e:KeyboardEvent){if(this.composing||e.isComposing)return;if(e.key==='Escape'){e.preventDefault();this.dismiss();return;}if(this.results.length&&['ArrowDown','ArrowUp','Enter'].includes(e.key)){e.preventDefault();if(e.key==='Enter')this.choose(this.results[this.active]!);else {this.active=(this.active+(e.key==='ArrowDown'?1:-1)+this.results.length)%this.results.length;this.requestUpdate();}return;}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?this.model.redo():this.model.undo();this.sync();this.dismiss();return;}if(['Backspace','Delete'].includes(e.key)&&!this.disabled&&!this.readOnly){e.preventDefault();this.selection();this.model.delete(e.key==='Backspace'?'backward':'forward');this.sync();this.query();}}
 private query(){const n=this.input();if(n.selectionStart!==n.selectionEnd)return this.dismiss();const match=this.registry.match(n.value.slice(0,n.selectionStart));if(!match)return this.dismiss();this.extension=match.extension;this.bookmark=this.bookmarks.capture(this.model.revision,{from:match.from,to:n.selectionStart});this.results=[];this.requestUpdate();this.task.start(match.query,({query,signal})=>this.hold?new Promise<readonly string[]>((resolve,reject)=>this.pending.push({query,signal,resolve,reject:()=>reject(Error('provider rejected'))})):match.extension.items.filter(x=>x.toLowerCase().startsWith(query.toLowerCase())),items=>{this.results=items;this.active=0;this.requestUpdate();void this.updateComplete.then(()=>{const popup=this.popup()!;if(!items.length){if(popup.matches(':popover-open'))popup.hidePopover();return;}if(!popup.matches(':popover-open'))popup.showPopover();const box=n.getBoundingClientRect();popup.style.left=Math.max(8,Math.min(box.left,innerWidth-328))+'px';popup.style.top=Math.max(8,Math.min(box.bottom,innerHeight-180))+'px';});},()=>this.dismiss());}
 dismiss(){this.task.cancel();this.results=[];this.bookmark=undefined;const popup=this.popup();if(popup?.matches(':popover-open'))popup.hidePopover();this.requestUpdate();}
 choose(label:string){if(!this.bookmark||!this.extension)return;const range=this.bookmarks.resolve(this.bookmark,this.model.revision);if(!range)return this.dismiss();this.model.select({anchor:range.from,focus:range.to});const prefix=this.extension.trigger;this.model.replace([{kind:'token',id:'local-'+(++this.count),type:this.extension.id,text:prefix+label,label:prefix+label,data:{key:label}}]);this.sync();this.dismiss();this.input().focus();}
 private copy(e:ClipboardEvent,cut=false){if(!e.clipboardData)return;this.selection();const {anchor,focus}=this.model.selection;const runs=sliceClipboardRuns(this.model.document.runs,Math.min(anchor,focus),Math.max(anchor,focus));if(writeEditorClipboard(e.clipboardData,runs)){e.preventDefault();if(cut&&!this.readOnly&&!this.disabled){this.model.replace([]);this.sync();this.dismiss();}}}
 private paste(e:ClipboardEvent){if(!e.clipboardData||this.readOnly||this.disabled)return;e.preventDefault();this.selection();const source=readEditorClipboard(e.clipboardData);const used=new Set(this.model.document.runs.flatMap(r=>r.kind==='token'?[r.id]:[]));const runs=source?importClipboardRuns(source.runs,type=>this.registry.has(type),used):[{kind:'text' as const,text:e.clipboardData.getData('text/plain')}];this.model.replace(runs);this.sync();this.dismiss();}
 protected override render(){return html`<div class="en-foundation"><label class="label" for="draft">Project draft</label><textarea id="draft" class="editor" aria-describedby="help" aria-controls="suggestions" aria-expanded=${String(!!this.results.length)} aria-activedescendant=${ifDefined(this.results[this.active]?'suggestion-'+this.active:undefined)} ?disabled=${this.disabled} ?readonly=${this.readOnly} @input=${this.edit} @keydown=${this.key} @compositionstart=${()=>this.composing=true} @compositionend=${()=>{this.composing=false;this.edit();}} @copy=${(e:ClipboardEvent)=>this.copy(e)} @cut=${(e:ClipboardEvent)=>this.copy(e,true)} @paste=${this.paste}></textarea><p id="help">Text draft with structured reference and tool preview. Type @ or /.</p><div class="preview" aria-label="Structured preview">${this.model.document.runs.map(run=>run.kind==='text'?run.text:html`<button type="button" data-token=${run.type} @click=${()=>{let from=0;for(const item of this.model.document.runs){if(item===run)break;from+=item.text.length;}this.model.select({anchor:from,focus:from+run.text.length});this.sync();this.input().focus();}}><span part="token-content">${run.label}</span></button>`)}</div><div class="popup" popover="manual" id="suggestions" role="listbox" aria-label="Suggestions">${this.results.map((item,i)=>html`<div class="option" role="option" id=${'suggestion-'+i} aria-selected=${String(i===this.active)} @mousedown=${(e:MouseEvent)=>e.preventDefault()} @click=${()=>this.choose(item)}>${item}</div>`)}</div><div class="actions"><button class="en-button" @click=${()=>{this.model.undo();this.sync();this.dismiss();}}>Undo</button><button class="en-button" @click=${()=>{this.model.redo();this.sync();this.dismiss();}}>Redo</button></div></div>`;}
}
customElements.define('recipe-editor',RecipeEditor);
class RecipeComposer extends LitElement {
 static override styles=[...(portable?[]:[...shared,chatStyles]),css`:host{display:block}.en-chat-composer{display:grid;gap:12px}`];
 sent?:ChatEditorSnapshot;message='No submission';
 private submit(e:Event){e.preventDefault();const editor=this.querySelector('recipe-editor')!;const adapter=getChatEditorAdapter(editor);if(!adapter||adapter.disabled||adapter.readOnly||adapter.composing||adapter.reportValidity?.()===false){this.message='Unavailable editor';this.requestUpdate();return;}const snapshot=snapshotChatEditor(adapter.getSnapshot());const event=new CustomEvent('before-send',{detail:snapshot,cancelable:true,bubbles:true,composed:true});if(this.dispatchEvent(event)){this.sent=snapshot;this.message=snapshot.value||'Empty draft';}this.requestUpdate();adapter.focus();}
 protected override render(){return html`${sheet('chat')}<form class="en-chat-composer en-foundation" @submit=${this.submit}><div class="en-chat-composer__editor"><slot></slot></div><div class="en-chat-actions en-chat-composer__actions"><button class="en-button en-chat-composer__send" type="submit">Send snapshot</button></div><p role="status">${this.message}</p></form>${this.sent?html`<article class="en-chat-message" aria-label="Submitted message"><header class="en-chat-message__header"><span class="en-chat-message__author">You</span><time class="en-chat-message__metadata">Just now</time></header><div class="en-chat-message__content">${this.sent.value}</div></article>`:null}`;}
}
customElements.define('recipe-composer',RecipeComposer);
class RecipeRich extends LitElement {
 static override styles=[...shared,tokenEditorStyles,richTextEditorStyles,css`:host{display:block}`];
 protected override render(){return html`<div class="en-foundation"><label class="label" id="rich-title">Native rich notes</label><div class="editor" role="textbox" aria-multiline="true" aria-labelledby="rich-title" contenteditable="true"><h2>Project brief</h2><p>Write <strong>bold ideas</strong> and <em>quiet notes</em>.</p><ul><li>First task</li><li>Second task</li></ul><p><a href="#guidance">Guidance</a></p></div></div>`;}
}
customElements.define('recipe-rich',RecipeRich);
class RecipePresence extends LitElement {
 static override styles=[...(portable?[]:[...shared,collaborationStyles]),css`:host{display:block}.avatar{inline-size:2rem;block-size:2rem;display:grid;place-items:center;flex:none}.members>*{flex:1;min-inline-size:160px}`];
 expanded=false;older=false;loading=false;
 protected override render(){return html`${sheet('collaboration')}<section class="en-foundation" aria-label="Team activity"><div class="members"><a class="presence" href="#alex"><span class="avatar" aria-hidden="true">AK</span><span class="identity"><span class="name">Alex Kim</span><span class="status" data-status="online"><span class="dot" aria-hidden="true"></span>Online</span></span></a><div class="presence"><span class="identity"><span class="name">Sam Jones</span><span class="status" data-status="away"><span class="dot" aria-hidden="true"></span>Away</span></span></div></div><div class="feed"><h2>Project activity</h2><p class="announcement" role="status">${this.loading?'Loading older activity':this.older?'Older activity loaded':'Up to date'}</p><div class="list" role="list">${(this.older?['Earlier draft','Current draft']:['Current draft']).map(title=>html`<article class="item" role="listitem"><header><span class="author">Alex Kim</span><time datetime="2026-10-02T12:00:00Z">12:00</time></header><div class="body">${title}</div></article>`)}</div><div class="history-pagination"><button class="en-button" ?disabled=${this.loading||this.older} @click=${()=>{this.loading=true;this.requestUpdate();}}>Load older</button><button class="en-button" ?disabled=${!this.loading} @click=${()=>{this.older=true;this.loading=false;this.requestUpdate();}}>Complete request</button></div></div></section>`;}
}
customElements.define('recipe-presence',RecipePresence);
// Explicit registry lifetime probe; uses independent elements, never an owning component.
Object.assign(window,{editorContracts:{registerChatEditor,getChatEditorAdapter,snapshotChatEditor,EditorBookmarks,EditorExtensionRegistry}});
