/** Reviewed public CSS contracts. Sources are consumers, not a promise that every
 * selector in a family consumes every hook. Exact source coverage is checked by
 * tooling/customization; runtime consumers never read the filesystem. */
export interface HookDeclaration {
  readonly cssName: string;
  readonly family: string;
  readonly syntax: string;
  readonly fallbackTokens: readonly string[];
  readonly fallbackCSS: readonly string[];
  readonly description: string;
  readonly consumers: readonly string[];
  readonly kind: 'override' | 'configuration' | 'mechanical';
  readonly states: readonly string[];
  readonly concepts: readonly string[];
  readonly size: 'none' | 'fixed' | 'minimum' | 'maximum' | 'preferred' | 'relative' | 'configuration' | 'mechanical';
  readonly consumerStatus: 'connected' | 'unwired';
}

interface Details {
  readonly css?: readonly string[];
  readonly note?: string;
  readonly state?: readonly string[];
  readonly concept?: readonly string[];
  readonly size?: HookDeclaration['size'];
  readonly kind?: HookDeclaration['kind'];
  readonly consumerStatus?: HookDeclaration['consumerStatus'];
}
const source = (name: string) => `packages/styles/src/${name}.ts`;
const element = (name: string) => `packages/elements/src/${name}.ts`;
const length = '<length-percentage>';
const radius = '<border-radius>';
const paint = '<background>';
const color = '<color>';
const gap = '<gap>';
const padding = '<padding>';
const weight = '<font-weight>';

/** These are recipe families, including recipes that consume only semantic
 * tokens. Keep family membership alongside the source contract declarations. */
export const customizationFamilies = [
  ['carousel', [source('carousel')]],
  ['collaboration', [source('collaboration')]],
  ['color-slider', [source('color-slider')]],
  ['color-picker', [source('color-picker')]],
  ['color-plane', [source('color-picker')]],
  ['color-wheel', [source('color-wheel')]],
  ['toast', [source('toast')]],
  ['foundations', [source('foundations')]],
  ['controls', [source('controls'), source('internal/control-shared'), source('internal/control-size')]],
  ['buttons', [source('buttons'), source('internal/button-rules')]],
  ['links', [source('links'), source('internal/link-rules')]],
  ['radio', [source('radio'), source('internal/radio-rules')]],
  ['combobox', [source('combobox')]],
  ['selection', [source('selection'), source('internal/option-paint')]],
  ['surfaces', [source('surfaces')]],
  ['overlays', [source('overlays')]],
  ['feedback', [source('feedback'), source('activity')]],
  ['recipes', [source('recipes')]],
  ['navigation', [source('navigation')]],
  ['commands', [source('commands')]],
  ['content', [source('content')]],
  ['table', [source('table'), element('data-table/element')]],
  ['pagination', [source('pagination')]],
  ['tree', [source('tree')]],
  ['file-upload', [source('file-upload')]],
  ['calendar', [source('calendar')]],
  ['chat', [source('chat')]],
  ['token-editor', [source('token-editor')]],
  ['rich-text-editor', [source('rich-text-editor'), element('rich-text-editor/element')]],
  ['editor-toolbar', [element('editor-toolbar')]],
  ['form-navigation', [source('form-navigation')]],
  ['typography', [source('typography')]],
] as const;

type Family = typeof customizationFamilies[number][0];
type DeclaredKind<D extends Details> = D extends {readonly kind: infer K extends HookDeclaration['kind']} ? K : 'override';
function hook<const N extends string, const D extends Details = {}>(cssName: N, family: Family, syntax: string, tokens: string[] = [], details: D = {} as D, consumers?: readonly string[]): Omit<HookDeclaration,'cssName' | 'kind'> & {readonly cssName: N; readonly kind: DeclaredKind<D>} {
  return {
    cssName, family, syntax, fallbackTokens: tokens, fallbackCSS: details.css ?? [],
    description: details.note ?? (tokens.length ? 'Contextual stylesheet fallback; a managed token default may differ from the rendered fallback.' : 'Uses the contextual stylesheet fallback when unset.'),
    consumers: consumers ?? customizationFamilies.find(([name]) => name === family)![1],
    kind: (details.kind ?? 'override') as DeclaredKind<D>, states: details.state ?? [],
    concepts: details.concept ?? (syntax === color || syntax === paint ? ['paint'] : syntax === radius ? ['radius','geometry'] : syntax === weight ? ['typography'] : ['geometry']),
    size: details.size ?? ([length,radius,gap,padding].includes(syntax) ? 'fixed' : 'none'),
    consumerStatus: details.consumerStatus ?? 'connected',
  };
}

/** Optional overrides retain the guaranteed-invalid/unset fallback. Existing
 * resettable names keep that policy, including older layout hooks. New authored
 * viewport/configuration inputs deliberately preserve inheritance. */
export const hookDeclarations = [
  hook('--en-switch-thumb-pressed-size','controls','<length>',[],{note:'Thumb-only held geometry; disabled/reduced motion retain the resting geometry.',state:['pressed']},[source('controls')]),
  hook('--en-slider-thumb-pressed-scale','controls','<number>',[],{note:'Thumb-only held geometry; disabled/reduced motion retain the resting geometry.',state:['pressed']},[source('internal/range')]),
  hook('--en-slider-thumb-press-duration','controls','<time>',[],{note:'Thumb-only held geometry; disabled/reduced motion retain the resting geometry.',state:['pressed']},[source('internal/range')]),
  hook('--en-slider-thumb-release-duration','controls','<time>',[],{note:'Thumb-only held geometry; disabled/reduced motion retain the resting geometry.',state:['pressed']},[source('internal/range')]),
  hook('--en-color-plane-thumb-pressed-scale','color-picker','<number>',[],{note:'Thumb-only held geometry; disabled/reduced motion retain the resting geometry.',state:['pressed']},[source('color-picker')]),
  hook('--en-color-plane-thumb-press-duration','color-picker','<time>',[],{note:'Thumb-only held geometry; disabled/reduced motion retain the resting geometry.',state:['pressed']},[source('color-picker')]),
  hook('--en-color-plane-thumb-release-duration','color-picker','<time>',[],{note:'Thumb-only held geometry; disabled/reduced motion retain the resting geometry.',state:['pressed']},[source('color-picker')]),
  hook('--en-segmented-pressed-scale','selection','<number>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-segmented-pressed-offset','selection','<length>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-segmented-press-duration','selection','<time>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-segmented-release-duration','selection','<time>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-segmented-pressed-shadow','selection','<shadow>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-segmented-pressed-background','selection','<color>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-segmented-pressed-color','selection','<color>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-segmented-pressed-border-color','selection','<color>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-accordion-pressed-scale','selection','<number>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-accordion-pressed-offset','selection','<length>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-accordion-press-duration','selection','<time>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-accordion-release-duration','selection','<time>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-accordion-pressed-shadow','selection','<shadow>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-accordion-pressed-background','selection','<color>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-accordion-pressed-color','selection','<color>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-tab-pressed-scale','selection','<number>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-tab-pressed-offset','selection','<length>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-tab-press-duration','selection','<time>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-tab-release-duration','selection','<time>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-tab-pressed-shadow','selection','<shadow>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-tab-pressed-color','selection','<color>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-rating-pressed-scale','selection','<number>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-rating-pressed-offset','selection','<length>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-rating-press-duration','selection','<time>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-rating-release-duration','selection','<time>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-rating-pressed-shadow','selection','<shadow>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-rating-pressed-background','selection','<color>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-rating-pressed-color','selection','<color>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-combobox-trigger-pressed-scale','combobox','<number>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-combobox-trigger-pressed-offset','combobox','<length>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-combobox-trigger-press-duration','combobox','<time>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-combobox-trigger-release-duration','combobox','<time>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-combobox-trigger-pressed-shadow','combobox','<shadow>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-combobox-trigger-pressed-background','combobox','<color>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-combobox-trigger-pressed-color','combobox','<color>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-navigation-pressed-scale','navigation','<number>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-navigation-pressed-offset','navigation','<length>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-navigation-press-duration','navigation','<time>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-navigation-release-duration','navigation','<time>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-navigation-pressed-shadow','navigation','<shadow>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-navigation-pressed-color','navigation','<color>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-editor-token-pressed-scale','token-editor','<number>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-editor-token-pressed-offset','token-editor','<length>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-editor-token-press-duration','token-editor','<time>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-editor-token-release-duration','token-editor','<time>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-editor-token-pressed-shadow','token-editor','<shadow>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-editor-token-pressed-background','token-editor','<color>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-editor-token-pressed-color','token-editor','<color>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-editor-token-pressed-border-color','token-editor','<color>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-option-pressed-scale','selection','<number>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-option-pressed-offset','selection','<length>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-option-press-duration','selection','<time>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-option-release-duration','selection','<time>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-option-pressed-shadow','selection','<shadow>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-calendar-pressed-scale','calendar','<number>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-calendar-pressed-offset','calendar','<length>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-calendar-press-duration','calendar','<time>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-calendar-release-duration','calendar','<time>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-calendar-pressed-shadow','calendar','<shadow>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-checkbox-pressed-scale','controls','<number>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-checkbox-pressed-offset','controls','<length>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-checkbox-press-duration','controls','<time>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-checkbox-release-duration','controls','<time>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-checkbox-pressed-shadow','controls','<shadow>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-checkbox-pressed-border-color','controls','<color>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-radio-pressed-scale','controls','<number>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-radio-pressed-offset','controls','<length>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-radio-press-duration','controls','<time>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-radio-release-duration','controls','<time>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-radio-pressed-shadow','controls','<shadow>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-radio-pressed-border-color','controls','<color>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-switch-pressed-scale','controls','<number>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-switch-pressed-offset','controls','<length>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-switch-press-duration','controls','<time>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-switch-release-duration','controls','<time>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-switch-pressed-shadow','controls','<shadow>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-switch-pressed-border-color','controls','<color>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-select-pressed-scale','controls','<number>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-select-pressed-offset','controls','<length>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-select-press-duration','controls','<time>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-select-release-duration','controls','<time>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-select-pressed-shadow','controls','<shadow>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-select-pressed-background','controls','<color>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-select-pressed-color','controls','<color>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-number-step-pressed-scale','controls','<number>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-number-step-pressed-offset','controls','<length>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-number-step-press-duration','controls','<time>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-number-step-release-duration','controls','<time>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-number-step-pressed-shadow','controls','<shadow>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-number-step-pressed-background','controls','<color>',[],{note:'Family held feedback; full surface motion is opt-in, bounded and reduced-motion safe.',state:['pressed']},[source('internal/press-recipes')]),
  hook('--en-input-radius','controls','<length>',[],{note:'Narrow field frame refinement; disabled and forced colors win.',state:[]},[source('internal/field-presentation')]),
  hook('--en-input-border-width','controls','<length>',[],{note:'Narrow field frame refinement; disabled and forced colors win.',state:[]},[source('internal/field-presentation')]),
  hook('--en-input-invalid-border-width','controls','<length>',[],{note:'Narrow field frame refinement; disabled and forced colors win.',state:['invalid']},[source('internal/field-presentation')]),
  hook('--en-input-border-color','controls','<color>',[],{note:'Narrow field frame refinement; disabled and forced colors win.',state:[]},[source('internal/field-presentation')]),
  hook('--en-input-hover-border-color','controls','<color>',[],{note:'Narrow field frame refinement; disabled and forced colors win.',state:['hover']},[source('internal/field-presentation')]),
  hook('--en-input-invalid-border-color','controls','<color>',[],{note:'Narrow field frame refinement; disabled and forced colors win.',state:['invalid']},[source('internal/field-presentation')]),
  hook('--en-surface-shadow','surfaces','<shadow>',[],{note:'Optional elevation on panels/cards; forced colors removes shadows.',state:[]},['packages/styles/src/css/surface.css']),
  hook('--en-card-shadow','surfaces','<shadow>',[],{note:'Optional elevation on panels/cards; forced colors removes shadows.',state:[]},['packages/styles/src/css/surface.css']),
  hook('--en-button-shadow','buttons','<shadow>',[],{note:'Whole-button presentation preserves layout allocation. Popup motion is theme-specific; explicit opt-out and reduced motion suppress movement.',state:['pressed']},[source('internal/button-rules')]),
  hook('--en-button-pressed-shadow','buttons','<shadow>',[],{note:'Whole-button presentation preserves layout allocation. Popup motion is theme-specific; explicit opt-out and reduced motion suppress movement.',state:['pressed']},[source('internal/button-rules')]),
  hook('--en-button-pressed-scale','buttons','<number>',[],{note:'Whole-button presentation preserves layout allocation. Popup motion is theme-specific; explicit opt-out and reduced motion suppress movement.',state:['pressed']},[source('internal/button-rules')]),
  hook('--en-button-popup-pressed-scale','buttons','<number>',[],{note:'Whole-button popup-trigger scale; falls back to ordinary pressed-scale.',state:['pressed']},[source('internal/button-rules')]),
  hook('--en-button-popup-pressed-offset','buttons','<length>',[],{note:'Whole-button popup-trigger translation; falls back to ordinary pressed-offset.',state:['pressed']},[source('internal/button-rules')]),
  hook('--en-button-pressed-offset','buttons','<length>',[],{note:'Whole-button presentation preserves layout allocation. Popup motion is theme-specific; explicit opt-out and reduced motion suppress movement.',state:['pressed']},[source('internal/button-rules')]),
  hook('--en-button-press-duration','buttons','<time>',[],{note:'Whole-button presentation preserves layout allocation. Popup motion is theme-specific; explicit opt-out and reduced motion suppress movement.',state:['pressed']},[source('internal/button-rules')]),
  hook('--en-button-release-duration','buttons','<time>',[],{note:'Whole-button presentation preserves layout allocation. Popup motion is theme-specific; explicit opt-out and reduced motion suppress movement.',state:['pressed']},[source('internal/button-rules')]),
  hook('--en-navigation-hover-background','navigation','<color>',[],{note:'Separate contextual state; old active hooks remain compatible fallbacks.',state:['hover']},[source('navigation')]),
  hook('--en-navigation-hover-color','navigation','<color>',[],{note:'Separate contextual state; old active hooks remain compatible fallbacks.',state:['hover']},[source('navigation')]),
  hook('--en-navigation-current-background','navigation','<color>',[],{note:'Separate contextual state; old active hooks remain compatible fallbacks.',state:['current']},[source('navigation')]),
  hook('--en-navigation-current-color','navigation','<color>',[],{note:'Separate contextual state; old active hooks remain compatible fallbacks.',state:['current']},[source('navigation')]),
  hook('--en-navigation-pressed-background','navigation','<color>',[],{note:'Separate contextual state; old active hooks remain compatible fallbacks.',state:['pressed']},[source('navigation')]),
  hook('--en-navigation-current-indicator-color','navigation','<color>',[],{note:'Separate contextual state; old active hooks remain compatible fallbacks.',state:['current']},[source('navigation')]),
  hook('--en-navigation-current-indicator-width','navigation','<length>',[],{note:'Separate contextual state; old active hooks remain compatible fallbacks.',state:['current']},[source('navigation')]),
  hook('--en-tab-hover-background','selection','<color>',[],{note:'Separate contextual state; old active hooks remain compatible fallbacks.',state:['hover']},[source('selection')]),
  hook('--en-tab-hover-color','selection','<color>',[],{note:'Separate contextual state; old active hooks remain compatible fallbacks.',state:['hover']},[source('selection')]),
  hook('--en-tab-selected-background','selection','<color>',[],{note:'Separate contextual state; old active hooks remain compatible fallbacks.',state:['selected']},[source('selection')]),
  hook('--en-tab-selected-color','selection','<color>',[],{note:'Separate contextual state; old active hooks remain compatible fallbacks.',state:['selected']},[source('selection')]),
  hook('--en-tab-pressed-background','selection','<color>',[],{note:'Separate contextual state; old active hooks remain compatible fallbacks.',state:['pressed']},[source('selection')]),
  hook('--en-tab-indicator-color','selection','<color>',[],{note:'Separate contextual state; old active hooks remain compatible fallbacks.',state:['indicator']},[source('selection')]),
  hook('--en-popup-enter-duration','overlays','<time>',['duration.enter'],{note:'Bounded family visual timing; interaction remains immediate.',state:['enter']},[source('internal/surface-motion')]),
  hook('--en-popup-enter-ease','overlays','<easing-function>',['ease.enter'],{note:'Bounded family visual timing; interaction remains immediate.',state:['enter']},[source('internal/surface-motion')]),
  hook('--en-popup-exit-duration','overlays','<time>',['duration.exit'],{note:'Bounded family visual timing; interaction remains immediate.',state:['exit']},[source('internal/surface-motion')]),
  hook('--en-popup-exit-ease','overlays','<easing-function>',['ease.exit'],{note:'Bounded family visual timing; interaction remains immediate.',state:['exit']},[source('internal/surface-motion')]),
  hook('--en-dialog-enter-duration','overlays','<time>',['duration.enter'],{note:'Bounded family visual timing; interaction remains immediate.',state:['enter']},[source('internal/surface-motion')]),
  hook('--en-dialog-enter-ease','overlays','<easing-function>',['ease.enter'],{note:'Bounded family visual timing; interaction remains immediate.',state:['enter']},[source('internal/surface-motion')]),
  hook('--en-dialog-exit-duration','overlays','<time>',['duration.exit'],{note:'Bounded family visual timing; interaction remains immediate.',state:['exit']},[source('internal/surface-motion')]),
  hook('--en-dialog-exit-ease','overlays','<easing-function>',['ease.exit'],{note:'Bounded family visual timing; interaction remains immediate.',state:['exit']},[source('internal/surface-motion')]),
  hook('--en-toast-enter-duration','toast','<time>',['duration.enter'],{note:'Bounded family visual timing; interaction remains immediate.',state:['enter']},[source('toast')]),
  hook('--en-toast-enter-ease','toast','<easing-function>',['ease.enter'],{note:'Bounded family visual timing; interaction remains immediate.',state:['enter']},[source('toast')]),
  hook('--en-toast-exit-duration','toast','<time>',['duration.exit'],{note:'Bounded family visual timing; interaction remains immediate.',state:['exit']},[source('toast')]),
  hook('--en-toast-exit-ease','toast','<easing-function>',['ease.exit'],{note:'Bounded family visual timing; interaction remains immediate.',state:['exit']},[source('toast')]),
  hook('--en-choice-size','controls','<length>',[],{note:'Visual anatomy; independent target floor remains enforced.',state:[]},[source('controls'),source('internal/radio-rules')]),
  hook('--en-switch-inline-size','controls','<length>',[],{note:'Visual anatomy; independent target floor remains enforced.',state:[]},[source('controls')]),
  hook('--en-switch-block-size','controls','<length>',[],{note:'Visual anatomy; independent target floor remains enforced.',state:[]},[source('controls')]),
  hook('--en-switch-thumb-size','controls','<length>',[],{note:'Visual anatomy; independent target floor remains enforced.',state:[]},[source('controls')]),
  hook('--en-carousel-gap','carousel',gap,['space.3']),
  hook('--en-carousel-radius','carousel',radius,['radius.container']),
  hook('--en-carousel-background','carousel',paint,['color.surface']),
  hook('--en-carousel-border-color','carousel',color,['color.line']),
  hook('--en-carousel-slides-per-view','carousel','<number>',[],{size:'relative',note:'Positive visible-slide count; falls back to the element-owned --_en-carousel-per-view value, then 1.'}),
  ...(['presence','activity'] as const).flatMap(family => [
    hook(`--en-${family}-gap`,'collaboration',gap,[family === 'presence' ? 'space.2' : 'space.3']),
    hook(`--en-${family}-padding`,'collaboration',padding,[family === 'presence' ? 'space.2' : 'space.4']),
    hook(`--en-${family}-border-color`,'collaboration',color,['color.line']),
    hook(`--en-${family}-radius`,'collaboration',radius,['radius.container']),
    hook(`--en-${family}-background`,'collaboration',paint,['color.surface']),
  ]),
  hook('--en-presence-hover-background','collaboration',paint,['color.surface-subtle'],{state:['hover']}),
  hook('--en-presence-hover-border-color','collaboration',color,['color.link'],{state:['hover']}),
  hook('--en-presence-online-color','collaboration',color,['color.success-text'],{state:['online'],concept:['status','paint']}),
  hook('--en-presence-busy-color','collaboration',color,['color.danger-text'],{state:['busy'],concept:['status','paint']}),
  hook('--en-presence-group-gap','collaboration',gap,['space.2']),
  hook('--en-color-slider-track-size','color-slider',length,[],{note:'Track thickness defaults to 1.5rem. The separate input minimum follows thumb size and target floors.'}),
  hook('--en-color-slider-thumb-size','color-slider',length,[],{note:'Native slider thumb diameter; fallback is 1.75rem.'}),
  hook('--en-color-slider-radius','color-slider',radius,['radius.control']),
  hook('--en-color-slider-checker-size','color-slider',length,[],{size:'relative',note:'Transparency tile size defaults to .5rem; the repeating checker uses twice this dimension.'}),
  hook('--en-color-slider-checker-light','color-slider',color,[],{note:'Transparency tile color; fallback is #fff.'}),
  hook('--en-color-slider-checker-dark','color-slider',color,[],{note:'Transparency tile color; fallback is #b8b8b8.'}),
  hook('--en-color-picker-inline-size','color-picker',length,[],{size:'preferred',note:'Preferred width defaults to 20rem and is capped by available space.'}),
  hook('--en-color-picker-gap','color-picker',gap,[],{css:['--en-field-gap'],note:'Falls back to the shared field gap, then .75rem.'}),
  hook('--en-color-picker-preview-size','color-picker',length,[],{note:'Square preview width; fallback is 3rem.'}),
  hook('--en-color-picker-preview-radius','color-picker',radius,['radius.control']),
  ...(['background','color','border-color','hover-background','pressed-background'] as const).map(role => hook(`--en-editor-token-${role}`,'token-editor',role.includes('background') ? paint : color,[({'background':'color.surface-subtle','color':'color.text','border-color':'color.line','hover-background':'color.selected','pressed-background':'color.accent-subtle'} as const)[role]],{state:role.startsWith('hover')?['hover']:role.startsWith('pressed')?['pressed']:[]})),
  hook('--en-editor-token-radius','token-editor',radius,['radius.control']),
  hook('--en-editor-token-inline-padding','token-editor',length,[],{note:'Inline token padding falls back to .375em.'}),
  hook('--en-editor-token-block-padding','token-editor',length,[],{note:'Block token padding falls back to .125em.'}),
  hook('--en-editor-token-gap','token-editor',length,[],{size:'relative',note:'Half this gap is applied on each inline margin; fallback is .25rem.'}),
  hook('--en-editor-token-min-size','token-editor',length,[],{size:'minimum',note:'Inline and block minimum defaults to 2rem; interactive tokens retain target floors.'}),
  hook('--en-toast-stack-offset','toast',length,['space.1'],{size:'relative',concept:['elevation','geometry']}),
  hook('--en-toast-shadow','toast','<shadow>',[],{note:'Rendered default is none, although the managed token default aliases shadow.overlay.',concept:['elevation']}),
  hook('--en-toast-icon-color','toast',color,[],{note:'General icon paint falls back to currentColor.',concept:['status','paint']}),
  ...(['info','success','warning','danger'] as const).flatMap(variant => (['background','color','border-color','icon-color'] as const).map(role => hook(`--en-toast-${variant}-${role}`,'toast',role === 'background' ? paint : color,[role === 'background' ? 'color.surface' : role === 'color' ? 'color.text' : role === 'border-color' ? 'color.line' : variant === 'info' ? 'color.action-text' : `color.${variant}-text`],{css:[`--en-toast-${role}`],state:[variant],concept:['status','paint'],note:'Variant paint refines the general toast hook before the contextual semantic fallback.'}))),
  hook('--en-toast-background','toast',paint,['color.surface']),
  hook('--en-toast-color','toast',color,['color.text']),
  hook('--en-toast-border-color','toast',color,['color.line']),
  hook('--en-toast-radius','toast',radius,['radius.container']),
  hook('--en-toast-padding','toast',padding,['space.panel']),
  hook('--en-toast-region-gap','toast',gap,['space.3']),
  hook('--en-toast-region-width','toast',length,[],{size:'preferred',note:'Preferred region width defaults to 24rem and is capped by the viewport.'}),
  hook('--en-toast-region-max-size','toast',length,[],{size:'maximum',note:'Maximum scroll size defaults to min(60dvh,32rem); fixed placements also allow for the keyboard.'}),
  hook('--en-toast-region-layer','toast','<integer>',[],{note:'Authored stacking level defaults to 100. Retains its existing full-theme reset policy.'}),
  ...(['button','input','option','overlay'] as const).flatMap(family => (['width','color','offset','halo-width','halo-color'] as const).map(role => hook(`--en-${family}-focus-${role}`,family === 'button' ? 'buttons' : family === 'input' ? 'controls' : family === 'option' ? 'selection' : 'overlays',role.includes('color') ? color : '<length>',[role === 'color' ? 'color.focus' : role === 'halo-color' ? 'color.focus-halo' : `focus.${role}`],{state:['focus-visible'],concept:['focus',role.includes('color')?'paint':'geometry'],note:role === 'offset' ? 'Explicit signed offset wins; inset consumers otherwise derive the negative effective family contour width.' : 'Family focus input refines the shared semantic role; forced colors keeps native contrast.'},[source('internal/focus-core')]))),
  hook('--en-input-focus-accent-width','controls','<length>',['focus.accent-width'],{state:['focus-visible'],concept:['focus','geometry']}),
  hook('--en-input-focus-accent-color','controls',color,['color.focus'],{state:['focus-visible'],concept:['focus','paint']}),
  hook('--en-button-background','buttons',paint,['color.action','color.action-hover','color.action-pressed','color.surface-subtle','color.selected','color.surface'],{state:['rest','hover','pressed'],note:'Broad fill remains the fallback beneath explicit state refinements across variants; ghost rest remains none unless explicitly refined.'}),
  hook('--en-button-color','buttons',color,['color.on-action','color.text','color.action-text','color.danger-text']),
  hook('--en-button-rest-background','buttons',paint,['color.action','color.surface-subtle','color.surface'],{css:['--en-button-background'],state:['rest'],note:'Explicit rest refinement precedes broad button paint and contextual variant defaults. Disabled and forced-color treatments take precedence; ghost rest fill is opt-in.'},[source('internal/button-rules')]),
  hook('--en-button-rest-color','buttons',color,['color.on-action','color.text','color.action-text','color.danger-text'],{css:['--en-button-color'],state:['rest'],note:'Explicit rest refinement precedes broad button paint and contextual variant defaults. Disabled and forced-color treatments take precedence; ghost rest fill is opt-in.'},[source('internal/button-rules')]),
  hook('--en-button-hover-background','buttons',paint,['color.action-hover','color.selected','color.surface-subtle'],{css:['--en-button-background'],state:['hover'],note:'Explicit hover refinement precedes broad button paint and contextual variant defaults. Disabled and forced-color treatments take precedence; ghost rest fill is opt-in.'},[source('internal/button-rules')]),
  hook('--en-button-hover-color','buttons',color,['color.on-action','color.text','color.action-text','color.danger-text'],{css:['--en-button-color'],state:['hover'],note:'Explicit hover refinement precedes broad button paint and contextual variant defaults. Disabled and forced-color treatments take precedence; ghost rest fill is opt-in.'},[source('internal/button-rules')]),
  hook('--en-button-pressed-background','buttons',paint,['color.action-pressed','color.selected','color.surface-subtle','color.surface'],{css:['--en-button-background'],state:['pressed'],note:'Explicit pressed refinement precedes broad button paint and contextual variant defaults. Disabled and forced-color treatments take precedence; ghost rest fill is opt-in.'},[source('internal/button-rules')]),
  hook('--en-button-pressed-color','buttons',color,['color.on-action','color.text','color.action-text','color.danger-text'],{css:['--en-button-color'],state:['pressed'],note:'Explicit pressed refinement precedes broad button paint and contextual variant defaults. Disabled and forced-color treatments take precedence; ghost rest fill is opt-in.'},[source('internal/button-rules')]),
  hook('--en-button-border-color','buttons',color,['color.action','color.boundary','color.line','color.danger-text']),
  hook('--en-button-radius','buttons',radius,['radius.control'],{css:['--en-control-radius'],note:'Button family radius refines shared control radius; with both hooks unset, selected-size control radius applies.'}),
  hook('--en-button-inline-padding','buttons',length,['space.control-inline'],{css:['--en-control-inline-padding'],note:'Button family inline padding refines shared control padding before selected-size semantic spacing.'}),
  hook('--en-input-inline-padding','controls',length,['space.control-inline'],{css:['--en-control-inline-padding'],note:'Input family inline padding refines shared control padding in fields, comboboxes and file drop before selected-size semantic spacing.'}),
  hook('--en-segmented-control-frame-inset','selection',length,['space.1'],{size:'relative',note:'Nonnegative frame padding and target reserve apply only to segmented controls. Ordinary text controls retain the semantic baseline reserve and do not grow from this family pin.'}),
  hook('--en-control-background','controls',paint,['color.surface'],{note:'Shared control paint supplies the fallback beneath input family background in fields, comboboxes and file drop.'}),
  hook('--en-control-color','controls',color,['color.text'],{note:'Shared control text color supplies the fallback beneath input family color.'}),
  hook('--en-control-border-color','controls',color,['color.boundary']),
  hook('--en-control-radius','controls',radius,['radius.control'],{note:'Shared control corners, including the button fallback; an explicit button family radius refines this value.'}),
  hook('--en-input-background','controls',paint,['color.surface'],{css:['--en-control-background'],note:'Input family background refines shared control background before the semantic surface fallback.'}),
  hook('--en-input-color','controls',color,['color.text'],{css:['--en-control-color'],note:'Input family text color refines shared control color before the semantic text fallback.'}),
  hook('--en-card-background','surfaces',paint,['color.surface'],{css:['--en-surface-background'],note:'Card family background refines shared surface background before the semantic surface fallback.'}),
  hook('--en-radio-selected-color','radio',color,['color.action'],{state:['selected']}),
  hook('--en-control-min-size','controls',length,['size.control-min'],{size:'minimum',note:'Shared minimum control size; text and target floors can grow the actual control. Ordinary text controls retain the semantic space.1-plus-border baseline reserve; only segmented controls also reserve their authored frame inset.'}),
  hook('--en-control-inline-padding','controls',length,['space.control-inline'],{note:'Shared inline padding supplies the fallback beneath button and input family padding, then selected-size semantic spacing.'}),
  hook('--en-field-gap','controls',length,['space.label-control','space.control-description'],{concept:['spacing','field']}),
  hook('--en-select-appearance','controls','<appearance>',[],{note:'Native select appearance defaults to base-select; arbitrary CSS appearance keywords stay CSS-only.'}),
  ...(['background','color','border-color'] as const).map(role => hook(`--en-option-list-${role}`,'selection',role === 'background' ? paint : color,[role === 'background' ? 'color.surface-raised' : role === 'color' ? 'color.text' : 'color.boundary'],{css:[`--en-overlay-${role}`],note:'Option-list hook refines legacy overlay paint before context-specific semantic or inherited paint.'},[source('combobox'),source('commands'),source('controls'),source('token-editor')])),
  ...(['rest','hover','active','pressed','selected','disabled'] as const).flatMap(state => (['background','color'] as const).map(role => hook(`--en-option-${state}-${role}`,'selection',role === 'background' ? paint : color, state === 'selected' && role === 'background' ? ['color.selected'] : state === 'disabled' && role === 'color' ? ['color.text-muted'] : [],{css:[`--en-option-${role}`],state:[state],concept:['selection','paint'],note:'State paint refines broad option paint. Combined precedence is disabled, pressed, hover, active, selected, rest; unset slots retain contextual paint.'},[source('internal/option-paint'),source('calendar')]))),
  hook('--en-option-list-radius','selection',radius,['radius.container'],{css:['--en-overlay-radius']},[source('combobox'),source('commands'),source('controls'),source('token-editor')]),
  hook('--en-option-list-padding','selection',length,['space.1','space.2'],{css:['--en-overlay-padding'],note:'Contextual list inset; combobox/menu/select also reserve effective inset-focus clearance and use the scalar inset to derive row radius.'},[source('combobox'),source('commands'),source('controls'),source('token-editor')]),
  hook('--en-option-list-gap','selection',length,[],{note:'Space between option rows; rendered default is 0px.'},[source('combobox'),source('commands'),source('controls')]),
  hook('--en-option-list-max-block-size','selection',length,['layout.panel-preferred'],{css:['--en-overlay-max-block-size'],size:'maximum',note:'Popup height ceiling, additionally capped by available viewport geometry.'},[source('combobox'),source('commands'),source('controls')]),
  hook('--en-option-inline-padding','selection',length,['space.control-inline'],{},[source('combobox'),source('commands'),source('controls')]),
  hook('--en-option-block-padding','selection',length,['space.control-block'],{},[source('combobox'),source('commands'),source('controls')]),
  hook('--en-option-font-weight','selection',weight,[],{note:'Default option font weight inherits from its context.'}),
  hook('--en-option-selected-font-weight','selection',weight,['font.label-strong.weight'],{css:['--en-option-font-weight'],state:['selected']}),
  hook('--en-option-list-shadow','selection','<shadow>',['shadow.overlay'],{concept:['elevation']},[source('combobox'),source('commands'),source('controls'),source('token-editor')]),
  hook('--en-option-background','selection',paint,['color.surface','color.surface-subtle','color.selected'],{state:['rest','hover','active','pressed','selected','disabled'],note:'Legacy broad paint; explicit state hooks refine it in shared option-paint consumers.'}),
  hook('--en-option-color','selection',color,['color.text'],{state:['rest','hover','active','pressed','selected','disabled']}),
  hook('--en-option-radius','selection',radius,['radius.control'],{css:['--en-option-list-radius','--en-option-list-padding','--en-overlay-radius','--en-overlay-padding'],note:'Lists derive unpinned row radius from effective list radius minus padding and border; other options use selected control radius.'}),
  hook('--en-tab-background','selection',paint,['color.surface','color.surface-subtle','color.selected'],{state:['rest','hover','selected']}),
  hook('--en-tab-color','selection',color,['color.text','color.action-text'],{state:['rest','selected']}),
  hook('--en-surface-background','surfaces',paint,['color.surface'],{note:'Shared surface paint supplies the fallback beneath card family background; this family covers panel/card surfaces, not every container.'}),
  hook('--en-surface-color','surfaces',color,['color.text']),
  hook('--en-surface-border-color','surfaces',color,['color.line']),
  hook('--en-surface-radius','surfaces',radius,['radius.container']),
  hook('--en-surface-padding','surfaces',padding,['space.panel']),
  hook('--en-inset-outer-radius','surfaces',length,['radius.container'],{size:'relative',note:'Outer geometry input for max(0px, outer radius - inset distance).'}),
  hook('--en-inset-distance','surfaces',length,['space.2'],{size:'relative',note:'Inset distance subtracted from the outer radius.'}),
  hook('--en-inset-child-radius','surfaces',radius,[],{css:['--en-inset-outer-radius','--en-inset-distance'],note:'Explicit child corners replace the derived concentric fallback.'}),
  ...(['background','color','border-color','header-background','header-color','footer-background','footer-color','row-selected-background','row-selected-color','row-selected-indicator-color','row-hover-background'] as const).map(role => hook(`--en-table-${role}`,'table',role.includes('background') ? paint : color,[({'background':'color.surface','color':'color.text','border-color':'color.line','header-background':'color.surface-subtle','header-color':'color.text','footer-background':'color.surface','footer-color':'color.text','row-selected-background':'color.selected','row-selected-color':'color.text','row-selected-indicator-color':'color.action','row-hover-background':'color.surface-subtle'} as const)[role]],{css:role.startsWith('footer-')?[`--en-table-${role.slice(7)}`]:[],state:role.includes('selected')?['selected']:role.includes('hover')?['hover']:[],concept:['data','paint']})),
  hook('--en-data-table-selection-width','table',length,[],{size:'minimum',note:'Selection column defaults to 3.25rem and grows to fit the target minimum plus .5rem.'},[element('data-table/element')]),
  hook('--en-table-cell-block-padding','table',length,['space.rows'],{note:'Native cells also consume the host-provided private selected-size padding fallback.'}),
  hook('--en-table-cell-inline-padding','table',length,['space.control-inline'],{note:'Native cells also consume the host-provided private selected-size padding fallback.'}),
  hook('--en-table-radius','table',radius,['radius.container']),
  hook('--en-file-list-gap','content',gap,['space.3']),
  hook('--en-file-list-padding','content',padding,['space.3']),
  hook('--en-file-list-media-size','content',length,['size.control-min'],{size:'preferred',note:'Thumbnail width defaults to twice the selected control minimum and is capped by available space.'}),
  hook('--en-file-list-metadata-gap','content',gap,['space.5']),
  hook('--en-stack-gap','surfaces',gap,['space.rows','space.2','space.4','space.6'],{note:'Stack gap defaults vary with the explicit data-gap choice.'}),
  hook('--en-cluster-gap','surfaces',gap,['space.actions']),
  hook('--en-grid-gap','surfaces',gap,['space.4']),
  hook('--en-grid-item-min','surfaces',length,['layout.form-max','layout.panel-preferred'],{size:'minimum',note:'Intrinsic grid minimum varies by the layout/content recipe and is capped by available width.'}),
  hook('--en-pagination-gap','pagination',gap,['space.actions']),
  hook('--en-pagination-page-min-inline-size','pagination',length,['size.control-min'],{css:['--en-control-min-size'],size:'minimum',note:'Page width also accommodates digit width, padding, border and target floors.'}),
  hook('--en-pagination-status-gap','pagination',gap,['space.1']),
  hook('--en-overlay-arrow-size','overlays',length,['space.2'],{note:'Opt-in tooltip/popover/hover-card pointer projection; base is twice this length.'},[source('overlays')]),
  hook('--en-overlay-background','overlays',paint,['color.surface-raised']),
  hook('--en-overlay-color','overlays',color,['color.text']),
  hook('--en-overlay-border-color','overlays',color,['color.boundary']),
  hook('--en-overlay-radius','overlays',radius,['radius.dialog','radius.control','radius.container'],{note:'Dialog, tooltip and option-list consumers retain different contextual corners.'}),
  hook('--en-overlay-padding','overlays',padding,['space.panel','space.2','space.1']),
  hook('--en-overlay-max-inline-size','overlays',length,['layout.form-max'],{size:'maximum'}),
  hook('--en-overlay-max-block-size','overlays',length,['space.8','layout.panel-preferred'],{size:'maximum',note:'Contextual viewport ceiling; anchored consumers also honor available-position geometry.'}),
  hook('--en-alert-background','feedback',paint,['color.surface']),
  hook('--en-alert-color','feedback',color,['color.text']),
  hook('--en-alert-border-color','feedback',color,['color.line','color.action','color.success-text','color.warning-text','color.danger-text'],{concept:['status','paint']}),
  hook('--en-badge-background','feedback',paint,['color.surface-subtle','color.accent-subtle']),
  hook('--en-badge-color','feedback',color,['color.text','color.action-text','color.success-text','color.warning-text','color.danger-text']),
  hook('--en-badge-radius','feedback',radius,['radius.control']),
  hook('--en-progress-color','feedback',color,['color.action']),
  hook('--en-progress-track-color','feedback',color,['color.surface-subtle']),
  hook('--en-progress-size','feedback',length,['size.progress']),
  hook('--en-avatar-size','feedback',length,['size.avatar']),
  hook('--en-avatar-radius','feedback',radius,['radius.pill']),
  hook('--en-media-radius','feedback',radius,['radius.container'],{css:['--en-surface-radius','--en-surface-padding','--en-file-list-padding'],note:'Ordinary media uses container radius; file-card media derives concentric corners from its surface.'}),
  hook('--en-media-aspect-ratio','feedback','<ratio> | auto',[],{note:'Authored media aspect ratio; default is auto.',size:'relative'}),
  hook('--en-navigation-background','navigation',paint,['color.canvas']),
  hook('--en-navigation-color','navigation',color,['color.text-muted']),
  hook('--en-navigation-active-background','navigation',paint,['color.surface-subtle'],{state:['current','hover']}),
  hook('--en-navigation-active-color','navigation',color,['color.text'],{state:['current','hover']}),
  hook('--en-navigation-indent','navigation',length,['space.4']),
  hook('--en-navigation-border-color','navigation',color,['color.line']),
  hook('--en-navigation-gap','navigation',gap,['space.1','space.2']),
  hook('--en-navigation-link-radius','navigation',radius,['radius.pill','radius.control']),
  hook('--en-swatch-size','feedback',length,['size.swatch'],{size:'minimum',note:'Preview dimensions retain independent target minimums.'}),
  hook('--en-slider-length','controls',length,['size.range-length']),
  hook('--en-rating-star-radius','selection',radius,['radius.control']),
  hook('--en-skeleton-color','feedback',paint,['color.surface-subtle']),
  hook('--en-skeleton-size','feedback',length,['size.skeleton-line','size.avatar','space.16'],{note:'The line/circle/rectangle shape selects a different contextual size.'}),
  hook('--en-divider-color','surfaces',color,['color.line']),
  hook('--en-prose-max-inline-size','typography',length,['layout.prose-max'],{size:'maximum'}),
  hook('--en-icon-size','feedback',length,['size.icon']),

  // Source-audited visual additions (COVER-02), including element-local CSS.
  hook('--en-calendar-inline-size','calendar',length,[],{size:'preferred',note:'Calendar width defaults to 22rem and is capped by its container.'}),
  hook('--en-calendar-day-size','calendar',length,[],{size:'minimum',note:'Day width defaults to 2.5rem; cell width and pointer target floors constrain it.'}),
  hook('--en-calendar-gap','calendar',length,[],{note:'Day/table gap defaults to 2px.'}),
  hook('--en-calendar-day-radius','calendar',radius,['radius.control'],{css:['--en-option-radius'],note:'Calendar day corners refine option radius; range ends currently use the semantic radius directly as fallback.'}),
  hook('--en-calendar-range-background','calendar',paint,['color.selected'],{state:['range'],concept:['selection','paint']}),
  hook('--en-calendar-range-endpoint-background','calendar',paint,[],{state:['range-start','range-end'],note:'Endpoint fill falls back to transparent; range borders remain visible.',concept:['selection','paint']}),
  hook('--en-calendar-range-preview-background','calendar',paint,[],{state:['preview'],note:'Preview tint defaults to color-mix(in srgb,currentColor 10%,transparent).',concept:['selection','paint']}),
  hook('--en-chat-background','chat',paint,['color.surface']),
  hook('--en-chat-color','chat',color,['color.text']),
  hook('--en-chat-border-color','chat',color,['color.line']),
  hook('--en-chat-outgoing-background','chat',paint,['color.accent-subtle'],{state:['outgoing']}),
  hook('--en-chat-padding','chat',padding,['space.panel']),
  hook('--en-chat-radius','chat',radius,['radius.container']),
  hook('--en-color-plane-block-size','color-plane',length,[],{size:'preferred',note:'Plane height defaults to 12rem with a separate 6rem minimum.'}),
  hook('--en-color-plane-radius','color-plane',radius,['radius.control']),
  hook('--en-color-plane-thumb-size','color-plane',length,[],{note:'Circular thumb diameter defaults to 1.25rem; functional dual contour remains unchanged.'}),
  hook('--en-color-wheel-size','color-wheel',length,[],{size:'preferred',note:'Wheel width defaults to 14rem, capped at 100%; circular hue geometry remains intrinsic.'}),
  hook('--en-color-wheel-thumb-size','color-wheel',length,[],{note:'Circular thumb diameter defaults to 1.5rem.'}),
  hook('--en-color-wheel-track-size','color-wheel',length,[],{size:'relative',note:'Hue-ring thickness defaults to 2rem and positions the thumb at half this inset.'}),
  hook('--en-editor-toolbar-background','editor-toolbar',paint,['color.surface']),
  hook('--en-editor-toolbar-gap','editor-toolbar',gap,['space.1'],{note:'Applied to the nested toolbar base Part; controls computed spacing (THEME-06).'}),
  hook('--en-progress-steps-gap','form-navigation',gap,['space.actions']),
  hook('--en-validation-summary-padding','form-navigation',padding,['space.panel']),
  hook('--en-validation-summary-radius','form-navigation',radius,['radius.container']),

  // Authored layout configuration is intentionally inherited across themes.
  hook('--en-activity-viewport-size','collaboration',length,[],{kind:'configuration',size:'configuration',note:'Virtual activity viewport height (28rem fallback) belongs to application layout; full themes preserve it.'}),
  hook('--en-carousel-viewport-size','carousel',length,[],{kind:'configuration',size:'configuration',note:'Collection viewport height (22rem fallback) belongs to application layout; full themes preserve it.'}),
  hook('--en-tree-viewport-size','tree',length,[],{kind:'configuration',size:'configuration',note:'Virtual tree viewport height belongs to application layout; full themes preserve it.'}),
  hook('--en-data-table-viewport-size','table',length,[],{kind:'configuration',size:'configuration',note:'Maximum scrollport height (24rem fallback) belongs to application layout; full themes preserve it.'},[element('data-table/element')]),
  hook('--en-data-table-min-inline-size','table',length,[],{kind:'configuration',size:'configuration',note:'Native table minimum width (32rem fallback) belongs to application layout; full themes preserve it.'},[element('data-table/element')]),
  hook('--en-editor-max-size','token-editor',length,[],{kind:'configuration',size:'configuration',note:'Editor scroll ceiling (20rem fallback) belongs to application layout; full themes preserve it.'}),
  hook('--en-pagination-align','pagination','<content-position>',[],{kind:'configuration',size:'configuration',note:'Shared justify-content/text-align choice defaults to center; full themes preserve authored alignment.'}),

  // Controller/data-owned inputs must never enter theme reset or managed editors.
  hook('--en-progress-value','feedback','<percentage>',[],{kind:'mechanical',size:'mechanical',concept:['data'],note:'Progress data percentage, clamped to 0%–100%; fallback 0%.'}),
  hook('--en-split-ratio','surfaces','<number>',[],{kind:'mechanical',size:'mechanical',concept:['layout-state'],note:'Interactive splitter ratio; fallback 0.5.'}),
  hook('--en-navigation-height','navigation',length,[],{kind:'mechanical',size:'mechanical',concept:['layout-state'],note:'Measured navigation height used for target scroll margin; fallback 0px.'}),
  hook('--en-navigation-offset','navigation',length,[],{kind:'mechanical',size:'mechanical',concept:['layout-state'],note:'Controller/author sticky offset; fallback 0px.'}),
  hook('--en-navigation-position','navigation','<position>',[],{kind:'mechanical',size:'mechanical',concept:['layout-state'],note:'Controller/author sticky position; fallback static until geometry is available.'}),
  hook('--en-navigation-z-index','navigation','<integer> | auto',[],{kind:'mechanical',size:'mechanical',concept:['layout-state'],note:'Controller/author sticky stacking order; fallback 20.'}),
] as const;

/** Direct lexical/helper consumers from the reviewed source inventory. Recipe
 * family membership above additionally includes composition/import boundaries. */
export const directHookConsumers: Readonly<Record<string,readonly string[]>> = {
  "--en-switch-thumb-pressed-size": ["packages/styles/src/controls.ts"],
  "--en-slider-thumb-pressed-scale": ["packages/styles/src/internal/range.ts"],
  "--en-slider-thumb-press-duration": ["packages/styles/src/internal/range.ts"],
  "--en-slider-thumb-release-duration": ["packages/styles/src/internal/range.ts"],
  "--en-color-plane-thumb-pressed-scale": ["packages/styles/src/color-picker.ts"],
  "--en-color-plane-thumb-press-duration": ["packages/styles/src/color-picker.ts"],
  "--en-color-plane-thumb-release-duration": ["packages/styles/src/color-picker.ts"],
  "--en-segmented-pressed-scale": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-segmented-pressed-offset": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-segmented-press-duration": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-segmented-release-duration": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-segmented-pressed-shadow": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-segmented-pressed-background": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-segmented-pressed-color": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-segmented-pressed-border-color": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-accordion-pressed-scale": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-accordion-pressed-offset": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-accordion-press-duration": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-accordion-release-duration": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-accordion-pressed-shadow": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-accordion-pressed-background": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-accordion-pressed-color": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-tab-pressed-scale": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-tab-pressed-offset": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-tab-press-duration": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-tab-release-duration": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-tab-pressed-shadow": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-tab-pressed-color": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-rating-pressed-scale": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-rating-pressed-offset": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-rating-press-duration": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-rating-release-duration": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-rating-pressed-shadow": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-rating-pressed-background": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-rating-pressed-color": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-combobox-trigger-pressed-scale": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-combobox-trigger-pressed-offset": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-combobox-trigger-press-duration": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-combobox-trigger-release-duration": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-combobox-trigger-pressed-shadow": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-combobox-trigger-pressed-background": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-combobox-trigger-pressed-color": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-navigation-pressed-scale": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-navigation-pressed-offset": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-navigation-press-duration": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-navigation-release-duration": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-navigation-pressed-shadow": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-navigation-pressed-color": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-editor-token-pressed-scale": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-editor-token-pressed-offset": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-editor-token-press-duration": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-editor-token-release-duration": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-editor-token-pressed-shadow": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-editor-token-pressed-color": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-editor-token-pressed-border-color": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-option-pressed-scale": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-option-pressed-offset": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-option-press-duration": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-option-release-duration": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-option-pressed-shadow": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-calendar-pressed-scale": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-calendar-pressed-offset": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-calendar-press-duration": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-calendar-release-duration": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-calendar-pressed-shadow": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-checkbox-pressed-scale": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-checkbox-pressed-offset": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-checkbox-press-duration": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-checkbox-release-duration": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-checkbox-pressed-shadow": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-checkbox-pressed-border-color": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-radio-pressed-scale": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-radio-pressed-offset": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-radio-press-duration": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-radio-release-duration": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-radio-pressed-shadow": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-radio-pressed-border-color": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-switch-pressed-scale": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-switch-pressed-offset": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-switch-press-duration": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-switch-release-duration": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-switch-pressed-shadow": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-switch-pressed-border-color": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-select-pressed-scale": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-select-pressed-offset": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-select-press-duration": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-select-release-duration": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-select-pressed-shadow": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-select-pressed-background": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-select-pressed-color": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-number-step-pressed-scale": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-number-step-pressed-offset": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-number-step-press-duration": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-number-step-release-duration": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-number-step-pressed-shadow": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-number-step-pressed-background": ["packages/styles/src/internal/press-recipes.ts"],
  "--en-activity-background": ["packages/styles/src/collaboration.ts"],
  "--en-activity-border-color": ["packages/styles/src/collaboration.ts"],
  "--en-activity-gap": ["packages/styles/src/collaboration.ts"],
  "--en-activity-padding": ["packages/styles/src/collaboration.ts"],
  "--en-activity-radius": ["packages/styles/src/collaboration.ts"],
  "--en-activity-viewport-size": ["packages/styles/src/collaboration.ts"],
  "--en-alert-background": ["packages/styles/src/feedback.ts"],
  "--en-alert-border-color": ["packages/styles/src/feedback.ts"],
  "--en-alert-color": ["packages/styles/src/feedback.ts"],
  "--en-avatar-radius": ["packages/styles/src/feedback.ts"],
  "--en-avatar-size": ["packages/styles/src/feedback.ts"],
  "--en-badge-background": ["packages/styles/src/feedback.ts"],
  "--en-badge-color": ["packages/styles/src/feedback.ts"],
  "--en-badge-radius": ["packages/styles/src/feedback.ts"],
  "--en-button-background": ["packages/styles/src/internal/button-rules.ts"],
  "--en-button-border-color": ["packages/styles/src/internal/button-rules.ts"],
  "--en-button-color": ["packages/styles/src/internal/button-rules.ts"],
  "--en-button-focus-color": ["packages/styles/src/internal/focus-core.ts"],
  "--en-button-focus-halo-color": ["packages/styles/src/internal/focus-core.ts"],
  "--en-button-focus-halo-width": ["packages/styles/src/internal/focus-core.ts"],
  "--en-button-focus-offset": ["packages/styles/src/internal/focus-core.ts"],
  "--en-button-focus-width": ["packages/styles/src/internal/focus-core.ts"],
  "--en-button-hover-background": ["packages/styles/src/internal/button-rules.ts"],
  "--en-button-hover-color": ["packages/styles/src/internal/button-rules.ts"],
  "--en-button-inline-padding": ["packages/styles/src/internal/button-rules.ts"],
  "--en-button-press-duration": ["packages/styles/src/internal/button-rules.ts"],
  "--en-button-pressed-background": ["packages/styles/src/internal/button-rules.ts"],
  "--en-button-pressed-color": ["packages/styles/src/internal/button-rules.ts"],
  "--en-button-pressed-offset": ["packages/styles/src/internal/button-rules.ts", "packages/styles/src/internal/press-recipes.ts"],
  "--en-button-popup-pressed-scale": ["packages/styles/src/internal/button-rules.ts"],
  "--en-button-popup-pressed-offset": ["packages/styles/src/internal/button-rules.ts"],
  "--en-button-pressed-scale": ["packages/styles/src/internal/button-rules.ts", "packages/styles/src/internal/press-recipes.ts"],
  "--en-button-pressed-shadow": ["packages/styles/src/internal/button-rules.ts"],
  "--en-button-radius": ["packages/styles/src/internal/button-rules.ts"],
  "--en-button-release-duration": ["packages/styles/src/internal/button-rules.ts"],
  "--en-button-rest-background": ["packages/styles/src/internal/button-rules.ts"],
  "--en-button-rest-color": ["packages/styles/src/internal/button-rules.ts"],
  "--en-button-shadow": ["packages/styles/src/internal/button-rules.ts"],
  "--en-calendar-day-radius": ["packages/styles/src/calendar.ts"],
  "--en-calendar-day-size": ["packages/styles/src/calendar.ts"],
  "--en-calendar-gap": ["packages/styles/src/calendar.ts"],
  "--en-calendar-inline-size": ["packages/styles/src/calendar.ts"],
  "--en-calendar-range-background": ["packages/styles/src/calendar.ts"],
  "--en-calendar-range-endpoint-background": ["packages/styles/src/calendar.ts"],
  "--en-calendar-range-preview-background": ["packages/styles/src/calendar.ts"],
  "--en-card-background": ["packages/styles/src/css/surface.css"],
  "--en-card-shadow": ["packages/styles/src/css/surface.css"],
  "--en-carousel-background": ["packages/styles/src/carousel.ts"],
  "--en-carousel-border-color": ["packages/styles/src/carousel.ts"],
  "--en-carousel-gap": ["packages/styles/src/carousel.ts"],
  "--en-carousel-radius": ["packages/styles/src/carousel.ts"],
  "--en-carousel-slides-per-view": ["packages/styles/src/carousel.ts"],
  "--en-carousel-viewport-size": ["packages/styles/src/carousel.ts"],
  "--en-chat-background": ["packages/styles/src/chat.ts"],
  "--en-chat-border-color": ["packages/styles/src/chat.ts"],
  "--en-chat-color": ["packages/styles/src/chat.ts"],
  "--en-chat-outgoing-background": ["packages/styles/src/chat.ts"],
  "--en-chat-padding": ["packages/styles/src/chat.ts"],
  "--en-chat-radius": ["packages/styles/src/chat.ts"],
  "--en-choice-size": ["packages/styles/src/controls.ts", "packages/styles/src/internal/radio-rules.ts"],
  "--en-cluster-gap": ["packages/styles/src/surfaces.ts"],
  "--en-color-picker-gap": ["packages/styles/src/color-picker.ts"],
  "--en-color-picker-inline-size": ["packages/styles/src/color-picker.ts"],
  "--en-color-picker-preview-radius": ["packages/styles/src/color-picker.ts"],
  "--en-color-picker-preview-size": ["packages/styles/src/color-picker.ts"],
  "--en-color-plane-block-size": ["packages/styles/src/color-picker.ts"],
  "--en-color-plane-radius": ["packages/styles/src/color-picker.ts"],
  "--en-color-plane-thumb-size": ["packages/styles/src/color-picker.ts"],
  "--en-color-slider-checker-dark": ["packages/styles/src/color-picker.ts", "packages/styles/src/color-slider.ts"],
  "--en-color-slider-checker-light": ["packages/styles/src/color-picker.ts", "packages/styles/src/color-slider.ts"],
  "--en-color-slider-checker-size": ["packages/styles/src/color-picker.ts", "packages/styles/src/color-slider.ts"],
  "--en-color-slider-radius": ["packages/styles/src/color-slider.ts"],
  "--en-color-slider-thumb-size": ["packages/styles/src/color-slider.ts"],
  "--en-color-slider-track-size": ["packages/styles/src/color-slider.ts"],
  "--en-color-wheel-size": ["packages/styles/src/color-wheel.ts"],
  "--en-color-wheel-thumb-size": ["packages/styles/src/color-wheel.ts"],
  "--en-color-wheel-track-size": ["packages/styles/src/color-wheel.ts"],
  "--en-control-background": ["packages/styles/src/controls.ts", "packages/styles/src/file-upload.ts", "packages/styles/src/internal/control-shared.ts", "packages/styles/src/token-editor.ts"],
  "--en-control-border-color": ["packages/styles/src/combobox.ts", "packages/styles/src/controls.ts", "packages/styles/src/file-upload.ts", "packages/styles/src/internal/control-shared.ts", "packages/styles/src/internal/field-presentation.ts"],
  "--en-control-color": ["packages/styles/src/controls.ts", "packages/styles/src/file-upload.ts", "packages/styles/src/internal/control-shared.ts", "packages/styles/src/token-editor.ts"],
  "--en-control-inline-padding": ["packages/styles/src/combobox.ts", "packages/styles/src/controls.ts", "packages/styles/src/file-upload.ts", "packages/styles/src/internal/button-rules.ts", "packages/styles/src/internal/control-shared.ts", "packages/styles/src/token-editor.ts"],
  "--en-control-min-size": ["packages/elements/src/data-table/element.ts", "packages/styles/src/internal/button-rules.ts", "packages/styles/src/internal/control-size.ts", "packages/styles/src/internal/target-size.ts", "packages/styles/src/pagination.ts"],
  "--en-control-radius": ["packages/styles/src/color-picker.ts", "packages/styles/src/color-slider.ts", "packages/styles/src/file-upload.ts", "packages/styles/src/internal/button-rules.ts", "packages/styles/src/internal/control-shared.ts", "packages/styles/src/internal/field-presentation.ts", "packages/styles/src/internal/focus.ts", "packages/styles/src/selection.ts"],
  "--en-data-table-min-inline-size": ["packages/elements/src/data-table/element.ts"],
  "--en-data-table-selection-width": ["packages/elements/src/data-table/element.ts"],
  "--en-data-table-viewport-size": ["packages/elements/src/data-table/element.ts"],
  "--en-dialog-enter-duration": ["packages/styles/src/internal/surface-motion.ts"],
  "--en-dialog-enter-ease": ["packages/styles/src/internal/surface-motion.ts"],
  "--en-dialog-exit-duration": ["packages/styles/src/internal/surface-motion.ts"],
  "--en-dialog-exit-ease": ["packages/styles/src/internal/surface-motion.ts"],
  "--en-divider-color": ["packages/styles/src/css/surface.css"],
  "--en-editor-max-size": ["packages/styles/src/token-editor.ts"],
  "--en-editor-token-background": ["packages/styles/src/token-editor.ts"],
  "--en-editor-token-block-padding": ["packages/styles/src/token-editor.ts"],
  "--en-editor-token-border-color": ["packages/styles/src/token-editor.ts"],
  "--en-editor-token-color": ["packages/styles/src/token-editor.ts"],
  "--en-editor-token-gap": ["packages/styles/src/token-editor.ts"],
  "--en-editor-token-hover-background": ["packages/styles/src/token-editor.ts"],
  "--en-editor-token-inline-padding": ["packages/styles/src/token-editor.ts"],
  "--en-editor-token-min-size": ["packages/styles/src/token-editor.ts"],
  "--en-editor-token-pressed-background": ["packages/styles/src/token-editor.ts", "packages/styles/src/internal/press-recipes.ts"],
  "--en-editor-token-radius": ["packages/styles/src/token-editor.ts"],
  "--en-editor-toolbar-background": ["packages/elements/src/editor-toolbar.ts"],
  "--en-editor-toolbar-gap": ["packages/elements/src/editor-toolbar.ts"],
  "--en-field-gap": ["packages/styles/src/color-picker.ts", "packages/styles/src/controls.ts", "packages/styles/src/token-editor.ts"],
  "--en-file-list-gap": ["packages/styles/src/content.ts"],
  "--en-file-list-media-size": ["packages/styles/src/content.ts"],
  "--en-file-list-metadata-gap": ["packages/styles/src/content.ts"],
  "--en-file-list-padding": ["packages/styles/src/content.ts"],
  "--en-grid-gap": ["packages/styles/src/content.ts", "packages/styles/src/surfaces.ts"],
  "--en-grid-item-min": ["packages/styles/src/content.ts", "packages/styles/src/surfaces.ts"],
  "--en-icon-size": ["packages/styles/src/feedback.ts", "packages/styles/src/internal/button-rules.ts", "packages/styles/src/pagination.ts"],
  "--en-input-background": ["packages/styles/src/controls.ts", "packages/styles/src/file-upload.ts", "packages/styles/src/token-editor.ts"],
  "--en-input-border-color": ["packages/styles/src/controls.ts", "packages/styles/src/internal/field-presentation.ts"],
  "--en-input-border-width": ["packages/styles/src/internal/field-presentation.ts"],
  "--en-input-color": ["packages/styles/src/controls.ts", "packages/styles/src/file-upload.ts", "packages/styles/src/token-editor.ts"],
  "--en-input-focus-accent-color": ["packages/styles/src/internal/focus.ts"],
  "--en-input-focus-accent-width": ["packages/styles/src/internal/focus.ts"],
  "--en-input-focus-color": ["packages/styles/src/internal/focus-core.ts"],
  "--en-input-focus-halo-color": ["packages/styles/src/internal/focus-core.ts"],
  "--en-input-focus-halo-width": ["packages/styles/src/internal/focus-core.ts"],
  "--en-input-focus-offset": ["packages/styles/src/internal/focus-core.ts"],
  "--en-input-focus-width": ["packages/styles/src/internal/focus-core.ts"],
  "--en-input-hover-border-color": ["packages/styles/src/internal/field-presentation.ts"],
  "--en-input-inline-padding": ["packages/styles/src/combobox.ts", "packages/styles/src/controls.ts", "packages/styles/src/file-upload.ts", "packages/styles/src/token-editor.ts"],
  "--en-input-invalid-border-color": ["packages/styles/src/controls.ts", "packages/styles/src/internal/field-presentation.ts"],
  "--en-input-invalid-border-width": ["packages/styles/src/internal/field-presentation.ts"],
  "--en-input-radius": ["packages/styles/src/internal/field-presentation.ts"],
  "--en-inset-child-radius": ["packages/styles/src/css/surface.css"],
  "--en-inset-distance": ["packages/styles/src/css/surface.css"],
  "--en-inset-outer-radius": ["packages/styles/src/css/surface.css"],
  "--en-media-aspect-ratio": ["packages/styles/src/feedback.ts"],
  "--en-media-radius": ["packages/styles/src/content.ts", "packages/styles/src/feedback.ts"],
  "--en-navigation-active-background": ["packages/styles/src/navigation.ts"],
  "--en-navigation-active-color": ["packages/styles/src/navigation.ts"],
  "--en-navigation-background": ["packages/styles/src/navigation.ts"],
  "--en-navigation-border-color": ["packages/styles/src/navigation.ts"],
  "--en-navigation-color": ["packages/styles/src/navigation.ts"],
  "--en-navigation-current-background": ["packages/styles/src/navigation.ts"],
  "--en-navigation-current-color": ["packages/styles/src/navigation.ts"],
  "--en-navigation-current-indicator-color": ["packages/styles/src/navigation.ts"],
  "--en-navigation-current-indicator-width": ["packages/styles/src/navigation.ts"],
  "--en-navigation-gap": ["packages/styles/src/navigation.ts"],
  "--en-navigation-height": ["packages/styles/src/navigation.ts"],
  "--en-navigation-hover-background": ["packages/styles/src/navigation.ts"],
  "--en-navigation-hover-color": ["packages/styles/src/navigation.ts"],
  "--en-navigation-indent": ["packages/styles/src/navigation.ts"],
  "--en-navigation-link-radius": ["packages/styles/src/navigation.ts"],
  "--en-navigation-offset": ["packages/styles/src/navigation.ts"],
  "--en-navigation-position": ["packages/styles/src/navigation.ts"],
  "--en-navigation-pressed-background": ["packages/styles/src/navigation.ts", "packages/styles/src/internal/press-recipes.ts"],
  "--en-navigation-z-index": ["packages/styles/src/navigation.ts"],
  "--en-option-active-background": ["packages/styles/src/internal/option-paint.ts", "packages/styles/src/selection.ts"],
  "--en-option-active-color": ["packages/styles/src/internal/option-paint.ts"],
  "--en-option-background": ["packages/styles/src/calendar.ts", "packages/styles/src/internal/option-paint.ts", "packages/styles/src/selection.ts"],
  "--en-option-block-padding": ["packages/styles/src/combobox.ts", "packages/styles/src/commands.ts", "packages/styles/src/controls.ts", "packages/styles/src/token-editor.ts", "packages/styles/src/tree.ts"],
  "--en-option-color": ["packages/styles/src/calendar.ts", "packages/styles/src/internal/option-paint.ts", "packages/styles/src/selection.ts"],
  "--en-option-disabled-background": ["packages/styles/src/internal/option-paint.ts"],
  "--en-option-disabled-color": ["packages/styles/src/internal/option-paint.ts"],
  "--en-option-focus-color": ["packages/styles/src/internal/focus-core.ts"],
  "--en-option-focus-halo-color": ["packages/styles/src/internal/focus-core.ts"],
  "--en-option-focus-halo-width": ["packages/styles/src/internal/focus-core.ts"],
  "--en-option-focus-offset": ["packages/styles/src/internal/focus-core.ts"],
  "--en-option-focus-width": ["packages/styles/src/internal/focus-core.ts"],
  "--en-option-font-weight": ["packages/styles/src/internal/option-paint.ts"],
  "--en-option-hover-background": ["packages/styles/src/calendar.ts", "packages/styles/src/internal/option-paint.ts"],
  "--en-option-hover-color": ["packages/styles/src/calendar.ts", "packages/styles/src/internal/option-paint.ts"],
  "--en-option-inline-padding": ["packages/styles/src/combobox.ts", "packages/styles/src/commands.ts", "packages/styles/src/controls.ts", "packages/styles/src/token-editor.ts", "packages/styles/src/tree.ts"],
  "--en-option-list-background": ["packages/styles/src/combobox.ts", "packages/styles/src/commands.ts", "packages/styles/src/controls.ts", "packages/styles/src/token-editor.ts"],
  "--en-option-list-border-color": ["packages/styles/src/combobox.ts", "packages/styles/src/commands.ts", "packages/styles/src/controls.ts", "packages/styles/src/token-editor.ts"],
  "--en-option-list-color": ["packages/styles/src/combobox.ts", "packages/styles/src/commands.ts", "packages/styles/src/controls.ts", "packages/styles/src/token-editor.ts"],
  "--en-option-list-gap": ["packages/styles/src/combobox.ts", "packages/styles/src/commands.ts", "packages/styles/src/controls.ts", "packages/styles/src/token-editor.ts", "packages/styles/src/tree.ts"],
  "--en-option-list-max-block-size": ["packages/styles/src/combobox.ts", "packages/styles/src/commands.ts", "packages/styles/src/controls.ts", "packages/styles/src/token-editor.ts"],
  "--en-option-list-padding": ["packages/styles/src/combobox.ts", "packages/styles/src/commands.ts", "packages/styles/src/controls.ts", "packages/styles/src/token-editor.ts"],
  "--en-option-list-radius": ["packages/styles/src/combobox.ts", "packages/styles/src/commands.ts", "packages/styles/src/controls.ts", "packages/styles/src/token-editor.ts"],
  "--en-option-list-shadow": ["packages/styles/src/combobox.ts", "packages/styles/src/commands.ts", "packages/styles/src/controls.ts", "packages/styles/src/token-editor.ts"],
  "--en-option-pressed-background": ["packages/styles/src/internal/option-paint.ts"],
  "--en-option-pressed-color": ["packages/styles/src/internal/option-paint.ts"],
  "--en-option-radius": ["packages/styles/src/calendar.ts", "packages/styles/src/combobox.ts", "packages/styles/src/commands.ts", "packages/styles/src/controls.ts", "packages/styles/src/selection.ts", "packages/styles/src/token-editor.ts", "packages/styles/src/tree.ts"],
  "--en-option-rest-background": ["packages/styles/src/calendar.ts", "packages/styles/src/internal/option-paint.ts"],
  "--en-option-rest-color": ["packages/styles/src/calendar.ts", "packages/styles/src/internal/option-paint.ts"],
  "--en-option-selected-background": ["packages/styles/src/calendar.ts", "packages/styles/src/internal/option-paint.ts"],
  "--en-option-selected-color": ["packages/styles/src/calendar.ts", "packages/styles/src/internal/option-paint.ts"],
  "--en-option-selected-font-weight": ["packages/styles/src/internal/option-paint.ts"],
  "--en-overlay-background": ["packages/styles/src/combobox.ts", "packages/styles/src/commands.ts", "packages/styles/src/controls.ts", "packages/styles/src/overlays.ts", "packages/styles/src/token-editor.ts"],
  "--en-overlay-border-color": ["packages/styles/src/combobox.ts", "packages/styles/src/commands.ts", "packages/styles/src/controls.ts", "packages/styles/src/overlays.ts", "packages/styles/src/token-editor.ts"],
  "--en-overlay-color": ["packages/styles/src/combobox.ts", "packages/styles/src/commands.ts", "packages/styles/src/controls.ts", "packages/styles/src/overlays.ts", "packages/styles/src/token-editor.ts"],
  "--en-overlay-focus-color": ["packages/styles/src/internal/focus-core.ts"],
  "--en-overlay-focus-halo-color": ["packages/styles/src/internal/focus-core.ts"],
  "--en-overlay-focus-halo-width": ["packages/styles/src/internal/focus-core.ts"],
  "--en-overlay-focus-offset": ["packages/styles/src/internal/focus-core.ts"],
  "--en-overlay-focus-width": ["packages/styles/src/internal/focus-core.ts"],
  "--en-overlay-max-block-size": ["packages/styles/src/combobox.ts", "packages/styles/src/commands.ts", "packages/styles/src/controls.ts", "packages/styles/src/overlays.ts"],
  "--en-overlay-max-inline-size": ["packages/styles/src/commands.ts", "packages/styles/src/overlays.ts"],
  "--en-overlay-padding": ["packages/styles/src/combobox.ts", "packages/styles/src/commands.ts", "packages/styles/src/controls.ts", "packages/styles/src/overlays.ts", "packages/styles/src/token-editor.ts"],
  "--en-overlay-radius": ["packages/styles/src/combobox.ts", "packages/styles/src/commands.ts", "packages/styles/src/controls.ts", "packages/styles/src/overlays.ts", "packages/styles/src/token-editor.ts"],
  "--en-pagination-align": ["packages/styles/src/pagination.ts"],
  "--en-pagination-gap": ["packages/styles/src/pagination.ts"],
  "--en-pagination-page-min-inline-size": ["packages/styles/src/pagination.ts"],
  "--en-pagination-status-gap": ["packages/styles/src/pagination.ts"],
  "--en-popup-enter-duration": ["packages/styles/src/internal/surface-motion.ts"],
  "--en-popup-enter-ease": ["packages/styles/src/internal/surface-motion.ts"],
  "--en-popup-exit-duration": ["packages/styles/src/internal/surface-motion.ts"],
  "--en-popup-exit-ease": ["packages/styles/src/internal/surface-motion.ts"],
  "--en-presence-background": ["packages/styles/src/collaboration.ts"],
  "--en-presence-border-color": ["packages/styles/src/collaboration.ts"],
  "--en-presence-busy-color": ["packages/styles/src/collaboration.ts"],
  "--en-presence-gap": ["packages/styles/src/collaboration.ts"],
  "--en-presence-group-gap": ["packages/styles/src/collaboration.ts"],
  "--en-presence-hover-background": ["packages/styles/src/collaboration.ts"],
  "--en-presence-hover-border-color": ["packages/styles/src/collaboration.ts"],
  "--en-presence-online-color": ["packages/styles/src/collaboration.ts"],
  "--en-presence-padding": ["packages/styles/src/collaboration.ts"],
  "--en-presence-radius": ["packages/styles/src/collaboration.ts"],
  "--en-progress-color": ["packages/styles/src/feedback.ts"],
  "--en-progress-size": ["packages/styles/src/feedback.ts"],
  "--en-progress-steps-gap": ["packages/styles/src/form-navigation.ts"],
  "--en-progress-track-color": ["packages/styles/src/feedback.ts"],
  "--en-progress-value": ["packages/styles/src/feedback.ts"],
  "--en-prose-max-inline-size": ["packages/styles/src/css/typography.css"],
  "--en-radio-selected-color": ["packages/styles/src/internal/radio-rules.ts"],
  "--en-rating-star-radius": ["packages/styles/src/selection.ts"],
  "--en-segmented-control-frame-inset": ["packages/styles/src/internal/control-size.ts"],
  "--en-select-appearance": ["packages/styles/src/controls.ts"],
  "--en-skeleton-color": ["packages/styles/src/activity.ts"],
  "--en-skeleton-size": ["packages/styles/src/activity.ts"],
  "--en-slider-length": ["packages/styles/src/controls.ts"],
  "--en-split-ratio": ["packages/styles/src/surfaces.ts"],
  "--en-stack-gap": ["packages/styles/src/surfaces.ts"],
  "--en-surface-background": ["packages/styles/src/css/surface.css"],
  "--en-surface-border-color": ["packages/styles/src/css/surface.css"],
  "--en-surface-color": ["packages/styles/src/css/surface.css"],
  "--en-surface-padding": ["packages/styles/src/content.ts", "packages/styles/src/css/surface.css"],
  "--en-surface-radius": ["packages/styles/src/content.ts", "packages/styles/src/css/surface.css"],
  "--en-surface-shadow": ["packages/styles/src/css/surface.css"],
  "--en-swatch-size": ["packages/styles/src/feedback.ts"],
  "--en-switch-block-size": ["packages/styles/src/controls.ts"],
  "--en-switch-inline-size": ["packages/styles/src/controls.ts"],
  "--en-switch-thumb-size": ["packages/styles/src/controls.ts"],
  "--en-tab-background": ["packages/styles/src/selection.ts"],
  "--en-tab-color": ["packages/styles/src/selection.ts"],
  "--en-tab-hover-background": ["packages/styles/src/selection.ts"],
  "--en-tab-hover-color": ["packages/styles/src/selection.ts"],
  "--en-tab-indicator-color": ["packages/styles/src/selection.ts"],
  "--en-tab-pressed-background": ["packages/styles/src/selection.ts", "packages/styles/src/internal/press-recipes.ts"],
  "--en-tab-selected-background": ["packages/styles/src/selection.ts"],
  "--en-tab-selected-color": ["packages/styles/src/selection.ts"],
  "--en-table-background": ["packages/styles/src/table.ts"],
  "--en-table-border-color": ["packages/styles/src/table.ts"],
  "--en-table-cell-block-padding": ["packages/styles/src/table.ts"],
  "--en-table-cell-inline-padding": ["packages/styles/src/table.ts"],
  "--en-table-color": ["packages/styles/src/table.ts"],
  "--en-table-footer-background": ["packages/styles/src/table.ts"],
  "--en-table-footer-color": ["packages/styles/src/table.ts"],
  "--en-table-header-background": ["packages/styles/src/table.ts"],
  "--en-table-header-color": ["packages/styles/src/table.ts"],
  "--en-table-radius": ["packages/styles/src/table.ts"],
  "--en-table-row-hover-background": ["packages/styles/src/table.ts"],
  "--en-table-row-selected-background": ["packages/styles/src/table.ts"],
  "--en-table-row-selected-color": ["packages/styles/src/table.ts"],
  "--en-table-row-selected-indicator-color": ["packages/styles/src/table.ts"],
  "--en-toast-background": ["packages/styles/src/toast.ts"],
  "--en-toast-border-color": ["packages/styles/src/toast.ts"],
  "--en-toast-color": ["packages/styles/src/toast.ts"],
  "--en-toast-danger-background": ["packages/styles/src/toast.ts"],
  "--en-toast-danger-border-color": ["packages/styles/src/toast.ts"],
  "--en-toast-danger-color": ["packages/styles/src/toast.ts"],
  "--en-toast-danger-icon-color": ["packages/styles/src/toast.ts"],
  "--en-toast-enter-duration": ["packages/styles/src/toast.ts"],
  "--en-toast-enter-ease": ["packages/styles/src/toast.ts"],
  "--en-toast-exit-duration": ["packages/styles/src/toast.ts"],
  "--en-toast-exit-ease": ["packages/styles/src/toast.ts"],
  "--en-toast-icon-color": ["packages/styles/src/toast.ts"],
  "--en-toast-info-background": ["packages/styles/src/toast.ts"],
  "--en-toast-info-border-color": ["packages/styles/src/toast.ts"],
  "--en-toast-info-color": ["packages/styles/src/toast.ts"],
  "--en-toast-info-icon-color": ["packages/styles/src/toast.ts"],
  "--en-toast-padding": ["packages/styles/src/toast.ts"],
  "--en-toast-radius": ["packages/styles/src/toast.ts"],
  "--en-toast-region-gap": ["packages/styles/src/toast.ts"],
  "--en-toast-region-layer": ["packages/styles/src/toast.ts"],
  "--en-toast-region-max-size": ["packages/styles/src/toast.ts"],
  "--en-toast-region-width": ["packages/styles/src/toast.ts"],
  "--en-toast-shadow": ["packages/styles/src/toast.ts"],
  "--en-toast-stack-offset": ["packages/styles/src/toast.ts"],
  "--en-toast-success-background": ["packages/styles/src/toast.ts"],
  "--en-toast-success-border-color": ["packages/styles/src/toast.ts"],
  "--en-toast-success-color": ["packages/styles/src/toast.ts"],
  "--en-toast-success-icon-color": ["packages/styles/src/toast.ts"],
  "--en-toast-warning-background": ["packages/styles/src/toast.ts"],
  "--en-toast-warning-border-color": ["packages/styles/src/toast.ts"],
  "--en-toast-warning-color": ["packages/styles/src/toast.ts"],
  "--en-toast-warning-icon-color": ["packages/styles/src/toast.ts"],
  "--en-tree-viewport-size": ["packages/styles/src/tree.ts"],
  "--en-validation-summary-padding": ["packages/styles/src/form-navigation.ts"],
  "--en-validation-summary-radius": ["packages/styles/src/form-navigation.ts"],
};
