import { html } from 'lit';

/** Calendar and editable picker share a date-only selection contract. */
export function calendarReference(href: (path: string) => string) {
	return html`
		<section class="api-section" id="api-calendar-guide" tabindex="-1" aria-labelledby="api-calendar-guide-title">
			<h3 id="api-calendar-guide-title">Dates, calendar navigation and forms</h3>
			<p><a href=${href('/api-examples/calendar')}>Review the calendar and date picker</a> with locale, first-weekday, application veto, form submission and inspired-theme controls. The maintained source appears below the isolated demo.</p>
			<h4>Choose the appropriate date surface</h4>
			<p><code>en-calendar</code> displays an inline date grid. <code>en-date-picker</code> pairs editable date input with a calendar dialog, retaining the input’s form, validation, label and description APIs. <code>en-date-input</code> remains available when the native date-input experience is sufficient. Single-date and range selection support Gregorian and modern Buddhist presentation. <code>en-time-field</code> supplies separate localized wall-time entry.</p>
			<pre dir="ltr"><code>import { html } from 'lit';
import '@en-reve/elements/define/date-picker.js';

export function reviewDate() {
	return html\`
		&lt;en-date-picker name="review-date" value="2026-09-18"
			min="2026-09-14" max="2026-10-30" today="2026-09-14" required&gt;
			&lt;span slot="label"&gt;Review date&lt;/span&gt;
			&lt;span slot="description"&gt;Choose a date during the review period.&lt;/span&gt;
		&lt;/en-date-picker&gt;
	\`;
}</code></pre>
            <h4>Inclusive date ranges</h4>
            <p>Set <code>selection="range"</code> on either control and assign <code>rangeValue = { start, end }</code>. Both strings use ISO dates; empty strings represent missing endpoints. The immutable pair is separate from the existing single-date <code>value</code>. Earlier endpoints normalize chronologically; same-day ranges are valid. Property assignments are silent authoritative writes.</p>
            <p>The first grid activation starts a draft, and the second completes it. The inline calendar commits the pair atomically; the picker waits for <strong>Apply range</strong>. Focus and pointer preview never change submission data. An incomplete draft cannot Apply. Cancel, closing the dialog or Escape discards the draft; Escape within the grid restores the last committed pair while leaving the dialog open. The picker includes <strong>Clear range</strong> and exposes <code>clearRange()</code>, both using the cancelable transaction. Required fields may be cleared but are then invalid.</p>
            <p><code>en-change</code> carries immutable <code>previous</code> and <code>proposed</code> pairs in range mode. Its <code>reason</code> is <code>range</code> or <code>clear</code>. During dispatch, tentative pair and FormData are available. A veto restores both endpoints; an explicit property write by the application takes precedence over rollback. Native draft fields remain Gregorian even in Buddhist presentation. The accepted summary and grid display the chosen calendar and era.</p>
            <pre dir="ltr"><code>picker.selection = 'range';
picker.rangeValue = { start: '2026-09-16', end: '2026-09-18' };
picker.startName = 'project-start';
picker.endName = 'project-end';
picker.unavailableDate = iso =&gt; unavailableDates.has(iso);
// After changing captured availability data:
picker.invalidateAvailability();</code></pre>
            <p>Use explicit <code>start-name</code> and <code>end-name</code> to submit two ISO entries. A missing endpoint name omits only that entry; the single-date <code>name</code> does not invent range naming conventions. Empty, partial or invalid ranges submit no pair. <code>required</code> means both valid endpoints. Reset restores the initial pair, and browser form-state restoration stores the pair separately from its two-entry FormData. Disabled fields submit nothing; readonly fields preserve submission and prevent editing.</p>
            <p>Inclusive bounds, day step and synchronous <code>unavailableDate(iso)</code> apply to every date in the interval, including interiors. Invalid intervals explain the rejection rather than skipping dates. Availability results are cached between proposals; replace the predicate or call <code>invalidateAvailability()</code> when captured state changes. Predicate-based intervals are limited to 36,600 days to bound synchronous work, with an explicit rejection above that size. Without a predicate the full supported calendar interval remains available. Async availability belongs to the application.</p>
            <p>One month remains visible on narrow screens, with one grid Tab stop. Range CSS Parts are <code>range-start</code>, <code>range-end</code>, <code>in-range</code>, <code>preview</code> and <code>range-status</code>; picker forwarding prefixes the first four with <code>calendar-</code>. The picker also exposes <code>range-summary</code>, <code>range-fields</code>, <code>range-actions</code> and <code>range-error</code>. Fill overrides are <code>--en-calendar-range-background</code>, <code>--en-calendar-range-endpoint-background</code> and <code>--en-calendar-range-preview-background</code>; endpoint borders and preview strokes retain meaning in forced colors. The interval fill is a continuous cell-level band behind individual buttons, wrapping across week rows; only the actual start/end dates have rounded caps. The same background covers the entire selected interval, including both endpoints; endpoint outlines distinguish its boundaries. Endpoint buttons are transparent by default, so translucent range fills are painted only once. Preview uses a lighter band. Parts <code>range-band</code>, <code>range-band-start</code>, <code>range-band-end</code> and <code>range-band-preview</code> expose the decoration (forwarded with <code>calendar-</code> prefixes by the picker). Individual date focus remains separate. The standalone calendar’s <code>draftRange</code>, <code>setRangeDraft()</code>, <code>cancelRange()</code> and <code>deferRangeCommit</code> support composition; applications normally use the picker for explicit confirmation.</p>
			<h4>Local time entry and composition</h4>
            <p><code>en-time-field</code> uses the shared field styling, label/description slots, sizes and form association. Pair it with a single date picker or two separately named times beside a range picker. <code>value</code>, <code>min</code> and <code>max</code> are local ASCII times: HH:mm, optionally HH:mm:ss with <code>precision="second"</code>. The default is minute precision and a 60-second <code>step</code>; minute precision requires a whole-minute step. Offsets, Z, fractions, 24:00 and leap seconds are rejected. Values are never converted into instants.</p>
            <p><code>locale</code> defaults to en-US for deterministic server rendering. <code>hour-cycle="auto|12|24"</code> controls localized display; auto follows the locale, with midnight shown as 00:00 or 12 AM. Localized digits and day-period labels round-trip, and canonical 24-hour text is accepted too. Unsupported locale/format configuration is visible and invalid. Application labels and built-in error translations remain consumer-owned; use label/description slots, <code>format-label</code>, <code>invalid-label</code>, <code>configuration-label</code> and <code>error</code>.</p>
            <p>Typing emits <code>en-input</code> with a raw localized draft. Enter, blur or <code>commit()</code> accepts valid text through cancelable <code>en-change</code>; previous/proposed are canonical strings. Veto restores accepted display and submission data, while explicit author writes win. Invalid text stays visible, blocks submission and is not rounded. Escape or <code>cancelEdit()</code> restores the accepted time. Uncommitted drafts are omitted from FormData; call commit before requesting programmatic submission during editing. Configuration changes preserve accepted values; a pending draft is parsed using its original display format.</p>
            <p>Arrow Up/Down adjusts the segment at the caret: hours, minutes, seconds, or AM/PM. Numeric changes use the smallest whole segment increment compatible with step and retain smaller units; AM/PM toggles by 12 hours if allowed. The changed segment stays selected. Separators target the preceding segment, and selections use their start offset. Carry across units is supported, but crossing midnight requires wrap. <code>stepUp()</code>/<code>stepDown()</code> still moves the whole value by one configured step, anchored to min or midnight. Bounds are inclusive. Use <code>wrap</code> explicitly with min greater than max for overnight availability, such as 22:00–02:00. This does not advance a date. Invalid author values are inspectable but cannot submit. Required, disabled, readonly, fieldset disabling, reset and browser restoration follow the shared field contract.</p>
            <pre dir="ltr"><code>&lt;en-date-picker name="date" label="Date" value="2026-09-18"&gt;&lt;/en-date-picker&gt;
&lt;en-time-field name="time" label="Time" value="09:30"
  locale="en-US" hour-cycle="12" min="09:00" max="17:00" step="900"&gt;
&lt;/en-time-field&gt;</code></pre>
            <p>Keep date and time fields separate in FormData. Applications own date-time ordering, timezone selection and daylight-saving ambiguity. CSS Parts include field, label, control, focus-frame, description, error and format-hint. <a href=${href('/api-examples/calendar#time-entry-example')}>Review appointment and date-range compositions</a>, seconds, overnight bounds and application veto.</p>
            <h4>Date-only values and server rendering</h4>
			<p><code>value</code>, <code>min</code>, <code>max</code> and <code>today</code> use ISO calendar dates (<code>YYYY-MM-DD</code>). They are not instants or timezone-bearing timestamps. Keep them as date-only strings in application storage and form submissions. Supply <code>today</code> from the application, identically on the server and client, to avoid an initial date changing across timezones or hydration. The inline calendar’s <code>month</code> sets the displayed month independently of selection.</p>
			<h4>Locale and direction</h4>
			<p><code>locale</code> controls calendar date and month formatting. <code>first-day-of-week</code> sets the first column explicitly, from 0 (Sunday) through 6 (Saturday); its default is Sunday. A locale change does not change the selected ISO date or implicitly change reading direction. Supply <code>dir</code> at the surrounding application boundary and translate application labels, descriptions and action labels as appropriate. Native text-entry presentation can differ between browsers.</p>
			<h4>Calendar systems and native editing</h4>
			<p><code>calendar="gregory"</code> is the default (ISO years 0001–9999). <code>calendar="buddhist"</code> displays modern Buddhist dates with BE year = ISO year + 543 and supports ISO 1941-01-01–9999-12-31. Months and leap days follow Gregorian arithmetic within this declared interval; historical civil reforms are not reconstructed. Calendar fields and inverse conversion live behind a private adapter, not an application plugin API. Hebrew, Islamic, Persian, Japanese and other calendar IDs are explicitly unsupported.</p>
			<p>All date values and constraints remain Gregorian ISO strings. Changing <code>calendar</code> or <code>locale</code> changes presentation without mutating selection. The grid visibly identifies the calendar and era, and the picker shows the formatted accepted date. Its native input remains a Gregorian editing route, with an explicit explanation; browsers choose its visual date order. It is not an alternate-year input.</p>
			<p>Unsupported IDs, missing Intl calendar data, invalid locale configuration or a selected or displayed date outside the calendar’s supported interval replace the grid with an explanation. There is no silent Gregorian substitution. The native field remains available to correct a date. Constraints outside the supported interval do not extend it; dates before 1941 are absent in Buddhist boundary grids. A reversed min/max interval remains empty.</p>
			<p>Use identical locale, calendar, today and Intl calendar capability on the server and client. The component checks <code>Intl.DateTimeFormat().resolvedOptions().calendar</code> in each environment; applications must align their Intl data/polyfills before hydration. <code>calendar-label</code>, <code>unsupported-label</code> and the picker’s <code>edit-label</code> provide translated application text. CSS Parts <code>calendar-label</code>, <code>configuration</code>, <code>calendar-summary</code> and <code>edit-hint</code> style this supporting content.</p>
			<h4>One cancelable selection event</h4>
			<p>Listen for <code>en-change</code>. The element exposes the tentative <code>value</code> during synchronous dispatch. Calling <code>preventDefault()</code> declines the selection and restores accepted state; explicit application property writes take precedence. There is no <code>controlled</code> attribute or separate request event. Read the accepted value after dispatch completes before updating a receipt or other dependent application surface. Moving keyboard focus or browsing months does not select a date.</p>
			<p>The standalone calendar also emits <code>en-action</code> with <code>action: 'confirm'</code> and the ISO date in <code>data</code> after an accepted activation, including activation of the already-selected date. This non-cancelable notification reports accepted single-date activation. In range composition it also emits <code>action: 'range-draft'</code> with the draft <code>DateRange</code> in <code>data</code>. The picker encapsulates its internal calendar and dialog events; consumers receive the field’s single cancelable <code>en-change</code> for date edits.</p>
			<h4>Keyboard and popup interaction</h4>
			<p>The calendar grid uses one Tab stop. Arrow keys move by day or week; Home and End move to week edges. Page Up and Page Down change months; adding Shift changes years. Enter or Space selects an available date. The picker’s calendar button opens a modal dialog, and Escape or its close action dismisses it with focus return. <code>showPicker()</code> and <code>hidePicker()</code> are available for application-owned orchestration.</p>
			<h4>Constraints and appearance</h4>
			<p>Date targets are square, with centered tabular numerals. <code>--en-calendar-day-size</code> sets their preferred size within the available column width, and <code>--en-calendar-day-radius</code> accepts circular (50%), rounded or square (0) shapes. Table-cell alignment places the first and last date columns at the month-action edges in either reading direction. Available dates use shared option rest/hover fills with a built-in tint above the fill: <code>--en-calendar-hover-opacity</code> defaults to 0.10 and <code>--en-calendar-pressed-opacity</code> to 0.16. This separates interaction feedback from the surrounding surface color. Set the tint strengths to zero only when supplying distinct rest/hover fills; selected and today indicators remain visible. The single-date picker has one close icon, labeled by <code>close-label</code>, without a duplicate footer button.</p>
			<p>The picker retains native form validation and reset through its editable date field. <code>required</code>, <code>min</code> and <code>max</code> apply to the submitted value. Disabled or read-only delivery prevents user editing. The calendar marks unavailable dates; consumers should not communicate availability through color alone. Use the generated CSS Parts and custom-property tables to style month navigation, date targets, selected/today/unavailable states and focus. Medium is the default size without an attribute.</p>
			<p>Review keyboard focus, constrained dates, RTL, mobile dialog behavior and screen-reader month announcements independently. Automated browser checks supplement device and assistive-technology review.</p>
		<p>Range actions expose <code>apply-label</code>, <code>cancel-label</code> and <code>clear-label</code> (properties <code>applyLabel</code>, <code>cancelLabel</code> and <code>clearLabel</code>). Removing a label attribute restores its default; an empty string remains intentional.</p>
  </section>
	`;
}
