import { html } from 'lit';
export function carouselReference(href: (path: string) => string) {
    return html `<section class="api-section" id="api-carousel-guide" tabindex="-1"><h3>Authored slides and native scrolling</h3>
<p>Review the <a href=${href('/api-examples/carousel')}>media and responsive card examples, with complete source</a>. The carousel owns navigation and position; applications own slide content. Direct en-carousel-slide children remain mounted and are never cloned.</p>
<pre><code>${`<en-carousel label="Project studies" slides-per-view="1">
  <en-carousel-slide label="Cover study">
    <img src="/cover.webp" alt="Blue mountain silhouettes">
    <a href="/projects/cover">Explore the cover study</a>
  </en-carousel-slide>
  <en-carousel-slide label="Color study">…</en-carousel-slide>
</en-carousel>`}</code></pre>
<h4>Opt-in navigation interfaces</h4>
<p>Both <code>controls</code> and <code>navigation</code> default to <code>none</code>. Without those attributes, no navigation row or picker is rendered. Native scrolling, swiping, viewport keyboard navigation and the public methods remain available. The scrollbar stays available when neither interface is displayed.</p>
<ul><li><code>controls="auto"</code>: show Previous, position and Next only when there is more than one valid window (or page in list mode).</li><li><code>controls="always"</code>: retain that row for single-window and empty collections, with unavailable actions disabled.</li><li><code>controls="none"</code>: omit the row; use a picker, native scrolling or application-owned controls.</li><li><code>navigation="positions|thumbnails"</code>: independently enable a picker. <code>navigation="none"</code> omits the picker, its caption and tooltips. Pickers are absent in list mode.</li><li><code>boundary-controls</code>: add First/Last to the same controls row. It defaults off and never enables the row itself.</li></ul>
<pre><code>${`<en-carousel>…</en-carousel>
<en-carousel controls="auto">…</en-carousel>
<en-carousel navigation="thumbnails">…</en-carousel>
<en-carousel controls="auto" boundary-controls navigation="thumbnails">…</en-carousel>`}</code></pre>
<p>Changing these options does not change selection. If a focused control is removed, focus returns to the viewport. Autoplay is a separate opt-in and retains its required pause/start control. In list mode, opt into controls or supply application-owned paging; viewport arrow keys and methods still advance pages. To preserve the earlier always-visible row, add <code>controls="always"</code> to existing carousels.</p>
<h4>Navigation and state</h4><p><code>index</code> is the zero-based leading slide, clamped to the last full visible window. <code>goTo(index)</code>, <code>next()</code> and <code>previous()</code> navigate without moving focus. These methods and control, keyboard or settled scroll changes emit cancelable <code>en-change</code> with previous/proposed indices and reason api, next, previous, keyboard, scroll autoplay or picker. Preventing a change restores the prior position; a synchronous author index assignment wins. Property writes are silent. <code>loop</code> wraps controls and methods; touch scrolling has finite edges.</p>
<pre><code>${`carousel.addEventListener('en-change', event => {
  if (hasUnsavedChanges) event.preventDefault();
});
carousel.goTo(2); // Cancellable navigation request.
carousel.index = 0; // Authoritative, silent assignment.`}</code></pre>
<p>Children may be inserted, removed, reordered or hidden over time. Existing nodes and the leading slide are retained when possible. Removing a focused slide returns focus to the viewport. Wrappers and forwarded slots are not flattened: author slides as direct children. Slot content can contain links, fields and controls; the carousel handles arrows only when its viewport itself has focus.</p>
<h4>Optional position and thumbnail pickers</h4>
<p><code>navigation="positions"</code> adds numbered window buttons. <code>navigation="thumbnails"</code> uses each leading slide’s optional <code>thumbnail</code> URL, falling back to the position when absent. The default is <code>none</code>. Previews are decorative images; the slide label and window position name each button. Supply small preview assets separately; authored media and interactive content are never cloned.</p>
<pre><code>${`<en-carousel label="Cover studies" navigation="thumbnails"
  picker-label="Choose a cover" pick-label="Show {position}: {label}">
  <en-carousel-slide label="Nightfall" thumbnail="/nightfall-preview.webp">
    <img src="/nightfall.webp" alt="Mountains beneath the moon">
  </en-carousel-slide>
  <en-carousel-slide label="Terracotta" thumbnail="/terracotta-preview.webp">…</en-carousel-slide>
</en-carousel>`}</code></pre>
<p>The picker contains one button per valid leading window: with five slides and three visible, it offers 1–3, 2–4 and 3–5. This preserves the existing index contract. The current button has <code>aria-current="true"</code>; keyboard focus is distinct. Tab enters the picker once. Left/Right (reversed in RTL), Home and End move focus without selecting; Enter/Space activate and emit cancelable <code>en-change</code> with reason <code>picker</code>. The picker scrolls within its own container to reveal focus or the current position without scrolling the page. Navigation stops autoplay. Dynamic labels, thumbnails, hiding and removal are reflected; focus recovers when its button disappears.</p>
<p>Use <code>::part(picker)</code> for spacing/overflow, <code>::part(picker-button)</code> for all buttons, <code>::part(picker-current)</code> for the current marker and <code>::part(thumbnail)</code> for preview dimensions/object-fit. Native picker buttons share the library’s button styles and focus tokens.</p>
<h4>Responsive delivery and customization</h4><p><code>slides-per-view</code> sets equal-width slides. Override <code>--en-carousel-slides-per-view</code> with a positive integer in your container queries. The last window stays full; position reports the visible range. The viewport keeps native horizontal scrolling. Its scrollbar stays available before hydration, then hides only while a navigation row or picker is displayed in carousel mode. Restore it with <code>en-carousel::part(viewport) { scrollbar-width: auto; }</code>. Slide height follows authored content, so use consistent media aspect ratios when stable height matters.</p>
<pre><code>${`.collection { container-type: inline-size; }
@container (min-width: 40rem) {
  en-carousel { --en-carousel-slides-per-view: 2; }
}
en-carousel::part(controls) { justify-content: space-between; }
en-carousel-slide::part(base) { padding: var(--en-space-3); }`}</code></pre>
<p>Carousel Parts: base, viewport, controls, first, previous, next, last, rotation, position, picker, picker-button, picker-current, thumbnail and announcement. Slide Part: base. The previous/next slots replace decorative control content inside the existing en-button; do not slot another button or link. Theme tokens component.carousel.gap, radius, background, border-color and slides-per-view map to matching CSS custom properties. Controls retain normal en-button theme, focus and touch-target behavior.</p>
<h4>Large keyed collections</h4>
<p><code>items</code> opts into application data instead of authored children. Each <code>CarouselItem</code> has a unique nonblank string <code>key</code>, a <code>label</code>, an optional decorative <code>thumbnail</code>, and application fields. <code>renderItem(item, index)</code> returns slide content (a Lit template, node or text); the carousel creates its slide wrapper. Collection indices clamp to a valid window before connection and during SSR (using <code>slides-per-view</code> until CSS geometry is available). An empty array means an empty collection; <code>undefined</code> restores authored slides. The getter returns <code>undefined</code> in authored mode; <code>null</code> remains a legacy setter input. The array is copied; treat item records as immutable and assign a new array for updates. Invalid or duplicate keys throw before changing the current collection. When mixing imperative data writes with Lit rendering, use <code>guard([items], () => items)</code> on the property binding so unrelated status updates do not reapply the source array; replace the dependency array reference for intentional application updates.</p>
<pre><code>${`carousel.items = studies.map(study => ({
  key: study.id, label: study.title, thumbnail: study.preview,
}));
carousel.renderItem = item => html\`<a href=\${'/studies/' + item.key}>\${item.label}</a>\`;
const outcome = carousel.requestGoToKey('study-500'); // ChangeOutcome or 'not-found'.
console.log(carousel.currentKey); // Leading key, or undefined when empty/authored.
carousel.readingMode = 'list'; // Ordinary paginated <ol>.
carousel.pageSize = 10;`}</code></pre>
<p>Data mode measures the viewport width and gap to calculate equal-width slide positions. It mounts the visible window plus <code>overscan</code> (default 2, clamped to 0–20) on each side and retains a focused slide by key. Native scrolling remains available; the settled position rounds to the closest leading slide. Programmatic jumps are immediate, avoiding animations through unmounted content. <code>--en-carousel-viewport-size</code> sets the common frame height (default <code>22rem</code>); slide content can scroll inside that frame. Responsive <code>slides-per-view</code> and its CSS override still apply. Keep persistent form/media state in your application: unmounted content is rendered again when revisited. Render callbacks must be safe to invoke repeatedly and should not perform fetching or other side effects.</p>
<p>In carousel mode the leading key survives insertion and reordering when a full final window permits it; list mode opens the page containing that key; removal falls back to the nearest valid index. Removing focused content returns focus to the viewport. A retained offscreen focused slide remains accessible until focus leaves. Other offscreen slides stay inert. Carousel keyboard traversal covers displayed content; use the list alternative for sequential reading through the entire collection. The thumbnail/position picker displays one contiguous window: seven choices when the viewport is at least 44rem wide, five from 32rem, otherwise three (or fewer if the entire collection is smaller). The window shifts at the ends to keep its count stable. With <code>boundary-controls</code>, First/Last in the main controls row jump to the first/last full slide window. The picker has no separate navigation row. Thumbnails show visible position numbers and themed hover/focus tooltips. A visible caption identifies the displayed range; in multi-slide layouts these numbers identify leading-window positions. Keyboard focus moves this same window without selecting a slide; pointer focus does not move it before click activation. Arrow keys can traverse every index; Home/End reaches either boundary without mounting every thumbnail. No interactive slide is cloned.</p>
<p><code>reading-mode="list"</code> renders an ordinary ordered list of up to <code>page-size</code> entries, with global item positions. Previous/Next advance pages, rotation and the thumbnail picker disappear, and every item on the page is readable without inert virtual slides. Navigation to a key opens its containing page. Provide an explicit mode selector in your application, as in the <a href=${href('/api-examples/carousel#large-carousel-example')}>large-collection example</a>; do not infer a screen reader. Before hydration, data mode renders one readable page rather than a virtual shell. Applications that load their data only after JavaScript must own their initial loading state.</p>
<p>Navigation Parts: <code>controls</code>, <code>first</code>, <code>previous</code>, <code>position</code>, <code>next</code>, <code>last</code>, <code>picker-range</code>, <code>picker-number</code>, and <code>picker-tooltip-surface</code> allow layout and tooltip customization. The former picker-navigation, picker-first and picker-last Parts are replaced by the shared controls row and first/last Parts. Localize <code>first-label</code>, <code>last-label</code>, and <code>picker-range-label</code> ({start}, {end}, {total}). Collection Parts: <code>track</code>, <code>slide</code>, <code>reading-list</code> and <code>reading-item</code>, alongside the existing navigation Parts. Localize <code>previous-page-label</code>, <code>next-page-label</code> and <code>list-label</code> for the reading alternative. Virtualization is optional by choosing authored slides or list delivery; unbounded carousel mounting, infinite clones, media loading and media playback remain application responsibilities.</p>
<p><code>requestGoToKey(key)</code> distinguishes committed, unchanged, canceled, superseded and not-found. Commit means semantic navigation, not completed scrolling. Existing <code>goToKey(key)</code> retains its key-found Boolean, including true when navigation is canceled. Reveal-only <code>scrollToKey</code> on tree/table/feed remains a separate contract.</p><h4>Rotation and accessibility</h4><p>Manual navigation is the default. <code>autoplay</code> enables a visible start/stop control before slides; <code>interval</code> defaults to 7000 milliseconds with a 5000 minimum. <code>play()</code> and <code>pause()</code> are explicit requests. Focus entry, manual navigation and gestures stop rotation until restarted. Hover and hidden documents suspend timers. Reduced motion prevents rotation and smooth scrolling, even after play(). Without loop, rotation stops at the last window. Disconnecting clears timers and observers.</p>
<p>The named group uses a carousel role description; slides have descriptive names with position. Only visible slide content participates in keyboard and accessibility navigation after hydration. A focused slide stays available while offscreen until focus leaves. Before JavaScript starts, every slide remains readable and the viewport scrolls natively; scripted controls appear after initialization. Manual navigation announces concise position; automatic rotation never announces slide bodies.</p>
<p>Localize label, previous-label, next-label, start-label, stop-label, position-label / range-label ({current}, {end}, {total}), empty-label, carousel-label, slide-label, viewport-label, picker-label and pick-label ({position}, {label}). Physical screen-reader and mobile swipe review remain part of acceptance. Infinite clones, media loading and media playback are outside the component contract.</p></section>`;
}
