import { html } from 'lit';
export function colorPickerReference(href: (path: string) => string) {
  return html`<section id="api-color-picker-guide"><h3>Inline color editing</h3>
    <p>Use <code>en-color-picker</code> for themed sRGB and Display-P3 color editing. Choose HEX, RGB or HSL using <code>format</code>. HEX presents a combined text field and RGB gradient sliders; RGB and HSL provide exact numeric channel inputs alongside their sliders. HEX and channel editors are composed en-text-field elements with size="small"; the gradient slider retains its own interaction sizing. Set show-hex to retain the combined HEX field in RGB/HSL modes, and editable-channels to keep exact numeric inputs in HEX mode too. Together these keep the preview, summary and channel rows stable as formats change, as demonstrated in the chat picker. The Alpha switch exposes a fourth channel. Changing format or hiding alpha preserves the accepted color, including existing transparency.</p>
    <p><code>value</code> and typed <code>colorValue</code> share one accepted state. Exact sRGB byte values serialize as lowercase six/eight-digit hex; fractional sRGB values use <code>color(srgb …)</code>, and Display-P3 uses <code>color(display-p3 …)</code>. Authored values accept literal hex, RGB, HSL and these two CSS color spaces. Invalid values retain the previous accepted color. Presentation changes preserve color space and alpha. In Display-P3, RGB inputs use normalized 0–1 channels; HEX/HSL show a read-only sRGB approximation until the explicit Convert to sRGB action is accepted.</p>
    <p>Pure helpers <code>parseColor</code>, <code>serializeColor</code>, <code>convertColor</code>, <code>inGamut</code>, <code>exportSRGB</code> and <code>colorPaint</code> are exported from color-picker.js. ColorValue contains space, immutable channels and alpha. Conversion retains extended coordinates; exportSRGB explicitly clips and reports <code>clipped</code>. Preview fallback never changes storage. <code>convertToSRGB()</code> performs the same cancelable conversion transaction as the button. Add <code>plane</code> to replace channel sliders with a two-dimensional saturation/value plane and equivalent Hue, Saturation, Value and optional Alpha controls. Each equivalent slider includes a small exact-value field. The textual <code>format</code> presentation is independent of these HSV controls.</p>
    <pre><code>${`import '@en-reve/elements/define/color-picker.js';
const picker = document.querySelector('en-color-picker');
picker.value = '#33669980'; // Silent authoritative write; alpha last.
picker.format = 'hsl';
picker.alpha = true;
picker.addEventListener('en-change', event => {
  if (!allowColor(event.detail.proposed)) event.preventDefault();
});`}</code></pre>
    <p><code>en-change</code> bubbles and is composed and cancelable, with <code>{previous, proposed, reason}</code>. Reasons include color-space, hex, red, green, blue, hue, saturation, lightness, brightness, plane and alpha. During the event, value contains the provisional color. Cancellation restores the accepted color and controls; an authoritative write by a listener wins. Format and alpha visibility are presentation settings and do not emit color changes.</p>
    <p>Hex and exact numeric drafts commit on Enter or blur; invalid drafts remain editable without changing the accepted color. Sliders retain native Arrow/Home/End behavior. Use <code>checkValidity()</code> to inspect draft validity, or <code>reportValidity()</code> to reveal feedback and focus the invalid field before Apply. The application owns form submission, popup lifetime and Apply/Cancel policy. <code>en-color-field</code> remains the form-associated field with a native browser chooser.</p>
    <p>Every channel uses <code>en-color-slider</code>. Its gradient changes that channel while holding the others steady. Alpha fades the current color over checkerboard tiles; a transparent preview also uses checkerboard. The reusable slider inherits the numeric value, exact-input, form, keyboard and cancelable-change APIs of <code>en-slider</code>. Supply <code>stops</code> as 2–64 evenly spaced validated CSS color literals in the supported spaces, from minimum to maximum; invalid lists fall back to black and white. Set <code>checkerboard</code> to reveal transparency. RTL and vertical orientation reverse the gradient with the value direction.</p>
    <pre><code>${`import '@en-reve/elements/define/color-slider.js';
const slider = document.querySelector('en-color-slider');
slider.label = 'Alpha';
slider.min = 0; slider.max = 100; slider.value = 60;
slider.editable = true;
slider.checkerboard = true;
slider.stops = ['#33669900', '#336699'];`}</code></pre>
    <h4>Standalone hue wheel</h4>
    <p><code>en-color-wheel</code> is an independently imported hue ring, with the same <code>value</code>/<code>colorValue</code> contract. It preserves encoded color space, saturation, HSV brightness and alpha. The opaque spectrum represents hue, not the final transparent color. Gray/black colors retain a local remembered hue; editing that hue alone cannot change an achromatic CSS color and therefore does not emit a color change. The wheel is not loaded by the standalone Color Picker import and does not change its default UI.</p>
    <p>The ring is a named, keyboard-focusable slider. Arrow Right/Up adds 1°, Left/Down subtracts 1°, Page Up/Down changes 10°, and Home/End selects 0°/360°. Keys stop at the endpoints; pointer movement traverses the circular seam. Hue increases clockwise from red at the top, including in RTL. The small exact field accepts fractional degrees between 0 and 360. <code>label</code> names the group and <code>hue-label</code> names both hue inputs. Use <code>disabled</code>, <code>focus()</code>, <code>checkValidity()</code> and <code>reportValidity()</code> as with the plane.</p>
    <p>Dragging emits draft <code>en-input</code> events without changing the accepted color. Release, a navigation key or an exact-field commit proposes <code>en-change</code> with reason <code>hue</code>. Escape, pointer cancellation, disabling or disconnecting rolls back an active drag. Author writes supersede it. Changes can be vetoed; read the settled value after dispatch when synchronizing other controls. The application owns forms and Apply/Cancel.</p>
    <pre><code>${`import '@en-reve/elements/define/color-wheel.js';
wheel.value = 'color(display-p3 0.3 0.5 0.8 / 0.65)';
wheel.addEventListener('en-change', event => {
  if (!allowColor(event.detail.proposed)) event.preventDefault();
  queueMicrotask(() => { plane.value = wheel.value; });
});`}</code></pre>
    <p>Parts: <code>base</code>, <code>label</code>, <code>control</code>, <code>ring</code>, <code>center</code>, <code>thumb</code>, <code>editor-field</code>, <code>editor</code>, <code>editor-label</code> and <code>error</code>. Geometry properties: <code>--en-color-wheel-size</code> (14rem), <code>--en-color-wheel-track-size</code> (2rem), and <code>--en-color-wheel-thumb-size</code> (1.5rem). Keep a circular surface and a usable ring hit target when customizing. Forced colors retain boundaries, the marker and exact entry; unsupported P3 paint uses an sRGB approximation without changing stored values.</p>
    <p><a href=${href('/api-examples/color-picker#color-wheel-example')}>Try the wheel and plane composition</a>.</p>
    <h4>Saturation/value plane</h4>
    <p><code>en-color-plane</code> is also available independently. It accepts the same <code>value</code>/<code>colorValue</code> model, <code>alpha</code> visibility and <code>disabled</code> state. Its HSV model operates within the accepted encoded RGB space; it is neither CSS HSL nor an implicit conversion to sRGB. Hue survives gray or white, and both hue and saturation survive black, so increasing Value restores the previous chromatic direction. The plane shows opaque colors; Alpha remains a separate checker-backed channel.</p>
    <p>Pointer/touch movement emits noncancelable <code>en-input</code> previews with the draft CSS color in <code>detail.value</code>, while the accepted <code>value</code> remains unchanged. Pointer release proposes one cancelable <code>en-change</code> with reason <code>plane</code>. Escape, pointer cancellation or disabling restores the accepted preview. An authoritative write, including an equal-value write, supersedes an active gesture. The containing picker forwards previews and updates its preview chip. Apply/Cancel and editor undo remain application-owned.</p>
    <pre><code>${`import '@en-reve/elements/define/color-plane.js';
const plane = document.querySelector('en-color-plane');
plane.value = 'color(display-p3 1 0.2 0.1 / 0.65)';
plane.alpha = true;
plane.addEventListener('en-input', event => preview(event.detail.value));
plane.addEventListener('en-change', event => {
  if (!allowColor(event.detail.proposed)) event.preventDefault();
});`}</code></pre>
    <p>The pointer surface is decorative to assistive technology; the separately named native sliders and exact text fields provide the full equivalent interaction. This avoids a nonstandard two-axis ARIA slider. Arrow/Home/End operate each slider independently, RTL reverses saturation's horizontal direction, and forced-colors mode retains controls and a contrasting position marker. Physical touch and VoiceOver qualification remain manual.</p>
    <p>Plane Parts include <code>plane</code>, <code>thumb</code>, <code>axes</code>, <code>channels</code>, <code>hue</code>, <code>saturation</code>, <code>brightness</code>, <code>alpha</code>, <code>slider</code>, <code>channel-field</code> and <code>channel-input</code>. The containing picker forwards the plane surface directly, <code>thumb</code> as <code>plane-thumb</code>, and <code>axes</code> as <code>plane-axes</code>; <code>plane-control</code> exposes the compound host. CSS properties <code>--en-color-plane-block-size</code>, <code>--en-color-plane-radius</code> and <code>--en-color-plane-thumb-size</code> configure its geometry. Hue, saturation, brightness, alpha and group labels are localizable properties.</p>
    <p>The picker's <code>palette</code> and <code>recent</code> slots accept application-owned controls. Set value from their actions; disable them separately when disabling the picker. Group, format, alpha and channel labels use the existing label attributes. <code>validation-text</code> supplies numeric constraint feedback on picker, plane and wheel without creating invalidity. Picker and plane accept property-only <code>messages</code> with <code>invalidColor</code>, <code>exactValueLabel</code> and <code>channels</code> overrides keyed by channel name; picker forwards these into plane mode too. Wheel accepts <code>messages.invalidColor</code> separately from exact-hue <code>validationText</code>. Picker <code>messages.hexGuidance</code> overrides the existing <code>invalid-message</code> HEX fallback. Additional picker messages localize approximation, gamut and conversion text. Replace the object to update. See <a href=${href('/reviews/api-normalization/api-08-localization.md')}>API-08 message keys and examples</a>.</p>
    <p>Shared control and focus tokens supply theme defaults. Managed <code>component.color-picker.*</code> settings configure width, spacing and preview geometry. <code>component.color-slider.*</code> configures track thickness, handle size, track radius, checker size and both checker colors. The corresponding CSS properties use <code>--en-color-picker-*</code> and <code>--en-color-slider-*</code>. Parts space, gamut-message and conversion expose color-space information and explicit conversion. Parts expose the summary wrapper, format controls, preview, hex, value and channel layout; slider and channel-input Parts forward the native range and exact text input; channel-field exposes the small en-text-field host. The standalone slider also exposes inherited label/control/editor Parts. Native track and thumb pseudo-elements are configured through tokens.</p>
    <p>Use <code>::part(summary)</code> to style or hide the preview/readout row, and <code>::part(format)</code> to hide the format selector independently of alpha. The summary contains the text input in HEX mode; choose RGB or HSL when hiding it to retain exact numeric entry. The <code>hex-field</code> Part exposes the text-field host; <code>hex</code>, <code>hex-description</code> and <code>hex-error</code> separately forward its native input, guidance and validation surfaces.</p>
    <pre><code>${`en-color-picker::part(summary) { display: none; }
en-color-picker::part(format) { display: none; }`}</code></pre>
    <p>In the <a href=${href('/api-examples/composable-chat')}>composed editor example</a>, # opens the Picker tab directly. Its application CSS forwards and styles the picker Parts: summary and format controls share the left column, channels occupy the right, and Cancel/Apply align at the bottom right. A container query stacks these sections at narrow widths. The preview-frame Part exposes the checkerboard wrapper so the preview can stretch with its summary. Typing a hex value or palette name updates the picker. The Chips tab offers matching palette/recent colors and preserves picker edits between tabs. Enter or Down Arrow enters the picker controls. Apply commits one undoable chip edit; Cancel or Escape preserves text or the original chip. Native-first and menu typeahead alternatives remain available. Native mode preserves an existing hex token's alpha while editing RGB. Wide-gamut or fractional tokens use the inline picker to avoid implicit conversion. The wide-gamut example shares one validated color extension between token and rich-text editors.</p>
  </section>`;
}
