import { html } from 'lit';
export function formNavigationReference(href: (path: string) => string) {
	return html`
		<section class="api-section" id="api-form-navigation-guide" tabindex="-1" aria-labelledby="form-navigation-title">
			<h3 id="form-navigation-title">Validation and step ownership</h3>
			<p>Form controls separate current state from reset defaults. Set <code>defaultValue</code> (the <code>value</code> attribute) or <code>defaultChecked</code> (the <code>checked</code> attribute) to establish a reset baseline. Defaults also update pristine controls. After a property assignment or user edit, changing a default preserves current state until reset. Date-picker ranges use <code>defaultRangeValue</code>; files reset empty. Property-only initialization no longer establishes a field’s reset default. See <a href=${href('/reviews/api-normalization/api-03-forms.md')}>API-03 migration notes</a>.</p>
			<p>All form-associated controls expose <code>form</code>, <code>labels</code>, <code>validity</code>, <code>validationMessage</code>, <code>willValidate</code>, <code>checkValidity()</code> and <code>reportValidity()</code>. Application <code>error</code> sets invalidity and associated visible feedback, including on choices, sliders, ratings and file upload. Clear it explicitly; reset retains it. <code>validationText</code> localizes constraint feedback without causing invalidity itself.</p>
			<p><a href=${href('/workflows/multi-step')}>Create a project brief</a>, or use the <a href=${href('/api-examples/multi-step')}>isolated example with inspired themes and full source</a>. Try empty submission, linked errors, revisiting earlier steps, application veto, and retry after a simulated failed save.</p>
			<h4>Progress steps</h4>
			<p>Assign <code>items</code> as an array of <code>{ value, label, status?, disabled? }</code> records. Values must be unique and nonempty; the first duplicate wins. Status is <code>pending</code>, <code>complete</code> or <code>error</code>. The application owns completion and availability independently from the current <code>value</code>. Reassign the array to update the list. A removed current key stays in the property and renders no current step until the application chooses another.</p>
			<p>Each item has an optional named label slot, such as <code>slot="step-details"</code> for value <code>details</code>. Supply noninteractive text or phrasing content. Native buttons remain owned by the component. <code>readonly</code> renders a static ordered status list; <code>disabled</code> temporarily prevents navigation. Localize <code>label</code>, item labels and all four state labels.</p>
			<p>Activating a step exposes the proposed <code>value</code> and emits one cancelable <code>en-change</code> with <code>{ previous, proposed, reason: 'activate' }</code>. Call <code>preventDefault()</code> to restore the previous value. An explicit property write inside the handler takes precedence. Accepted navigation does not validate a form, load a panel or move focus to it: the application performs those actions after acceptance. There is no <code>controlled</code> attribute or request-change event.</p>
			<p>Steps are an ordered navigation list with <code>aria-current="step"</code>, not tabs or a progressbar. Tab reaches available step buttons; Enter and Space activate. Text identifies current, complete and error states. At container widths up to 30rem, a native disclosure summarizes the current step and expands to show the same list. It works before hydration. Accepted selection or Escape closes it; canceled selection stays open. Larger containers show the whole list. Logical layout supports RTL without changing reading order. Localize <code>summary-label</code> with <code>{current}</code>/<code>{total}</code> placeholders and <code>completed-label</code> with <code>{total}</code>. The <code>summary</code> slot replaces the compact text; its fallback uses the current item’s plain label. The <code>disclosure-control</code> and <code>disclosure</code> Parts expose the new surfaces. <code>list</code>, <code>item</code>, <code>control</code>, <code>number</code>, <code>label</code> and <code>status</code> Parts support alternative distribution and presentation.</p>
			<h4>Validation summary</h4>
			<p>Assign <code>items</code> as ordered <code>{ target, message }</code> records. Each target is an element ID in the summary host's document or shadow root. Use the same message for the field's <code>error</code> property and its summary entry. The summary renders nothing for an empty array. Heading content supports an attribute or the <code>heading</code> slot; the <code>description</code> attribute/property supplies plain guidance. Both named slots remain supported and assigned slot content always takes precedence, including an empty assigned element. Removing that content restores the current fallback.</p>
			<p>After unsuccessful submission, render the errors, await the summary's <code>updateComplete</code>, then call <code>focus()</code>. It is a named region, intentionally without an automatic live announcement or focus-on-render effect. This lets the application choose one announcement path and avoids stealing focus while someone corrects a field.</p>
			<p>A link focuses the target through its public <code>focus()</code> method, including encapsulated fields. Its cancelable <code>en-action</code> has <code>action: 'focus'</code> and the issue in <code>data</code>. Cancel this command to reveal an earlier panel, await rendering and focus its field, or to handle a cross-root target. This is a focus command, not a state-control event. Native anchors remain in initial HTML; cross-shadow focus enhancement requires JavaScript.</p>
			<h4>Slotted content and child-authored lists</h4>
			<p>Both patterns accept complete child-authored lists alongside <code>items</code>. Direct recognized children take precedence, including when all are hidden. Removing the final child restores the array fallback. Insert, remove, reorder or edit children to update the list; original nodes and their application bindings are preserved.</p>
			<pre><code>${`<en-progress-steps value="details" label="Create a project">
  <en-progress-step value="details" status="complete">Project details</en-progress-step>
  <en-progress-step value="review" disabled>Review <strong>brief</strong></en-progress-step>
</en-progress-steps>
<en-validation-summary>
  <a href="#project-name">Enter a <strong>project name</strong>.</a>
  <a href="#work-email">Enter a work email address.</a>
</en-validation-summary>`}</code></pre>
			<p><code>en-progress-step</code> supplies a unique nonempty <code>value</code>, optional <code>status</code>, <code>disabled</code>, <code>hidden</code> and rich noninteractive label content. Its <code>label</code> attribute supplies fallback content and plain text for the compact summary; otherwise text content is used. Keep links and controls out of step labels. The parent owns navigation buttons, current value and the single cancelable <code>en-change</code>. Child updates never infer completion or choose a replacement value.</p>
			<p>Validation children are native <code>a</code> elements with same-document fragment links such as <code>href="#project-name"</code>. URI-encode IDs when needed. The same focus command applies; modified clicks, download links and alternate browsing targets retain native behavior. Use <code>hidden</code> to omit a link. Style authored anchors directly; the <code>link</code> Part applies to array-generated anchors.</p>
			<p>Only direct descriptors or anchors define the list: wrapping containers and forwarded lists are not traversed. Existing named slots remain available. Rich label content may use your component composition; provide an explicit plain <code>label</code> when its text is not in the descriptor’s light DOM. Invalid descriptors or link fragments produce an authoring error instead of silently switching to the array. The <code>error</code> Part exposes that message.</p>
			<p>Use <code>renderToString()</code> from <code>@en-reve/ssr</code> for server rendering. Its adapter discovers children, emits the initial ordered list and assigns internal slots before hydration, preserving the authored nodes. Do not author generated <code>slot</code> values or <code>data-en-form-children</code> metadata. Plain client rendering needs no adapter. The example’s Review scenarios includes a switch between children and arrays.</p>
			<h4>Form and service policy</h4>
			<p>These components do not scan forms, infer completion, persist data, submit requests or replace native/server validation. The example supplies a local business-validation policy, disables inactive fields, preserves accepted values in application state, moves focus after step changes, and uses an explicitly simulated service failure. Production consumers must validate on the server and decide their own pending, cancellation and retry policy.</p>
			<p>Both components use shared theme color, spacing, action and focus tokens. Medium sizing needs no attribute. Review inspired themes, forced colors, narrow widths and real assistive technology with the surrounding workflow.</p>
			<p>Background: <a href="https://www.w3.org/WAI/tutorials/forms/multi-page/">WAI multi-page forms</a> and <a href="https://design-system.service.gov.uk/components/error-summary/">GOV.UK error summaries</a>.</p>
		</section>
	`;
}
