import {html} from 'lit';
export function richTextReference(href:(path:string)=>string){return html`<section class="api-section" id="api-rich-text-guide" tabindex="-1"><h3>Rich documents and shared extensions</h3>
<p>Try the <a href=${href('/api-examples/rich-text')}>standalone editor, composer and token-editor comparison with full source</a>. en-rich-text-editor is optional: selective token-editor and composer imports do not load its block-editing backend.</p>
<pre><code>${`import '@en-reve/elements/define/rich-text-editor.js';
import '@en-reve/elements/define/editor-toolbar.js';
// HTML:
<en-editor-toolbar for="brief" label="Formatting"></en-editor-toolbar>
<en-rich-text-editor id="brief" label="Project brief"></en-rich-text-editor>
<en-editor-toolbar for="brief" mode="contextual"
  label="Selection formatting"></en-editor-toolbar>`}</code></pre>
<h4>Document ownership</h4><p><code>document</code> is a detached immutable {type: 'en-rich-text', version: 1, doc} block tree. Supported nodes: doc, paragraph, heading (level 1–3), bullet_list, ordered_list, list_item, text, hard_break and atomic token (attrs.run uses the existing token run). Marks: strong, em and link (attrs.href). It is a separate format from token-editor v1; use <code>richDocumentFromRuns(runs)</code> for explicit conversion. <code>value</code> is its plain-text projection; assigning value replaces formatting. Author writes are silent, validated, authoritative and reset history. Do not assign document on every selection notification.</p>
<p><code>en-change</code> is a cancelable transaction with immutable previous/proposed documents and reason. Tentative reads see the proposed content; cancellation restores the prior state, while a synchronous author write wins. Ordinary selection movements emit <code>en-editor-state</code> rather than document changes. <code>en-input</code> reports native draft/composition input. The composer adapter supplies plain value plus structured content through its existing immutable send snapshot. Submit remains application-owned.</p>
<p>Both editors expose <code>value</code> as the document text, readonly <code>draftValue</code> for live native text and readonly <code>composing</code>. Draft previews should use <code>en-input.detail.value</code> or <code>draftValue</code>; token-editor value no longer switches to unaccepted IME text. Tentative en-change reads still expose the proposed document. Editor action data is detached JSON, deeply frozen before dispatch; compare application IDs instead of provider-object identity.</p><p><code>focus(options)</code> returns void and forwards native options. Toolbar waits for its render; token editor requires its textbox to be rendered, and rich editor requires its asynchronous backend to be mounted. Calls before editor readiness are no-ops; rich-editor updateComplete alone does not guarantee backend mounting.</p><h4>Commands, selection and toolbars</h4><p><code>getCommandState(name)</code> reports enabled, active and mixed. <code>execute(name, value?, bookmark?)</code> supports bold, italic, paragraph, heading (level 2), bullet-list, ordered-list, link (URL), unlink, undo and redo. <code>captureBookmark()</code>, <code>restoreBookmark(bookmark)</code> and <code>replaceBookmark(bookmark, runs)</code> provide opaque targets owned by one editor and document revision. Stale or cross-editor bookmarks fail without editing. A valid target survives focus moving to an associated toolbar or link field.</p>
<p>Toolbars associate with <code>for</code> in the same root or an explicit <code>.editor</code> across roots. Persistent is the default. Contextual mode appears only for an eligible nonempty selection and yields to extension pickers. It never moves focus on opening. Alt+F10 enters an available toolbar; Escape returns to the editor and dismisses the current contextual selection. The default command subset is configurable through <code>.commands</code>; slot a custom <code>en-toolbar</code> with your own controls for full presentation ownership.</p>
<p>Generated controls are constructed eagerly in persistent and contextual toolbars. Contextual visibility follows the eligible editor selection; dismissal retains those controls. Authored slot content replaces their presentation without transferring editor or selection ownership.</p>
<p><code>placement="auto"</code> docks contextual controls near the visible editor bottom on narrow or coarse-pointer viewports, otherwise anchors above/below the selection and clamps to the viewport. Use floating or docked to override. Parts: base, toolbar, command, command-icon, link-editor. Default command buttons pair visible labels with decorative en-icon symbols (bold, italic, heading, paragraph, bullet-list, ordered-list, link, unlink, undo, redo), so both persistent and contextual controls share the same visual vocabulary. Icons inherit button sizing and theme color. Style or hide the icons with ::part(command-icon); use the default slot for a completely custom toolbar. Customize opaque background and spacing with --en-editor-toolbar-background and --en-editor-toolbar-gap. Editor parts: editor, token, token-content, popup and option; existing --en-editor-token-* hooks and control/theme families apply.</p>
<h4>Application extensions</h4><p>Import <code>EditorExtension</code> from <code>@en-reve/elements/editor-extensions.js</code>. Existing token-editor type imports also work. The same registerExtension, registerToken and openExtension APIs support @ references, / tools and optional picker extensions in both editors. en-editor-trigger accepts either backend through its registration capability. Providers receive query and AbortSignal; removed/replaced providers and newer input invalidate stale work. Action-only choices dispatch cancelable en-action and remove the accepted trigger text. Token insertions participate in the same undo history as formatting. Register a token with extension and deleteBehavior='edit' to reopen its picker on click. Backspace immediately after a chip, or Delete immediately before it, replaces the chip with its editable trigger and opens suggestions; no chip selection is required. Keep typing a new query or press Backspace again to remove the trigger. This is one cancelable, undoable edit. Explicit range deletion removes the selected content. With deleteBehavior='remove' (the default), an adjacent deletion removes the chip immediately. A focused chip supports the same deletion behavior. The public editToken(tokenId, {query?}) method restores the trigger plus an optional query, matching the token editor; openExtension(id, {tokenId}) retains the chip while choosing a replacement.</p>
<p>Typed extension menus align with the leading edge of the @ or / trigger, remaining horizontally stable as the query grows. When text wraps, vertical placement keeps the active typing line clear. A trigger scrolled out of view falls back to the visible caret; if both are hidden, controls clamp to the visible editor edge. Manual opens use the caret; editing a token stays anchored to its chip. Shared geometry handles ancestor scrolling, wrapping, viewport clamping and RTL without moving selection. <code>session.getAnchorRect()</code> exposes the current anchor for application-owned pickers.</p>
<h4>Keyboard, SSR and boundaries</h4><p>Enter creates a paragraph; Shift+Enter inserts a line break. Mod+B/I applies emphasis; Mod+Z and Shift+Mod+Z undo/redo. In lists, Enter splits an item; Mod+[ / Mod+] changes nesting. Suggestion lists use Up/Down, Enter and Escape. Semantic initial HTML remains readable before JavaScript; controls become available after the browser editing backend mounts. Triple-clicking the editing content selects the whole document, including offscreen blocks and tokens, like Mod+A. Single-click caret placement and double-click word selection remain unchanged. Selection does not change the document or undo history. Readonly preserves reading/selection, including triple-click selection; disabled removes the editing Tab stop.</p>
<p>For another document, capture the public rich <code>document</code> as a JSON string with <code>JSON.stringify</code> and remove the source editor while it still belongs to its original document, releasing its backend and listeners. Then load the editor in the destination realm, register its definitions in the destination registry and create a fresh editor there. Parse the string with the destination realm's <code>JSON.parse</code>, then assign the decoded document with supported configuration and destination-owned extensions/renderers and retarget the toolbar through <code>.editor</code> after the new backend mounts. Assigning <code>document</code> resets history. Opaque bookmarks, undo history, live selection, active IME composition and link drafts do not transfer. A moved toolbar releases its old association and link state; the destination editor owns new selection and focus. Moving an existing rich-editor host does not promise to preserve its active editing session.</p>
<p>Copy/cut writes readable plain text, safe HTML and a versioned <code>application/x-en-editor+json</code> fragment. Compatible rich editors preserve supported marks, lists and tokens; token editors retain text and registered tokens without formatting. Paste creates new token occurrence IDs; unregistered types become their readable text. External HTML accepts paragraphs, headings 1–3, lists, bold, italic, safe links and line breaks only. Styles, arbitrary attributes, images, executable content and token-looking HTML never become application markup or tokens. Invalid or unsupported structured payloads fall back to text; structured and HTML payloads are bounded to 1,000,000 UTF-16 code units, depth 40 and 20,000 values/nodes. Cut/paste is one cancelable <code>en-change</code> transaction in the same undo history. Applications must still validate token data for their domain; a registered renderer is trusted application code. Clipboard MIME availability depends on the browser and destination app. Drop import, collaboration and advanced embeds remain outside this slice. URLs allow http, https, mailto and relative links; executable and protocol-relative links are rejected. Custom token renderers are trusted application code. Physical mobile selection/keyboard, real IME and VoiceOver remain manual review items.</p><p>Token and rich editors expose <code>control</code> for the native editing surface, <code>token</code> for atomic wrappers and <code>token-content</code> for their noninteractive contents. With <code>TokenOptions.extension</code>, the wrapper is a <code>token-interactive</code> button even before registration; it is disabled while its extension is unavailable or the editor is disabled/read-only. Both editors fall back to <code>token.text</code> when a renderer is absent or throws; <code>token.label</code> remains the accessible name. An optional type-specific <code>part</code> supplements these semantic roles. Custom DOM renderers apply after hydration; SSR uses escaped text fallback.</p><h4>Localizing editor controls</h4>
    <p>Token and rich editors and the default editor toolbar accept property-only <code>messages</code> using the shared <code>EditorMessages</code> type from <code>@en-reve/elements/editor-extensions.js</code>. Partial groups include <code>suggestions</code> (loading, unavailable, empty, keyboardHint and fallback label), <code>instructions</code> (picker and richText), <code>commands</code> and <code>link</code> (label, placeholder, applyLabel, cancelLabel and invalid). Missing entries use English defaults; empty strings are preserved. Replace the object to update; assign it independently to the editor and toolbar. The component label, extension labels, choice text and custom slot/picker UI remain application-owned.</p>
    <p>Both editor backends expose choice <code>label</code> as the accessible option name and optional <code>description</code> as its associated description, including with custom option rendering. See <a href=${href('/reviews/api-normalization/api-08-localization.md')}>API-08 examples and ownership rules</a>.</p>
  </section>`;}
