import { html } from 'lit';
export function toastReference(href:(path:string)=>string){return html`<section class="api-section" id="api-toast-guide" tabindex="-1"><h3>Notifications, timing and ownership</h3>
<p>Try the <a href=${href('/api-examples/toast')}>isolated themed notification demo and full source</a>, or save a change in <a href=${href('/workflows/settings')}>Settings</a>. Messages are persistent by default, accept rich slotted content, and never take focus when added.</p>
<pre><code>${`<en-toast-region label="Notifications" max="3">
  <en-toast variant="warning">
    Upload paused. Your file is still available.
    <en-button slot="actions" type="button">Retry upload</en-button>
    <en-button slot="actions" type="button" variant="secondary">View details</en-button>
  </en-toast>
</en-toast-region>
// For plain text, after registration:
const toast = region.notify({ message: 'Snapshot saved.', variant: 'success' });
// Application actions remain ordinary slotted buttons with application handlers.
toast.addEventListener('en-change', event => {
  if (mustKeepMessage) event.preventDefault();
});`}</code></pre>
<p><strong>Application-provided actions:</strong> assign one or more buttons to <code>slot="actions"</code> and attach ordinary <code>click</code> handlers. Activating an action does not automatically close the toast. In the demo, <strong>View details</strong> updates the activity and keeps the message open; <strong>Retry upload</strong> simulates success and closes it. For a toast returned by <code>notify()</code>, create the buttons, set <code>button.slot = 'actions'</code>, register their handlers, and call <code>toast.append(retryButton, detailsButton)</code>. Use <code>type="button"</code> inside forms. Actions wrap below the message in authored keyboard order and prevent timeout. Call <code>toast.dismiss()</code> after a successful action to honor cancellation and region focus recovery; direct <code>open = false</code> writes are silent and require application-owned focus recovery. Keep an asynchronous retry available if it fails. The <a href=${href('/api-examples/toast')}>failed-upload demo and full source</a> show both handlers.</p>
<p><code>open</code> is exposed as false during a dismiss attempt. The single cancelable <code>en-change</code> includes previous/proposed values and reason <code>dismiss</code>, <code>escape</code> <code>timeout</code> or <code>swipe</code>. Cancel to restore open; an explicit author write wins. Property writes are silent. <code>dismissAll()</code> proposes each toast’s dismissal independently. Closing does not remove the authored element; applications own removal, durable history, undo, retry and service requests.</p>
<p><code>duration="0"</code> is persistent. A positive duration requests an optional timeout in milliseconds. The actual <code>effectiveDuration</code> is the longest of that request, 5,000 ms, or 2,000 ms plus the larger of 350 ms per whitespace-separated word and 60 ms per non-space Unicode code point in <code>messageText</code>. For example, 20 four-letter words receive 9 seconds. <code>announcement</code> supplies the text when richer content needs an explicit equivalent; icon and action slots are excluded. This reading allowance is a heuristic, not a guarantee of accessibility for every reader. Offer persistent notifications or user-adjustable timing for information that is not available elsewhere. Pointer hover, keyboard focus and a hidden document pause the current countdown without resetting it. The <code>actions</code> slot prevents timeout, regardless of duration. A canceled timeout is not repeatedly proposed; change duration, change message text, reopen, or re-admit it from the stack to start a fresh budget. See <a href="https://react-spectrum.adobe.com/Toast#dismissal">Spectrum’s dismissal guidance</a> and <a href="https://www.w3.org/WAI/WCAG22/Understanding/timing-adjustable.html">WCAG timing guidance</a>. Keep essential information recoverable elsewhere and do not make important actions time-limited. Disconnect stops timers and pending announcements.</p>
<p>The region keeps separate polite and assertive live nodes mounted. New/opened messages are queued for announcement; initial SSR content stays readable without being replayed on hydration. Use <code>announcement</code> for a plain localized summary, particularly when rich child content has its own shadow DOM. Default-slot text excludes action labels. <code>priority="assertive"</code> is explicit and independent of visual variant; reserve it for urgent interruptions. <code>priority="off"</code> avoids a duplicate when another status region already announces the same outcome, as in Settings. DOM snapshots cannot prove spoken output: review actual assistive technology.</p>
<p>Notifications remain in DOM order and are never silently discarded. Without <code>max</code>, the region is a scrollable collection. Set <code>max="3"</code> for three full toasts with extra messages represented by a decorative stack behind the last visible toast. <code>placement="inline"</code> is the default. <code>block-start</code> or <code>block-end</code> attaches it to the window at the logical inline end, with safe-area padding. Use a root-level region for window placement; transformed ancestors can establish another containing block. The region is not a modal or a top-layer popup. Explicit variants add the logical inline edge: <code>block-start-start</code>, <code>block-start-center</code>, <code>block-start-end</code>, <code>block-end-start</code>, <code>block-end-center</code>, and <code>block-end-end</code>. Existing short names remain inline-end aliases. All variants preserve top-to-bottom DOM and keyboard order; bottom placement does not reverse the queue. Visual viewport resize helps bottom placement avoid software keyboards, subject to browser support.</p>
<p>Waiting toasts retain <code>open=true</code> and application-owned content but are hidden from focus and the accessibility tree. They do not count down while waiting, and they announce only when admitted. Each return to the visible group starts a full <code>effectiveDuration</code>, even if some time elapsed before displacement. Dismissing a visible toast promotes the oldest waiting message; a canceled <code>en-change</code> leaves admission unchanged. <code>queuedCount</code> reports the backlog; localize its visible explanation with <code>stack-label</code> and style it through <code>::part(stack-summary)</code>. Zero, absent, negative or non-finite <code>max</code> means unlimited; positive fractions round down. Changes to max, child additions/removals, <code>hidden</code> and <code>interrupt</code> are reactive. A focused toast retains a visible slot when the cap shrinks.</p>
<p>For timely delivery, use <code>region.notify({message: 'Save before the session ends.', interrupt: true})</code> or an authored <code>&lt;en-toast interrupt&gt;</code>. With <code>notify({interrupt:true})</code>, the new toast is prepended to the entire list, including ahead of earlier interruptions. Ordinary notifications append in arrival order. Visual, reading and Tab order follow that actual DOM order. Authored slotted toasts retain their consumer-chosen DOM position; the <code>interrupt</code> attribute grants admission priority, so author them first when they should lead the list. A displaced ordinary toast waits without counting down and receives a fresh full budget when featured again. Focused content is never displaced, so with max=1 an interruption may wait until focus leaves. This option does not imply <code>priority="assertive"</code>; choose spoken urgency separately. Timeouts alone never grant admission priority.</p>
<p>The library SSR adapter applies the initial cap to direct and forwarded named-slot messages before hydration. It preserves the authored nodes and open/hidden state; initial visible messages are not replayed by the live region. Without this adapter, browser enhancement applies the cap after registration. <code>dismissAll()</code> also proposes dismissal of waiting messages. The visual stack remains a queue indicator. Enable <code>history</code> for a separate keyboard-accessible disclosure of waiting text and recently closed messages; <code>history-limit</code> bounds retention (20 by default, 0–1000). Waiting previews do not start timers or replay announcements. Recent snapshots are newest closure first, contain plain text without actions, and are cleared by <code>clearHistory()</code> or disabling history. <code>historyItems</code> exposes copied message/variant records. Localize the four history labels and style the <code>history</code>, <code>history-summary</code> and <code>history-list</code> Parts. Persistent inbox storage and removal of authored closed elements remain application-owned.</p>
<p>Expose a consumer button calling <code>region.focus()</code> for direct keyboard access. Normal Tab navigation reaches message actions and dismissal; Escape affects only a focused notification. Dismissing a focused toast moves to another toast’s close control or the named region, unless the application already moved focus. Actions remain available through ordinary slot composition, including forwarded slots.</p>
<p>CSS Parts expose <code>base</code>, <code>icon</code>, <code>content</code>, <code>actions</code>, <code>close</code>; the collection exposes its own <code>base</code> Part. Shared surface, button, focus and motion tokens apply across inspired themes. Optional <code>--en-toast-*</code> overrides customize geometry and paint; the region offers gap, width, maximum block size and layer overrides. Motion honors reduced-motion preferences. Initial HTML contains message content and empty announcement nodes; JavaScript supplies enhancement.</p>
<p>Theme JSONs support <code>component.toast.background</code>, <code>color</code>, <code>border-color</code>, <code>icon-color</code>, <code>radius</code>, <code>padding</code> and <code>shadow</code>, plus <code>component.toast-region.width</code> and <code>gap</code>. Each status can refine paint through, for example, <code>component.toast.danger-background</code> and <code>danger-color</code>; these emit matching <code>--en-toast-*</code> CSS properties and retain paired light/dark behavior. A specific status override takes precedence over general toast paint. The close button adapts its ink, hover tint and focus to the actual toast surface.</p>
<p>A decorative <code>icon</code> slot replaces the shared status glyph. It is excluded from announcements; keep the status meaning in the message text. Use ordinary rich default-slot content for headings and descriptions, and <code>::part(content)</code> or <code>::part(actions)</code> for application layout. The inspired recipes interpret source colors, spacing and elevation; source-specific global shortcuts are not implemented. Optional <code>swipe</code> enables horizontal dismissal while preserving vertical scrolling; focused or interactive content is protected and pointer cancellation leaves the toast open. <code>notify({swipe:true})</code> opts a generated message in. Buttons and Escape remain available, and gesture dismissal uses the cancelable <code>swipe</code> reason. Theme switching never changes urgency or dismissal policy.</p>
<p>Background: <a href="https://www.w3.org/WAI/WCAG21/Understanding/status-messages">W3C status messages</a> and <a href="https://www.w3.org/WAI/WCAG21/Understanding/timing-adjustable">timing adjustable</a>.</p></section>`;}
