import {LitElement,html,css,nothing} from 'lit';
import {ifDefined} from 'lit/directives/if-defined.js';
import {createSelectionModel} from '@en-reve/primitives/state/selection.js';
import {RovingFocusController} from '@en-reve/primitives/interactions/roving-focus.js';
import {dispatchChange} from '@en-reve/primitives/interactions/events.js';
import {foundationStyles} from '@en-reve/styles/foundations.js';
import {buttonStyles} from '@en-reve/styles/buttons.js';
import {controlStyles,formStyles} from '@en-reve/styles/controls.js';
import {selectionStyles} from '@en-reve/styles/selection.js';
import {surfaceStyles,layoutStyles} from '@en-reve/styles/surfaces.js';
import {comboboxStyles} from '@en-reve/styles/combobox.js';
import {menuStyles,menuItemStyles,toolbarStyles,commandPaletteStyles} from '@en-reve/styles/commands.js';
import {overlayStyles} from '@en-reve/styles/overlays.js';
const portable=new URL(location.href).searchParams.get('delivery')==='css';
const sheet=(name:string)=>portable?html`<link rel="stylesheet" href=${`/${name}.css`}>`:nothing;
const shared=portable?[]:[foundationStyles,buttonStyles,controlStyles,formStyles];
class RecipeChoices extends LitElement{
 static override styles=[...shared,...(portable?[]:[selectionStyles,surfaceStyles,layoutStyles]),css`:host{display:block}.en-grid{--en-grid-item-min:220px}.en-option{cursor:pointer}.en-tab-panel[hidden],.en-accordion-panel[hidden]{display:none}fieldset{min-inline-size:0}button{font:inherit}`];
 mode='draft';tab='summary';expanded=false;veto=false;private revision=0;
 readonly tags=createSelectionModel<string>([],{multiple:true});
 readonly roving=new RovingFocusController(this,{items:()=>[...this.renderRoot.querySelectorAll<HTMLElement>('[role=tab]')],recoverFocus:true});
 setMode(value:string){this.mode=value;this.revision++;this.syncMode();this.requestUpdate();}
 private syncMode(){for(const input of this.renderRoot.querySelectorAll<HTMLInputElement>('input[name=mode]'))input.checked=input.value===this.mode;}
 private chooseMode(value:string){const result=dispatchChange(this,{previous:this.mode,proposed:value,reason:'select',getRevision:()=>this.revision,stage:value=>{this.mode=value;this.syncMode();},rollback:value=>{this.mode=value;this.syncMode();}},{eventName:'recipe-change'});this.requestUpdate();return result;}
 constructor(){super();this.addEventListener('recipe-change',e=>{if(this.veto)e.preventDefault();});}
 protected override render(){return html`${sheet('choices')}<section class="en-foundation en-stack"><form class="en-panel"><fieldset><legend>Output mode</legend><div class="en-segmented-control">${['draft','review','locked'].map(value=>html`<label class="en-segmented-item" ?data-selected=${this.mode===value} ?data-disabled=${value==='locked'}><input class="en-sr-only" type="radio" name="mode" value=${value} ?disabled=${value==='locked'} .checked=${this.mode===value} @change=${()=>this.chooseMode(value)}><span class="en-segmented-label">${value}</span></label>`)}</div></fieldset><fieldset class="en-choice-group" data-orientation="vertical"><legend>Include sections</legend>${['Notes','Sources'].map(label=>html`<label class="en-option" ?data-selected=${this.tags.has(label)}><input class="en-checkbox" type="checkbox" name="sections" value=${label} .checked=${this.tags.has(label)} @change=${()=>{this.tags.toggle(label);this.requestUpdate();}}>${label}</label>`)}</fieldset></form><section class="en-tabs"><div class="en-tab-list" role="tablist" aria-label="Project details">${['summary','history','restricted'].map(key=>html`<button class="en-tab" role="tab" id=${`tab-${key}`} aria-controls=${`panel-${key}`} aria-selected=${String(this.tab===key)} aria-disabled=${String(key==='restricted')} @click=${()=>{if(key!=='restricted'){this.tab=key;this.requestUpdate();}}}>${key}</button>`)}</div>${['summary','history','restricted'].map(key=>html`<section class="en-tab-panel" role="tabpanel" id=${`panel-${key}`} aria-labelledby=${`tab-${key}`} ?hidden=${this.tab!==key} tabindex="0">${key} content</section>`)}</section><div class="en-grid">${['Project brief','Review guidance'].map(title=>html`<article class="en-card"><h2 class="en-card__header">${title}</h2><div class="en-card__body">Consumer-owned content with a stable surface contract.</div><footer class="en-card__footer"><a href="#details">Read ${title}</a></footer></article>`)}</div><hr class="en-divider"><section class="en-accordion"><div class="en-accordion-item"><button class="en-accordion-trigger" aria-expanded=${String(this.expanded)} aria-controls="guidance" @click=${()=>{this.expanded=!this.expanded;this.requestUpdate();}}>Extra guidance</button><div class="en-accordion-panel" id="guidance" ?hidden=${!this.expanded}><a href="#guidance">Read workflow guidance</a></div></div></section></section>`;}
}
const options=[{key:'alpha',label:'Alpha project'},{key:'beta',label:'Beta project'},{key:'closed',label:'Closed project',disabled:true},{key:'gamma',label:'Gamma project'}];
class RecipeCombo extends LitElement{
 static override styles=[...shared,...(portable?[]:[comboboxStyles]),css`:host{display:block}.en-combobox-input{inline-size:100%}.en-combobox-option[hidden]{display:none}`];
 query='';selected='';active='';opened=false;veto=false;private revision=0;private observer?:ResizeObserver;
 get choices(){return options.filter(x=>x.label.toLowerCase().includes(this.query.toLowerCase()));}
 private input(){return this.renderRoot.querySelector<HTMLInputElement>('input')!;}
 private popup(){return this.renderRoot.querySelector<HTMLElement>('[popover]')!;}
 override connectedCallback(){super.connectedCallback();window.addEventListener('resize',this.position);window.addEventListener('scroll',this.position,true);this.updateComplete.then(()=>{if(this.isConnected){this.observer=new ResizeObserver(this.position);this.observer.observe(this);}});}
 override disconnectedCallback(){super.disconnectedCallback();window.removeEventListener('resize',this.position);window.removeEventListener('scroll',this.position,true);this.observer?.disconnect();}
 private position=()=>{if(!this.opened)return;const a=this.input().getBoundingClientRect(),p=this.popup();p.style.setProperty('--_en-combobox-x',Math.max(8,Math.min(a.left,innerWidth-a.width-8))+'px');p.style.setProperty('--_en-combobox-y',Math.min(a.bottom+4,innerHeight-120)+'px');p.style.setProperty('--_en-combobox-width',a.width+'px');p.style.setProperty('--_en-combobox-max-height',Math.max(80,innerHeight-a.bottom-12)+'px');p.style.setProperty('--_en-combobox-visibility','visible');};
 async openChoices(){this.opened=true;this.active=this.choices.find(x=>!x.disabled)?.key??'';this.requestUpdate();await this.updateComplete;this.position();if(!this.popup().matches(':popover-open'))this.popup().showPopover();this.input().focus();}
 closeChoices(){this.opened=false;this.active='';if(this.popup().matches(':popover-open'))this.popup().hidePopover();this.requestUpdate();}
 private async choose(key:string){if(options.find(x=>x.key===key)?.disabled)return;const result=dispatchChange(this,{previous:this.selected,proposed:key,reason:'select',getRevision:()=>this.revision,stage:value=>{this.selected=value;},rollback:value=>{this.selected=value;}},{eventName:'recipe-change'});if(result==='committed'){this.query=options.find(x=>x.key===key)!.label;this.input().value=this.query;this.closeChoices();this.input().focus();}this.requestUpdate();}
 constructor(){super();this.addEventListener('recipe-change',e=>{if(this.veto)e.preventDefault();});}
 private async key(event:KeyboardEvent){if(event.isComposing)return;if(event.key==='Escape'){event.preventDefault();this.closeChoices();return;}if(event.key==='Tab'){this.closeChoices();return;}if(event.key==='Enter'&&this.opened&&this.active){event.preventDefault();await this.choose(this.active);return;}if(!['ArrowDown','ArrowUp'].includes(event.key))return;event.preventDefault();if(!this.opened){await this.openChoices();return;}const choices=this.choices.filter(x=>!x.disabled),index=choices.findIndex(x=>x.key===this.active),delta=event.key==='ArrowDown'?1:-1;this.active=choices[(index+delta+choices.length)%choices.length]?.key??'';this.requestUpdate();}
 protected override render(){return html`${sheet('combo')}<div class="en-foundation en-field en-combobox"><label class="en-label" for="project">Project</label><div class="en-combobox-anchor"><input id="project" class="en-input en-combobox-input" role="combobox" aria-autocomplete="list" aria-controls="projects" aria-expanded=${String(this.opened)} aria-activedescendant=${ifDefined(this.opened&&this.active?'option-'+this.active:undefined)} @input=${async(e:Event)=>{this.query=(e.target as HTMLInputElement).value;await this.openChoices();}} @keydown=${this.key}><button class="en-combobox-trigger" aria-label="Choose project" @click=${()=>this.opened?this.closeChoices():this.openChoices()}>⌄</button></div><div class="en-combobox-popup" popover="auto" @toggle=${(e:Event)=>{if((e as ToggleEvent).newState==='closed'&&this.opened){this.opened=false;this.active='';this.requestUpdate();}}}><ul class="en-combobox-listbox" role="listbox" id="projects" aria-label="Projects">${this.choices.map(x=>html`<li class="en-combobox-option" role="option" id=${'option-'+x.key} aria-selected=${String(x.key===this.selected)} aria-disabled=${String(!!x.disabled)} ?data-active=${x.key===this.active} @mousedown=${(e:MouseEvent)=>e.preventDefault()} @click=${()=>this.choose(x.key)}>${x.label}<span class="en-combobox-check" aria-hidden="true">✓</span></li>`)}</ul><p class="en-combobox-status" role="status">${this.choices.length?`${this.choices.length} projects`:'No projects found'}</p></div><p class="en-description">Type a name, then choose an available project.</p><p role="status" aria-label="Selection">${this.selected||'No project selected'}</p></div>`;}
}
class RecipeCommands extends LitElement{
 static override styles=[...shared,...(portable?[]:[overlayStyles,menuStyles,menuItemStyles,toolbarStyles,commandPaletteStyles]),css`:host{display:block}.en-menu{--_en-menu-visibility:visible;--_en-menu-x:16px;--_en-menu-y:80px}.en-command-palette{min-inline-size:0}.en-menu-item[aria-disabled=true]{cursor:default}`];
 menuOpen=false;query='';active=0;result='No action';checked=false;veto=false;private invoker?:HTMLButtonElement;
 readonly toolbarRoving=new RovingFocusController(this,{items:()=>[...this.renderRoot.querySelectorAll<HTMLElement>('.en-toolbar > button')],recoverFocus:true});
 readonly menuRoving=new RovingFocusController(this,{items:()=>this.menuOpen?[...this.renderRoot.querySelectorAll<HTMLElement>('.en-menu-item')]:[],orientation:'vertical',recoverFocus:true});
 get commands(){return ['Create brief','Export PDF','Show history',...Array.from({length:20},(_,i)=>`Archive ${i+1}`)].filter(label=>label.toLowerCase().includes(this.query.toLowerCase()));}
 private dialog(){return this.renderRoot.querySelector<HTMLDialogElement>('dialog')!;}
 private menu(){return this.renderRoot.querySelector<HTMLElement>('.en-menu')!;}
 private async openMenu(e:Event){this.invoker=e.currentTarget as HTMLButtonElement;this.menuOpen=true;this.requestUpdate();await this.updateComplete;this.menu().showPopover();this.menuRoving.refresh();this.renderRoot.querySelector<HTMLButtonElement>('.en-menu-item')?.focus();}
 private closeMenu(){this.menuOpen=false;if(this.menu().matches(':popover-open'))this.menu().hidePopover();this.requestUpdate();this.invoker?.focus();}
 private openPalette(e:Event){this.invoker=e.currentTarget as HTMLButtonElement;this.query='';this.active=0;this.renderRoot.querySelector<HTMLInputElement>('#command-query')!.value='';this.requestUpdate();this.dialog().showModal();this.renderRoot.querySelector<HTMLInputElement>('#command-query')!.focus();}
 private closePalette(){this.dialog().close();this.invoker?.focus();}
 private act(label:string){const e=new CustomEvent('before-command',{detail:{label},cancelable:true,bubbles:true,composed:true});if(this.veto)e.preventDefault();this.dispatchEvent(e);if(e.defaultPrevented)return;if(label==='Pin project')this.checked=!this.checked;this.result=label;this.requestUpdate();if(this.menuOpen)this.closeMenu();if(this.dialog().open)this.closePalette();}
 private paletteKey(e:KeyboardEvent){if(e.isComposing)return;if(e.key==='Enter'&&this.commands[this.active]){e.preventDefault();this.act(this.commands[this.active]);}if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();this.active=e.key==='Home'?0:e.key==='End'?this.commands.length-1:(this.active+(e.key==='ArrowDown'?1:-1)+this.commands.length)%this.commands.length;this.requestUpdate();this.updateComplete.then(()=>this.renderRoot.querySelector('[data-active]')?.scrollIntoView({block:'nearest'}));}}
 protected override render(){return html`${sheet('commands')}<div class="en-foundation"><div class="en-toolbar" role="toolbar" aria-label="Project commands"><button class="en-button" @click=${this.openMenu} aria-haspopup="menu" aria-expanded=${String(this.menuOpen)}>Actions</button><button class="en-button" @click=${this.openPalette}>Command palette</button><button class="en-button" disabled>Unavailable command</button><button class="en-button" @click=${()=>this.act('Save')}>Save</button></div><div class="en-menu" role="menu" aria-label="Project actions" popover="auto" @keydown=${(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();this.closeMenu();}}} @toggle=${(e:Event)=>{if((e as ToggleEvent).newState==='closed'&&this.menuOpen){this.menuOpen=false;this.requestUpdate();}}}><button class="en-menu-item" role="menuitem" @click=${()=>this.act('Export PDF')}><span class="en-menu-item-prefix" aria-hidden="true">⇩</span><span class="en-menu-item-label">Export PDF</span><span class="en-menu-item-shortcut">⌘E</span></button><button class="en-menu-item" role="menuitem" aria-disabled="true" @click=${()=>{}}>Unavailable action</button><hr role="separator"><button class="en-menu-item" role="menuitemcheckbox" aria-checked=${String(this.checked)} @click=${()=>this.act('Pin project')}><span class="en-menu-item-check" aria-hidden="true">${this.checked?'✓':''}</span><span class="en-menu-item-label">Pin project</span></button></div><dialog class="en-dialog en-command-palette" aria-labelledby="palette-title" @cancel=${(e:Event)=>{e.preventDefault();this.closePalette();}}><header class="en-overlay-header"><h2 id="palette-title">Project command palette</h2><button class="en-button en-overlay-close" @click=${this.closePalette}>Close palette</button></header><div class="en-overlay-body"><div class="en-command-palette-content"><label class="en-label" for="command-query">Search commands</label><input class="en-input en-command-palette-input" id="command-query" role="combobox" aria-autocomplete="list" aria-controls="command-results" aria-expanded="true" aria-activedescendant=${ifDefined(this.commands[this.active]?'command-'+this.active:undefined)} @input=${(e:Event)=>{this.query=(e.target as HTMLInputElement).value;this.active=0;this.requestUpdate();}} @keydown=${this.paletteKey}><div class="en-command-list" id="command-results" role="listbox" aria-label="Commands">${this.commands.map((label,i)=>html`<div class="en-command-option" role="option" id=${'command-'+i} aria-selected=${String(this.active===i)} ?data-active=${this.active===i} @mousedown=${(e:MouseEvent)=>e.preventDefault()} @click=${()=>this.act(label)}><span class="en-command-label">${label}</span><span class="en-command-shortcut">${i===0?'Enter':''}</span></div>`)}</div><p class="en-command-status" role="status">${this.commands.length?`${this.commands.length} commands`:'No commands found'}</p></div></div></dialog><p role="status" aria-label="Command result">${this.result}</p></div>`;}
}
class RecipeOverlay extends LitElement{
 static override styles=[...shared,...(portable?[]:[overlayStyles]),css`:host{display:block}.en-overlay-body p{max-inline-size:42ch}.en-tooltip{inset:auto;left:16px;top:16px}`];
 narrow=innerWidth<560;veto=false;private invoker?:HTMLButtonElement;private resize=()=>{this.narrow=innerWidth<560;this.requestUpdate();};
 override connectedCallback(){super.connectedCallback();window.addEventListener('resize',this.resize);}
 override disconnectedCallback(){super.disconnectedCallback();window.removeEventListener('resize',this.resize);}
 private dialog(){return this.renderRoot.querySelector<HTMLDialogElement>('dialog')!;}
 private open(e:Event){this.invoker=e.currentTarget as HTMLButtonElement;this.dialog().showModal();this.renderRoot.querySelector<HTMLInputElement>('#title')!.focus();}
 private close(){const e=new CustomEvent('before-close',{cancelable:true,bubbles:true,composed:true});if(this.veto)e.preventDefault();this.dispatchEvent(e);if(e.defaultPrevented)return;this.dialog().close();this.invoker?.focus();}
 protected override render(){return html`${sheet('overlays')}<section class="en-foundation"><button class="en-button" @click=${this.open}>Edit project</button><dialog class=${this.narrow?'en-drawer':'en-dialog'} data-placement="start" aria-labelledby="edit-title" aria-describedby="description" @cancel=${(e:Event)=>{e.preventDefault();this.close();}}><header class="en-overlay-header"><h2 id="edit-title">Project settings</h2><button class="en-button en-overlay-close" @click=${this.close}>Close settings</button></header><div class="en-overlay-description" id="description"><p class="en-overlay-description-fallback">Changes remain in this local example.</p></div><div class="en-overlay-body"><label class="en-label" for="title">Project title</label><input class="en-input" id="title"><div>${Array.from({length:12},(_,i)=>html`<p>Guidance ${i+1}: Keep controls reachable when the available content area changes.</p>`)}</div><a href="#guidance">Further guidance</a></div><footer class="en-overlay-footer"><button class="en-button" @click=${this.close}>Done</button></footer></dialog></section>`;}
}
customElements.define('recipe-choices',RecipeChoices);customElements.define('recipe-combo',RecipeCombo);customElements.define('recipe-commands',RecipeCommands);customElements.define('recipe-overlay',RecipeOverlay);
