import {html,render} from 'lit';
import {registerAll} from '@en-reve/elements/catalog.js';
import '@en-reve/styles/foundations.css';
import '@en-reve/styles/controls.css';
import '@en-reve/styles/patterns.css';
import './component-patterns.css';
import {presetItems,loadPreset} from './showcase/presets.js';
import {attachDocumentTheme} from './theme-review/document-theme.js';
import {resolvePreviewPair} from './preview-theme.js';
import {meterTemplate,navigationFlyoutTemplate,joinedFieldTemplate,attachmentTemplate,buttonGroupTemplate,choiceCardTemplate,localDateTimeTemplate,messageMarkerTemplate,systemMessageTemplate,codeBlockTemplate,scrollAreaTemplate,chartDetailTemplate,appShellTemplate,mediaCardTemplate} from '@en-reve/primitives/templates/patterns.js';
import type {EnTranscript} from '@en-reve/elements/transcript.js';
import type {EnSelectionCollection} from '@en-reve/elements/selection-collection.js';
import type {EnMediaViewer} from '@en-reve/elements/media-viewer.js';
import type {EnDialog} from '@en-reve/elements/dialog.js';
registerAll();
const root=document.querySelector<HTMLElement>('main')!,status=document.querySelector('#demo-status')!;
const say=(text:string)=>{status.textContent=text;};
const revealFormattingAction=(event:FocusEvent)=>{
 const action=event.target;
 if(action instanceof HTMLElement&&action!==event.currentTarget)action.scrollIntoView({block:'nearest',inline:'nearest',behavior:'instant'});
};
const choices=[{value:'design',label:'Design',description:'Shape the product and its interface.'},{value:'engineering',label:'Engineering',description:'Build reusable systems.'},{value:'research',label:'Research',description:'Understand people and their work.'}];
const files=[{value:'brief',label:'Project brief',description:'Updated today'},{value:'design',label:'Design study',description:'Updated yesterday'},{value:'notes',label:'Research notes',description:'Updated Monday'}];
const image=(color:string,title:string)=>'data:image/svg+xml,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="650" viewBox="0 0 1000 650"><rect width="1000" height="650" fill="${color}"/><circle cx="730" cy="190" r="130" fill="white" opacity=".3"/><path d="M0 620 L330 200 L650 650Z" fill="white" opacity=".6"/><text x="55" y="100" fill="white" font-size="48" font-family="sans-serif">${title}</text></svg>`);
const media=[{key:'dawn',src:image('#795a68','Dawn / 01'),alt:'Rose composition with a circle and triangular mountain',caption:'Dawn — geometric study'},{key:'noon',src:image('#42697c','Noon / 02'),alt:'Blue composition with a circle and triangular mountain',caption:'Noon — geometric study'}];
render(html`
 <div class="pattern-grid">
 <section id="choices"><h2>Choose, keep, combine</h2><p>Pressed feedback and persistent selection are separate states.</p><div class="formatting-scroll" role="region" aria-label="Text formatting controls" tabindex="0" @focusin=${revealFormattingAction}>${buttonGroupTemplate('Text formatting',html`<en-toggle-button><en-icon slot="prefix" name="bold"></en-icon>Bold</en-toggle-button><en-toggle-button><en-icon slot="prefix" name="italic"></en-icon>Italic</en-toggle-button><en-toggle-button pressed="mixed"><en-icon slot="prefix" name="underline"></en-icon>Underline</en-toggle-button>`)}</div><en-toggle-group joined label="Text alignment" .items=${[{value:'start',label:'Start',icon:'align-start'},{value:'center',label:'Center',icon:'align-center'},{value:'end',label:'End',icon:'align-end'}]} value='["start"]'></en-toggle-group><form @submit=${(event:SubmitEvent)=>{event.preventDefault();say('Submitted locally: '+JSON.stringify([...new FormData(event.currentTarget as HTMLFormElement)]));}}><en-checkbox-group label="Disciplines" name="discipline" cards value='["design"]'>${choices.map(choice=>html`<en-choice-option value=${choice.value}><strong>${choice.label}</strong><span slot="description">${choice.description}</span></en-choice-option>`)}</en-checkbox-group><en-multiselect label="Invite teams" name="teams" .items=${choices} value='["engineering"]' required></en-multiselect><div class="row"><en-button type="submit">Inspect values</en-button><en-button type="reset" variant="ghost">Reset</en-button></div></form><en-tag label="Draft" value="draft" removable @en-action=${(event:Event)=>{(event.currentTarget as HTMLElement).hidden=true;say('Draft tag removed.');}}></en-tag></section>
 <section id="fields"><h2>Give fields context</h2><en-text-field label="Budget" adorned value="1200"><span slot="prefix" aria-hidden="true">$</span><span slot="suffix">USD</span><en-button slot="help-action" variant="ghost" @click=${()=>say('Budget is the maximum project spend in US dollars.')}>Budget help</en-button></en-text-field>${joinedFieldTemplate({label:'Project address',name:'slug',value:'new-project',actions:html`<button type="button" class="en-button" data-variant="secondary" @click=${()=>say('Project address checked locally.')}>Check</button>`})}<en-range-slider label="Price interval" lower-label="Minimum price" upper-label="Maximum price" value="[20,80]" min-gap="10"></en-range-slider>${localDateTimeTemplate({label:'Review appointment (local time)',name:'appointment',value:'2026-09-22T10:00'})}<en-otp-field label="Verification code" description="A single input supports paste and one-time-code autofill." required></en-otp-field></section>
 <section id="context"><h2>Act in context</h2><p id="context-target" tabindex="0" class="target">Project brief — right-click, long-press, or use Shift+F10.</p><en-context-menu id="file-menu" for="context-target" label="Project actions" @en-action=${(event:CustomEvent)=>say('Requested '+event.detail.action)}><en-menu-item action="rename">Rename</en-menu-item><en-menu-item action="duplicate">Duplicate</en-menu-item></en-context-menu><en-button @click=${()=>{const target=document.querySelector<HTMLElement>('#context-target')!;(document.querySelector('#file-menu') as any).showFor(target);}}>Project actions</en-button><en-button id="pattern-help" variant="ghost">About previews</en-button><en-tooltip arrow for="pattern-help" block="start"><span slot="content">Hover for a preview; activate to explore its links.</span></en-tooltip><en-button id="profile-preview" variant="secondary">Preview collaborator</en-button><en-hover-card arrow for="profile-preview" label="Sam Rivera"><p>Design systems engineer. Working on the next release.</p><a class="en-link" href="#collection">View shared work</a></en-hover-card><en-button id="confirm-trigger" variant="danger">Archive project</en-button><en-dialog id="confirm" for="confirm-trigger" kind="alertdialog" label="Archive this project?" description="It will move out of your active projects. You can restore it later." initial-focus="keep-project"><en-button slot="footer" id="keep-project" variant="secondary" @click=${()=>document.querySelector<EnDialog>('#confirm')!.hide()}>Keep project</en-button><en-button slot="footer" @click=${()=>{document.querySelector<EnDialog>('#confirm')!.hide();say('Project archived locally.');}}>Archive</en-button></en-dialog></section>
 <section id="collection"><h2>Selection with independent actions</h2><en-selection-collection id="files" label="Project files" .items=${files}><en-button slot="actions" variant="secondary" @click=${()=>say('Selected files: '+(document.querySelector<EnSelectionCollection>('#files')!.value.join(', ')||'none'))}>Inspect selection</en-button>${files.map(file=>html`<en-button slot=${'actions-'+file.value} variant="ghost" @click=${()=>say('Opened '+file.label+' locally.')}>Open ${file.label}</en-button>`)}</en-selection-collection><p>Resize the window to move actions into the disclosure.</p><en-action-overflow .items=${['Download','Share link','Move to folder','Duplicate','Archive'].map((label,index)=>({value:String(index),label}))} @en-action=${(event:CustomEvent)=>say('Overflow action '+event.detail.action)}></en-action-overflow></section>
 <section id="navigation"><h2>Commands and destinations</h2><en-menubar label="Document commands" .items=${[{value:'file',label:'File',items:[{value:'new',label:'New document'},{value:'save',label:'Save copy'}]},{value:'edit',label:'Edit',items:[{value:'undo',label:'Undo'},{value:'redo',label:'Redo'}]}]} @en-action=${(event:CustomEvent)=>say('Command: '+event.detail.action)}></en-menubar><nav aria-label="Example destinations" class="row">${navigationFlyoutTemplate({label:'Explore patterns',links:[{label:'Fields',href:'#fields'},{label:'Workflows',href:'#workflows'}]})}<a class="en-link" href="#content">Content recipes</a></nav><en-button id="sheet-trigger" variant="secondary">Open resizable sheet</en-button><en-sheet for="sheet-trigger" label="Project details"><p>Drag the resize handle, use its Up and Down keys, or choose Smaller and Larger.</p><en-text-field label="Project name" value="Pattern study"></en-text-field><p>Scrolling the content never starts a sheet drag.</p></en-sheet></section>
 <section id="feedback"><h2>Measure and inform</h2><en-alert announcement="none" title="A useful note">Static context stays available without announcing itself.</en-alert>${meterTemplate({label:'Storage used',value:72,max:100,low:60,high:85,optimum:20})}<en-progress-bar label="Upload progress" shape="circle" value="64" max="100"></en-progress-bar><en-chart label="Weekly output" summary="Research increased; one design item returned for revision." .data=${[{key:'research',label:'Research',value:8},{key:'design',label:'Design',value:-1},{key:'build',label:'Build',value:12}]}></en-chart></section>
 <section id="workflows"><h2>Draft a structured query</h2><en-query-builder label="Find project work" .fields=${[{value:'title',label:'Title'},{value:'effort',label:'Effort',type:'number'}]} @en-change=${(event:CustomEvent)=>queueMicrotask(()=>{if(!event.defaultPrevented)say('Applied query: '+JSON.stringify((event.currentTarget as any)?.value??event.detail.proposed));})}></en-query-builder></section>
 <section id="questionnaire"><h2>One question at a time</h2><en-questionnaire label="Project intake" .questions=${[{id:'name',label:'What is your project called?',required:true},{id:'note',label:'Anything else we should know?',optional:true},{id:'team',label:'Which teams own it?',required:true,multiple:true,options:choices.map(({value,label})=>({value,label}))}]} @en-action=${(event:CustomEvent)=>{if(event.detail.action==='submit')say('Completed locally: '+JSON.stringify(event.detail.data.answers));}}></en-questionnaire></section>
 <section id="transcript"><h2>Stay with the conversation</h2><en-transcript id="conversation" follow-latest .messages=${Array.from({length:8},(_,index)=>({id:String(index),author:index%2?'Sam':'You',outgoing:!(index%2),text:['The first prototype is ready.','Let’s try it with every theme.'][index%2]}))}></en-transcript><div class="row"><en-button @click=${()=>{const transcript=document.querySelector<EnTranscript>('#conversation')!;transcript.messages=[...transcript.messages,{id:String(Date.now()),author:'Sam',text:'Another update arrived. Scroll up before adding one to keep your reading position.'}];}}>Add message</en-button><en-button variant="secondary" @click=${()=>{const transcript=document.querySelector<EnTranscript>('#conversation')!;transcript.messages=transcript.messages.map((m,index)=>index===transcript.messages.length-1?{...m,text:m.text+' More text…'}:m);}}>Stream a phrase</en-button></div></section>
 <section id="media"><h2>Look closer</h2><div class="media-preview">${media.map(item=>html`<button type="button" class="preview-image" aria-label=${'View '+item.caption} @click=${()=>{const viewer=document.querySelector<EnMediaViewer>('#viewer')!;viewer.activeKey=item.key;viewer.show();}}><img src=${item.src} alt=""></button>`)}</div><en-media-viewer id="viewer" label="Geometric studies" .items=${media}></en-media-viewer></section>
 <section id="composition" class="wide"><h2>Compose a working shell</h2>${appShellTemplate({navigationLabel:'Example shell sections',embedded:true,header:html`<h3>Project workspace</h3>`,navigation:html`<en-navigation label="Project workspace"><a href="#choices">Overview</a><a href="#fields">Schedule</a><a href="#transcript">Conversation</a></en-navigation>`,main:html`<div class="en-form-grid">${systemMessageTemplate({label:'Design review complete',detail:html`<p>The component review has finished. <a class="en-link" href="#context">Review project actions</a>.</p>`})}${chartDetailTemplate('Output detail',[{label:'Completed',value:'12 items'},{label:'In review',value:'4 items'}])}</div>${messageMarkerTemplate('New since your last visit')}${scrollAreaTemplate('Implementation notes',html`<p>Native scrolling preserves keyboard navigation and platform scrollbars.</p>${codeBlockTemplate({label:'Theme configuration',code:'const theme = resolveTheme({ mode: "light" });',onCopy:()=>{void navigator.clipboard.writeText('const theme = resolveTheme({ mode: "light" });').then(()=>say('Code copied.'),()=>say('Copy was unavailable; select the code to copy it.'));}})}`)}${mediaCardTemplate({src:media[0].src,alt:media[0].alt,caption:'Inset media and native caption',actions:html`<a class="en-link" href="#media">Open gallery</a>`})}`})}</section>
 <section id="content" class="wide"><h2>Native content, shared presentation</h2><div class="content-grid"><div><p>Use <code class="en-code">theme.resolve()</code>, then press <kbd class="en-keycap">Enter</kbd>.</p><p>Updated <time datetime="2026-09-20">September 20, 2026</time>.</p><hr class="en-separator">${buttonGroupTemplate('Document delivery',html`<button type="button" class="en-button" @click=${()=>say('Saved locally.')}>Save</button><button type="button" class="en-button" data-variant="secondary" @click=${()=>say('Copy created locally.')}>Save a copy</button>`)}</div><div>${attachmentTemplate({name:'Pattern notes.txt',url:'data:text/plain,Reusable%20patterns%20with%20native%20semantics.',detail:'44 bytes',onRemove:()=>say('Attachment removal requested.')})}${choiceCardTemplate({type:'checkbox',name:'updates',value:'yes',label:'Keep me informed',description:'A native checkbox fills the whole card.'})}</div></div></section>
 </div>`,document.querySelector('#specimens')!);
const themeSelect=document.querySelector<HTMLSelectElement>('#theme')!,appearance=document.querySelector<HTMLSelectElement>('#appearance')!,direction=document.querySelector<HTMLSelectElement>('#direction')!;
for(const item of presetItems)themeSelect.add(new Option(item.label,item.value));
const params=new URLSearchParams(location.search);themeSelect.value=presetItems.some(i=>i.value===params.get('theme'))?params.get('theme')!:'default';appearance.value=params.get('appearance')==='dark'?'dark':'light';
const documentTheme=attachDocumentTheme({root});let generation=0;
async function paint(){const current=++generation;const theme=themeSelect.value==='default'?resolvePreviewPair({name:'patterns',density:'comfortable'}):(await loadPreset(themeSelect.value)).workspace.presentation;if(current!==generation)return;documentTheme.apply(theme,{appearance:appearance.value as 'light'|'dark',direction:direction.value as 'ltr'|'rtl'});const url=new URL(location.href);url.searchParams.set('theme',themeSelect.value);url.searchParams.set('appearance',appearance.value);history.replaceState(null,'',url);}
for(const control of [themeSelect,appearance,direction])control.addEventListener('change',()=>void paint());await paint();
if(params.has('progress-report')){document.querySelector<HTMLElement>('#progress-return')!.hidden=false;for(const anchor of document.querySelectorAll<HTMLAnchorElement>('a[data-preserve-report]')){const url=new URL(anchor.href);url.searchParams.set('progress-report','');anchor.href=url.href;}}
