import { css } from 'lit';
import { token as t } from './values.js';
import type { PressRecipe } from './press.js';

/** Explicit public names form the reviewed discovery contract. Geometry is opt-in per family. */
export const pressRecipes = {
  'segmented': {
    scale: css`var(--en-segmented-pressed-scale, 1)`,
    offset: css`var(--en-segmented-pressed-offset, 0px)`,
    press: css`var(--en-segmented-press-duration, ${t('--en-duration-press')})`,
    release: css`var(--en-segmented-release-duration, ${t('--en-duration-release')})`,
    shadow: css`var(--en-segmented-pressed-shadow, 0 0 0 0 transparent)`,
    paint: css`background: var(--en-segmented-pressed-background, ${t("--en-color-accent-subtle")}); color: var(--en-segmented-pressed-color, ${t("--en-color-text")}); border-color: var(--en-segmented-pressed-border-color, ${t("--en-color-boundary")});`,
  },
  'accordion': {
    scale: css`var(--en-accordion-pressed-scale, 1)`,
    offset: css`var(--en-accordion-pressed-offset, 0px)`,
    press: css`var(--en-accordion-press-duration, ${t('--en-duration-press')})`,
    release: css`var(--en-accordion-release-duration, ${t('--en-duration-release')})`,
    shadow: css`var(--en-accordion-pressed-shadow, 0 0 0 0 transparent)`,
    paint: css`background: var(--en-accordion-pressed-background, ${t("--en-color-accent-subtle")}); color: var(--en-accordion-pressed-color, ${t("--en-color-text")});`,
  },
  'tab': {
    scale: css`var(--en-tab-pressed-scale, 1)`,
    offset: css`var(--en-tab-pressed-offset, 0px)`,
    press: css`var(--en-tab-press-duration, ${t('--en-duration-press')})`,
    release: css`var(--en-tab-release-duration, ${t('--en-duration-release')})`,
    shadow: css`var(--en-tab-pressed-shadow, 0 0 0 0 transparent)`,
    paint: css`background: var(--en-tab-pressed-background, ${t("--en-color-accent-subtle")}); color: var(--en-tab-pressed-color, var(--en-tab-color, ${t("--en-color-action-text")}));`,
  },
  'rating': {
    scale: css`var(--en-rating-pressed-scale, var(--_en-source-rating-pressed-scale, 1))`,
    offset: css`var(--en-rating-pressed-offset, var(--_en-source-rating-pressed-offset, 0px))`,
    press: css`var(--en-rating-press-duration, ${t('--en-duration-press')})`,
    release: css`var(--en-rating-release-duration, ${t('--en-duration-release')})`,
    shadow: css`var(--en-rating-pressed-shadow, var(--_en-source-rating-pressed-shadow, 0 0 0 0 transparent))`,
    paint: css`background: var(--en-rating-pressed-background, var(--_en-source-rating-pressed-background, ${t("--en-color-accent-subtle")})); color: var(--en-rating-pressed-color, ${t("--en-color-text")});`,
  },
  'combobox-trigger': {
    scale: css`var(--en-combobox-trigger-pressed-scale, 1)`,
    offset: css`var(--en-combobox-trigger-pressed-offset, 0px)`,
    press: css`var(--en-combobox-trigger-press-duration, ${t('--en-duration-press')})`,
    release: css`var(--en-combobox-trigger-release-duration, ${t('--en-duration-release')})`,
    shadow: css`var(--en-combobox-trigger-pressed-shadow, 0 0 0 0 transparent)`,
    paint: css`background: var(--en-combobox-trigger-pressed-background, ${t("--en-color-accent-subtle")}); color: var(--en-combobox-trigger-pressed-color, ${t("--en-color-text")});`,
  },
  'navigation': {
    scale: css`var(--en-navigation-pressed-scale, 1)`,
    offset: css`var(--en-navigation-pressed-offset, 0px)`,
    press: css`var(--en-navigation-press-duration, ${t('--en-duration-press')})`,
    release: css`var(--en-navigation-release-duration, ${t('--en-duration-release')})`,
    shadow: css`var(--en-navigation-pressed-shadow, 0 0 0 0 transparent)`,
    paint: css`background: var(--en-navigation-pressed-background, ${t("--en-color-accent-subtle")}); color: var(--en-navigation-pressed-color, ${t("--en-color-action-text")});`,
  },
  'editor-token': {
    scale: css`var(--en-editor-token-pressed-scale, 1)`,
    offset: css`var(--en-editor-token-pressed-offset, 0px)`,
    press: css`var(--en-editor-token-press-duration, ${t('--en-duration-press')})`,
    release: css`var(--en-editor-token-release-duration, ${t('--en-duration-release')})`,
    shadow: css`var(--en-editor-token-pressed-shadow, 0 0 0 0 transparent)`,
    paint: css`background: var(--en-editor-token-pressed-background, ${t("--en-color-accent-subtle")}); color: var(--en-editor-token-pressed-color, var(--en-editor-token-color, ${t("--en-color-text")})); border-color: var(--en-editor-token-pressed-border-color, var(--en-editor-token-border-color, ${t("--en-color-line")}));`,
  },
  'option': {
    scale: css`var(--en-option-pressed-scale, 1)`,
    offset: css`var(--en-option-pressed-offset, 0px)`,
    press: css`var(--en-option-press-duration, ${t('--en-duration-press')})`,
    release: css`var(--en-option-release-duration, ${t('--en-duration-release')})`,
    shadow: css`var(--en-option-pressed-shadow, 0 0 0 0 transparent)`,
    paint: css``,
  },
  'calendar': {
    scale: css`var(--en-calendar-pressed-scale, 1)`,
    offset: css`var(--en-calendar-pressed-offset, 0px)`,
    press: css`var(--en-calendar-press-duration, ${t('--en-duration-press')})`,
    release: css`var(--en-calendar-release-duration, ${t('--en-duration-release')})`,
    shadow: css`var(--en-calendar-pressed-shadow, 0 0 0 0 transparent)`,
    paint: css``,
  },
  'checkbox': {
    scale: css`var(--en-checkbox-pressed-scale, 1)`,
    offset: css`var(--en-checkbox-pressed-offset, 0px)`,
    press: css`var(--en-checkbox-press-duration, ${t('--en-duration-press')})`,
    release: css`var(--en-checkbox-release-duration, ${t('--en-duration-release')})`,
    shadow: css`var(--en-checkbox-pressed-shadow, inset 0 0 0 1px currentColor)`,
    paint: css`border-color: var(--en-checkbox-pressed-border-color, ${t("--en-color-action-pressed")});`,
  },
  'radio': {
    scale: css`var(--en-radio-pressed-scale, 1)`,
    offset: css`var(--en-radio-pressed-offset, 0px)`,
    press: css`var(--en-radio-press-duration, ${t('--en-duration-press')})`,
    release: css`var(--en-radio-release-duration, ${t('--en-duration-release')})`,
    shadow: css`var(--en-radio-pressed-shadow, inset 0 0 0 1px currentColor)`,
    paint: css`border-color: var(--en-radio-pressed-border-color, ${t("--en-color-action-pressed")});`,
  },
  'switch': {
    scale: css`var(--en-switch-pressed-scale, 1)`,
    offset: css`var(--en-switch-pressed-offset, 0px)`,
    press: css`var(--en-switch-press-duration, ${t('--en-duration-press')})`,
    release: css`var(--en-switch-release-duration, ${t('--en-duration-release')})`,
    shadow: css`var(--en-switch-pressed-shadow, inset 0 0 0 1px currentColor)`,
    paint: css`border-color: var(--en-switch-pressed-border-color, ${t("--en-color-action-pressed")});`,
  },
  'select': {
    scale: css`var(--en-select-pressed-scale, 1)`,
    offset: css`var(--en-select-pressed-offset, 0px)`,
    press: css`var(--en-select-press-duration, ${t('--en-duration-press')})`,
    release: css`var(--en-select-release-duration, ${t('--en-duration-release')})`,
    shadow: css`var(--en-select-pressed-shadow, 0 0 0 0 transparent)`,
    paint: css`background: var(--en-select-pressed-background, var(--en-input-background, ${t("--en-color-accent-subtle")})); color: var(--en-select-pressed-color, var(--en-input-color, ${t("--en-color-text")}));`,
  },
  'number-step': {
    scale: css`var(--en-number-step-pressed-scale, var(--en-button-pressed-scale, 1))`,
    offset: css`var(--en-number-step-pressed-offset, var(--en-button-pressed-offset, 0px))`,
    press: css`var(--en-number-step-press-duration, ${t('--en-duration-press')})`,
    release: css`var(--en-number-step-release-duration, ${t('--en-duration-release')})`,
    shadow: css`var(--en-number-step-pressed-shadow, 0 0 0 0 transparent)`,
    paint: css`background: var(--en-number-step-pressed-background, var(--en-button-pressed-background, ${t("--en-color-accent-subtle")}));`,
  },
} satisfies Record<string, PressRecipe>;
