import {test,expect,type Page} from '@playwright/test';
const mime='application/x-en-editor+json';
async function load(page:Page){await page.goto('/api-examples/rich-text.html');await expect(page.locator('#rich-brief').getByRole('textbox')).toHaveAttribute('contenteditable','true');await expect(page.locator('#plain-reply').getByRole('textbox')).toHaveAttribute('contenteditable','true');}
async function selectAll(page:Page,id:string){const box=page.locator('#'+id).getByRole('textbox');await box.focus();await box.press('ControlOrMeta+a');}
async function copy(page:Page,id:string,type='copy') {return page.locator('#'+id).getByRole('textbox').evaluate((el,type)=>{const values:Record<string,string>={};const data={setData:(key:string,value:string)=>values[key]=value,getData:(key:string)=>values[key]??''};const event=new Event(type,{bubbles:true,cancelable:true});Object.defineProperty(event,'clipboardData',{value:data});el.dispatchEvent(event);return values;},type);}
async function paste(page:Page,id:string,values:Record<string,string>){await page.locator('#'+id).getByRole('textbox').evaluate((el,values)=>{const event=new Event('paste',{bubbles:true,cancelable:true});Object.defineProperty(event,'clipboardData',{value:{getData:(key:string)=>values[key]??''}});el.dispatchEvent(event);},values);}
async function reset(page:Page,id:string,value=''){await page.locator('#'+id).evaluate((el:any,value)=>{el.value=value;el.focus();},value);await selectAll(page,id);}
test('structured token clipboard interoperates with rich editors and regenerates occurrence IDs',async({page})=>{
 await load(page);await reset(page,'plain-reply');const input=page.locator('#plain-reply').getByRole('textbox');await input.pressSequentially('@Cov');await page.locator('#plain-reply').getByRole('option',{name:'Cover study',exact:true}).waitFor();await input.press('Enter');await selectAll(page,'plain-reply');const data=await copy(page,'plain-reply');expect(data['text/plain']).toBe('@Cover study');expect(JSON.parse(data[mime]).version).toBe(1);
 await reset(page,'rich-brief');await paste(page,'rich-brief',data);await expect(page.locator('#rich-brief').locator('[data-token]')).toHaveCount(1);await paste(page,'rich-brief',data);await expect(page.locator('#rich-brief').locator('[data-token]')).toHaveCount(2);
 const ids=await page.locator('#rich-brief').locator('[data-token]').evaluateAll(els=>els.map(el=>(el as HTMLElement).dataset.token));expect(new Set(ids).size).toBe(2);expect(ids).not.toContain(JSON.parse(data[mime]).runs[0].id);
 await selectAll(page,'rich-brief');const back=await copy(page,'rich-brief');await reset(page,'plain-reply');await paste(page,'plain-reply',back);await expect(page.locator('#plain-reply').locator('[data-token]')).toHaveCount(2);await expect(page.locator('#plain-reply')).toHaveJSProperty('value','@Cover study@Cover study');
 await page.locator('#plain-reply').evaluate((el:any)=>el.undo());await expect(page.locator('#plain-reply')).toHaveJSProperty('value','');await page.locator('#plain-reply').evaluate((el:any)=>el.redo());await expect(page.locator('#plain-reply').locator('[data-token]')).toHaveCount(2);
});
test('rich clipboard retains bounded formatting, lists and safe links with one paste undo',async({page})=>{
 await load(page);await reset(page,'rich-brief');await paste(page,'rich-brief',{'text/plain':'Title\nBold italic link\nFirst\nSecond','text/html':'<h2>Title</h2><p><strong>Bold</strong> <em>italic</em> <a href="https://example.com">link</a></p><ul><li><p>First</p></li><li><p>Second</p></li></ul>'});
 await expect(page.locator('#rich-brief').locator('h2')).toHaveText('Title');await expect(page.locator('#rich-brief').locator('strong')).toHaveText('Bold');await expect(page.locator('#rich-brief').locator('li')).toHaveCount(2);await selectAll(page,'rich-brief');const data=await copy(page,'rich-brief');expect(data['text/html']).toContain('<strong>Bold</strong>');
 await reset(page,'rich-reply','Before');await paste(page,'rich-reply',data);await expect(page.locator('#rich-reply').locator('h2')).toHaveText('Title');await expect(page.locator('#rich-reply').locator('a')).toHaveAttribute('href','https://example.com');await page.locator('#rich-reply').evaluate((el:any)=>el.undo());await expect(page.locator('#rich-reply')).toHaveJSProperty('value','Before');await page.locator('#rich-reply').evaluate((el:any)=>el.redo());await expect(page.locator('#rich-reply').getByRole('textbox').locator('strong')).toHaveText('Bold');
 await reset(page,'plain-reply');await paste(page,'plain-reply',data);await expect(page.locator('#plain-reply')).toHaveJSProperty('value','Title\nBold italic link\nFirst\nSecond');await expect(page.locator('#plain-reply').getByRole('textbox').locator('strong')).toHaveCount(0);
});
test('unsafe HTML and malformed envelopes cannot introduce markup or unregistered tokens',async({page})=>{
 await load(page);await reset(page,'rich-brief');await paste(page,'rich-brief',{'text/plain':'Safe text','text/html':'<p onclick="alert(1)">Safe <b style="color:red">text</b><script>alert(1)</script><img src=x onerror="alert(1)"><a href="javascript:alert(1)">unsafe</a><span data-token="fake">plain</span></p>'});
 await expect(page.locator('#rich-brief').locator('script,img,[onclick],[style],a,[data-token]')).toHaveCount(0);await expect(page.locator('#rich-brief')).toHaveJSProperty('value','Safe textunsafeplain');
 const token={kind:'token',id:'untrusted',type:'not-installed',text:'@readable',label:'Readable',data:{id:1}};
 const envelope={type:'en-editor-clipboard',version:1,runs:[token]};
 for(const id of ['plain-reply','rich-brief']){await reset(page,id);await paste(page,id,{[mime]:JSON.stringify(envelope),'text/plain':'fallback'});await expect(page.locator('#'+id)).toHaveJSProperty('value','@readable');await expect(page.locator('#'+id).locator('[data-token]')).toHaveCount(0);
  for(const raw of ['{broken',JSON.stringify({...envelope,version:9}),JSON.stringify({...envelope,runs:[{...token,label:42}]}),JSON.stringify({...envelope,runs:[token,token]}),JSON.stringify({...envelope,runs:[{kind:'text',text:'x'.repeat(1_000_001)}]})]){await reset(page,id);await paste(page,id,{[mime]:raw,'text/plain':'fallback'});await expect(page.locator('#'+id)).toHaveJSProperty('value','fallback');}}
 await reset(page,'rich-brief');await paste(page,'rich-brief',{[mime]:JSON.stringify({...envelope,rich:{content:[{type:'paragraph',content:[{type:'text',text:'Bad',marks:[{type:'link',attrs:{href:'javascript:alert(1)'}}]}]}]}}),'text/plain':'fallback'});await expect(page.locator('#rich-brief')).toHaveJSProperty('value','fallback');
});
test('cut and paste respect cancellation, author writes, readonly and one-step undo',async({page})=>{
 await load(page);
 for(const id of ['plain-reply','rich-brief']){
  await reset(page,id,'Original');await page.locator('#'+id).evaluate(el=>el.addEventListener('en-change',e=>e.preventDefault(),{once:true}));const cut=await copy(page,id,'cut');expect(cut['text/plain']).toBe('Original');await expect(page.locator('#'+id)).toHaveJSProperty('value','Original');
  await copy(page,id,'cut');await expect(page.locator('#'+id)).toHaveJSProperty('value','');await page.locator('#'+id).evaluate((el:any)=>el.undo());await expect(page.locator('#'+id)).toHaveJSProperty('value','Original');
  await selectAll(page,id);await page.locator('#'+id).evaluate(el=>el.addEventListener('en-change',e=>e.preventDefault(),{once:true}));await paste(page,id,{'text/plain':'Rejected'});await expect(page.locator('#'+id)).toHaveJSProperty('value','Original');
  await page.locator('#'+id).evaluate((el:any)=>el.addEventListener('en-change',()=>{el.value='Author wins';},{once:true}));await paste(page,id,{'text/plain':'Stale'});await expect(page.locator('#'+id)).toHaveJSProperty('value','Author wins');
  await selectAll(page,id);await page.locator('#'+id).evaluate((el:any)=>el.readOnly=true);await paste(page,id,{'text/plain':'Disallowed'});await copy(page,id,'cut');await expect(page.locator('#'+id)).toHaveJSProperty('value','Author wins');await page.locator('#'+id).evaluate((el:any)=>el.readOnly=false);
 }
});
