import {chromium,firefox,webkit} from '@playwright/test';import {mkdir,readFile,writeFile,appendFile} from 'node:fs/promises';import {resolve} from 'node:path';import os from 'node:os';import {createHash} from 'node:crypto';import assert from 'node:assert/strict';
import {serve} from './server.mjs';import {installMilestones} from './milestones.mjs';import {installProbe} from './browser-probe.mjs';import {exclusiveBrowserWork} from '../../../showcases/performance/src/lock.mjs';import {rng,shuffle} from '../../../showcases/performance/src/config.mjs';
const qualify=process.argv.includes('--qualify'),policies=['intent','route','eager'];const run=process.argv.find(a=>a.startsWith('--run='))?.slice(6)??(qualify?'qualification':'campaign');const base=resolve('artifacts/scoped-registry-phase-4-followup'),out=resolve(base,run);await mkdir(out,{recursive:true});await writeFile(resolve(out,'started.json'),JSON.stringify({at:new Date().toISOString(),qualify}),{flag:'wx'});const sha=b=>createHash('sha256').update(b).digest('hex');
const receipts=await Promise.all(policies.map(async policy=>({...JSON.parse(await readFile(resolve(base,policy,'receipt.json'))),policy})));async function verify(){for(const r of receipts)for(const a of r.assets)assert.equal(sha(await readFile(resolve(base,r.policy,'site',a.path))),a.sha256,'Build mutated');}await verify();
const configs=[...['chromium','firefox','webkit'].map(browser=>({browser,profile:'desktop',input:'keyboard'})),{browser:'chromium',profile:'constrained',input:'keyboard'},{browser:'chromium',profile:'constrained-mobile',input:'touch'},{browser:'chromium',profile:'constrained',input:'abandon'}];const cells=policies.flatMap(policy=>configs.map(c=>({...c,policy})));const random=rng(20261002),jobs=[];for(let block=0;block<(qualify?1:30);block++)jobs.push(...shuffle(cells,random).map(x=>({...x,block,kind:'timing'})));for(let block=0;block<(qualify?1:5);block++)jobs.push(...shuffle(policies,random).map(policy=>({policy,browser:'chromium',profile:'desktop',input:'keyboard',block,kind:'retention'})));
await writeFile(resolve(out,'manifest.json'),JSON.stringify({createdAt:new Date().toISOString(),qualify,jobs,receipts:receipts.map(r=>({policy:r.policy,sourceDigest:r.sourceDigest,assetsDigest:r.assetsDigest})),host:{cpu:os.cpus()[0].model,platform:os.platform(),release:os.release(),node:process.version},protocolSha256:sha(await readFile(resolve(base,'protocol.md'))),harness:await Promise.all(['campaign.mjs','server.mjs','milestones.mjs','browser-probe.mjs'].map(async name=>({name,sha256:sha(await readFile(resolve(import.meta.dirname,name)))})))},null,2)+'\n');
await exclusiveBrowserWork(async()=>{const servers=new Map();for(const policy of policies)servers.set(policy,await serve(policy));try{for(const [index,job]of jobs.entries()){
 const browser=await ({chromium,firefox,webkit})[job.browser].launch(),errors=[],failures=[];try{
 const mobile=job.input==='touch';const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1280,height:900},...(mobile?{hasTouch:true,isMobile:true}:{}),serviceWorkers:'block',ignoreHTTPSErrors:true});await context.addInitScript(input=>{window.__studyInput=input;},job.input);await context.addInitScript(installProbe);await context.addInitScript(installMilestones);const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failures.push({url:r.url(),status:r.status()});});page.on('requestfailed',r=>failures.push({url:r.url(),error:r.failure()?.errorText}));const cdp=job.browser==='chromium'?await context.newCDPSession(page):null;
 if(job.profile.startsWith('constrained')){await cdp.send('Emulation.setCPUThrottlingRate',{rate:4});await cdp.send('Network.enable');await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:150,downloadThroughput:1600000/8,uploadThroughput:750000/8});}
 const response=await page.goto(servers.get(job.policy).url+'/workflows/settings.html',{waitUntil:'load',timeout:60000});await page.waitForFunction(()=>!!window.__deliveryProbe.startup,{},{timeout:30000});const startup=await page.evaluate(()=>__deliveryProbe.startup);assert.equal(startup.paletteDefined,job.policy==='eager');assert.equal(startup.paletteCount,1);assert.equal(startup.triggerCount,1);assert(startup.ssrMarkerRemoved);assert.equal(response.headers()['content-encoding'],'gzip');assert(startup.resources.filter(r=>r.name.endsWith('.js')).every(r=>r.protocol==='h2'));await page.evaluate(()=>__activationMilestones.attach());const trigger=page.getByRole('button',{name:'Search commands',exact:true});
 const beforeAction=await page.evaluate(()=>__deliveryProbe.snapshot());let action=null,activation=null,second=null,abandoned=null,unused=null,checkpoints=null;
 if(job.input==='abandon'){
  await page.waitForTimeout(500);unused=await page.evaluate(()=>({...__deliveryProbe.snapshot(),defined:!!customElements.get('en-command-palette'),open:!!document.querySelector('#settings-command-palette').open}));assert.equal(unused.open,false);assert.equal(unused.defined,job.policy==='eager');
  await trigger.focus();await trigger.evaluate(el=>el.blur());await page.waitForTimeout(500);
  abandoned=await page.evaluate(()=>({atMs:performance.now(),defined:!!customElements.get('en-command-palette'),open:!!document.querySelector('#settings-command-palette').open,status:document.querySelector('#settings-command-status').textContent,busy:document.querySelector('#settings-command-trigger').getAttribute('aria-busy'),focusId:document.activeElement?.id??'',snapshot:__deliveryProbe.snapshot()}));assert.equal(abandoned.defined,job.policy==='eager');assert.equal(abandoned.open,false);assert.equal(abandoned.status,'');assert.equal(abandoned.busy,'false');
 }else{
  if(mobile)await trigger.tap();else await trigger.press('Enter');action=await page.evaluate(()=>__deliveryProbe.actionPromise);activation=await page.evaluate(()=>__activationMilestones.finish());assert(action?.focusInside);assert.notEqual(activation.focusMs,null);await page.getByRole('dialog',{name:'Settings commands',exact:true}).waitFor({state:'visible'});
  await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('#settings-command-palette').open);if(mobile)await trigger.tap();else await trigger.press('Enter');second=await page.evaluate(()=>__deliveryProbe.actionPromise);await page.evaluate(()=>{__activationMilestones.finish();return __deliveryProbe.close();});
 }
 const after=await page.evaluate(()=>__deliveryProbe.snapshot());await page.evaluate(()=>__activationMilestones.detach());
 if(job.kind==='retention'){checkpoints=[];for(let cycle=0;cycle<=100;cycle++){if(cycle>0)await page.evaluate(async()=>{await __deliveryProbe.remount();await __deliveryProbe.openSynthetic();await __deliveryProbe.close();});if([0,10,50,100].includes(cycle)){await cdp.send('HeapProfiler.collectGarbage');await cdp.send('HeapProfiler.collectGarbage');const heap=await cdp.send('Runtime.getHeapUsage'),dom=await cdp.send('Memory.getDOMCounters');checkpoints.push({cycle,heapBytes:heap.usedSize,dom,apps:await page.locator('en-workflows-app').count()});}}}
 errors.push(...await page.evaluate(()=>__deliveryProbe.errors));assert.deepEqual(errors,[]);assert.deepEqual(failures,[]);
 const metrics={readyMs:startup.readyMs,fcpMs:startup.fcpMs,firstUseMs:action?.firstUseMs??null,firstFocusMs:activation?.focusMs??null,firstDefinedMs:activation?.definedMs??null,navigationToFocusMs:activation?activation.start+activation.focusMs:null,navigationToReadyMs:action?action.actionStartMs+action.firstUseMs:null,secondUseMs:second?.firstUseMs??null,startupJSBytes:startup.jsBytes,startupJSRequests:startup.jsRequests,totalJSBytes:after.jsBytes,totalJSRequests:after.jsRequests,postStartupJSBytes:after.jsBytes-startup.jsBytes,htmlBytes:startup.htmlBytes,unusedJSBytes:unused?.jsBytes??null,unusedJSRequests:unused?.jsRequests??null,unusedPostStartupJSBytes:unused?unused.jsBytes-startup.jsBytes:null,unusedWindowMs:unused?unused.atMs-beforeAction.atMs:null,abandonWindowMs:abandoned?abandoned.atMs-beforeAction.atMs:null};
 await appendFile(resolve(out,'samples.jsonl'),JSON.stringify({...job,status:'ok',browserVersion:browser.version(),metrics,startup,beforeAction,action,activation,second,abandoned,unused,checkpoints,errors,failures})+'\n');console.log(`${index+1}/${jobs.length} ${job.policy}/${job.browser}/${job.profile}/${job.input}/${job.kind} startup=${metrics.readyMs.toFixed(1)} first=${metrics.firstUseMs?.toFixed(1)??'-'}`);
 }catch(error){await writeFile(resolve(out,'failure.json'),JSON.stringify({job,error:String(error),stack:error.stack,errors,failures},null,2));throw error;}finally{await browser.close();}
 }}finally{for(const s of servers.values())await s.close();}});await verify();await writeFile(resolve(out,'summary.json'),JSON.stringify({at:new Date().toISOString(),passed:jobs.length,failed:0,timing:jobs.filter(j=>j.kind==='timing').length,retention:jobs.filter(j=>j.kind==='retention').length,configurations:cells.length,qualify},null,2)+'\n');
