import {readFile,writeFile,mkdir,cp,readdir,stat,chmod,rename} from 'node:fs/promises';import {resolve,relative} from 'node:path';import {createHash} from 'node:crypto';import assert from 'node:assert/strict';
const base=resolve('artifacts/scoped-registry-phase-4-followup'),target=resolve('showcases/performance/baselines/scoped-registry-phase-4-followup-v1'),pending=target+'.pending',sha=b=>createHash('sha256').update(b).digest('hex');
async function verify(dir){const seal=JSON.parse(await readFile(resolve(dir,'seal.json')));assert.equal(sha(await readFile(resolve(dir,'checksums.json'))),seal.checksumsSha256);const rows=JSON.parse(await readFile(resolve(dir,'checksums.json'))).files;for(const row of rows)assert.equal(sha(await readFile(resolve(dir,row.path))),row.sha256,row.path);return {path:dir,seal:seal.checksumsSha256,verifiedFiles:rows.length};}
if(process.argv.includes('--verify')){console.log(await verify(target));process.exit();}assert.equal(await stat(target).catch(()=>null),null);assert.equal(await stat(pending).catch(()=>null),null);
const manifest=JSON.parse(await readFile(resolve(base,'campaign/manifest.json')));assert.equal(JSON.parse(await readFile(resolve(base,'campaign/summary.json'))).passed,555);assert.equal(JSON.parse(await readFile(resolve(base,'functional.json'))).passed,33);assert.equal(sha(await readFile(resolve(base,'protocol.md'))),manifest.protocolSha256);for(const h of manifest.harness)assert.equal(sha(await readFile(resolve('probes/production-registry/phase4-followup',h.name))),h.sha256);
const support=JSON.parse(await readFile(resolve(base,'support-before.json')));for(const h of support){const audit=JSON.parse(await readFile(resolve(base,'support-audit.json')));assert.equal(sha(await readFile(h.path)),h.path===audit.changedPath?audit.afterSha256:h.sha256);}
await mkdir(pending);for(const e of await readdir(base,{withFileTypes:true})){if(e.isFile()&&/\.(json|log|md|txt|patch|mjs)$/.test(e.name))await cp(resolve(base,e.name),resolve(pending,e.name));else if(e.isDirectory()&&/^(campaign|qualification)/.test(e.name))await cp(resolve(base,e.name),resolve(pending,e.name),{recursive:true});}await cp('probes/production-registry/phase4-followup',resolve(pending,'harness'),{recursive:true});
for(const h of support){const dest=resolve(pending,'support',h.path);await mkdir(resolve(dest,'..'),{recursive:true});await cp(h.path,dest);}
for(const policy of ['intent','route','eager','eager-preflight-wrapper']){const dir=resolve(base,policy),dest=resolve(pending,policy),receipt=JSON.parse(await readFile(resolve(dir,'receipt.json')));if(policy!=='eager-preflight-wrapper'){const m=manifest.receipts.find(r=>r.policy===policy);assert.equal(receipt.sourceDigest,m.sourceDigest);assert.equal(receipt.assetsDigest,m.assetsDigest);for(const a of receipt.assets)assert.equal(sha(await readFile(resolve(dir,'site',a.path))),a.sha256);}await mkdir(dest);for(const name of ['receipt.json','source-final.json','source.tar.gz','site.tar.gz',...(policy!=='intent'?['build.log','typecheck.log']:[])])await cp(resolve(dir,name),resolve(dest,name));}
await writeFile(resolve(pending,'previous-seal.json'),JSON.stringify(await verify(resolve('showcases/performance/baselines/scoped-registry-phase-4-v1')),null,2)+'\n');await writeFile(resolve(pending,'baseline.json'),JSON.stringify({name:'scoped-registry-phase-4-followup-v1',status:'frozen',at:new Date().toISOString(),samples:540,interactionTimings:450,abandonedObservations:90,configurations:18,minimumSamples:30,retentionRuns:15,repetitionsPerPolicy:5,productionDefaultUnchanged:true,manualScreenReaderReview:'outstanding'},null,2)+'\n');
async function walk(dir){const files=[];for(const e of await readdir(dir,{withFileTypes:true})){assert(!e.isSymbolicLink());const p=resolve(dir,e.name);files.push(...(e.isDirectory()?await walk(p):[p]));}return files.sort();}const files=[];for(const p of await walk(pending)){const b=await readFile(p);files.push({path:relative(pending,p),bytes:b.length,sha256:sha(b)});}await writeFile(resolve(pending,'checksums.json'),JSON.stringify({algorithm:'sha256',files},null,2)+'\n');await writeFile(resolve(pending,'seal.json'),JSON.stringify({algorithm:'sha256',checksumsSha256:sha(await readFile(resolve(pending,'checksums.json')))},null,2)+'\n');await verify(pending);for(const p of await walk(pending))await chmod(p,0o444);await rename(pending,target);console.log(await verify(target));
