import {execFileSync,spawnSync} from 'node:child_process';
import {mkdir,readFile,writeFile,readdir,symlink,cp,stat} from 'node:fs/promises';
import {resolve} from 'node:path';import {createHash} from 'node:crypto';import assert from 'node:assert/strict';
const root=resolve(import.meta.dirname,'../../..'),base=resolve(root,'artifacts/scoped-registry-phase-4-followup'),original=resolve(root,'artifacts/scoped-registry-phase-4/candidate'),frozen=resolve(root,'showcases/performance/baselines/scoped-registry-phase-4-v1');
const sha=b=>createHash('sha256').update(b).digest('hex');
const seal=JSON.parse(await readFile(resolve(frozen,'seal.json')));assert.equal(sha(await readFile(resolve(frozen,'checksums.json'))),seal.checksumsSha256);
for(const f of JSON.parse(await readFile(resolve(frozen,'checksums.json'))).files)assert.equal(sha(await readFile(resolve(frozen,f.path))),f.sha256,f.path);
const prior=JSON.parse(await readFile(resolve(original,'receipt.json')));for(const a of prior.assets)assert.equal(sha(await readFile(resolve(original,'site',a.path))),a.sha256);
assert.equal(sha(await readFile(resolve(original,'source.tar.gz'))),sha(await readFile(resolve(frozen,'candidate/source.tar.gz'))));
async function inventory(dir,prefix=''){const result=[];for(const e of (await readdir(dir,{withFileTypes:true})).sort((a,b)=>a.name.localeCompare(b.name))){if(e.name==='node_modules'||e.name==='.git'||(!prefix&&e.name==='dist'))continue;const path=resolve(dir,e.name),name=prefix+e.name;if(e.isDirectory())result.push(...await inventory(path,name+'/'));else if(e.isFile()){const b=await readFile(path);result.push({path:name,bytes:b.length,sha256:sha(b)});}}return result;}
for(const policy of (process.argv.includes('--eager-only')?['eager']:['intent','route','eager'])){
 const dest=resolve(base,policy),stage=resolve(dest,'source');assert.equal(await stat(dest).catch(()=>null),null,'Refuse overwrite');await mkdir(dest,{recursive:true});
 if(policy==='intent'){for(const file of ['source.tar.gz','site.tar.gz','source-final.json'])await cp(resolve(original,file),resolve(dest,file));await cp(resolve(original,'site'),resolve(dest,'site'),{recursive:true});await writeFile(resolve(dest,'receipt.json'),JSON.stringify({...prior,policy,originSeal:seal.checksumsSha256},null,2)+'\n');continue;}
 await mkdir(stage);execFileSync('tar',['-xzf',resolve(original,'source.tar.gz'),'-C',stage]);execFileSync('chmod',['-R','u+w',stage]);
 const entry='apps/docs/src/workflow-pages/settings-entry.ts',before=await readFile(resolve(stage,entry),'utf8');
 const after=policy==='route'?before.replace("import { createSettingsWorkflowApp }", "// Route-entry preparation is load-only and never delays workflow hydration.\nvoid commands.load(['en-command-palette']).catch(() => { /* Explicit opening owns retry and error feedback. */ });\nimport { createSettingsWorkflowApp }"):before.replace(/import \{createDefinitionLoader\}[\s\S]*?\n\}\);/, "import '@en-reve/elements/define/command-palette.js';").replace(", options => commands.ensure(['en-command-palette'], options), async options => { await commands.load(['en-command-palette'], options); }",'');assert.notEqual(after,before);await writeFile(resolve(stage,entry),after);
 await mkdir(resolve(stage,'node_modules/@en-reve'),{recursive:true});for(const name of await readdir(resolve(root,'node_modules')))if(name!=='@en-reve'&&!name.startsWith('.'))await symlink(resolve(root,'node_modules',name),resolve(stage,'node_modules',name));for(const name of ['elements','primitives','styles','tokens','ssr'])await symlink(resolve(stage,'packages',name),resolve(stage,'node_modules/@en-reve',name));
 const check=spawnSync(process.execPath,[resolve(root,'node_modules/typescript/bin/tsc'),'--noEmit','-p','apps/docs/tsconfig.json'],{cwd:stage,encoding:'utf8'});await writeFile(resolve(dest,'typecheck.log'),check.stdout+'\n'+check.stderr);assert.equal(check.status,0);
 const build=spawnSync(process.execPath,['apps/docs/scripts/build-ssr.mjs'],{cwd:stage,encoding:'utf8',maxBuffer:100*1024*1024});await writeFile(resolve(dest,'build.log'),build.stdout+'\n'+build.stderr);assert.equal(build.status,0);await cp(resolve(stage,'dist'),resolve(dest,'site'),{recursive:true});
 const source=await inventory(stage),assets=await inventory(resolve(dest,'site'));const sourceControl=JSON.parse(await readFile(resolve(original,'source-final.json')));const changed=source.filter(f=>sourceControl.find(p=>p.path===f.path)?.sha256!==f.sha256);assert.deepEqual(changed.map(f=>f.path),[entry]);
 const receipt={policy,originSeal:seal.checksumsSha256,sourceDigest:sha(JSON.stringify(source)),assetsDigest:sha(JSON.stringify(assets)),assets,overlays:[{path:entry,before:sha(before),sha256:sha(after)}],viteConfigSha256:sha(await readFile(resolve(stage,'apps/docs/vite.config.ts'))),dependencyLockSha256:sha(await readFile(resolve(stage,'package-lock.json'))),note:'Frozen Phase 4 source and compiled library; only settings-entry.ts changes. Full unchanged Vite/SSR pipeline. Production workspace default untouched.'};assert.equal(receipt.viteConfigSha256,prior.viteConfigSha256);assert.equal(receipt.dependencyLockSha256,prior.dependencyLockSha256);
 await writeFile(resolve(dest,'source-final.json'),JSON.stringify(source,null,2)+'\n');await writeFile(resolve(dest,'receipt.json'),JSON.stringify(receipt,null,2)+'\n');execFileSync('tar',['-czf',resolve(dest,'source.tar.gz'),'--exclude=*/node_modules','-C',stage,...(await readdir(stage)).filter(n=>n!=='node_modules'&&n!=='dist')]);execFileSync('tar',['-czf',resolve(dest,'site.tar.gz'),'-C',resolve(dest,'site'),'.']);console.log(JSON.stringify({policy,sourceDigest:receipt.sourceDigest,assetsDigest:receipt.assetsDigest,changedFiles:changed.length}));
}
