import { test, expect } from '@playwright/test';

test('medium needs no attribute; explicit inheritance and concrete scopes remain available', async ({ page }) => {
  await page.goto('/packages/elements/src/internal/tests/size-fixture.html');
  const parent = page.locator('#parent');
  const child = page.locator('#child');
  const root = page.locator('#root');
  await expect(parent).toHaveJSProperty('size', 'medium');
  await expect(parent).not.toHaveAttribute('size');
  await expect(child).not.toHaveAttribute('size');
  await expect(root).toHaveCSS('font-size', '20px');
  await expect(parent).toHaveCSS('font-size', '20px');
  await expect(child).toHaveCSS('font-size', '20px');
  await parent.evaluate((host: any) => { host.size = 'small'; });
  await expect(parent).toHaveAttribute('size', 'small');
  await expect(parent).toHaveCSS('font-size', '10px');
  await expect(child).toHaveCSS('font-size', '20px');
  await child.evaluate((host: any) => { host.size = 'inherit'; });
  await expect(child).toHaveAttribute('size', 'inherit');
  await expect(child).toHaveJSProperty('size', 'inherit');
  await expect(child).toHaveCSS('font-size', '10px');
  await child.evaluate((host: any) => { host.size = 'large'; });
  await expect(child).toHaveCSS('font-size', '30px');
  await parent.evaluate((host: any) => { host.size = 'large'; });
  await expect(child).toHaveCSS('font-size', '30px');
  await child.evaluate((host: any) => host.removeAttribute('size'));
  await expect(child).not.toHaveAttribute('size');
  await expect(child).toHaveJSProperty('size', 'medium');
  await expect(child).toHaveCSS('font-size', '20px');
  await child.evaluate((host: any) => { host.size = 'medium'; });
  await expect(child).toHaveAttribute('size', 'medium');
  await child.evaluate((host: any) => host.setAttribute('size', 'small'));
  await expect(child).toHaveJSProperty('size', 'small');
  await expect(child).toHaveCSS('font-size', '10px');
  await child.evaluate((host: any) => { host.size = 'invalid'; });
  await expect(child).toHaveAttribute('size', 'medium');
  await expect(child).toHaveCSS('font-size', '20px');
  await child.evaluate((host: any) => host.setAttribute('size', 'invalid'));
  await expect(child).toHaveJSProperty('size', 'medium');
  await expect(child).toHaveCSS('font-size', '20px');
  await child.evaluate((host: any) => { host.size = 'medium'; });
  await expect(child).toHaveAttribute('size', 'medium');
});
