import {execFileSync} from 'node:child_process';
import {singlePackOutput} from '../../tooling/test-pipeline/npm-pack.mjs';
import {mkdir, readFile, writeFile, mkdtemp, readdir, symlink, cp, rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {resolve, relative} from 'node:path';
import {createHash} from 'node:crypto';
import {pathToFileURL} from 'node:url';
import {build} from '../../showcases/performance/node_modules/esbuild/lib/main.js';
const root = resolve(import.meta.dirname, '../..');
const out = resolve(root, process.env.EN_CONSUMER_CONTRACTS_OUT ?? 'artifacts/scoped-followup-consumer-contracts');
const site = resolve(out, 'site');
const stage = await mkdtemp(resolve(tmpdir(), 'en-consumer-contracts-'));
const packages = [];
await rm(site, {recursive:true,force:true});
await mkdir(site, {recursive:true});
for (const name of ['elements','primitives','styles','tokens','ssr']) {
  const archive = singlePackOutput(execFileSync('npm', ['pack','--ignore-scripts','--offline','--json','--cache',resolve(stage,'cache'),'--pack-destination',stage], {cwd:resolve(root,'packages',name),encoding:'utf8'}), '@en-reve/'+name);
  const destination = resolve(stage,'node_modules/@en-reve',name);
  await mkdir(destination,{recursive:true});
  execFileSync('tar',['-xzf',resolve(stage,archive.filename),'-C',destination,'--strip-components=1']);
  packages.push({name,integrity:archive.integrity,shasum:archive.shasum});
}
for (const name of await readdir(resolve(root,'node_modules'))) if (name !== '@en-reve' && !name.startsWith('.')) await symlink(resolve(root,'node_modules',name),resolve(stage,'node_modules',name));
await writeFile(resolve(stage,'package.json'),' {"type":"module"}\n');
for (const name of ['recipes','entry','ssr-entry','ssr-module','public.types']) await cp(resolve(import.meta.dirname,`${name}.ts`),resolve(stage,`${name}.ts`));
execFileSync(process.execPath, [resolve(root,'node_modules/typescript/bin/tsc'),'--ignoreConfig','--strict','--noEmit','--target','ES2022','--module','NodeNext','--moduleResolution','NodeNext','--skipLibCheck','entry.ts','ssr-entry.ts','ssr-module.ts','public.types.ts'], {cwd:stage,stdio:'inherit'});
const result = await build({entryPoints:{entry:resolve(stage,'entry.ts'),ssr:resolve(stage,'ssr-entry.ts')},outdir:site,bundle:true,splitting:true,format:'esm',platform:'browser',target:'es2022',minify:true,metafile:true,chunkNames:'chunks/[name]-[hash]'});
const outputs = result.metafile.outputs;
const closure = (file, seen = new Set()) => { if(seen.has(file)) return seen; seen.add(file); for(const dep of outputs[file].imports) if(dep.kind !== 'dynamic-import' && !dep.external) closure(dep.path,seen); return seen; };
const inputsFor = file => [...new Set([...closure(file)].flatMap(f => Object.keys(outputs[f].inputs)))];
const startup = Object.fromEntries(['entry','ssr'].map(name => {const file=Object.keys(outputs).find(f=>f.endsWith(`/${name}.js`));return [name,{files:[...closure(file)],inputs:inputsFor(file)}];}));
if (Object.keys(result.metafile.inputs).some(p=>/\/packages\/.*\/src\//.test(p) || /elements\/dist\/(define\/|catalog\.js|index\.js|lazy\.js)/.test(p))) throw Error('Workspace source or broad/eager entry in consumer bundle');
for(const value of Object.values(startup)) if(value.inputs.some(p=>/elements\/dist\/(card|toast|text-field)|lit-element\//.test(p))) throw Error('Optional component or LitElement leaked into startup');
const toast = Object.keys(outputs).find(f=>outputs[f].entryPoint?.endsWith('/definitions/toast-region.js'));
if(!toast || !inputsFor(toast).some(p=>p.endsWith('/elements/dist/toast.js'))) throw Error('Toast hard dependency closure not emitted');
if(Object.keys(result.metafile.inputs).some(p=>/elements\/dist\/(calendar|command-palette)/.test(p))) throw Error('Unselected family was emitted');
// Node render entry resolves the same packed packages; fresh workers load this public-only module.
await build({entryPoints:[resolve(stage,'ssr-module.ts')],outfile:resolve(stage,'ssr-module.js'),bundle:true,packages:'external',format:'esm',platform:'node',target:'es2022'});
await writeFile(resolve(stage,'render.mjs'),`import {createScopedRenderer,renderIslandMarkup,serializeHydrationManifest} from '@en-reve/ssr/scoped.js';
export async function renderPages(){const renderer=createScopedRenderer({form:{module:new URL('./ssr-module.js',import.meta.url),version:'consumer-v1'}});try{const [a,b]=await Promise.all([renderer.render({key:'form',snapshot:{message:'Initial'}}),renderer.render({key:'form',snapshot:{message:'Other request'}})]);if(!a.html.includes('Initial')||a.html.includes('Other request')||!b.html.includes('Other request')||b.html.includes('Initial')||globalThis.customElements?.get('en-text-field'))throw Error('Request isolation failed');return {requestIsolation:{snapshots:['Initial','Other request'],first:a.html,second:b.html,callerRegistryUntouched:!globalThis.customElements?.get('en-text-field')},pages:['shadow','global'].map(mode=>{const island=renderIslandMarkup(a,'form-island',mode);return {mode,...island,serialized:serializeHydrationManifest(island.manifest)};})};}finally{renderer.dispose();}}`);
const {renderPages} = await import(pathToFileURL(resolve(stage,'render.mjs')));
const {pages,requestIsolation} = await renderPages();
const requestEvidence = {snapshots:requestIsolation.snapshots, callerRegistryUntouched:requestIsolation.callerRegistryUntouched, distinctHTML:requestIsolation.first !== requestIsolation.second, htmlSHA256:[requestIsolation.first,requestIsolation.second].map(html=>createHash('sha256').update(html).digest('hex'))};
const head = '<!doctype html><html lang="en"><meta charset="UTF-8"><meta name="viewport" content="width=device-width"><title>Packed consumer contracts</title><style>body{font:1rem system-ui;max-width:50rem;margin:2rem auto;padding:1rem}button,input{font:inherit;margin:.4rem}#report{position:fixed;bottom:1rem;right:1rem}</style><body><h1>Packed consumer contracts</h1><p id="mode"></p>';
const reportLink = `<script>if(new URLSearchParams(location.search).has('progress-report')){const a=document.createElement('a');a.id='report';a.href='http://127.0.0.1:4177';a.textContent='Progress Report';document.body.append(a);}</script>`;
await writeFile(resolve(site,'index.html'),head+'<form><label>Essential draft <input name="draft" value="Keep this" required></label><button type="reset">Reset</button></form><button id="activate">Load optional details</button><button id="cancel">Cancel</button><p id="status" role="status">Optional details available.</p><p><a id="eager" href="?eager">Use eager delivery on reload</a></p><div id="optional"></div><script type="module" src="./entry.js"></script>'+reportLink+`<script>const p=new URLSearchParams(location.search);p.set('eager','');document.querySelector('#eager').search=p.toString();</script>`);
for(const p of pages) await writeFile(resolve(site,`ssr-${p.mode}.html`),head+p.html+`<button id="hydrate">Enhance form</button><script id="manifest" type="application/json">${p.serialized}</script><script type="module" src="./ssr.js"></script>`+reportLink);
await writeFile(resolve(out,'metafile.json'),JSON.stringify(result.metafile,null,2)+'\n');
const hashes = Object.fromEntries(await Promise.all(Object.keys(outputs).map(async f=>[relative(site,resolve(f)),createHash('sha256').update(await readFile(f)).digest('hex')])));
await writeFile(resolve(out,'packed.json'),JSON.stringify({packages,stage,types:'passed',production:{minify:true,splitting:true,format:'esm',startup,toastClosure:inputsFor(toast),hashes},ssr:{requestIsolation:requestEvidence, htmlSHA256:Object.fromEntries(await Promise.all(pages.map(async p=>[p.mode,createHash('sha256').update(await readFile(resolve(site,`ssr-${p.mode}.html`))).digest('hex')])))},note:'No timings or retail-browser support inference. All @en-reve runtime and declaration inputs come from tarballs.'},null,2)+'\n');
console.log('Packed types, production graph and request isolation passed. '+site);
