import "@en-reve/elements/define/accordion.js";
import "@en-reve/elements/define/accordion-item.js";
import "@en-reve/elements/define/avatar.js";
import "@en-reve/elements/define/badge.js";
import "@en-reve/elements/define/breadcrumbs.js";
import "@en-reve/elements/define/button.js";
import "@en-reve/elements/define/card.js";
import "@en-reve/elements/define/checkbox.js";
import "@en-reve/elements/define/color-field.js";
import "@en-reve/elements/define/combobox.js";
import "@en-reve/elements/define/command-palette.js";
import "@en-reve/elements/define/date-picker.js";
import "@en-reve/elements/define/dialog.js";
import "@en-reve/elements/define/drawer.js";
import "@en-reve/elements/define/icon.js";
import "@en-reve/elements/define/menu.js";
import "@en-reve/elements/define/menu-item.js";
import "@en-reve/elements/define/navigation.js";
import "@en-reve/elements/define/number-field.js";
import "@en-reve/elements/define/popover.js";
import "@en-reve/elements/define/progress-bar.js";
import "@en-reve/elements/define/radio.js";
import "@en-reve/elements/define/radio-group.js";
import "@en-reve/elements/define/rating.js";
import "@en-reve/elements/define/segmented-control.js";
import "@en-reve/elements/define/segmented-item.js";
import "@en-reve/elements/define/select.js";
import "@en-reve/elements/define/select-option.js";
import "@en-reve/elements/define/slider.js";
import "@en-reve/elements/define/stack.js";
import "@en-reve/elements/define/swatch.js";
import "@en-reve/elements/define/switch.js";
import "@en-reve/elements/define/tab.js";
import "@en-reve/elements/define/tab-panel.js";
import "@en-reve/elements/define/tabs.js";
import "@en-reve/elements/define/text-field.js";
import "@en-reve/elements/define/textarea.js";
import "@en-reve/elements/define/toolbar.js";
import { ShowcaseApp } from "./app.ts";
import "./theme.css";
import "./base.css";
import "./styles.css";
import "../../shared/progress.js";
customElements.define("en-showcase-app", ShowcaseApp);
document
  .getElementById("root")
  .append(document.createElement("en-showcase-app"));
