/** Reviewable activation policy. Historical recipes remain visible, never silently run against current outputs. */
export const workloadFamilies = [
  {id:'library-correctness',tier:'correctness',pathway:'correctness',sourceRoots:['packages','apps/docs','tooling','probes'],
   obligations:'Every maintained Node assertion source, production/test/consumer type gate, direct current-library verifier and Playwright configuration. Distinct project and delivery contexts remain separate.',
   policy:'Shared deterministic build and preparation; a total three-worker correctness budget; fresh assertion execution.'},
  {id:'framework-cohorts',tier:'correctness',pathway:'framework',sourceRoots:['probes/framework-consumption'],
   obligations:'Independent React 18/19, Vue 2/3, Svelte 4/5 and plain HTML consumers; all configured engines.',
   policy:'Builder installation precedes independent cohort installation; actual isolated dependencies and built consumers retained.'},
  {id:'packed-registry',tier:'correctness',pathway:'registry',sourceRoots:['probes/scoped-registry','probes/lazy-registry','probes/lazy-delivery','probes/lazy-delivery-editor','probes/lazy-delivery-pagination','probes/activation-registry','probes/activation-library','tooling/registration'],
   obligations:'Actual tarballs, native scoped ownership and global fallback, lazy activation/failure/retry and typed consumption.',
   policy:'Only identical pack modes may share actual archives. Offline/workspaces=false remains a distinct producer.'},
  {id:'hydration-current',tier:'correctness',pathway:'hydration',sourceRoots:['probes/scoped-hydration'],
   obligations:'Current built SSR preparation, complete/incremental HTML, native/global delivery, all configured engines, no-JS and retained input identity.',
   policy:'Keep actual browser interaction and documented unsupported states. Archived production comparisons are separate.'},
  {id:'reader',tier:'correctness',pathway:'reader',sourceRoots:['showcases/performance-results'],
   obligations:'Reader Node checks, exact exhaustive numeric-sort coverage, keyboard/CSV/mobile/print/links/no-JavaScript; all three engines. Report-specific verifiers retain their additional exact-value checks.',
   policy:'Balanced table groups and batched observations; trusted clicks and settled-state retries; no partial-rerun repair of failed full receipts.'},
  {id:'native-showcase',tier:'qualification',pathway:'native-qualification',sourceRoots:['showcases/tools','showcases/performance'],
   obligations:'All active systems from registry; independent installed/built demos; smoke, secondary checks, inspection validation, source-bound receipt, lab functional checks and calibration.',
   policy:'Prepare deterministic fixtures before serial acquisition. Screenshots remain review evidence.'},
  {id:'native-performance',tier:'full-campaign',pathway:'native-full',sourceRoots:['showcases/performance'],
   obligations:'Full lane from ci/lane-plan.mjs: load/startup/interactions 30 samples, diagnostic 1, memory/Lighthouse/BFCache/observer overhead 5; original profiles/cache cells and lifecycle checkpoints.',
   requiredInputs:['fresh run IDs','prepared qualified system inventory','compatible reviewed load and interaction anchors for regression comparison'],
   policy:'Serial fresh sessions; no build/browser contention; no historical sample reuse or automatic baseline promotion. Reduced development panels are separate pathways.'},
  {id:'registry-exploration',tier:'specialized',pathway:'registry-performance',sourceRoots:['showcases/performance/src/registry-runner.mjs','showcases/performance/tests/registry-browser.mjs'],
   obligations:'Activation/scaling/containment/lifecycle/SSR, all selected workflow/ownership/count/engine/profile/cache cells; three injected-fault controls.',
   requiredInputs:['explicit study matrix and fresh campaign ID'],
   policy:'Retain current source fixture builds and actual ownership; source-verified preparation may be shared, timed observations cannot.'},
  {id:'date-performance',tier:'specialized',pathway:'date',sourceRoots:['probes/date-picker-performance'],
   obligations:'Packed parent/candidate preparation, assets, Node/types, functional/extended/scaling/range, retry/re-enable, SSR, warm-cache proof, full cold/warm campaigns, budgets and input checks.',
   requiredInputs:['fresh PHASE6_BASE','explicit parent/candidate stage pointers and overlay','unchanged reviewed budgets'],
   policy:'30 successful samples per cell and five separate retention runs per arm in cold lane; full warm cells retained. --qualify alone does not reduce the workload. No changed measurement protocol here.'},
  {id:'historical-production-studies',tier:'historical-reproduction',pathway:'historical-production',sourceRoots:['probes/production-registry','probes/scoped-hydration/production','probes/scoped-hydration/closeout','probes/scoped-hydration/ssr-profile'],
   obligations:'Explicit Phase 0–5 reconstruction, source/archive parity, functional qualification, serial capture/retention, analysis and report verification for that frozen cohort.',
   requiredInputs:['original sealed archives','fresh isolated reproduction checkout and output roots','phase-specific documented recipe'],
   policy:'Active reproduction commands remain inventoried. They are not independent current-library tests and cannot be rebound to current builds. Preserve exact historical packages and all failure records.'},
  {id:'historical-native-recipes',tier:'historical-reproduction',pathway:'historical-native',sourceRoots:['showcases/performance/experiments'],
   obligations:'Named acquisition recipes and report integrations preserve their exact historical IDs, harnesses and sealed results.',
   policy:'Use normal CLI with fresh IDs for new acquisition. Do not rerun run-/finish-/resume-/archive- recipes over retained reports. Reusable calibration, evidence and delivery checks require their documented fixtures.'},
  {id:'external-authoring-pilot',tier:'optional-external',pathway:'authoring-pilot',sourceRoots:['tooling/theme-authoring-pilot'],
   obligations:'Original external-engine experiment requires its separately supplied audited source and compiler. Production authoring parity remains in correctness.',
   requiredInputs:['REVE_CSS_FUNCTIONS_SOURCE matching original audited engine'],
   policy:'Do not replace the external subject or label a missing engine as passed.'},
  {id:'manual',tier:'manual',pathway:'manual',sourceRoots:['probes/scoped-hydration/form-review','probes/scoped-hydration/manual-followup','probes/date-picker-performance'],
   obligations:'Physical device, actual assistive technology/speech, saved-profile autofill/history and physical IME acceptance.',
   policy:'Automated fixture mechanics do not establish human review or device acceptance.'},
];
export const protectedHistoricalPatterns = [
  'showcases/performance/baselines/**', 'showcases/performance/runs/**',
  'showcases/performance/experiments/{run,finish,resume,archive}-*.mjs',
];
