import test from 'node:test';import assert from 'node:assert/strict';import {comprehensiveGraph} from './comprehensive.mjs';import {integrationPlan} from './integration-plan.mjs';import {catalog,selection} from '../integration-gates/catalog.mjs';import {root} from './pathways.mjs';
test('integration shares canonical builds, maps every required stage and schedules registry types before docs',async()=>{const graph=await comprehensiveGraph();const before=selection(catalog(root),{mode:'integration'});const plan=integrationPlan(graph,before),byId=new Map(plan.stages.map(s=>[s.id,s]));assert.equal(plan.stages.filter(t=>t.id==='build:elements').length,1);assert.equal(byId.get('build').kind,'barrier');assert.deepEqual(byId.get('registry-types').deps,['build:elements']);assert(plan.schedulePreview.indexOf('registry-types')<plan.schedulePreview.indexOf('build:docs'));assert(plan.schedulePreview.indexOf('diagnostics-unit')<plan.schedulePreview.indexOf('build:docs'));for(const stage of before)assert(byId.has(stage.id));assert(plan.mapping.every(row=>row.canonicalTasks.length));assert(!byId.get('tooling').command.includes('npm'));assert(!byId.get('theme-unit').nodeSources.includes('tooling/theme-candidates/catalogue.test.mjs'));});
test('explicit integration subset contains every producer dependency and no duplicate identities',async()=>{const graph=await comprehensiveGraph();const plan=integrationPlan(graph,selection(catalog(root),{only:['virtualization']}));const required=plan.stages.filter(t=>t.required);assert.equal(new Set(required.map(t=>t.id)).size,required.length);for(const stage of required)for(const dep of stage.deps)assert(required.some(t=>t.id===dep));});

test('explicit build skip propagates to its canonical producers and stays unfulfilled',async()=>{const graph=await comprehensiveGraph(),selected=selection(catalog(root),{only:['registry-types']});selected.find(s=>s.id==='build').requestedSkip=true;const plan=integrationPlan(graph,selected);for(const stage of plan.stages.filter(t=>t.kind==='producer'&&t.canonicalTasks[0]===t.id))assert.equal(stage.requestedSkip,true);});

test('an explicit registry type selection does not prepare docs or browsers',async()=>{const graph=await comprehensiveGraph();const plan=integrationPlan(graph,selection(catalog(root),{only:['registry-types']}));const ids=plan.stages.filter(stage=>stage.required).map(stage=>stage.id);assert(ids.includes('build:elements'));assert(!ids.includes('build:docs'));assert(!plan.stages.some(stage=>stage.required&&stage.config));});

test('integration view remains finite portable data for the canonical inventory digest',async()=>{const {inventoryDigest}=await import('../evidence/setup.mjs');const graph=await comprehensiveGraph();const plan=integrationPlan(graph,selection(catalog(root),{mode:'integration'}));assert.match(inventoryDigest(plan),/^sha256:/);});
