import {readFile,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';import {describe,pairedDifference} from '../../../showcases/performance/src/analysis.mjs';
const base='artifacts/scoped-registry-phase-3-cleanup',read=async p=>JSON.parse(await readFile(`${base}/${p}`));const manifest=await read('campaign/manifest.json'),summary=await read('campaign/summary.json'),samples=(await readFile(`${base}/campaign/samples.jsonl`,'utf8')).trim().split('\n').map(JSON.parse);const key=r=>[r.kind,r.phase,r.browser,r.profile,r.block].join('/');assert.equal(samples.length,250);assert.equal(summary.passed,250);assert.deepEqual(samples.map(key),manifest.jobs.map(key));assert.equal(new Set(samples.map(key)).size,250);assert(samples.every(s=>s.status==='ok'&&!s.errors.length&&!s.failures.length));
const timing=[],retention=[];
for(const [browser,profile]of [['chromium','desktop'],['firefox','desktop'],['webkit','desktop'],['chromium','constrained']]){
 const groups=['control','candidate'].map(phase=>samples.filter(r=>r.kind==='timing'&&r.phase===phase&&r.browser===browser&&r.profile===profile));groups.forEach(g=>assert.equal(g.length,30));
 for(const metric of Object.keys(groups[0][0].metrics)){
  const pairs=groups[0].flatMap(a=>{const b=groups[1].find(b=>b.block===a.block);return Number.isFinite(a.metrics[metric])&&Number.isFinite(b.metrics[metric])?[[a,b]]:[];});
  const arms=[0,1].map(i=>describe(pairs.map(p=>p[i].metrics[metric]))),available=groups.map(g=>describe(g.map(r=>r.metrics[metric])));const delta=pairedDifference(pairs.map(p=>({block:p[1].block,value:p[1].metrics[metric]})),pairs.map(p=>({block:p[0].block,value:p[0].metrics[metric]})));
  timing.push({browser,profile,metric,unit:metric.endsWith('Ms')?'ms':metric.endsWith('Requests')?'count':'bytes',pairedSamples:pairs.length,arms,available,change:{...delta,percent:arms[0].median&&delta.difference!==null?delta.difference/arms[0].median*100:null}});
 }
}
const groups=['control','candidate'].map(phase=>samples.filter(r=>r.kind==='retention'&&r.phase===phase));groups.forEach(g=>{assert.equal(g.length,5);g.forEach(r=>{assert.deepEqual(r.checkpoints.map(c=>c.cycle),[0,10,50,100]);assert(r.checkpoints.every(c=>c.apps===1));});});
for(const cycle of [0,10,50,100,'10–100'])for(const metric of ['heapBytes','nodes','jsEventListeners','documents']){
 const extract=(r,c)=>{const p=r.checkpoints.find(p=>p.cycle===c);return metric==='heapBytes'?p.heapBytes:p.dom[metric];};const value=r=>cycle==='10–100'?extract(r,100)-extract(r,10):extract(r,cycle);const arms=groups.map(g=>describe(g.map(value))),difference=arms[1].median-arms[0].median;
 retention.push({browser:'chromium',profile:'desktop',cycle,metric,unit:metric==='heapBytes'?'bytes':'count',arms,change:{difference,percent:arms[0].median?difference/arms[0].median*100:null,ci95:null}});
}
const data={at:new Date().toISOString(),summary,host:manifest.host,browsers:Object.fromEntries(samples.map(r=>[r.browser,r.browserVersion])),methodology:'Paired rerun of original Phase 3 and cleanup production builds. Thirty randomized serial blocks per configuration; five separate retention runs per arm. Identical external observers and gzip HTTPS/HTTP2. Reported timing medians use only complete paired observations for that metric; available sample counts are retained separately. Bootstrap intervals are exploratory, not multiplicity-adjusted. Frame opportunities are not confirmed paint or INP.',timing,retention};await writeFile(`${base}/comparison.json`,JSON.stringify(data,null,2)+'\n');console.log(JSON.stringify({constrained:timing.filter(r=>r.profile==='constrained').map(r=>({metric:r.metric,n:r.pairedSamples,medians:r.arms.map(a=>a.median),change:r.change})),retention:retention.filter(r=>r.cycle==='10–100')},null,2));
