import {readFile,writeFile,mkdir,cp,readdir,stat,chmod,rename} from 'node:fs/promises';import {resolve,relative} from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';import {verifyReference} from '../../../showcases/performance/src/registry-reference.mjs';
const base=resolve('artifacts/scoped-registry-phase-3-cleanup'),target=resolve('showcases/performance/baselines/scoped-registry-phase-3-cleanup-v1'),pending=target+'.pending',sha=b=>createHash('sha256').update(b).digest('hex');
if(process.argv.includes('--verify')){console.log(await verifyReference(target));process.exit();}
assert.equal(await stat(target).catch(()=>null),null,'Never overwrite frozen results');assert.equal(await stat(pending).catch(()=>null),null,'Unexpected pending freeze');
const manifest=JSON.parse(await readFile(resolve(base,'campaign/manifest.json'))),summary=JSON.parse(await readFile(resolve(base,'campaign/summary.json')));assert.equal(summary.passed,250);assert.equal(summary.timing,240);assert.equal(summary.retention,10);
for(const h of manifest.harness)assert.equal(sha(await readFile(resolve('probes/production-registry/cleanup',h.name))),h.sha256);assert.equal(sha(await readFile(resolve(base,'protocol.md'))),manifest.protocolSha256);
const candidate=JSON.parse(await readFile(resolve(base,'candidate/receipt.json')));for(const overlay of candidate.overlays)assert.equal(sha(await readFile(overlay.path)),overlay.sha256,'Workspace no longer matches measured candidate');
await mkdir(pending);for(const file of ['protocol.md','before.json','comparison.json','findings.json','capture-verification.json','production-functional.json','typecheck.log','browser.json','browser.log','workflow-core.log','production-build.log','power-before.txt','power-after.txt','thermal-before.txt','thermal-after.txt','host-before.json','previous-seal-verification.json'])await cp(resolve(base,file),resolve(pending,file));
await cp(resolve(base,'campaign'),resolve(pending,'run'),{recursive:true});await cp(resolve(base,'qualification'),resolve(pending,'qualification'),{recursive:true});await cp('probes/production-registry/cleanup',resolve(pending,'harness/cleanup'),{recursive:true});await cp('probes/production-registry/browser-probe.mjs',resolve(pending,'harness/browser-probe.mjs'));await cp('showcases/performance/src',resolve(pending,'performance-support'),{recursive:true});
await mkdir(resolve(pending,'rejected'));for(const name of ['campaign-collector-rejected','qualification-collector-rejected','campaign-collector-rejected.log','qualification-collector-rejected.log'])await cp(resolve(base,name),resolve(pending,'rejected',name),{recursive:true});
await mkdir(resolve(pending,'implementation'));for(const overlay of candidate.overlays){await mkdir(resolve(pending,'implementation',overlay.path,'..'),{recursive:true});await cp(overlay.path,resolve(pending,'implementation',overlay.path));}
await mkdir(resolve(pending,'tests'));for(const name of ['runtime.ts','lazy.spec.ts','cleanup.config.ts','prepare.mjs','server.mjs'])await cp(resolve('probes/lazy-registry',name),resolve(pending,'tests',name));
for(const phase of ['control','candidate']){
 const dir=resolve(phase==='control'?'artifacts/scoped-registry-production-v1/phase-3':base+'/candidate'),dest=resolve(pending,phase),receipt=JSON.parse(await readFile(resolve(dir,'receipt.json'))),m=manifest.receipts.find(r=>r.phase===phase);assert.equal(receipt.assetsDigest,m.assetsDigest);assert.equal(receipt.sourceDigest,m.sourceDigest);for(const a of receipt.assets)assert.equal(sha(await readFile(resolve(dir,'site',a.path))),a.sha256);await mkdir(dest);
 for(const file of ['receipt.json','source-final.json','site.tar.gz','build.log'])await cp(resolve(dir,file),resolve(dest,file));
 if(phase==='control'){const stage=resolve(dir,'source');execFileSync('tar',['-czf',resolve(dest,'source.tar.gz'),'--exclude=*/node_modules','-C',stage,...(await readdir(stage)).filter(n=>n!=='node_modules'&&n!=='dist')]);}else await cp(resolve(dir,'source.tar.gz'),resolve(dest,'source.tar.gz'));
}
const original=await verifyReference(resolve('showcases/performance/baselines/scoped-registry-production-v1'));await writeFile(resolve(pending,'original-production-seal.json'),JSON.stringify(original,null,2)+'\n');
const baseline={name:'scoped-registry-phase-3-cleanup-v1',status:'frozen',frozenAt:new Date().toISOString(),timing:{configurations:8,successfulSamples:240,minimumPerConfiguration:30},retention:{configurations:2,successfulRuns:10,repetitionsPerConfiguration:5,checkpoints:[0,10,50,100]},arms:['control','candidate'],hostIdentity:manifest.host,methodology:'Paired actual Vite production Phase 3 vs local-feedback/guarded-catalog cleanup. Original readiness plus additive focus/feedback observations. Global registry, SSR, gzip HTTPS/HTTP2. Two workflow files changed; all 2744 compiled library files identical.'};await writeFile(resolve(pending,'baseline.json'),JSON.stringify(baseline,null,2)+'\n');
async function walk(dir){const files=[];for(const e of await readdir(dir,{withFileTypes:true})){assert.ok(!e.isSymbolicLink());const p=resolve(dir,e.name);files.push(...(e.isDirectory()?await walk(p):[p]));}return files.sort();}
const files=[];for(const p of await walk(pending)){const b=await readFile(p);files.push({path:relative(pending,p),bytes:b.length,sha256:sha(b)});}await writeFile(resolve(pending,'checksums.json'),JSON.stringify({algorithm:'sha256',files},null,2)+'\n');await writeFile(resolve(pending,'seal.json'),JSON.stringify({algorithm:'sha256',checksumsSha256:sha(await readFile(resolve(pending,'checksums.json')))},null,2)+'\n');await verifyReference(pending);for(const p of await walk(pending))await chmod(p,0o444);await rename(pending,target);console.log(await verifyReference(target));
