import '@en-reve/tokens/default.css';
import '@en-reve/styles/foundations.css';
import '@en-reve/styles/controls.css';
import '@en-reve/styles/combobox.css';
import '@en-reve/styles/selection.css';
import '@en-reve/styles/surfaces.css';
import '@en-reve/styles/file-upload.css';
import '@en-reve/elements/define/text-field.js';
import '@en-reve/elements/define/search-input.js';
import '@en-reve/elements/define/date-input.js';
import '@en-reve/elements/define/textarea.js';
import '@en-reve/elements/define/select.js';
import '@en-reve/elements/define/number-field.js';
import '@en-reve/elements/define/color-field.js';
import '@en-reve/elements/define/file-upload.js';
import '@en-reve/elements/define/combobox.js';
import '@en-reve/elements/define/button.js';
import '@en-reve/elements/define/card.js';
import '@en-reve/elements/define/checkbox.js';
import '@en-reve/elements/define/segmented-control.js';
import { resolveTheme, emitThemeCSS } from '@en-reve/tokens';
Object.assign(window, { resolveTheme, emitThemeCSS });
document.body.dataset.ready = 'true';
