import {test,expect,type Locator} from '@playwright/test';
const configure=(host:Locator,values:Record<string,unknown>)=>host.evaluate((n,v)=>(n as any).configure(v),values);
const day=(host:Locator,value:string)=>host.locator(`button[data-date="${value}"]`);
for(const delivery of ['lit','css'])test.describe(delivery,()=>{
 test.beforeEach(async({page})=>{await page.goto('/?delivery='+delivery);await expect(page.locator('body')).toHaveAttribute('data-ready','true');});
 test('native grid has 42 days, full weekday headings and one named keyboard entry',async({page})=>{
  const host=page.locator('consumer-calendar').first();await expect(host.getByRole('grid',{name:'February 2024'})).toHaveCount(1);await expect(host.getByRole('gridcell')).toHaveCount(42);for(const [index,name] of ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].entries())await expect(host.getByRole('columnheader').nth(index)).toHaveAccessibleName(name);await expect(host.locator('button[data-date][tabindex="0"]')).toHaveCount(1);await expect(day(host,'2024-02-15')).toHaveAccessibleName('Thursday, February 15, 2024');await expect(day(host,'2024-02-15')).toHaveAttribute('aria-current','date');await expect(day(host,'2024-01-29')).toHaveAttribute('data-outside');
 });
 test('single selection uses native activation and produces the application form payload',async({page})=>{
  const host=page.locator('consumer-calendar').first(),selected=day(host,'2024-02-29');await selected.focus();await selected.press('Enter');await expect(selected.locator('..')).toHaveAttribute('aria-selected','true');await host.getByRole('button',{name:'Submit dates'}).click();await expect(host.getByLabel('Submitted dates')).toHaveText('[["date","2024-02-29"]]');await expect(host.getByRole('status',{name:'Selection feedback'})).toContainText('Thursday, February 29, 2024');await host.getByRole('button',{name:'Clear selection'}).click();await expect(selected.locator('..')).toHaveAttribute('aria-selected','false');
 });
 test('arrow navigation crosses leap-day and month boundaries without changing selection',async({page})=>{
  const host=page.locator('consumer-calendar').first();await day(host,'2024-02-28').focus();await page.keyboard.press('ArrowRight');await expect(day(host,'2024-02-29')).toBeFocused();await page.keyboard.press('ArrowRight');await expect(day(host,'2024-03-01')).toBeFocused();await expect(host.getByRole('grid')).toHaveAccessibleName('March 2024');await page.keyboard.press('ArrowUp');await expect(day(host,'2024-02-23')).toBeFocused();await expect(host.locator('td[aria-selected="true"]')).toHaveCount(0);
 });
 test('Home End and month/year paging retain predictable cursor dates',async({page})=>{
  const host=page.locator('consumer-calendar').first();await day(host,'2024-02-15').focus();await page.keyboard.press('Home');await expect(day(host,'2024-02-12')).toBeFocused();await page.keyboard.press('End');await expect(day(host,'2024-02-18')).toBeFocused();await configure(host,{month:'2024-01-31'});await day(host,'2024-01-31').focus();await page.keyboard.press('PageDown');await expect(day(host,'2024-02-29')).toBeFocused();await page.keyboard.press('Shift+PageDown');await expect(day(host,'2025-02-28')).toBeFocused();await page.keyboard.press('PageUp');await expect(day(host,'2025-01-28')).toBeFocused();
 });
 test('inclusive bounds disable selection and prevent navigation into unavailable months',async({page})=>{
  const host=page.locator('consumer-calendar').first();await configure(host,{month:'2024-02-15',min:'2024-02-10',max:'2024-02-20'});await expect(host.getByRole('button',{name:'Previous month'})).toBeDisabled();await expect(host.getByRole('button',{name:'Next month'})).toBeDisabled();await day(host,'2024-02-09').focus();await page.keyboard.press('Enter');await expect(host.locator('td[aria-selected="true"]')).toHaveCount(0);await day(host,'2024-02-10').focus();await page.keyboard.press('ArrowLeft');await expect(day(host,'2024-02-10')).toBeFocused();await day(host,'2024-02-20').click();await expect(day(host,'2024-02-20').locator('..')).toHaveAttribute('aria-selected','true');
 });
 test('reversed bounds stay empty while malformed bounds do not disable valid dates',async({page})=>{
  const host=page.locator('consumer-calendar').first();await configure(host,{min:'2024-03-01',max:'2024-02-01'});await expect(host.locator('button[data-date][aria-disabled="true"]')).toHaveCount(42);await expect(host.getByRole('button',{name:'Previous month'})).toBeDisabled();await expect(host.getByRole('button',{name:'Next month'})).toBeDisabled();await configure(host,{min:'not-a-date',max:'2024-02-30'});await expect(host.locator('button[data-date][aria-disabled="false"]')).toHaveCount(42);
 });
 test('fractional helper steps stay literal and retain native validation observations',async({page})=>{
  const host=page.locator('consumer-calendar').first();await configure(host,{step:.3,stepBase:'2024-02-10',min:'2024-02-10'});await expect(day(host,'2024-02-13')).toHaveAttribute('aria-disabled','false');await expect(day(host,'2024-02-11')).toHaveAttribute('aria-disabled','true');const actual=await host.evaluate(n=>{const input=document.createElement('input');input.type='date';input.min='2024-02-10';input.step='.3';return ['2024-02-10','2024-02-11','2024-02-13'].map(value=>{input.value=value;return {native:input.validity.stepMismatch,helper:n.shadowRoot!.querySelector(`[data-date="${value}"]`)!.getAttribute('aria-disabled')==='true'};});});expect(actual.map(value=>value.helper)).toEqual([false,true,false]);await test.info().attach('native-fractional-step-observation',{body:JSON.stringify(actual),contentType:'application/json'});
 });
 test('whole-day steps agree with native date validation on the same base',async({page})=>{
  const host=page.locator('consumer-calendar').first();await configure(host,{step:2,stepBase:'2024-02-10',min:'2024-02-10'});const rows=await host.evaluate(n=>{const input=document.createElement('input');input.type='date';input.min='2024-02-10';input.step='2';return ['2024-02-10','2024-02-11','2024-02-12'].map(value=>{input.value=value;return {native:input.validity.stepMismatch,helper:n.shadowRoot!.querySelector(`[data-date="${value}"]`)!.getAttribute('aria-disabled')==='true'};});});expect(rows.map(row=>row.native)).toEqual([false,true,false]);for(const row of rows)expect(row.native).toBe(row.helper);
 });
 test('range selection normalizes reverse order and submits both endpoints',async({page})=>{
  const host=page.locator('consumer-calendar').first();await configure(host,{mode:'range'});await day(host,'2024-02-19').click();await expect(host.getByRole('status',{name:'Selection feedback'})).toHaveText('Choose the end date.');await day(host,'2024-02-16').click();await expect(host.locator('td[aria-selected="true"]')).toHaveCount(4);await host.getByRole('button',{name:'Submit dates'}).click();await expect(host.getByLabel('Submitted dates')).toHaveText('[["start","2024-02-16"],["end","2024-02-19"]]');await expect(host.getByRole('grid')).toHaveAttribute('aria-multiselectable','true');
 });
 test('an unfinished range previews without committing and Escape clears only that draft',async({page})=>{
  const host=page.locator('consumer-calendar').first();await configure(host,{mode:'range'});await day(host,'2024-02-12').click();await day(host,'2024-02-15').hover();await expect(host.locator('[part~="range-band-preview"]')).toHaveCount(4);await expect(host.locator('td[aria-selected="true"]')).toHaveCount(0);await day(host,'2024-02-12').focus();await page.keyboard.press('Escape');await expect(host.locator('[part~="range-band"]')).toHaveCount(0);await expect(host.getByRole('status',{name:'Selection feedback'})).toHaveText('Range selection canceled.');await expect(day(host,'2024-02-12')).toBeFocused();
 });
 test('range persists while navigating months and new selection starts a new draft',async({page})=>{
  const host=page.locator('consumer-calendar').first();await configure(host,{mode:'range'});await day(host,'2024-02-28').click();await host.getByRole('button',{name:'Next month'}).click();await day(host,'2024-03-03').click();await expect(host.getByRole('status',{name:'Selection feedback'})).toHaveText('Range 2024-02-28 to 2024-03-03.');await host.getByRole('button',{name:'Previous month'}).click();await expect(day(host,'2024-02-29').locator('..')).toHaveAttribute('aria-selected','true');await day(host,'2024-02-10').click();await expect(host.getByRole('status',{name:'Selection feedback'})).toHaveText('Choose the end date.');await expect(host.locator('td[aria-selected="true"]')).toHaveCount(0);
 });
 test('range bands join at cell boundaries and retain rounded endpoint and hover paint',async({page})=>{
  const host=page.locator('consumer-calendar').first();await configure(host,{mode:'range'});await day(host,'2024-02-13').click();await day(host,'2024-02-16').click();const bands=host.locator('[part~="range-band"]');await expect(bands).toHaveCount(4);const boxes=await bands.evaluateAll(nodes=>nodes.map(n=>{const r=n.getBoundingClientRect();return {left:r.left,right:r.right};}));for(let i=1;i<boxes.length;i++)expect(Math.abs(boxes[i].left-boxes[i-1].right)).toBeLessThan(1);const middle=day(host,'2024-02-14');await middle.hover();await expect(middle).toHaveCSS('border-radius','8px');expect(await middle.evaluate(n=>getComputedStyle(n).backgroundImage)).not.toBe('none');await expect(bands.first()).toHaveCSS('background-color','rgb(208, 224, 255)');await expect(bands.last()).toHaveCSS('background-color','rgb(208, 224, 255)');
 });
 test('scoped calendar pins affect one instance while preserving sibling theme',async({page})=>{
  const host=page.locator('consumer-calendar').first(),sibling=page.locator('#independent');await configure(host,{mode:'range'});await configure(sibling,{mode:'range'});for(const item of [host,sibling]){await day(item,'2024-02-13').click();await day(item,'2024-02-16').click();}await host.evaluate(n=>{n.style.setProperty('--en-calendar-range-background','#ead6fa');n.style.setProperty('--en-calendar-day-radius','11px');n.style.setProperty('--en-calendar-inline-size','24rem');});await expect(host.locator('[part~="range-band"]').first()).toHaveCSS('background-color','rgb(234, 214, 250)');await expect(sibling.locator('[part~="range-band"]').first()).toHaveCSS('background-color','rgb(208, 224, 255)');await expect(day(host,'2024-02-14')).toHaveCSS('border-radius','11px');await expect(day(sibling,'2024-02-14')).toHaveCSS('border-radius','8px');expect(await host.locator('link').count()).toBe(delivery==='css'?1:0);
 });
 test('locale headings change presentation while submitted dates remain Gregorian ISO',async({page})=>{
  const host=page.locator('consumer-calendar').first();await configure(host,{locale:'fr-FR',firstDay:0});await expect(host.getByRole('grid')).toHaveAccessibleName('février 2024');await expect(host.getByRole('columnheader').first()).toHaveAccessibleName('dimanche');await expect(day(host,'2024-02-29')).toHaveAccessibleName('jeudi 29 février 2024');await configure(host,{locale:'en-US-u-ca-buddhist'});await expect(host.getByRole('grid')).toHaveAccessibleName('February 2024');await day(host,'2024-02-29').click();await host.getByRole('button',{name:'Submit dates'}).click();await expect(host.getByLabel('Submitted dates')).toHaveText('[["date","2024-02-29"]]');
 });
 test('RTL reverses horizontal keyboard movement and keeps day geometry square',async({page})=>{
  const host=page.locator('consumer-calendar').first();await page.evaluate(()=>document.documentElement.dir='rtl');await day(host,'2024-02-15').focus();await page.keyboard.press('ArrowRight');await expect(day(host,'2024-02-14')).toBeFocused();await page.keyboard.press('ArrowLeft');await expect(day(host,'2024-02-15')).toBeFocused();const b=await day(host,'2024-02-15').boundingBox();expect(Math.abs(b!.width-b!.height)).toBeLessThan(1);await expect(day(host,'2024-02-15')).toHaveCSS('font-variant-numeric','tabular-nums');
 });
 test('unrelated renders preserve the focused native day and keyboard focus indicator',async({page})=>{
  const host=page.locator('consumer-calendar').first(),button=day(host,'2024-02-15');await button.focus();await page.keyboard.press('ArrowRight');const next=day(host,'2024-02-16');await next.evaluate(n=>{(window as any).focusedDay=n;document.querySelector<any>('consumer-calendar').requestUpdate();});await expect(next).toBeFocused();expect(await next.evaluate(n=>n===(window as any).focusedDay)).toBe(true);expect(await next.evaluate(n=>{const s=getComputedStyle(n);return s.outlineStyle!=='none'||s.boxShadow!=='none';})).toBe(true);
 });
 test('supported year edges leave blank cells instead of duplicate boundary dates',async({page})=>{
  const host=page.locator('consumer-calendar').first();await configure(host,{month:'0001-01-01',firstDay:0});await expect(day(host,'0001-01-01')).toHaveCount(1);await expect(host.getByRole('gridcell').first().locator('button')).toHaveCount(0);await expect(host.locator('td[aria-selected="true"]')).toHaveCount(0);await day(host,'0001-01-01').focus();await page.keyboard.press('ArrowLeft');await expect(day(host,'0001-01-01')).toBeFocused();await configure(host,{month:'9999-12-31'});await expect(day(host,'9999-12-31')).toHaveCount(1);await expect(host.getByRole('gridcell').last().locator('button')).toHaveCount(0);await day(host,'9999-12-31').focus();await page.keyboard.press('ArrowRight');await expect(day(host,'9999-12-31')).toBeFocused();
 });
 test('narrow enlarged text uses local calendar scrolling without document overflow',async({page})=>{
  await page.setViewportSize({width:320,height:800});await page.evaluate(()=>{document.documentElement.dir='rtl';document.documentElement.style.fontSize='24px';});const host=page.locator('consumer-calendar').first();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(320);const area=host.locator('.en-calendar');expect(await area.evaluate(n=>n.scrollWidth>=n.clientWidth)).toBe(true);await day(host,'2024-02-15').focus();await page.keyboard.press('End');await expect(day(host,'2024-02-18')).toBeFocused();
 });
 test('forced colors preserve range endpoints and disabled semantic state',async({page})=>{
  const host=page.locator('consumer-calendar').first();await configure(host,{mode:'range',min:'2024-02-10'});await day(host,'2024-02-13').click();await day(host,'2024-02-16').click();await page.emulateMedia({forcedColors:'active'});await expect(day(host,'2024-02-13')).toHaveCSS('border-top-style','solid');await expect(day(host,'2024-02-13')).toHaveCSS('border-top-width','2px');await expect(day(host,'2024-02-09')).toHaveAttribute('aria-disabled','true');const supported=await page.evaluate(()=>CSS.supports('forced-color-adjust','none'));if(supported)await expect(host.locator('[part~="range-band"]').first()).toHaveCSS('forced-color-adjust','none');else test.info().annotations.push({type:'capability-limit',description:'This engine does not expose forced-color-adjust; border and disabled semantics remain asserted.'});
 });
 test('browser timezone changes do not shift displayed date-only grids',async({browser,baseURL})=>{
  const results=[];for(const timezoneId of ['America/New_York','Pacific/Apia']){const context=await browser.newContext({timezoneId});try{const page=await context.newPage();await page.goto(baseURL+'/?delivery='+delivery);await expect(page.locator('body')).toHaveAttribute('data-ready','true');const host=page.locator('consumer-calendar').first();await configure(host,{month:'2011-12-30'});await day(host,'2011-12-30').focus();await page.keyboard.press('ArrowRight');results.push(await host.locator('button[data-date][tabindex="0"]').getAttribute('data-date'));}finally{await context.close();}}expect(results).toEqual(['2011-12-31','2011-12-31']);
 });
});
