import {LitElement,html,css,nothing} from 'lit';
import {repeat} from 'lit/directives/repeat.js';
import {addDays,addMonths,clampDate,compareDates,dateInRange,dateOnStep,daysInMonth,formatDate,localizedDate,monthGrid,monthInRange,parseDate,weekdayLabels,type CalendarDate} from '@en-reve/primitives/interactions/calendar.js';
import {calendarStyles} from '@en-reve/styles/calendar.js';
import {foundationStyles} from '@en-reve/styles/foundations.js';
import {buttonStyles} from '@en-reve/styles/buttons.js';
const portable=new URLSearchParams(location.search).get('delivery')==='css';
type Config={month:string;min:string;max:string;step:number;stepBase:string;locale:string;firstDay:number;mode:'single'|'range'};
class ConsumerCalendar extends LitElement {
 static override styles=[...(portable?[]:[foundationStyles,buttonStyles,calendarStyles]),css`:host{display:block;min-inline-size:0;--en-color-selected:#d0e0ff;--en-color-action-text:#163b72;--en-color-text:#15202b;--en-color-text-muted:#425568;--en-color-action:#1458aa;--en-space-2:.5rem;--en-radius-control:6px}.en-foundation{min-inline-size:0}form{margin:0;min-inline-size:0}.en-calendar-header>span{overflow-wrap:anywhere;min-inline-size:0}output{display:block;overflow-wrap:anywhere}[part=range-status]{max-inline-size:22rem}button{font:inherit}.actions{display:flex;flex-wrap:wrap;gap:.5rem;margin-block:1rem}.en-calendar-header button{min-inline-size:2.5rem;min-block-size:2.5rem}.en-calendar-header{position:sticky;inset-inline-start:0}.en-calendar{padding:2px;box-sizing:border-box}`];
 private config:Config={month:'2024-02-15',min:'',max:'',step:1,stepBase:'1970-01-01',locale:'en-US',firstDay:1,mode:'single'};
 private month=parseDate(this.config.month)!;private cursor='2024-02-15';private selected='';private start='';private end='';private preview='';private submitted='';private announcements='Choose a review date.';
 configure(values:Partial<Config>){this.config={...this.config,...values};this.month=parseDate(this.config.month)!;const clamped=clampDate(this.month,this.config.min,this.config.max);this.cursor=clamped?formatDate(clamped):'';this.selected=this.start=this.end=this.preview='';this.requestUpdate();}
 private available(date:CalendarDate){return dateInRange(date,this.config.min,this.config.max)&&dateOnStep(date,this.config.step,this.config.stepBase);}
 private async focusDate(date:CalendarDate){const key=formatDate(date);this.cursor=key;this.month={...date,day:1};this.config.month=key;this.requestUpdate();await this.updateComplete;this.renderRoot.querySelector<HTMLButtonElement>(`button[data-date="${key}"]`)?.focus();}
 private async navigate(delta:number){const target=addMonths(parseDate(this.cursor)||this.month,delta);if(monthInRange(target,this.config.min,this.config.max)){const limited=clampDate(target,this.config.min,this.config.max);if(limited)await this.focusDate(limited);}}
 private key(event:KeyboardEvent,date:CalendarDate){let target:CalendarDate|undefined;const rtl=getComputedStyle(this).direction==='rtl';
  if(event.key==='ArrowRight')target=addDays(date,rtl?-1:1);else if(event.key==='ArrowLeft')target=addDays(date,rtl?1:-1);else if(event.key==='ArrowDown')target=addDays(date,7);else if(event.key==='ArrowUp')target=addDays(date,-7);
  else if(event.key==='Home'||event.key==='End'){const cell=monthGrid(this.month,{firstDayOfWeek:this.config.firstDay}).findIndex(c=>c.value===formatDate(date));target=addDays(date,(event.key==='End'?6:0)-cell%7);}
  else if(event.key==='PageUp'||event.key==='PageDown'){event.preventDefault();void this.navigate((event.key==='PageUp'?-1:1)*(event.shiftKey?12:1));return;}
  else if(event.key==='Escape'&&this.config.mode==='range'&&!this.end){event.preventDefault();this.start=this.preview='';this.announcements='Range selection canceled.';this.requestUpdate();return;}
  if(target){event.preventDefault();const limited=clampDate(target,this.config.min,this.config.max);if(limited)void this.focusDate(limited);}
 }
 private choose(date:CalendarDate){if(!this.available(date))return;const key=formatDate(date);this.cursor=key;
  if(this.config.mode==='single'){this.selected=key;this.announcements=`Selected ${localizedDate(date,this.config.locale)}.`;}
  else if(!this.start||this.end){this.start=key;this.end=this.preview='';this.announcements='Choose the end date.';}
  else {const first=parseDate(this.start)!;this.end=compareDates(first,date)<=0?key:this.start;this.start=compareDates(first,date)<=0?this.start:key;this.preview='';this.announcements=`Range ${this.start} to ${this.end}.`;}
  this.requestUpdate();
 }
 private band(value:string){if(!value||!this.start)return '';const other=this.end||this.preview||this.start;const low=this.start<other?this.start:other,high=this.start<other?other:this.start;if(value<low||value>high)return '';return `range-band${!this.end&&this.preview?' range-band-preview':''}${value===low?' range-band-start':''}${value===high?' range-band-end':''}`;}
 override render(){const c=this.config;const cells=monthGrid(this.month,{firstDayOfWeek:c.firstDay,min:c.min,max:c.max});const weeks=Array.from({length:6},(_,i)=>cells.slice(i*7,i*7+7));const label=localizedDate(this.month,c.locale,{month:'long',year:'numeric'});const previous=addMonths(this.month,-1),next=addMonths(this.month,1);return html`${portable?html`<link rel="stylesheet" href="/calendar.css">`:nothing}<div class="en-foundation"><form @submit=${(e:SubmitEvent)=>{e.preventDefault();this.submitted=JSON.stringify([...new FormData(e.currentTarget as HTMLFormElement)]);this.requestUpdate();}}>
 <div class="en-calendar" data-selection=${c.mode}><div class="en-calendar-header"><button class="en-button" type="button" aria-label="Previous month" ?disabled=${!monthInRange(previous,c.min,c.max)||compareDates(previous,this.month)===0} @click=${()=>this.navigate(-1)}>‹</button><span id="month" part="heading">${label}</span><button class="en-button" type="button" aria-label="Next month" ?disabled=${!monthInRange(next,c.min,c.max)||compareDates(next,this.month)===0} @click=${()=>this.navigate(1)}>›</button></div>
 <table role="grid" aria-labelledby="month" aria-describedby="instructions" aria-multiselectable=${c.mode==='range'?'true':nothing}><thead><tr>${weekdayLabels(c.locale,c.firstDay).map(d=>html`<th scope="col" aria-label=${d.long}><span class="en-calendar-weekday" aria-hidden="true">${d.short}</span></th>`)}</tr></thead><tbody>${weeks.map(week=>html`<tr>${repeat(week,day=>day.value||`blank-${week.indexOf(day)}`,day=>{const selected=c.mode==='single'?!!day.value&&day.value===this.selected:!!this.end&&!!this.band(day.value);const parts=['day',day.value===this.start?'range-start':'',day.value===this.end?'range-end':'',selected&&c.mode==='range'?'in-range':'',!this.end&&this.preview&&this.band(day.value)?'preview':''].filter(Boolean).join(' ');return html`<td role="gridcell" aria-selected=${String(selected)}>${c.mode==='range'&&this.band(day.value)?html`<span part=${this.band(day.value)} aria-hidden="true"></span>`:nothing}${day.date?html`<button type="button" class="en-calendar-day" part=${parts} data-date=${day.value} ?data-outside=${!day.inMonth} aria-label=${localizedDate(day.date,c.locale)} aria-disabled=${String(!this.available(day.date))} aria-current=${day.value==='2024-02-15'?'date':nothing} tabindex=${day.value===this.cursor?0:-1} @keydown=${(e:KeyboardEvent)=>this.key(e,day.date!)} @click=${()=>this.choose(day.date!)} @focus=${()=>{this.cursor=day.value;this.requestUpdate();}} @pointerenter=${()=>{if(c.mode==='range'&&this.start&&!this.end&&this.available(day.date!)){this.preview=day.value;this.requestUpdate();}}}>${day.date.day}</button>`:nothing}</td>`;})}</tr>`)}</tbody></table></div>
 <p id="instructions">Use arrow keys for days, Home/End for the week, Page Up/Down for months and Shift for years. Enter chooses a date. Escape cancels an unfinished range.</p><p role="status" aria-label="Selection feedback" part="range-status">${this.announcements}</p>
 ${c.mode==='single'?html`<input type="hidden" name="date" value=${this.selected}>`:html`<input type="hidden" name="start" value=${this.start}><input type="hidden" name="end" value=${this.end}>`}<div class="actions"><button class="en-button" type="button" @click=${()=>{this.selected=this.start=this.end=this.preview='';this.announcements='Selection cleared.';this.requestUpdate();}}>Clear selection</button><button class="en-button">Submit dates</button></div><output aria-label="Submitted dates">${this.submitted}</output><output aria-label="Month length">${daysInMonth(this.month.year,this.month.month)}</output></form></div>`;}
}
customElements.define('consumer-calendar',ConsumerCalendar);
await Promise.all([...document.querySelectorAll<ConsumerCalendar>('consumer-calendar')].map(n=>n.updateComplete));
await Promise.all([...document.querySelectorAll('consumer-calendar')].flatMap(e=>[...e.shadowRoot!.querySelectorAll('link')].map(link=>link.sheet?Promise.resolve():new Promise<void>((ok,fail)=>{link.onload=()=>ok();link.onerror=()=>fail(new Error('CSS failed'));}))));
document.body.dataset.ready='true';
