// Generated by tooling/metadata/lazy-manifest.ts. Edit the delivery policy/inventory, not this file.
import type {DeliveryFeature, DeliveryIdentity, DeliveryInitialProperties} from '../delivery.js';
import {freezeDeliveryData} from './delivery-data.js';
export interface ProfilePolicy extends DeliveryIdentity { readonly initialProperties: readonly DeliveryInitialProperties[]; }
export const eagerProfilePolicy: ProfilePolicy = /* @__PURE__ */ freezeDeliveryData({
  "schemaVersion": 1,
  "id": "en-reve/eager",
  "version": "1",
  "initialProperties": []
});
export const datePickerSingleDeferredPolicy: ProfilePolicy = /* @__PURE__ */ freezeDeliveryData({
  "schemaVersion": 1,
  "id": "en-reve/date-picker-single-deferred",
  "version": "1",
  "initialProperties": [
    {
      "tag": "en-date-picker",
      "properties": {
        "calendarLoading": "deferred",
        "selection": "single"
      }
    }
  ]
});
export const datePickerCalendarFeature: DeliveryFeature = /* @__PURE__ */ freezeDeliveryData({
  "id": "en-reve/en-date-picker/calendar",
  "version": "1",
  "disposition": "implemented",
  "owner": "element",
  "deferredCosts": [
    "optional-code",
    "registration",
    "construction"
  ],
  "definitionTags": [
    "en-calendar"
  ],
  "fallback": "The essential single native date editor remains available; hydrate its shell promptly for form participation.",
  "prerequisites": [
    "Select the date-picker shell profile before loading definitions.",
    "Set calendarLoading to deferred and selection to single before the first update.",
    "The date picker owns construction, readiness, focus and cancellation."
  ]
});
export const commandPaletteRootFeature: DeliveryFeature = /* @__PURE__ */ freezeDeliveryData({
  "id": "en-reve/en-command-palette/root",
  "version": "1",
  "disposition": "implemented",
  "owner": "application",
  "deferredCosts": [
    "component-loading",
    "registration",
    "construction"
  ],
  "definitionTags": [
    "en-command-palette"
  ],
  "fallback": "A native launcher, loading/error text and essential navigation remain outside the application-owned activation root.",
  "prerequisites": [
    "Use createElementActivation with an explicit scope, template or dormant root and actual readiness callback.",
    "The application owns cancellation and disposal; definition preparation does not open the palette."
  ]
});
export const deliveryProfiles: { readonly eager: ProfilePolicy; readonly datePickerSingleDeferred: ProfilePolicy } = /* @__PURE__ */ freezeDeliveryData({eager: eagerProfilePolicy, datePickerSingleDeferred: datePickerSingleDeferredPolicy});
export const deliveryFeatures: { readonly datePickerCalendar: DeliveryFeature; readonly commandPaletteRoot: DeliveryFeature } = /* @__PURE__ */ freezeDeliveryData({datePickerCalendar: datePickerCalendarFeature, commandPaletteRoot: commandPaletteRootFeature});
