import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{await page.goto('/');await expect(page.locator('body')).toHaveAttribute('data-ready','true');});
test('query copy and validation drive application-owned all/any filtering from native fields',async({page})=>{
 const host=page.locator('consumer-filter'),first=host.getByRole('group',{name:'Condition 1',exact:true});await expect(host.getByRole('list',{name:'Matching briefs'}).getByRole('button')).toHaveText(['Cover study','Cover outline']);await host.getByRole('button',{name:'Add condition'}).click();await host.getByRole('button',{name:'Apply filters'}).click();await expect(host.getByRole('listitem')).toHaveCount(1);await expect(host.getByRole('listitem')).toContainText('Cover outline');
 await host.getByLabel('Match',{exact:true}).selectOption('any');await host.getByRole('button',{name:'Apply filters'}).click();await expect(host.getByRole('listitem')).toHaveCount(3);
 await first.getByLabel('Operator',{exact:true}).selectOption('not-equals');await first.getByLabel('Value',{exact:true}).fill('Cover study');await host.getByLabel('Match',{exact:true}).selectOption('all');await host.getByRole('button',{name:'Apply filters'}).click();await expect(host.getByRole('listitem')).toHaveCount(2);
});
test('invalid numeric and field/operator drafts keep the last accepted query intact',async({page})=>{
 const host=page.locator('consumer-filter'),first=host.getByRole('group',{name:'Condition 1',exact:true});await first.getByLabel('Operator',{exact:true}).selectOption('greater-than');await host.getByRole('button',{name:'Apply filters'}).click();await expect(host.getByRole('status')).toHaveText('This comparison requires a numeric field.');await expect(host.getByRole('listitem')).toHaveCount(2);
 await first.getByLabel('Field',{exact:true}).selectOption('score');await first.getByLabel('Value',{exact:true}).fill('not a number');await host.getByRole('button',{name:'Apply filters'}).click();await expect(host.getByRole('status')).toHaveText('Enter a number.');
 await first.getByLabel('Value',{exact:true}).fill('');await host.getByRole('button',{name:'Apply filters'}).click();await expect(host.getByRole('status')).toHaveText('Enter a value for every condition.');
 await first.getByLabel('Value',{exact:true}).fill('50');await host.getByRole('button',{name:'Apply filters'}).click();await expect(host.getByRole('status')).toBeEmpty();await expect(host.getByRole('listitem')).toHaveCount(2);await expect(host.getByRole('list').getByRole('button')).toHaveText(['Draft review','Cover outline']);
});
test('query proposal can be canceled or superseded and exported copies do not alias accepted state',async({page})=>{
 const host=page.locator('consumer-filter');await host.evaluate(n=>{const q=(n as any).query;q.clauses[0].value='Wrong';(window as any).mutatedCopy=q;n.addEventListener('en-change',e=>{(window as any).tentative=(n as any).query;e.preventDefault();},{once:true});});await host.getByLabel('Value',{exact:true}).fill('Draft');await host.getByRole('button',{name:'Apply filters'}).click();await expect(host.getByRole('list').getByRole('button')).toHaveText(['Cover study','Cover outline']);expect(await page.evaluate(()=>(window as any).tentative.clauses[0].value)).toBe('Draft');
 await host.evaluate(n=>n.addEventListener('en-change',e=>{(n as any).query={match:'all',clauses:[{id:'author',field:'score',operator:'less-than',value:'50'}]};e.preventDefault();},{once:true}));await host.getByRole('button',{name:'Apply filters'}).click();await expect(host.getByRole('list').getByRole('button')).toHaveText(['Cover study']);
});
test('invalid authoritative query is rejected without changing accepted results',async({page})=>{
 const result=await page.locator('consumer-filter').evaluate(n=>{const errors=[];for(const q of [{match:'all',clauses:[{id:'same',field:'title',operator:'contains',value:'x'},{id:'same',field:'score',operator:'equals',value:'3'}]},{match:'all',clauses:[{id:'bad',field:'unknown',operator:'equals',value:'x'}]},{match:'all',clauses:[{id:'bad',field:'score',operator:'unknown',value:'3'}]}])try{(n as any).query=q;}catch(e){errors.push((e as Error).message);}return errors;});expect(result).toEqual(['Clause identifiers must be unique.','Choose a field for every condition.','Choose a supported operator.']);await expect(page.locator('consumer-filter').getByRole('listitem')).toHaveCount(2);
});
test('opaque canonical collection keys preserve row identity while reorder and labels change',async({page})=>{
 const host=page.locator('consumer-filter'),row=host.locator('[data-key=" cover "]');await row.evaluate(n=>(window as any).row=n);await host.evaluate(n=>(n as any).setItems([{key:'outline',oldKey:'legacy-outline',title:'Cover outline',score:90},{key:' cover ',oldKey:'legacy-cover',title:'Cover changed',score:30}]));await expect(host.getByRole('list').getByRole('button')).toHaveText(['Cover outline','Cover changed']);expect(await row.evaluate(n=>n===(window as any).row)).toBe(true);await expect(row).toHaveAttribute('data-key',' cover ');
});
test('legacy key extraction is explicit and invalid component identities cannot replace records',async({page})=>{
 const host=page.locator('consumer-filter');await host.evaluate(n=>(n as any).setItems([{key:'canonical',oldKey:'legacy',title:'Cover legacy',score:25}],true));await expect(host.locator('[data-key="legacy"]')).toBeVisible();
 const errors=await host.evaluate(n=>{const result=[];for(const keys of [[' ','valid'],['duplicate','duplicate']])try{(n as any).setItems(keys.map(key=>({key,oldKey:key,title:'Cover',score:1})));}catch(e){result.push((e as Error).message);}return result;});expect(errors).toHaveLength(2);await expect(host.getByRole('list').getByRole('button')).toHaveText(['Cover legacy']);
});
test('interval movement uses native keyboard steps and preserves ordered minimum gap',async({page})=>{
 const host=page.locator('consumer-range'),low=host.getByRole('slider',{name:'Minimum score'}),high=host.getByRole('slider',{name:'Maximum score'});await low.focus();await low.press('ArrowRight');await expect(low).toHaveValue('25');await low.press('End');await expect(low).toHaveValue('50');await high.press('Home');await expect(high).toHaveValue('60');await high.press('End');await expect(high).toHaveValue('100');await low.press('Home');await expect(low).toHaveValue('0');await expect(host.getByLabel('Score window',{exact:true})).toHaveText('0 – 100');
});
test('interval normalization, fractional limits and synchronous veto retain coherent native values',async({page})=>{
 const host=page.locator('consumer-range');await host.evaluate(n=>{(n as any).configure({min:0,max:1,step:.1,minGap:.21});(n as any).value=[.87,.12];});await expect(host.getByRole('slider',{name:'Minimum score'})).toHaveValue('0.1');await expect(host.getByRole('slider',{name:'Maximum score'})).toHaveValue('0.9');
 await host.evaluate(n=>n.addEventListener('en-change',e=>{(window as any).tentativeForm=[...new FormData(n.shadowRoot!.querySelector('form')!)];e.preventDefault();},{once:true}));await host.getByRole('slider',{name:'Minimum score'}).press('ArrowRight');expect(await page.evaluate(()=>(window as any).tentativeForm)).toEqual([['low','0.2'],['high','0.9']]);await expect(host.getByRole('slider',{name:'Minimum score'})).toHaveValue('0.1');
 await host.evaluate(n=>{(window as any).count=0;n.addEventListener('en-change',()=>((window as any).count++));(n as any).value=[.9,.9];});await expect(host.getByRole('slider',{name:'Minimum score'})).toHaveValue('0.7');await expect(host.getByRole('slider',{name:'Maximum score'})).toHaveValue('1');expect(await page.evaluate(()=>(window as any).count)).toBe(0);
});
test('overflow reserves a measured disclosure and exposes every action once',async({page})=>{
 const host=page.locator('consumer-overflow'),group=host.getByRole('group',{name:'Brief actions'});await host.evaluate(n=>n.style.width='600px');await expect(group.getByRole('button')).toHaveText(['Rename','Duplicate','Download','Archive']);await expect(group.locator('summary')).toBeHidden();await host.evaluate(n=>n.style.width='240px');await expect(group.locator('summary')).toBeVisible();await group.locator('summary').click();const buttons=group.getByRole('button');await expect(buttons).toHaveText(['Rename','Duplicate','Download','Archive']);await group.getByRole('button',{name:'Download',exact:true}).click();await expect(host.getByLabel('Last action')).toHaveText('Download');
 await host.evaluate(n=>n.style.width='90px');await expect(group.locator(':scope > button:visible')).toHaveCount(0);await expect(buttons).toHaveCount(4);expect(await host.evaluate(n=>n.scrollWidth<=n.clientWidth+1)).toBe(true);
});
test('overflow recovers focused action through collapse and expansion using native controls',async({page})=>{
 const host=page.locator('consumer-overflow'),group=host.getByRole('group',{name:'Brief actions'});await host.evaluate(n=>n.style.width='600px');const archive=group.getByRole('button',{name:'Archive',exact:true});await archive.focus();await host.evaluate(n=>n.style.width='220px');await expect(group.locator('details')).toHaveAttribute('open','');await expect(archive).toBeFocused();await archive.press('Enter');await expect(host.getByLabel('Last action')).toHaveText('Archive');await host.evaluate(n=>n.style.width='600px');await expect(archive).toBeFocused();await expect(group.locator('summary')).toBeHidden();
});
test('overflow reconnect remeasures narrow RTL without page overflow or stale prefix',async({page})=>{
 await page.setViewportSize({width:320,height:800});await page.evaluate(()=>{document.documentElement.dir='rtl';document.documentElement.style.fontSize='22px';const n=document.querySelector('consumer-overflow')!;(window as any).overflow=n;n.remove();});await page.evaluate(()=>document.querySelector('main')!.prepend((window as any).overflow));const host=page.locator('consumer-overflow');await expect(host.locator('.row summary')).toBeVisible();await host.locator('.row summary').click();await expect(host.getByRole('group').getByRole('button')).toHaveCount(4);expect(await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth,overflow:[...document.querySelectorAll('main,main>*,input')].filter(n=>n.getBoundingClientRect().right>innerWidth+1||n.getBoundingClientRect().left< -1).map(n=>n.tagName+'#'+n.id)}))).toMatchObject({scroll:320,width:320,overflow:[]});
});
test('definition import is lazy; prepare registers nothing and ensure upgrades dependency-first preserving inputs',async({page})=>{
 const chunks:string[]=[];page.on('request',r=>{if(/lazy-panel.*\.js/.test(r.url()))chunks.push(r.url());});const note=page.getByLabel('Retained note');await note.fill('Keep this edit');await note.evaluate(n=>(window as any).note=n);expect(await page.evaluate(()=>customElements.get('consumer-lazy-panel')===undefined)).toBe(true);await page.getByRole('button',{name:'Prepare details'}).click();await expect(page.getByLabel('Loader state')).toHaveText('Prepared without registration');expect(chunks).toHaveLength(1);expect(await page.evaluate(()=>customElements.get('consumer-lazy-panel')===undefined&&customElements.get('consumer-panel-status')===undefined)).toBe(true);
 await page.getByRole('button',{name:'Open details'}).click();await expect(page.getByLabel('Loader state')).toHaveText('Registered');await expect(page.locator('consumer-lazy-panel')).toHaveAttribute('data-child-registered','true');await expect(page.locator('consumer-panel-status')).toHaveText('Details ready');await expect(note).toHaveValue('Keep this edit');expect(await note.evaluate(n=>n===(window as any).note)).toBe(true);expect(chunks).toHaveLength(1);
});
test('concurrent loader requests share imports and idempotent registry work',async({page})=>{
 const result=await page.evaluate(async()=>{const d=(window as any).consumerDiagnostics;await Promise.all([d.preparation.load(['consumer-lazy-panel']),d.loader.load(['consumer-lazy-panel']),d.loader.ensure(['consumer-lazy-panel']),d.loader.ensure(['consumer-lazy-panel','consumer-lazy-panel'])]);const def=await d.definition();d.registerDefinition(customElements,def);return {loads:d.metrics.loads,closure:d.collectDefinitions([def,def]).map((x:any)=>x.tagName),statuses:document.querySelectorAll('consumer-panel-status').length};});expect(result).toEqual({loads:1,closure:['consumer-panel-status','consumer-lazy-panel'],statuses:1});
});
test('unknown manifest request fails lookup before any import or registration',async({page})=>{
 const result=await page.evaluate(async()=>{const d=(window as any).consumerDiagnostics;try{await d.loader.ensure(['consumer-lazy-panel','unknown-panel']);return null;}catch(e){return {stage:(e as any).stage,loads:d.metrics.loads,registered:!!customElements.get('consumer-lazy-panel')};}});expect(result).toEqual({stage:'lookup',loads:0,registered:false});
});
test('failed consumer loading stays cached until explicit retry and never partially upgrades',async({page})=>{
 await page.evaluate(()=>(window as any).consumerDiagnostics.metrics.fail=true);await page.getByRole('button',{name:'Open details'}).click();await expect(page.getByLabel('Loader state')).toHaveText('load: consumer-lazy-panel');await page.evaluate(()=>(window as any).consumerDiagnostics.metrics.fail=false);await page.getByRole('button',{name:'Open details'}).click();await expect(page.getByLabel('Loader state')).toHaveText('load: consumer-lazy-panel');expect(await page.evaluate(()=>(window as any).consumerDiagnostics.metrics.loads)).toBe(1);expect(await page.evaluate(()=>!!customElements.get('consumer-panel-status'))).toBe(false);await page.getByRole('button',{name:'Retry details'}).click();await expect(page.getByLabel('Loader state')).toHaveText('Registered');expect(await page.evaluate(()=>(window as any).consumerDiagnostics.metrics.loads)).toBe(2);
});
test('native registry conflicts preflight dependencies and remain permanent for the request',async({page})=>{
 const result=await page.evaluate(async()=>{const d=(window as any).consumerDiagnostics;customElements.define('consumer-lazy-panel',class extends HTMLElement{});const errors=[];for(let i=0;i<2;i++)try{await d.loader.ensure(['consumer-lazy-panel'],{retry:true});}catch(e){errors.push((e as any).stage);}return {errors,loads:d.metrics.loads,dependencyRegistered:!!customElements.get('consumer-panel-status')};});expect(result).toEqual({errors:['registration','registration'],loads:1,dependencyRegistered:false});
});
