// Actual Firefox workflows over BiDi. Existing Playwright suites remain the full contract.
import assert from 'node:assert/strict';
import {spawn,execFileSync} from 'node:child_process';
import {mkdir,readFile,writeFile,realpath,stat} from 'node:fs/promises';
import {resolve,join,extname} from 'node:path';
import {createServer} from 'node:http';
import {setTimeout as delay} from 'node:timers/promises';
import {withMachineOwner} from '../../tooling/testing/machine-owner.mjs';
import {withExecutionOwner} from '../../tooling/testing/execution-owner.mjs';
import {contentInventory,inventoryDigest} from '../../tooling/evidence/setup.mjs';
import {firefox} from './firefox.mjs';
const root=resolve(import.meta.dirname,'../..'), output=process.env.EN_EXECUTION_OUTPUT;
assert(process.platform==='darwin');assert(output?.startsWith('/'),'Absolute fresh EN_EXECUTION_OUTPUT required');await mkdir(output);
const bundle=await realpath(process.env.EN_FIREFOX_APP??'/Applications/Firefox.app');assert(bundle.endsWith('.app'));
const metadata=path=>JSON.parse(execFileSync('plutil',['-convert','json','-o','-',join(path,'Contents/Info.plist')],{encoding:'utf8'}));
const receipt={schemaVersion:1,status:'running',sourceBase:execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),startedAt:new Date().toISOString(),cases:[],host:{version:execFileSync('sw_vers',['-productVersion'],{encoding:'utf8'}).trim(),build:execFileSync('sw_vers',['-buildVersion'],{encoding:'utf8'}).trim(),arch:process.arch},scope:'Native input on existing qualified production assets. Selected functional workflows, not complete Playwright parity, hydration interception, no-JS, axe, all layout/history variants, speech/IME or physical-device qualification.'};
const save=()=>writeFile(join(output,'result.json'),JSON.stringify(receipt,null,2)+'\n');
const children=[];
function child(file,args,name){const p=spawn(file,args,{stdio:['ignore','pipe','pipe']});let log='',error;p.stdout.on('data',x=>log+=x);p.stderr.on('data',x=>log+=x);p.once('error',e=>error=e);const closed=new Promise(r=>p.once('close',(code,signal)=>r({code,signal})));const item={p,closed,name,log:()=>log,error:()=>error};children.push(item);return item;}
async function stop(item){if(item.p.exitCode===null&&item.p.signalCode===null)item.p.kill('SIGTERM');await Promise.race([item.closed,delay(5000).then(()=>{if(item.p.exitCode===null&&item.p.signalCode===null)item.p.kill('SIGKILL');})]);await item.closed;await writeFile(join(output,item.name+'.log'),item.log());}
async function until(fn,label){let last;for(let i=0;i<100;i++){try{if(await fn())return;}catch(e){last=e;}await delay(100);}throw Error('Timed out: '+label,{cause:last});}
// Transport's endpoint acquisition needs the returned value.
async function ready(fn,label){let value;await until(async()=>Boolean(value=await fn()),label);return value;}
async function identity(paths){const files=await contentInventory(root,paths,undefined,true,{includeModes:true});return {files,digest:inventoryDigest(files)};}
let browser,scene,server;
const expr=selector=>`document.querySelector(${JSON.stringify(selector)})`;
const q=selector=>expr('#'+scene+' '+selector);
async function check(expression,expected){let last;await until(async()=>{last=await browser.evaluate(expression);try{assert.deepEqual(last,expected);return true;}catch{return false;}},expression+' expected '+JSON.stringify(expected));}
async function named(role,name){let nodes;await until(async()=>{nodes=await browser.locateAcrossRoots(role,name,scene==='chat'&&role==='button'&&name==='Send message'?q('[data-testid=chat-send]'):expr('#'+scene));return nodes.length===1;},`${scene} ${role} ${name}`);return nodes[0];}
async function key(value){await browser.actions([{type:'key',id:'keyboard',actions:[{type:'keyDown',value},{type:'keyUp',value}]}]);}
async function focus(node){await browser.call(node,'e=>{e.scrollIntoView({block:"center"});e.focus();return true;}');}
async function press(name){const node=await named('button',name);await focus(node);await key('\uE007');}
async function clickNode(node){const point=await browser.call(node,'e=>{e.scrollIntoView({block:"center"});const r=e.getBoundingClientRect();if(!r.width||!r.height)throw Error("Hidden target");return {x:Math.round(r.x+r.width/2),y:Math.round(r.y+r.height/2)};}');await browser.actions([{type:'pointer',id:'mouse',parameters:{pointerType:'mouse'},actions:[{type:'pointerMove',origin:'viewport',...point},{type:'pointerDown',button:0},{type:'pointerUp',button:0}]}]);}
async function fill(role,name,value){const node=await named(role,name);await focus(node);await browser.actions([{type:'key',id:'keyboard',actions:[{type:'keyDown',value:'\uE03D'},{type:'keyDown',value:'a'},{type:'keyUp',value:'a'},{type:'keyUp',value:'\uE03D'}]}]);await key('\uE003');for(const c of value)await key(c);await checkNode(node,'e=>e.value',value);return node;}
async function checkNode(node,source,expected){let actual;try{await until(async()=>{actual=await browser.call(node,source);try{assert.deepEqual(actual,expected);return true;}catch{return false;}},source+' expected '+JSON.stringify(expected));}catch(error){throw Error(error.message+'; actual '+JSON.stringify(actual)+'; node '+JSON.stringify(node.value),{cause:error});}}
async function select(name,value){
 const node=await named('combobox',name);if(await browser.call(node,'e=>e.value')===value)return;
 const options=await browser.call(node,'e=>Array.from(e.options,o=>({value:o.value,label:o.label,disabled:o.disabled}))');const index=options.findIndex(o=>o.value===value);assert(index>=0&&!options[index].disabled);
 const trace={name,value,options,states:[]};(receipt.nativeSelectTraces??=[]).push(trace);
 const snapshot=async key=>trace.states.push({key,...await browser.call(node,'e=>({value:e.value,index:e.selectedIndex,focused:e.getRootNode().activeElement===e,connected:e.isConnected})')});
 await browser.call(node,'e=>{window.selectEvents=[];for(const type of ["keydown","input","change","blur"])e.addEventListener(type,event=>selectEvents.push({type,key:event.key,value:e.value,focused:e.getRootNode().activeElement===e,connected:e.isConnected}));return true;}');await focus(node);for(const character of options[index].label)await key(character);await snapshot('Typeahead');await key('\uE004');await snapshot('Tab');trace.events=await browser.evaluate('selectEvents');await checkNode(node,'e=>e.value',value);
}
async function text(selector,value){await check(q(selector)+'.textContent.trim()',value);}
async function heading(name){const node=await named('heading',name);await checkNode(node,'e=>e.getRootNode().activeElement===e',true);}
async function details(name){await browser.evaluate(`(()=>{const e=Array.from(${expr('#'+scene)}.querySelectorAll('summary')).find(e=>e.textContent.trim()===${JSON.stringify(name)});if(!e)throw Error('Missing summary');window.probeSummary=e;return true;})()`);if(!await browser.evaluate('probeSummary.parentElement.open')){await browser.evaluate('(probeSummary.focus(),true)');await key('\uE007');}await check('probeSummary.parentElement.open',true);}
async function open(id){scene=id;await browser.navigate(base+(id==='sso'?'/workflows':'/workflows/'+id));await check(`Boolean(document.querySelector('en-workflows-app')?.hasUpdated&&!document.querySelector('en-workflows-app').hasAttribute('data-ssr'))`,true);await check("document.querySelectorAll('.workflow-section').length",1);await check('Boolean('+expr('#'+id)+')',true);await check("document.querySelectorAll('en-navigation.section-nav > a').length",6);}
async function account(workspace='Studio North',email='alex@example.test'){await fill('textbox','Workspace',workspace);await fill('textbox','Work email',email);await key('\uE007');await heading('Choose your sign-in provider');}
async function ssoFixture(outcome='success',timing='immediate'){await details('Scenario controls for sign-in');await select('Sign-in outcome',outcome);await select('Sign-in response timing',timing);}
async function settingsFixture(outcome='success'){await details('Settings simulation controls');await select('Settings save result',outcome);await select('Settings response delivery','held');}
async function opacity(value){await fill('spinbutton','Layer opacity Exact value',value);await key('\uE007');}
async function chatFixture(reply='success',timing='immediate'){await details('Chat simulation controls');await select('Next reply',reply);await select('Response timing',timing);}
async function adjustment(){await press('Send message');await check('Boolean('+q('[data-testid="chat-adjustment"]')+')',true);await text('[data-testid="chat-current"]','Current: 68% opacity · revision 7');}
const cases=[
 ['sso-success','SSO keyboard provider choice submits captured account',async()=>{await open('sso');await ssoFixture();await account();await focus(await named('radio','Studio identity'));await key('\uE015');await checkNode(await named('radio','Partner identity'),'e=>e.checked',true);await press('Continue');await heading('Example sign-in complete');await text('[data-sso-attempts]','1');assert((await browser.evaluate(q('*')+'.parentElement.textContent')).includes('alex@example.test'));}],
 ['sso-retry','SSO rejected request retries once and retains provider',async()=>{await open('sso');await ssoFixture('reject-once');await account();await clickNode(await named('radio','Partner identity'));await press('Continue');await text('[role=status]','The example provider declined this attempt. Retry or choose the other provider.');await checkNode(await named('radio','Partner identity'),'e=>e.checked',true);await press('Retry');await heading('Example sign-in complete');await text('[data-sso-attempts]','2');}],
 ['sso-cancel','SSO cancellation ignores stale response and retains later draft',async()=>{await open('sso');await ssoFixture('success','held');await account();await press('Continue');await press('Continue');await text('[data-sso-attempts]','1');await press('Cancel sign-in');await checkNode(await named('button','Continue'),'e=>e.getRootNode().activeElement===e',true);await press('Back');await fill('textbox','Workspace','Later local workspace');await press('Release response 1');await checkNode(await named('textbox','Workspace'),'e=>e.value','Later local workspace');await checkNode(await named('textbox','Work email'),'e=>e.value','alex@example.test');assert.equal((await browser.locateAcrossRoots('heading','Example sign-in complete',expr('#sso'))).length,0);}],
 ['sso-reset','SSO reset isolates old and new pending requests',async()=>{await open('sso');await ssoFixture('success','held');await account('Old workspace','old@example.test');await press('Continue');await press('Reset sign-in scenario');await checkNode(await named('textbox','Workspace'),'e=>e.value','');await ssoFixture('success','held');await account('New workspace','new@example.test');await clickNode(await named('radio','Partner identity'));await press('Continue');await press('Release response 1');assert.equal((await browser.locateAcrossRoots('heading','Example sign-in complete',expr('#sso'))).length,0);await named('button','Cancel sign-in');await press('Release response 2');await heading('Example sign-in complete');await check(`${expr('#sso')}.textContent.includes('new@example.test')`,true);}],
 ['settings-snapshot','Settings captured save preserves later local edits and cancellation',async()=>{await open('settings');await settingsFixture();await opacity('70');assert.deepEqual(await browser.evaluate(`Object.fromEntries(new FormData(${q('form')}))`),{opacity:'70',format:'png',layout:'portrait',background:'on'});await press('Save settings');await select('Output format','svg');await press('Deliver held response');await text('[data-settings-saved]','70% opacity · PNG · Portrait · Background included');await text('[data-settings-current]','70% opacity · SVG · Portrait · Background included');await text('[data-settings-status]','Saved revision 2. Newer local changes are still unsaved.');await press('Save settings');await press('Deliver held response');await opacity('72');await press('Save settings');await clickNode(await named('checkbox','Include background'));await press('Cancel save');await text('[data-settings-current]','72% opacity · SVG · Portrait · Transparent background');await text('[data-settings-saved]','70% opacity · SVG · Portrait · Background included');await checkNode(await named('button','Deliver held response'),'e=>e.disabled',true);}],
 ['settings-retry','Settings failed save retains local value and Retry succeeds',async()=>{await open('settings');await settingsFixture('failure');await opacity('71');await press('Save settings');await press('Deliver held response');await text('[data-settings-status]','The simulated save failed. Your local settings are intact. Retry save when ready.');await checkNode(await named('spinbutton','Layer opacity Exact value'),'e=>e.value','71');await text('[data-settings-saved]','64% opacity · PNG · Portrait · Background included');await press('Retry save');await press('Deliver held response');await text('[data-settings-saved]','71% opacity · PNG · Portrait · Background included');await text('[data-settings-status]','Saved revision 2.');}],
 ['settings-incoming','Incoming settings preserve unfinished editor identity and explicit Keep/Use choices',async()=>{await open('settings');await details('Settings simulation controls');await select('Output format','svg');await press('Queue collaborator update');const original=await fill('spinbutton','Layer opacity Exact value','101');await named('region','Incoming opacity change');await checkNode(original,'e=>e.isConnected&&e.getRootNode().activeElement===e',true);await text('[data-settings-current]','64% opacity · SVG · Portrait · Background included');await press('Keep my opacity');await heading('Creative output settings');await checkNode(original,'e=>e.value','101');await focus(original);await key('\uE00C');await checkNode(original,'e=>e.value','64');await press('Queue collaborator update');await fill('spinbutton','Layer opacity Exact value','101');await press('Use updated opacity');await heading('Creative output settings');await checkNode(original,'e=>e.value','82');await checkNode(await named('combobox','Output format'),'e=>e.value','svg');}],
 ['chat-safe-preview','Chat text stays inert and only a reviewed valid preview applies',async()=>{await open('chat');await chatFixture();const message='<img src=x onerror="window.untrustedMessageRan=true">';await fill('textbox','Message',message);await key('\uE007');await checkNode(await named('textbox','Message'),'e=>e.value',message+'\n');await adjustment();await check(q('[data-testid="chat-transcript"]')+'.querySelectorAll("img").length',0);await check('Boolean(window.untrustedMessageRan)',false);await press('Review latest adjustment');await heading('Cover image adjustment');await fill('spinbutton','Proposed opacity Exact value','101');await press('Preview adjustment');await checkNode(await named('spinbutton','Proposed opacity Exact value'),'e=>e.getAttribute("aria-invalid")','true');await focus(await named('spinbutton','Proposed opacity Exact value'));await key('\uE00C');await press('Preview adjustment');await fill('spinbutton','Proposed opacity Exact value','77');await key('\uE007');assert.equal((await browser.locateAcrossRoots('button','Apply adjustment',expr('#chat'))).length,0);await press('Preview adjustment');await press('Apply adjustment');await text('[data-testid="chat-current"]','Current: 77% opacity · revision 8');await text('[data-testid="chat-status"]','Adjustment applied. Cover image opacity is 77%.');}],
 ['chat-stale','Held chat apply revalidates collaborator revision',async()=>{await open('chat');await chatFixture();await adjustment();await press('Preview adjustment');await select('Response timing','held');await press('Apply adjustment');await press('Apply adjustment');await press('Add collaborator turn');await text('[data-testid="chat-current"]','Current: 74% opacity · revision 8');await press('Release pending response');await text('[data-testid="chat-problem"]','The image changed after revision 7; it is now revision 8. Refresh the preview before applying your adjustment.');await press('Refresh preview');await press('Apply adjustment');await press('Release pending response');await text('[data-testid="chat-current"]','Current: 85% opacity · revision 9');}],
 ['chat-cancel','Pending chat sends deduplicate and cancel/reset preserve appropriate drafts',async()=>{await open('chat');await chatFixture('success','held');await fill('textbox','Message','The first request');await press('Send message');await press('Send message');assert.equal((await browser.locateAcrossRoots('article','You message',expr('#chat'))).length,1);await fill('textbox','Message','A later draft to keep');await press('Cancel pending requests');await checkNode(await named('textbox','Message'),'e=>({value:e.value,focused:e.getRootNode().activeElement===e})',{value:'A later draft to keep',focused:true});await checkNode(await named('button','Release pending response'),'e=>e.disabled',true);await press('Send message');await press('Reset chat');await checkNode(await named('button','Release pending response'),'e=>e.disabled',true);assert.equal((await browser.locateAcrossRoots('article','You message',expr('#chat'))).length,0);await checkNode(await named('textbox','Message'),'e=>e.value','Make the cover image a little stronger.\nKeep the text easy to read.');}],
 ['selection-assignment','Selection accepts explicit keys and rejects unresolved text',async()=>{await open('selection');await fill('combobox','Project','Willow · Year in review');await key('\uE015');await key('\uE007');await text('[data-selection-accepted]','Willow · Year in review · project-40');assert.equal(await browser.evaluate(`new FormData(${q('form')}).get('project')`),'project-40');await press('Assign brief');await text('[data-selection-submission]','Submission 1: Willow · Year in review · project=project-40');await fill('combobox','Project','no matching project 999');await key('\uE007');await browser.evaluate(`${q('form')}.requestSubmit()`);await check(q('form')+'.checkValidity()',false);await text('[data-selection-submission]','Submission 1: Willow · Year in review · project=project-40');await focus(await named('combobox','Project'));await key('\uE00C');await checkNode(await named('combobox','Project'),'e=>e.value','Willow · Year in review');await fill('combobox','Project','Atlas · Website refresh');await key('\uE015');await key('\uE007');await text('[data-selection-accepted]','Atlas · Website refresh · project-10');await press('Assign brief');await text('[data-selection-submission]','Submission 2: Atlas · Website refresh · project=project-10');}],
];
let base;
try{await withMachineOwner(()=>withExecutionOwner(root,async()=>{
 const inputs=['dist','probes/native-browser-products/workflows.mjs','probes/native-browser-products/firefox.mjs','apps/docs/tests/workflows.spec.ts','apps/docs/tests/selection.spec.ts'];
 const before=await identity([bundle,...inputs]);await writeFile(join(output,'identity-before.json'),JSON.stringify(before,null,2)+'\n');receipt.identityBefore=before.digest;
 const app=metadata(bundle);receipt.product={name:'Firefox',version:app.CFBundleShortVersionString,build:app.CFBundleVersion,bundle};
 server=createServer(async(req,res)=>{try{let path=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(path==='/')path='/index.html';if(!extname(path))path+='.html';const file=resolve(root,'dist','.'+path);assert(file.startsWith(join(root,'dist')+'/'));const real=await realpath(file);assert(real.startsWith(join(root,'dist')+'/'));assert((await stat(real)).isFile());const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.woff2':'font/woff2','.png':'image/png','.jpg':'image/jpeg'}[extname(file)]??'application/octet-stream';res.setHeader('Content-Type',mime);res.end(await readFile(real));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port;
 for(const [id,title,run] of cases){const result={id,title,status:'running'};receipt.cases.push(result);await save();const caseOutput=join(output,id);await mkdir(caseOutput);console.log('START '+id);
  try{browser=await firefox({bundle,output:caseOutput,metadata,child:(file,args,name)=>child(file,args,id+'-'+name),until:ready,stop});assert.equal(browser.capabilities.browserVersion,app.CFBundleShortVersionString);result.capabilities=browser.capabilities;await browser.setViewport({width:1280,height:900});await browser.addPreload('()=>{window.probeErrors=[];addEventListener("error",e=>probeErrors.push(e.message));addEventListener("unhandledrejection",e=>probeErrors.push(String(e.reason)));const original=console.error;console.error=(...args)=>{probeErrors.push(args.map(String).join(" "));original.apply(console,args);};}');await run();assert.deepEqual(await browser.evaluate('probeErrors'),[]);result.status='passed';}
  catch(error){result.status='failed';result.error=String(error.stack??error);try{result.diagnostic=await browser?.evaluate('({url:location.href,errors:window.probeErrors,body:document.body.innerText})');}catch{};throw error;}
  finally{await browser?.close();browser=null;await save();}console.log('PASS '+id);
 }
 const after=await identity([bundle,...inputs]);await writeFile(join(output,'identity-after.json'),JSON.stringify(after,null,2)+'\n');receipt.identityAfter=after.digest;assert.equal(after.digest,before.digest);receipt.status='passed';
}));}catch(error){receipt.status='failed';receipt.error=String(error.stack??error);process.exitCode=1;}finally{await browser?.close();for(const item of children)await stop(item);if(server){server.closeAllConnections();await new Promise(r=>server.close(r));}receipt.completedAt=new Date().toISOString();receipt.stats={passed:receipt.cases.filter(c=>c.status==='passed').length,failed:receipt.cases.filter(c=>c.status==='failed').length,planned:cases.length};await save();console.log(receipt.status+' '+JSON.stringify(receipt.stats));}
