import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
for(const delivery of ['lit','css'])test.describe(delivery,()=>{
 test.beforeEach(async({page})=>{await page.goto('/?delivery='+delivery);await expect(page.locator('body')).toHaveAttribute('data-ready','true');});
 test('shell uses native landmarks and changes from two columns to a narrow single column',async({page})=>{
  const host=page.locator('consumer-presentation');await expect(host.getByRole('navigation',{name:'Project navigation'})).toHaveCount(1);await expect(host.getByRole('main')).toHaveCount(1);await expect(host.getByRole('heading',{name:'Project delivery',level:1})).toBeVisible();
  const measure=()=>host.evaluate(n=>{const nav=n.shadowRoot!.querySelector('nav')!.getBoundingClientRect(),main=n.shadowRoot!.querySelector('main')!.getBoundingClientRect();return {side:main.left>=nav.right,below:main.top>=nav.bottom};});await page.setViewportSize({width:1200,height:900});expect((await measure()).side).toBe(true);await page.setViewportSize({width:375,height:850});expect((await measure()).below).toBe(true);
  await host.evaluate(n=>{n.setAttribute('embedded','');(n as any).requestUpdate();});await expect(host.getByRole('main')).toHaveCount(0);
 });
 test('flyout uses native links and Tab order, with Escape focus recovery',async({page,browserName})=>{
  const nav=page.getByRole('navigation',{name:'Project navigation'}),summary=nav.locator('summary');await summary.focus();await summary.press('Enter');const chart=nav.getByRole('link',{name:'Chart data'});await summary.press(browserName==='webkit'?'Alt+Tab':'Tab');await expect(chart).toBeFocused();await expect(chart).toHaveAttribute('aria-current','page');await chart.press('Escape');await expect(summary).toBeFocused();await expect(nav.locator('details')).not.toHaveAttribute('open');await summary.press('Enter');await chart.click();await expect(page).toHaveURL(/#chart-data$/);
 });
 test('native choice cards submit checkbox and mutually exclusive radio values',async({page})=>{
  const host=page.getByRole('region',{name:'Delivery choices'});await host.getByRole('checkbox',{name:/Send updates/}).check();await host.getByRole('radio',{name:'Text',exact:true}).check();await expect(host.getByRole('radio',{name:'PDF',exact:true})).not.toBeChecked();await expect(host.getByRole('checkbox',{name:'Locked option'})).toBeDisabled();await host.getByRole('button',{name:'Submit choices'}).click();await expect(host.getByLabel('Submitted choices')).toHaveText('[["updates","yes"],["format","text"]]');
 });
 test('authored checked state reconciles controls after native edits without replacing nodes',async({page})=>{
  const host=page.getByRole('region',{name:'Delivery choices'}),updates=host.getByRole('checkbox',{name:/Send updates/});await updates.check();await updates.evaluate(n=>(window as any).originalChoice=n);await host.getByRole('radio',{name:'Text',exact:true}).check();await host.getByRole('button',{name:'Clear choices'}).click();await expect(updates).not.toBeChecked();await expect(host.getByRole('radio',{name:'PDF',exact:true})).toBeChecked();expect(await updates.evaluate(n=>n===(window as any).originalChoice)).toBe(true);
 });
 test('omitted checked preserves native selection across unrelated renders',async({page})=>{
  const choice=page.getByRole('checkbox',{name:'Keep native selection'});await choice.check();await page.getByRole('button',{name:'Clear choices'}).click();await expect(choice).toBeChecked();await choice.uncheck();await page.getByRole('button',{name:'Update budget'}).click();await expect(choice).not.toBeChecked();
 });
 test('joined field retains native draft and caret through unrelated renders and names actions separately',async({page})=>{
  const field=page.getByRole('textbox',{name:'Search draft',exact:true});await field.fill('Find the project');await field.evaluate(n=>{const input=n as HTMLInputElement;input.setSelectionRange(4,7);(window as any).field=n;document.querySelector<any>('consumer-presentation').requestUpdate();});await expect(field).toBeFocused();expect(await field.evaluate(n=>[(n as HTMLInputElement).selectionStart,(n as HTMLInputElement).selectionEnd])).toEqual([4,7]);expect(await field.evaluate(n=>n===(window as any).field)).toBe(true);await page.getByRole('button',{name:'Find',exact:true}).click();await expect(page.getByLabel('Action result')).toHaveText('Find the project');
 });
 test('joined actions retain native activation, disabled behavior and logical vertical geometry',async({page})=>{
  const group=page.getByRole('group',{name:'Document actions'});await group.getByRole('button',{name:'Duplicate',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.getByLabel('Action result')).toHaveText('Copied');await expect(group.getByRole('button',{name:'Delete',exact:true})).toBeDisabled();await expect(group).toHaveCSS('gap','0px');await page.getByRole('button',{name:'Change action orientation'}).click();await expect(group).toHaveCSS('flex-direction','column');await page.evaluate(()=>document.documentElement.dir='rtl');expect(await group.getByRole('button').first().evaluate(n=>getComputedStyle(n).borderBottomLeftRadius)).toBe('0px');
 });
 test('attachments use a real download plus a separate removal action',async({page})=>{
  const region=page.getByRole('region',{name:'Project attachment'}),link=region.getByRole('link',{name:'Brief notes'});await expect(link).toHaveAttribute('download','');expect(await link.locator('button').count()).toBe(0);const [download]=await Promise.all([page.waitForEvent('download'),link.click()]);expect(await readFile((await download.path())!,'utf8')).toBe('Project notes.\n');await region.getByRole('button',{name:'Remove attachment'}).click();await expect(region.getByRole('link')).toHaveCount(0);await expect(region).toContainText('Attachment removed');
 });
 test('local date-time constraints and submitted value remain native and timezone-free',async({page})=>{
  const input=page.getByLabel('Review time',{exact:true});await expect(input).toHaveAttribute('type','datetime-local');await input.fill('2026-10-02T13:30');expect(await input.evaluate(n=>(n as HTMLInputElement).validity.valid)).toBe(true);expect(await input.evaluate(n=>new FormData((n as HTMLInputElement).form!).get('review'))).toBe('2026-10-02T13:30');await input.fill('2026-10-02T18:00');expect(await input.evaluate(n=>(n as HTMLInputElement).validity.rangeOverflow)).toBe(true);await input.fill('');expect(await input.evaluate(n=>(n as HTMLInputElement).validity.valueMissing)).toBe(true);
 });
 test('meter keeps native range thresholds and updates its measured value',async({page})=>{
  const meter=page.getByRole('meter');await expect(meter).toHaveAccessibleName(/Budget used/);expect(await meter.evaluate(n=>{const m=n as HTMLMeterElement;return [m.value,m.min,m.max,m.low,m.high,m.optimum];})).toEqual([35,0,100,20,80,50]);await page.getByRole('button',{name:'Update budget'}).click();await expect(meter).toHaveAttribute('value','65');
 });
 test('code markup stays escaped and copy callback receives literal authored text',async({page})=>{
  const region=page.getByRole('region',{name:'Source sample'});await expect(region.locator('code')).toHaveText('<img src=x onerror="window.badMarkup=true">');await expect(region.locator('img')).toHaveCount(0);await region.getByRole('button',{name:'Copy code'}).click();await expect(region.getByLabel('Copied source')).toHaveText('<img src=x onerror="window.badMarkup=true">');expect(await page.evaluate(()=>(window as any).badMarkup)).toBeUndefined();
 });
 test('system disclosure and message marker preserve native semantics without synthetic widgets',async({page})=>{
  const host=page.locator('consumer-presentation'),status=host.locator('.en-system-message');await expect(status).toHaveAttribute('role','status');await expect(status.getByText('All assets prepared.')).toBeHidden();await status.locator('summary').click();await expect(status.getByText('All assets prepared.')).toBeVisible();await expect(host.locator('.en-message-marker')).toHaveText('Today');await expect(host.locator('.en-message-marker')).not.toHaveAttribute('role');
 });
 test('scroll area exposes its name and retains native keyboard scrolling',async({page})=>{
  const area=page.getByRole('region',{name:'Long notes'});await area.focus();await area.press('End');await expect.poll(()=>area.evaluate(n=>n.scrollTop)).toBeGreaterThan(0);await expect(area).toHaveCSS('overflow-y','auto');await expect(area.getByRole('listitem')).toHaveCount(35);
 });
 test('chart filters nonfinite values and pairs decorative signed bars with complete native data',async({page})=>{
  const region=page.getByRole('region',{name:'Review counts'}),table=region.getByRole('table',{name:'Review counts'});await expect(table.getByRole('row')).toHaveCount(3);await expect(table.getByRole('cell')).toHaveText(['-5','12']);await expect(region.locator('svg')).toHaveAttribute('aria-hidden','true');await expect(region.locator('svg')).toHaveAttribute('focusable','false');
  const geometry=await region.locator('svg').evaluate(n=>{const baseline=Number(n.querySelector('line')!.getAttribute('y1'));return [...n.querySelectorAll('rect')].map(r=>({y:Number(r.getAttribute('y')),height:Number(r.getAttribute('height')),baseline}));});expect(geometry[0].y).toBeCloseTo(geometry[0].baseline);expect(geometry[1].y).toBeLessThan(geometry[1].baseline);expect(geometry.every(r=>r.height>0)).toBe(true);await expect(region.getByRole('region',{name:'Review details'}).locator('dd')).toHaveText(['-5','12']);
 });
 test('chart handles empty/zero data and responds to scoped theme colors',async({page})=>{
  const host=page.locator('consumer-presentation');await host.evaluate(n=>{(n as any).data=[{key:'zero',label:'Zero',value:0}];});const chart=host.locator('.chart');await expect(chart.locator('rect')).toHaveCount(1);await expect(chart.locator('rect')).toHaveAttribute('height','1');await host.evaluate(n=>n.style.setProperty('--en-color-action','#8532b0'));await expect(chart.locator('rect')).toHaveCSS('fill','rgb(133, 50, 176)');await host.evaluate(n=>(n as any).data=[]);await expect(chart.locator('rect')).toHaveCount(0);await expect(chart).toContainText('No chart data');await expect(chart.locator('tbody tr')).toHaveCount(0);
 });
 test('native button, link and radio leaf styles honor scoped pins and keyboard focus',async({page,browserName})=>{
  const host=page.locator('consumer-presentation');await host.evaluate(n=>{n.style.setProperty('--en-button-radius','13px');n.style.setProperty('--en-color-link','#854a16');n.style.setProperty('--en-radio-selected-color','#8030a0');});const button=host.getByRole('button',{name:'Clear choices'});await expect(button).toHaveCSS('border-radius','13px');await expect(host.getByRole('link',{name:'Review cover'})).toHaveCSS('color','rgb(133, 74, 22)');const radio=host.getByRole('radio',{name:'PDF',exact:true});await expect(radio).toHaveCSS('border-top-color','rgb(128, 48, 160)');await button.focus();await button.press(browserName==='webkit'?'Alt+Tab':'Tab');const submit=host.getByRole('button',{name:'Submit choices'});await expect(submit).toBeFocused();expect(await submit.evaluate(n=>{const s=getComputedStyle(n);return s.outlineStyle!=='none'||s.boxShadow!=='none';})).toBe(true);expect(await host.locator('link').count()).toBe(delivery==='css'?1:0);
 });
 test('native recipe styling retains table/description/quote/disclosure semantics and forced-color boundaries',async({page})=>{
  const host=page.locator('consumer-presentation'),section=host.getByRole('region',{name:'Native recipes'});await expect(section.locator('dt')).toHaveText('Owner');await expect(section.locator('dd')).toHaveText('Alex Kim');await expect(section.locator('figcaption')).toHaveText('Review note');await expect(section.locator('blockquote')).toHaveCSS('border-left-style','solid');await section.locator('summary').focus();await section.locator('summary').press('Enter');await expect(section.getByText('Native disclosure content.')).toBeVisible();await page.emulateMedia({forcedColors:'active'});await expect(host.locator('.en-recipe-table td').first()).toHaveCSS('border-bottom-style','solid');await expect(host.locator('.en-recipe-table td').first()).toHaveCSS('font-variant-numeric','tabular-nums');expect(await host.getByRole('heading',{level:1,name:'Project delivery'}).evaluate(n=>Number.parseFloat(getComputedStyle(n).fontSize))).toBeGreaterThan(20);
 });
 test('media keeps alternative text, caption and action separate with responsive geometry',async({page})=>{
  const host=page.locator('consumer-presentation'),img=host.getByRole('img',{name:'Blue cover study'});await expect.poll(()=>img.evaluate(n=>(n as HTMLImageElement).complete&&(n as HTMLImageElement).naturalWidth)).toBe(320);await expect(host.locator('.en-media-card figcaption')).toHaveText('Cover concept');await expect(host.getByRole('link',{name:'Review cover'})).toBeVisible();const dimensions=await img.boundingBox();expect(dimensions!.width/dimensions!.height).toBeCloseTo(16/9,1);
 });
 test('enlarged RTL and text spacing preserve readable content without document overflow',async({page})=>{
  await page.setViewportSize({width:375,height:850});await page.evaluate(()=>{document.documentElement.dir='rtl';document.documentElement.style.fontSize='22px';const root=document.querySelector('consumer-presentation')!.shadowRoot!;const style=document.createElement('style');style.textContent='*{letter-spacing:.12em!important;word-spacing:.16em!important;line-height:1.5!important}';root.append(style);});expect(await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth}))).toEqual({scroll:375,width:375});await expect(page.getByRole('textbox',{name:'Search draft',exact:true})).toBeVisible();await expect(page.locator('consumer-presentation').getByRole('heading',{name:'Project delivery'})).toBeVisible();
 });
});
