import {chromium,firefox,webkit} from '@playwright/test';import {readFile,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
import {exclusiveBrowserWork} from '../../../showcases/performance/src/lock.mjs';
const base='artifacts/scoped-registry-phase-5/production/',report=JSON.parse(await readFile(base+'report.json')),checks=[];
await exclusiveBrowserWork(async()=>{for(const [name,type]of Object.entries({chromium,firefox,webkit})){const browser=await type.launch();try{const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(report.url);await page.waitForFunction(()=>!!customElements.get('en-table'));
 assert.equal(await page.locator('en-table').count(),5);assert(await page.locator('#report-return').isVisible());
 const button=page.locator('#timing button[data-key="prepared-eager-delta"]');await button.click();assert.equal(await button.evaluate(el=>el.closest('th').getAttribute('aria-sort')),'ascending');await button.click();assert.equal(await button.evaluate(el=>el.closest('th').getAttribute('aria-sort')),'descending');
 const values=await page.locator('#timing tbody tr').evaluateAll(rows=>rows.map(r=>Number(r.querySelector('[data-pair-column="prepared-eager"]').dataset.value)));for(let i=1;i<values.length;i++)assert(values[i]<=values[i-1]);
 await page.locator('#timing input').fill('chromium constrained');assert(await page.locator('#timing tbody tr:not([hidden])').count()>0);assert(await page.locator('#timing tbody tr[hidden]').count()>0);
 for(const id of ['timing','retention','settled','server'])assert.match(await page.locator('#'+id+'-note').textContent(),/negative/i);
 await page.screenshot({path:base+'report-'+name+'.png',fullPage:false});await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 if(name==='chromium')await page.screenshot({path:base+'report-mobile.png',fullPage:false});
 const plain=report.url.replace('?progress-report','');await page.goto(plain);assert(!(await page.locator('#report-return').isVisible()));assert.deepEqual(errors,[]);checks.push({browser:name,passed:true,sortableTables:5});
 }finally{await browser.close();}}});await writeFile(base+'report-verification.json',JSON.stringify({at:new Date().toISOString(),checks},null,2)+'\n');
